// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: chargehive/chtype/charge.proto

package chtype

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ChargeMetaType int32

const (
	CHARGE_META_TYPE_INVALID ChargeMetaType = 0
	CHARGE_META_TYPE_SOURCE  ChargeMetaType = 1
	CHARGE_META_TYPE_APPEND  ChargeMetaType = 2
)

var ChargeMetaType_name = map[int32]string{
	0: "CHARGE_META_TYPE_INVALID",
	1: "CHARGE_META_TYPE_SOURCE",
	2: "CHARGE_META_TYPE_APPEND",
}

var ChargeMetaType_value = map[string]int32{
	"CHARGE_META_TYPE_INVALID": 0,
	"CHARGE_META_TYPE_SOURCE":  1,
	"CHARGE_META_TYPE_APPEND":  2,
}

func (x ChargeMetaType) String() string {
	return proto.EnumName(ChargeMetaType_name, int32(x))
}

func (ChargeMetaType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8da54e8823fce2f7, []int{0}
}

type ChargeIntent int32

const (
	CHARGE_INTENT_INVALID        ChargeIntent = 0
	CHARGE_INTENT_METHOD_ADD     ChargeIntent = 1
	CHARGE_INTENT_METHOD_REFRESH ChargeIntent = 2
	CHARGE_INTENT_METHOD_VERIFY  ChargeIntent = 3
	CHARGE_INTENT_CAPTURE        ChargeIntent = 4
	CHARGE_INTENT_REFUND         ChargeIntent = 5
)

var ChargeIntent_name = map[int32]string{
	0: "CHARGE_INTENT_INVALID",
	1: "CHARGE_INTENT_METHOD_ADD",
	2: "CHARGE_INTENT_METHOD_REFRESH",
	3: "CHARGE_INTENT_METHOD_VERIFY",
	4: "CHARGE_INTENT_CAPTURE",
	5: "CHARGE_INTENT_REFUND",
}

var ChargeIntent_value = map[string]int32{
	"CHARGE_INTENT_INVALID":        0,
	"CHARGE_INTENT_METHOD_ADD":     1,
	"CHARGE_INTENT_METHOD_REFRESH": 2,
	"CHARGE_INTENT_METHOD_VERIFY":  3,
	"CHARGE_INTENT_CAPTURE":        4,
	"CHARGE_INTENT_REFUND":         5,
}

func (x ChargeIntent) String() string {
	return proto.EnumName(ChargeIntent_name, int32(x))
}

func (ChargeIntent) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8da54e8823fce2f7, []int{1}
}

type ChargeEnvironment int32

const (
	CHARGE_ENVIRONMENT_INVALID   ChargeEnvironment = 0
	CHARGE_ENVIRONMENT_RETAIL    ChargeEnvironment = 1
	CHARGE_ENVIRONMENT_ECOMMERCE ChargeEnvironment = 2
	CHARGE_ENVIRONMENT_MOTO      ChargeEnvironment = 3
	CHARGE_ENVIRONMENT_RENEWAL   ChargeEnvironment = 4
)

var ChargeEnvironment_name = map[int32]string{
	0: "CHARGE_ENVIRONMENT_INVALID",
	1: "CHARGE_ENVIRONMENT_RETAIL",
	2: "CHARGE_ENVIRONMENT_ECOMMERCE",
	3: "CHARGE_ENVIRONMENT_MOTO",
	4: "CHARGE_ENVIRONMENT_RENEWAL",
}

var ChargeEnvironment_value = map[string]int32{
	"CHARGE_ENVIRONMENT_INVALID":   0,
	"CHARGE_ENVIRONMENT_RETAIL":    1,
	"CHARGE_ENVIRONMENT_ECOMMERCE": 2,
	"CHARGE_ENVIRONMENT_MOTO":      3,
	"CHARGE_ENVIRONMENT_RENEWAL":   4,
}

func (x ChargeEnvironment) String() string {
	return proto.EnumName(ChargeEnvironment_name, int32(x))
}

func (ChargeEnvironment) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8da54e8823fce2f7, []int{2}
}

type DeviceType int32

const (
	DEVICE_TYPE_INVALID  DeviceType = 0
	DEVICE_TYPE_MOBILE   DeviceType = 1
	DEVICE_TYPE_TABLET   DeviceType = 2
	DEVICE_TYPE_DESKTOP  DeviceType = 3
	DEVICE_TYPE_WEARABLE DeviceType = 4
	DEVICE_TYPE_CONSOLE  DeviceType = 5
	DEVICE_TYPE_VEHICLE  DeviceType = 6
)

var DeviceType_name = map[int32]string{
	0: "DEVICE_TYPE_INVALID",
	1: "DEVICE_TYPE_MOBILE",
	2: "DEVICE_TYPE_TABLET",
	3: "DEVICE_TYPE_DESKTOP",
	4: "DEVICE_TYPE_WEARABLE",
	5: "DEVICE_TYPE_CONSOLE",
	6: "DEVICE_TYPE_VEHICLE",
}

var DeviceType_value = map[string]int32{
	"DEVICE_TYPE_INVALID":  0,
	"DEVICE_TYPE_MOBILE":   1,
	"DEVICE_TYPE_TABLET":   2,
	"DEVICE_TYPE_DESKTOP":  3,
	"DEVICE_TYPE_WEARABLE": 4,
	"DEVICE_TYPE_CONSOLE":  5,
	"DEVICE_TYPE_VEHICLE":  6,
}

func (x DeviceType) String() string {
	return proto.EnumName(DeviceType_name, int32(x))
}

func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8da54e8823fce2f7, []int{3}
}

type StatementDescriptor struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatementDescriptor) Reset()         { *m = StatementDescriptor{} }
func (m *StatementDescriptor) String() string { return proto.CompactTextString(m) }
func (*StatementDescriptor) ProtoMessage()    {}
func (*StatementDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_8da54e8823fce2f7, []int{0}
}
func (m *StatementDescriptor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatementDescriptor.Unmarshal(m, b)
}
func (m *StatementDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatementDescriptor.Marshal(b, m, deterministic)
}
func (m *StatementDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatementDescriptor.Merge(m, src)
}
func (m *StatementDescriptor) XXX_Size() int {
	return xxx_messageInfo_StatementDescriptor.Size(m)
}
func (m *StatementDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_StatementDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_StatementDescriptor proto.InternalMessageInfo

func (m *StatementDescriptor) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *StatementDescriptor) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type Charge struct {
	ChargeId             string                    `protobuf:"bytes,1,opt,name=charge_id,json=chargeId,proto3" json:"charge_id,omitempty"`
	Version              string                    `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Intent               ChargeIntent              `protobuf:"varint,3,opt,name=intent,proto3,enum=chargehive.chtype.ChargeIntent" json:"intent,omitempty"`
	Contract             ContractType              `protobuf:"varint,4,opt,name=contract,proto3,enum=chargehive.chtype.ContractType" json:"contract,omitempty"`
	Amount               *Amount                   `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethodIds     []string                  `protobuf:"bytes,6,rep,name=payment_method_ids,json=paymentMethodIds,proto3" json:"payment_method_ids,omitempty"`
	ExpiryTime           *timestamppb.Timestamp    `protobuf:"bytes,7,opt,name=expiry_time,json=expiryTime,proto3" json:"expiry_time,omitempty"`
	MerchantReference    string                    `protobuf:"bytes,8,opt,name=merchant_reference,json=merchantReference,proto3" json:"merchant_reference,omitempty"`
	StatementDescriptor  *StatementDescriptor      `protobuf:"bytes,9,opt,name=statement_descriptor,json=statementDescriptor,proto3" json:"statement_descriptor,omitempty"`
	References           map[string]string         `protobuf:"bytes,10,rep,name=references,proto3" json:"references,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Labels               []*Label                  `protobuf:"bytes,11,rep,name=labels,proto3" json:"labels,omitempty"`
	ChargeKey            string                    `protobuf:"bytes,12,opt,name=charge_key,json=chargeKey,proto3" json:"charge_key,omitempty"`
	UserLocale           string                    `protobuf:"bytes,13,opt,name=user_locale,json=userLocale,proto3" json:"user_locale,omitempty"`
	UserLocation         string                    `protobuf:"bytes,14,opt,name=user_location,json=userLocation,proto3" json:"user_location,omitempty"`
	Environment          ChargeEnvironment         `protobuf:"varint,15,opt,name=environment,proto3,enum=chargehive.chtype.ChargeEnvironment" json:"environment,omitempty"`
	Language             Language                  `protobuf:"varint,16,opt,name=language,proto3,enum=chargehive.chtype.Language" json:"language,omitempty"`
	PreferredMethodType  PaymentMethodType         `protobuf:"varint,17,opt,name=preferred_method_type,json=preferredMethodType,proto3,enum=chargehive.chtype.PaymentMethodType" json:"preferred_method_type,omitempty"`
	BillingProfileId     string                    `protobuf:"bytes,18,opt,name=billing_profile_id,json=billingProfileId,proto3" json:"billing_profile_id,omitempty"`
	InitialTransaction   []*InitialTransactionData `protobuf:"bytes,19,rep,name=initial_transaction,json=initialTransaction,proto3" json:"initial_transaction,omitempty"`
	SubscriptionId       string                    `protobuf:"bytes,20,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Charge) Reset()         { *m = Charge{} }
func (m *Charge) String() string { return proto.CompactTextString(m) }
func (*Charge) ProtoMessage()    {}
func (*Charge) Descriptor() ([]byte, []int) {
	return fileDescriptor_8da54e8823fce2f7, []int{1}
}
func (m *Charge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Charge.Unmarshal(m, b)
}
func (m *Charge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Charge.Marshal(b, m, deterministic)
}
func (m *Charge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Charge.Merge(m, src)
}
func (m *Charge) XXX_Size() int {
	return xxx_messageInfo_Charge.Size(m)
}
func (m *Charge) XXX_DiscardUnknown() {
	xxx_messageInfo_Charge.DiscardUnknown(m)
}

var xxx_messageInfo_Charge proto.InternalMessageInfo

func (m *Charge) GetChargeId() string {
	if m != nil {
		return m.ChargeId
	}
	return ""
}

func (m *Charge) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Charge) GetIntent() ChargeIntent {
	if m != nil {
		return m.Intent
	}
	return CHARGE_INTENT_INVALID
}

func (m *Charge) GetContract() ContractType {
	if m != nil {
		return m.Contract
	}
	return CONTRACT_TYPE_INVALID
}

func (m *Charge) GetAmount() *Amount {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *Charge) GetPaymentMethodIds() []string {
	if m != nil {
		return m.PaymentMethodIds
	}
	return nil
}

func (m *Charge) GetExpiryTime() *timestamppb.Timestamp {
	if m != nil {
		return m.ExpiryTime
	}
	return nil
}

func (m *Charge) GetMerchantReference() string {
	if m != nil {
		return m.MerchantReference
	}
	return ""
}

func (m *Charge) GetStatementDescriptor() *StatementDescriptor {
	if m != nil {
		return m.StatementDescriptor
	}
	return nil
}

func (m *Charge) GetReferences() map[string]string {
	if m != nil {
		return m.References
	}
	return nil
}

func (m *Charge) GetLabels() []*Label {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Charge) GetChargeKey() string {
	if m != nil {
		return m.ChargeKey
	}
	return ""
}

func (m *Charge) GetUserLocale() string {
	if m != nil {
		return m.UserLocale
	}
	return ""
}

func (m *Charge) GetUserLocation() string {
	if m != nil {
		return m.UserLocation
	}
	return ""
}

func (m *Charge) GetEnvironment() ChargeEnvironment {
	if m != nil {
		return m.Environment
	}
	return CHARGE_ENVIRONMENT_INVALID
}

func (m *Charge) GetLanguage() Language {
	if m != nil {
		return m.Language
	}
	return LANGUAGE_INVALID
}

func (m *Charge) GetPreferredMethodType() PaymentMethodType {
	if m != nil {
		return m.PreferredMethodType
	}
	return PAYMENT_METHOD_TYPE_INVALID
}

func (m *Charge) GetBillingProfileId() string {
	if m != nil {
		return m.BillingProfileId
	}
	return ""
}

func (m *Charge) GetInitialTransaction() []*InitialTransactionData {
	if m != nil {
		return m.InitialTransaction
	}
	return nil
}

func (m *Charge) GetSubscriptionId() string {
	if m != nil {
		return m.SubscriptionId
	}
	return ""
}

type ChargeItem struct {
	SubscriptionId       string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	RenewalNumber        int32                  `protobuf:"varint,2,opt,name=renewal_number,json=renewalNumber,proto3" json:"renewal_number,omitempty"`
	Duration             int64                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	StartDate            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	ProductType          ProductType            `protobuf:"varint,6,opt,name=product_type,json=productType,proto3,enum=chargehive.chtype.ProductType" json:"product_type,omitempty"`
	SkuType              SKUType                `protobuf:"varint,7,opt,name=sku_type,json=skuType,proto3,enum=chargehive.chtype.SKUType" json:"sku_type,omitempty"`
	Delivery             *Delivery              `protobuf:"bytes,8,opt,name=delivery,proto3" json:"delivery,omitempty"`
	Quantity             int64                  `protobuf:"varint,9,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice            *Amount                `protobuf:"bytes,10,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	TaxAmount            *Amount                `protobuf:"bytes,11,opt,name=tax_amount,json=taxAmount,proto3" json:"tax_amount,omitempty"`
	DiscountAmount       *Amount                `protobuf:"bytes,12,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	Name                 string                 `protobuf:"bytes,13,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,14,opt,name=description,proto3" json:"description,omitempty"`
	ProductCode          string                 `protobuf:"bytes,15,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`
	SkuCode              string                 `protobuf:"bytes,16,opt,name=sku_code,json=skuCode,proto3" json:"sku_code,omitempty"`
	TermUnits            int64                  `protobuf:"varint,17,opt,name=term_units,json=termUnits,proto3" json:"term_units,omitempty"`
	TermType             TermType               `protobuf:"varint,18,opt,name=term_type,json=termType,proto3,enum=chargehive.chtype.TermType" json:"term_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ChargeItem) Reset()         { *m = ChargeItem{} }
func (m *ChargeItem) String() string { return proto.CompactTextString(m) }
func (*ChargeItem) ProtoMessage()    {}
func (*ChargeItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_8da54e8823fce2f7, []int{2}
}
func (m *ChargeItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChargeItem.Unmarshal(m, b)
}
func (m *ChargeItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChargeItem.Marshal(b, m, deterministic)
}
func (m *ChargeItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChargeItem.Merge(m, src)
}
func (m *ChargeItem) XXX_Size() int {
	return xxx_messageInfo_ChargeItem.Size(m)
}
func (m *ChargeItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ChargeItem.DiscardUnknown(m)
}

var xxx_messageInfo_ChargeItem proto.InternalMessageInfo

func (m *ChargeItem) GetSubscriptionId() string {
	if m != nil {
		return m.SubscriptionId
	}
	return ""
}

func (m *ChargeItem) GetRenewalNumber() int32 {
	if m != nil {
		return m.RenewalNumber
	}
	return 0
}

func (m *ChargeItem) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *ChargeItem) GetStartDate() *timestamppb.Timestamp {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *ChargeItem) GetEndDate() *timestamppb.Timestamp {
	if m != nil {
		return m.EndDate
	}
	return nil
}

func (m *ChargeItem) GetProductType() ProductType {
	if m != nil {
		return m.ProductType
	}
	return PRODUCT_TYPE_INVALID
}

func (m *ChargeItem) GetSkuType() SKUType {
	if m != nil {
		return m.SkuType
	}
	return SKU_TYPE_INVALID
}

func (m *ChargeItem) GetDelivery() *Delivery {
	if m != nil {
		return m.Delivery
	}
	return nil
}

func (m *ChargeItem) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *ChargeItem) GetUnitPrice() *Amount {
	if m != nil {
		return m.UnitPrice
	}
	return nil
}

func (m *ChargeItem) GetTaxAmount() *Amount {
	if m != nil {
		return m.TaxAmount
	}
	return nil
}

func (m *ChargeItem) GetDiscountAmount() *Amount {
	if m != nil {
		return m.DiscountAmount
	}
	return nil
}

func (m *ChargeItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChargeItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ChargeItem) GetProductCode() string {
	if m != nil {
		return m.ProductCode
	}
	return ""
}

func (m *ChargeItem) GetSkuCode() string {
	if m != nil {
		return m.SkuCode
	}
	return ""
}

func (m *ChargeItem) GetTermUnits() int64 {
	if m != nil {
		return m.TermUnits
	}
	return 0
}

func (m *ChargeItem) GetTermType() TermType {
	if m != nil {
		return m.TermType
	}
	return TERM_TYPE_INVALID
}

type ChargeMeta struct {
	BillingAddress       *Address               `protobuf:"bytes,1,opt,name=billing_address,json=billingAddress,proto3" json:"billing_address,omitempty"`
	DeliveryAddress      *Address               `protobuf:"bytes,2,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	Items                []*ChargeItem          `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Terms                string                 `protobuf:"bytes,4,opt,name=terms,proto3" json:"terms,omitempty"`
	Note                 string                 `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	MerchantMemo         string                 `protobuf:"bytes,6,opt,name=merchant_memo,json=merchantMemo,proto3" json:"merchant_memo,omitempty"`
	InvoiceDate          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=invoice_date,json=invoiceDate,proto3" json:"invoice_date,omitempty"`
	DueDate              *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	DiscountAmount       *Amount                `protobuf:"bytes,9,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	DeliveryAmount       *Amount                `protobuf:"bytes,10,opt,name=delivery_amount,json=deliveryAmount,proto3" json:"delivery_amount,omitempty"`
	TaxAmount            *Amount                `protobuf:"bytes,11,opt,name=tax_amount,json=taxAmount,proto3" json:"tax_amount,omitempty"`
	TotalAmount          *Amount                `protobuf:"bytes,12,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Person               *Person                `protobuf:"bytes,13,opt,name=person,proto3" json:"person,omitempty"`
	Company              *Company               `protobuf:"bytes,14,opt,name=company,proto3" json:"company,omitempty"`
	IpAddress            string                 `protobuf:"bytes,15,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Delivery             *Delivery              `protobuf:"bytes,16,opt,name=delivery,proto3" json:"delivery,omitempty"`
	Device               *Device                `protobuf:"bytes,17,opt,name=device,proto3" json:"device,omitempty"`
	CustomerId           string                 `protobuf:"bytes,18,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	PlacementId          string                 `protobuf:"bytes,19,opt,name=placement_id,json=placementId,proto3" json:"placement_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ChargeMeta) Reset()         { *m = ChargeMeta{} }
func (m *ChargeMeta) String() string { return proto.CompactTextString(m) }
func (*ChargeMeta) ProtoMessage()    {}
func (*ChargeMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_8da54e8823fce2f7, []int{3}
}
func (m *ChargeMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChargeMeta.Unmarshal(m, b)
}
func (m *ChargeMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChargeMeta.Marshal(b, m, deterministic)
}
func (m *ChargeMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChargeMeta.Merge(m, src)
}
func (m *ChargeMeta) XXX_Size() int {
	return xxx_messageInfo_ChargeMeta.Size(m)
}
func (m *ChargeMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ChargeMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ChargeMeta proto.InternalMessageInfo

func (m *ChargeMeta) GetBillingAddress() *Address {
	if m != nil {
		return m.BillingAddress
	}
	return nil
}

func (m *ChargeMeta) GetDeliveryAddress() *Address {
	if m != nil {
		return m.DeliveryAddress
	}
	return nil
}

func (m *ChargeMeta) GetItems() []*ChargeItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ChargeMeta) GetTerms() string {
	if m != nil {
		return m.Terms
	}
	return ""
}

func (m *ChargeMeta) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *ChargeMeta) GetMerchantMemo() string {
	if m != nil {
		return m.MerchantMemo
	}
	return ""
}

func (m *ChargeMeta) GetInvoiceDate() *timestamppb.Timestamp {
	if m != nil {
		return m.InvoiceDate
	}
	return nil
}

func (m *ChargeMeta) GetDueDate() *timestamppb.Timestamp {
	if m != nil {
		return m.DueDate
	}
	return nil
}

func (m *ChargeMeta) GetDiscountAmount() *Amount {
	if m != nil {
		return m.DiscountAmount
	}
	return nil
}

func (m *ChargeMeta) GetDeliveryAmount() *Amount {
	if m != nil {
		return m.DeliveryAmount
	}
	return nil
}

func (m *ChargeMeta) GetTaxAmount() *Amount {
	if m != nil {
		return m.TaxAmount
	}
	return nil
}

func (m *ChargeMeta) GetTotalAmount() *Amount {
	if m != nil {
		return m.TotalAmount
	}
	return nil
}

func (m *ChargeMeta) GetPerson() *Person {
	if m != nil {
		return m.Person
	}
	return nil
}

func (m *ChargeMeta) GetCompany() *Company {
	if m != nil {
		return m.Company
	}
	return nil
}

func (m *ChargeMeta) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *ChargeMeta) GetDelivery() *Delivery {
	if m != nil {
		return m.Delivery
	}
	return nil
}

func (m *ChargeMeta) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *ChargeMeta) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *ChargeMeta) GetPlacementId() string {
	if m != nil {
		return m.PlacementId
	}
	return ""
}

type Delivery struct {
	Standard             DeliveryStandard `protobuf:"varint,1,opt,name=standard,proto3,enum=chargehive.chtype.DeliveryStandard" json:"standard,omitempty"`
	Type                 DeliveryType     `protobuf:"varint,2,opt,name=type,proto3,enum=chargehive.chtype.DeliveryType" json:"type,omitempty"`
	TrackingCode         string           `protobuf:"bytes,3,opt,name=tracking_code,json=trackingCode,proto3" json:"tracking_code,omitempty"`
	Courier              string           `protobuf:"bytes,4,opt,name=courier,proto3" json:"courier,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Delivery) Reset()         { *m = Delivery{} }
func (m *Delivery) String() string { return proto.CompactTextString(m) }
func (*Delivery) ProtoMessage()    {}
func (*Delivery) Descriptor() ([]byte, []int) {
	return fileDescriptor_8da54e8823fce2f7, []int{4}
}
func (m *Delivery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Delivery.Unmarshal(m, b)
}
func (m *Delivery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Delivery.Marshal(b, m, deterministic)
}
func (m *Delivery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delivery.Merge(m, src)
}
func (m *Delivery) XXX_Size() int {
	return xxx_messageInfo_Delivery.Size(m)
}
func (m *Delivery) XXX_DiscardUnknown() {
	xxx_messageInfo_Delivery.DiscardUnknown(m)
}

var xxx_messageInfo_Delivery proto.InternalMessageInfo

func (m *Delivery) GetStandard() DeliveryStandard {
	if m != nil {
		return m.Standard
	}
	return DELIVERY_STANDARD_INVALID
}

func (m *Delivery) GetType() DeliveryType {
	if m != nil {
		return m.Type
	}
	return DELIVERY_TYPE_INVALID
}

func (m *Delivery) GetTrackingCode() string {
	if m != nil {
		return m.TrackingCode
	}
	return ""
}

func (m *Delivery) GetCourier() string {
	if m != nil {
		return m.Courier
	}
	return ""
}

type ChargeSummary struct {
	Amount               *Amount  `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Status               Status   `protobuf:"varint,2,opt,name=status,proto3,enum=chargehive.chtype.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChargeSummary) Reset()         { *m = ChargeSummary{} }
func (m *ChargeSummary) String() string { return proto.CompactTextString(m) }
func (*ChargeSummary) ProtoMessage()    {}
func (*ChargeSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_8da54e8823fce2f7, []int{5}
}
func (m *ChargeSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChargeSummary.Unmarshal(m, b)
}
func (m *ChargeSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChargeSummary.Marshal(b, m, deterministic)
}
func (m *ChargeSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChargeSummary.Merge(m, src)
}
func (m *ChargeSummary) XXX_Size() int {
	return xxx_messageInfo_ChargeSummary.Size(m)
}
func (m *ChargeSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_ChargeSummary.DiscardUnknown(m)
}

var xxx_messageInfo_ChargeSummary proto.InternalMessageInfo

func (m *ChargeSummary) GetAmount() *Amount {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *ChargeSummary) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return STATUS_INVALID
}

type Dimension struct {
	Width                int32    `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dimension) Reset()         { *m = Dimension{} }
func (m *Dimension) String() string { return proto.CompactTextString(m) }
func (*Dimension) ProtoMessage()    {}
func (*Dimension) Descriptor() ([]byte, []int) {
	return fileDescriptor_8da54e8823fce2f7, []int{6}
}
func (m *Dimension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dimension.Unmarshal(m, b)
}
func (m *Dimension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dimension.Marshal(b, m, deterministic)
}
func (m *Dimension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dimension.Merge(m, src)
}
func (m *Dimension) XXX_Size() int {
	return xxx_messageInfo_Dimension.Size(m)
}
func (m *Dimension) XXX_DiscardUnknown() {
	xxx_messageInfo_Dimension.DiscardUnknown(m)
}

var xxx_messageInfo_Dimension proto.InternalMessageInfo

func (m *Dimension) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Dimension) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type Device struct {
	BrowserAcceptHeader  string     `protobuf:"bytes,1,opt,name=browser_accept_header,json=browserAcceptHeader,proto3" json:"browser_accept_header,omitempty"`
	ColorDepth           int32      `protobuf:"varint,2,opt,name=color_depth,json=colorDepth,proto3" json:"color_depth,omitempty"`
	JavaEnabled          bool       `protobuf:"varint,3,opt,name=java_enabled,json=javaEnabled,proto3" json:"java_enabled,omitempty"`
	JavascriptEnabled    bool       `protobuf:"varint,4,opt,name=javascript_enabled,json=javascriptEnabled,proto3" json:"javascript_enabled,omitempty"`
	Language             string     `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	Screen               *Dimension `protobuf:"bytes,6,opt,name=screen,proto3" json:"screen,omitempty"`
	ScreenAvailable      *Dimension `protobuf:"bytes,7,opt,name=screen_available,json=screenAvailable,proto3" json:"screen_available,omitempty"`
	WindowInner          *Dimension `protobuf:"bytes,8,opt,name=window_inner,json=windowInner,proto3" json:"window_inner,omitempty"`
	WindowOuter          *Dimension `protobuf:"bytes,9,opt,name=window_outer,json=windowOuter,proto3" json:"window_outer,omitempty"`
	TimezoneOffsetMins   int32      `protobuf:"varint,10,opt,name=timezone_offset_mins,json=timezoneOffsetMins,proto3" json:"timezone_offset_mins,omitempty"`
	UserAgent            string     `protobuf:"bytes,11,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	IpAddress            string     `protobuf:"bytes,12,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	CookiesEnabled       bool       `protobuf:"varint,13,opt,name=cookies_enabled,json=cookiesEnabled,proto3" json:"cookies_enabled,omitempty"`
	FlashVersion         string     `protobuf:"bytes,14,opt,name=flash_version,json=flashVersion,proto3" json:"flash_version,omitempty"`
	IsTouch              bool       `protobuf:"varint,15,opt,name=is_touch,json=isTouch,proto3" json:"is_touch,omitempty"`
	Os                   string     `protobuf:"bytes,16,opt,name=os,proto3" json:"os,omitempty"`
	OsVersion            string     `protobuf:"bytes,17,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	Browser              string     `protobuf:"bytes,18,opt,name=browser,proto3" json:"browser,omitempty"`
	BrowserVersion       string     `protobuf:"bytes,19,opt,name=browser_version,json=browserVersion,proto3" json:"browser_version,omitempty"`
	DeviceManufacturer   string     `protobuf:"bytes,20,opt,name=device_manufacturer,json=deviceManufacturer,proto3" json:"device_manufacturer,omitempty"`
	DeviceName           string     `protobuf:"bytes,21,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	DeviceVersion        string     `protobuf:"bytes,22,opt,name=device_version,json=deviceVersion,proto3" json:"device_version,omitempty"`
	Fingerprint          string     `protobuf:"bytes,23,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Type                 DeviceType `protobuf:"varint,24,opt,name=type,proto3,enum=chargehive.chtype.DeviceType" json:"type,omitempty"`
	Timezone             string     `protobuf:"bytes,25,opt,name=timezone,proto3" json:"timezone,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_8da54e8823fce2f7, []int{7}
}
func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetBrowserAcceptHeader() string {
	if m != nil {
		return m.BrowserAcceptHeader
	}
	return ""
}

func (m *Device) GetColorDepth() int32 {
	if m != nil {
		return m.ColorDepth
	}
	return 0
}

func (m *Device) GetJavaEnabled() bool {
	if m != nil {
		return m.JavaEnabled
	}
	return false
}

func (m *Device) GetJavascriptEnabled() bool {
	if m != nil {
		return m.JavascriptEnabled
	}
	return false
}

func (m *Device) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Device) GetScreen() *Dimension {
	if m != nil {
		return m.Screen
	}
	return nil
}

func (m *Device) GetScreenAvailable() *Dimension {
	if m != nil {
		return m.ScreenAvailable
	}
	return nil
}

func (m *Device) GetWindowInner() *Dimension {
	if m != nil {
		return m.WindowInner
	}
	return nil
}

func (m *Device) GetWindowOuter() *Dimension {
	if m != nil {
		return m.WindowOuter
	}
	return nil
}

func (m *Device) GetTimezoneOffsetMins() int32 {
	if m != nil {
		return m.TimezoneOffsetMins
	}
	return 0
}

func (m *Device) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *Device) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *Device) GetCookiesEnabled() bool {
	if m != nil {
		return m.CookiesEnabled
	}
	return false
}

func (m *Device) GetFlashVersion() string {
	if m != nil {
		return m.FlashVersion
	}
	return ""
}

func (m *Device) GetIsTouch() bool {
	if m != nil {
		return m.IsTouch
	}
	return false
}

func (m *Device) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *Device) GetOsVersion() string {
	if m != nil {
		return m.OsVersion
	}
	return ""
}

func (m *Device) GetBrowser() string {
	if m != nil {
		return m.Browser
	}
	return ""
}

func (m *Device) GetBrowserVersion() string {
	if m != nil {
		return m.BrowserVersion
	}
	return ""
}

func (m *Device) GetDeviceManufacturer() string {
	if m != nil {
		return m.DeviceManufacturer
	}
	return ""
}

func (m *Device) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *Device) GetDeviceVersion() string {
	if m != nil {
		return m.DeviceVersion
	}
	return ""
}

func (m *Device) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *Device) GetType() DeviceType {
	if m != nil {
		return m.Type
	}
	return DEVICE_TYPE_INVALID
}

func (m *Device) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func init() {
	proto.RegisterEnum("chargehive.chtype.ChargeMetaType", ChargeMetaType_name, ChargeMetaType_value)
	golang_proto.RegisterEnum("chargehive.chtype.ChargeMetaType", ChargeMetaType_name, ChargeMetaType_value)
	proto.RegisterEnum("chargehive.chtype.ChargeIntent", ChargeIntent_name, ChargeIntent_value)
	golang_proto.RegisterEnum("chargehive.chtype.ChargeIntent", ChargeIntent_name, ChargeIntent_value)
	proto.RegisterEnum("chargehive.chtype.ChargeEnvironment", ChargeEnvironment_name, ChargeEnvironment_value)
	golang_proto.RegisterEnum("chargehive.chtype.ChargeEnvironment", ChargeEnvironment_name, ChargeEnvironment_value)
	proto.RegisterEnum("chargehive.chtype.DeviceType", DeviceType_name, DeviceType_value)
	golang_proto.RegisterEnum("chargehive.chtype.DeviceType", DeviceType_name, DeviceType_value)
	proto.RegisterType((*StatementDescriptor)(nil), "chargehive.chtype.StatementDescriptor")
	golang_proto.RegisterType((*StatementDescriptor)(nil), "chargehive.chtype.StatementDescriptor")
	proto.RegisterType((*Charge)(nil), "chargehive.chtype.Charge")
	golang_proto.RegisterType((*Charge)(nil), "chargehive.chtype.Charge")
	proto.RegisterMapType((map[string]string)(nil), "chargehive.chtype.Charge.ReferencesEntry")
	golang_proto.RegisterMapType((map[string]string)(nil), "chargehive.chtype.Charge.ReferencesEntry")
	proto.RegisterType((*ChargeItem)(nil), "chargehive.chtype.ChargeItem")
	golang_proto.RegisterType((*ChargeItem)(nil), "chargehive.chtype.ChargeItem")
	proto.RegisterType((*ChargeMeta)(nil), "chargehive.chtype.ChargeMeta")
	golang_proto.RegisterType((*ChargeMeta)(nil), "chargehive.chtype.ChargeMeta")
	proto.RegisterType((*Delivery)(nil), "chargehive.chtype.Delivery")
	golang_proto.RegisterType((*Delivery)(nil), "chargehive.chtype.Delivery")
	proto.RegisterType((*ChargeSummary)(nil), "chargehive.chtype.ChargeSummary")
	golang_proto.RegisterType((*ChargeSummary)(nil), "chargehive.chtype.ChargeSummary")
	proto.RegisterType((*Dimension)(nil), "chargehive.chtype.Dimension")
	golang_proto.RegisterType((*Dimension)(nil), "chargehive.chtype.Dimension")
	proto.RegisterType((*Device)(nil), "chargehive.chtype.Device")
	golang_proto.RegisterType((*Device)(nil), "chargehive.chtype.Device")
}

func init() { proto.RegisterFile("chargehive/chtype/charge.proto", fileDescriptor_8da54e8823fce2f7) }
func init() {
	golang_proto.RegisterFile("chargehive/chtype/charge.proto", fileDescriptor_8da54e8823fce2f7)
}

var fileDescriptor_8da54e8823fce2f7 = []byte{
	// 2147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x58, 0xdd, 0x72, 0xdb, 0xc6,
	0x15, 0x0e, 0x49, 0x89, 0x22, 0x0f, 0x25, 0x0a, 0x5a, 0xc9, 0x36, 0x24, 0xff, 0xa9, 0x72, 0xd3,
	0xb8, 0x9e, 0x56, 0x8a, 0x65, 0x77, 0xec, 0x34, 0xcd, 0x64, 0x68, 0x12, 0x8e, 0x38, 0x16, 0x49,
	0xcd, 0x8a, 0x56, 0xea, 0x4c, 0x66, 0x30, 0x2b, 0x60, 0x45, 0x6e, 0x45, 0x60, 0x59, 0x60, 0x21,
	0x5b, 0xbd, 0xeb, 0x7d, 0x5f, 0xa6, 0xb7, 0xbd, 0x68, 0x7a, 0x9d, 0xab, 0xbe, 0x42, 0xdb, 0x17,
	0xe9, 0xec, 0x1f, 0x49, 0x8b, 0xa4, 0xe5, 0xe4, 0x8a, 0xd8, 0x73, 0xbe, 0xef, 0xec, 0x62, 0xcf,
	0x39, 0x1f, 0x76, 0x09, 0xf7, 0x82, 0x3e, 0x49, 0x7a, 0xb4, 0xcf, 0x2e, 0xe8, 0x5e, 0xd0, 0x17,
	0x97, 0x43, 0xf9, 0x23, 0x2d, 0xbb, 0xc3, 0x84, 0x0b, 0x8e, 0xd6, 0xc6, 0xfe, 0x5d, 0xed, 0xdf,
	0xda, 0xe8, 0xf1, 0x1e, 0x57, 0xde, 0x3d, 0xf9, 0xa4, 0x81, 0x5b, 0xf7, 0xa7, 0x03, 0xf5, 0x68,
	0x4c, 0x13, 0x16, 0xcc, 0x07, 0x04, 0x3c, 0x16, 0x24, 0x10, 0x06, 0xb0, 0x3d, 0x0d, 0x18, 0x90,
	0xb8, 0x97, 0x11, 0xbb, 0x98, 0xad, 0x3b, 0xd3, 0x08, 0x1a, 0x67, 0x91, 0xf1, 0x3e, 0x98, 0xf6,
	0x8a, 0x84, 0xc4, 0x29, 0x09, 0x04, 0xe3, 0xb1, 0x5d, 0x45, 0x8f, 0xf3, 0xde, 0x80, 0xee, 0xa9,
	0xd1, 0x69, 0x76, 0xb6, 0x27, 0x58, 0x44, 0x53, 0x41, 0xa2, 0xa1, 0x06, 0xec, 0x78, 0xb0, 0x7e,
	0x2c, 0x88, 0xa0, 0x11, 0x8d, 0x45, 0x83, 0xa6, 0x41, 0xc2, 0x86, 0x82, 0x27, 0xc8, 0x85, 0xa5,
	0x88, 0xa6, 0x29, 0xe9, 0x51, 0x37, 0xb7, 0x9d, 0x7b, 0x58, 0xc6, 0x76, 0x88, 0x36, 0x60, 0x71,
	0xd8, 0xe7, 0x31, 0x75, 0xf3, 0xca, 0xae, 0x07, 0x3b, 0x7f, 0x2b, 0x43, 0xb1, 0xae, 0xd6, 0x83,
	0x6e, 0x43, 0x59, 0xaf, 0xcc, 0x67, 0xa1, 0x21, 0x97, 0xb4, 0xa1, 0x19, 0xca, 0xb8, 0x17, 0x34,
	0x49, 0x19, 0x8f, 0x0d, 0xdf, 0x0e, 0xd1, 0x33, 0x28, 0xb2, 0x58, 0xd0, 0x58, 0xb8, 0x85, 0xed,
	0xdc, 0xc3, 0xea, 0xfe, 0xfd, 0xdd, 0xa9, 0x54, 0xec, 0xea, 0x19, 0x9a, 0x0a, 0x86, 0x0d, 0x1c,
	0x7d, 0x09, 0x25, 0xb9, 0xb1, 0x09, 0x09, 0x84, 0xbb, 0x30, 0x9f, 0x6a, 0x20, 0xdd, 0xcb, 0x21,
	0xc5, 0x23, 0x02, 0x7a, 0x0c, 0x45, 0x12, 0xf1, 0x2c, 0x16, 0xee, 0xe2, 0x76, 0xee, 0x61, 0x65,
	0x7f, 0x73, 0x06, 0xb5, 0xa6, 0x00, 0xd8, 0x00, 0xd1, 0x6f, 0x00, 0x0d, 0xc9, 0xa5, 0xdc, 0x2f,
	0x3f, 0xa2, 0xa2, 0xcf, 0x43, 0x9f, 0x85, 0xa9, 0x5b, 0xdc, 0x2e, 0x3c, 0x2c, 0x63, 0xc7, 0x78,
	0x5a, 0xca, 0xd1, 0x0c, 0x53, 0xf4, 0x25, 0x54, 0xe8, 0xbb, 0x21, 0x4b, 0x2e, 0x7d, 0xb9, 0xf3,
	0xee, 0x92, 0x9a, 0x65, 0x6b, 0x57, 0xa7, 0x65, 0xd7, 0xa6, 0x65, 0xb7, 0x6b, 0xd3, 0x82, 0x41,
	0xc3, 0xa5, 0x01, 0xfd, 0x16, 0x50, 0x44, 0x93, 0xa0, 0x4f, 0x62, 0xe1, 0x27, 0xf4, 0x8c, 0x26,
	0x34, 0x0e, 0xa8, 0x5b, 0x52, 0x1b, 0xb7, 0x66, 0x3d, 0xd8, 0x3a, 0xd0, 0x1b, 0xd8, 0x48, 0x6d,
	0x2e, 0xfd, 0x70, 0x94, 0x4c, 0xb7, 0xac, 0x26, 0xfd, 0xd5, 0x8c, 0x57, 0x9b, 0x91, 0x7a, 0xbc,
	0x9e, 0xce, 0xa8, 0x87, 0x26, 0xc0, 0x68, 0x01, 0xa9, 0x0b, 0xdb, 0x85, 0x87, 0x95, 0xfd, 0x5f,
	0xcf, 0xcd, 0xd0, 0xee, 0x68, 0x4d, 0xa9, 0x17, 0x8b, 0xe4, 0x12, 0x4f, 0x90, 0xd1, 0xe7, 0x50,
	0x1c, 0x90, 0x53, 0x3a, 0x48, 0xdd, 0x8a, 0x0a, 0xe3, 0xce, 0x08, 0x73, 0x28, 0x01, 0xd8, 0xe0,
	0xd0, 0x5d, 0x00, 0x53, 0x51, 0xe7, 0xf4, 0xd2, 0x5d, 0x56, 0xaf, 0x6f, 0x6a, 0xec, 0x15, 0xbd,
	0x44, 0xf7, 0xa1, 0x92, 0xa5, 0x34, 0xf1, 0x07, 0x3c, 0x20, 0x03, 0xea, 0xae, 0x28, 0x3f, 0x48,
	0xd3, 0xa1, 0xb2, 0xa0, 0x07, 0xb0, 0x32, 0x02, 0xc8, 0xde, 0x70, 0xab, 0x0a, 0xb2, 0x6c, 0x21,
	0xd2, 0x86, 0x5e, 0x42, 0x85, 0xc6, 0x17, 0x2c, 0xe1, 0xb1, 0x7c, 0x75, 0x77, 0x55, 0x55, 0xd2,
	0x2f, 0xe7, 0xbe, 0xa2, 0x37, 0xc6, 0xe2, 0x49, 0x22, 0x7a, 0x06, 0x25, 0xdb, 0xc6, 0xae, 0xa3,
	0x82, 0xdc, 0x9e, 0xf9, 0x82, 0x1a, 0x82, 0x47, 0x60, 0xf4, 0x47, 0xb8, 0x31, 0x54, 0xdb, 0x94,
	0xd0, 0xd0, 0x56, 0x96, 0xc4, 0xba, 0x6b, 0x73, 0x97, 0x72, 0x34, 0x59, 0x6d, 0xaa, 0xb2, 0xd7,
	0x47, 0x21, 0xc6, 0x46, 0x59, 0xb1, 0xa7, 0x6c, 0x30, 0x60, 0x71, 0xcf, 0x1f, 0x26, 0xfc, 0x8c,
	0x0d, 0x54, 0x6b, 0x22, 0xb5, 0x09, 0x8e, 0xf1, 0x1c, 0x69, 0x47, 0x33, 0x44, 0xdf, 0xc1, 0x3a,
	0x8b, 0x99, 0x60, 0x64, 0xe0, 0x4f, 0xe8, 0x89, 0xbb, 0x3e, 0x37, 0xe7, 0x4d, 0x8d, 0xee, 0x8e,
	0xc1, 0x0d, 0x22, 0x08, 0x46, 0x6c, 0xca, 0x8e, 0x3e, 0x83, 0xd5, 0x34, 0x3b, 0xd5, 0x55, 0xc5,
	0x78, 0x2c, 0x97, 0xb1, 0xa1, 0x96, 0x51, 0x9d, 0x34, 0x37, 0xc3, 0xad, 0xaf, 0x60, 0xf5, 0x4a,
	0x0d, 0x21, 0x07, 0x0a, 0x32, 0xfd, 0x5a, 0x51, 0xe4, 0xa3, 0x94, 0xa2, 0x0b, 0x32, 0xc8, 0x46,
	0x52, 0xa4, 0x06, 0xbf, 0xcf, 0x3f, 0xcf, 0xed, 0xfc, 0xb3, 0x08, 0x60, 0xc4, 0x42, 0xd0, 0x68,
	0xd6, 0xb4, 0xb9, 0x59, 0xd3, 0xa2, 0x4f, 0xa1, 0x9a, 0xd0, 0x98, 0xbe, 0x25, 0x03, 0x3f, 0xce,
	0xa2, 0x53, 0x9a, 0xa8, 0xd0, 0x8b, 0x78, 0xc5, 0x58, 0xdb, 0xca, 0x88, 0xb6, 0xa0, 0x14, 0x66,
	0x89, 0xae, 0x25, 0xa9, 0x56, 0x05, 0x3c, 0x1a, 0xa3, 0x2f, 0x00, 0x52, 0x41, 0x12, 0xe1, 0x87,
	0x44, 0x50, 0x25, 0x48, 0x1f, 0xee, 0xf7, 0xb2, 0x42, 0x37, 0x88, 0xa0, 0xe8, 0x77, 0x50, 0xa2,
	0x71, 0xa8, 0x89, 0x8b, 0xd7, 0x12, 0x97, 0x68, 0x1c, 0x2a, 0x5a, 0x0d, 0x96, 0x87, 0x09, 0x0f,
	0xb3, 0x40, 0xe8, 0x7a, 0x29, 0xaa, 0x7a, 0xb9, 0x37, 0xab, 0x5e, 0x34, 0x4c, 0x55, 0x4a, 0x65,
	0x38, 0x1e, 0xc8, 0x99, 0xd3, 0xf3, 0x4c, 0xd3, 0x97, 0x14, 0x7d, 0x6b, 0x96, 0x5a, 0xbc, 0x7a,
	0xad, 0xa8, 0x4b, 0xe9, 0x79, 0xa6, 0x68, 0xcf, 0xa0, 0x14, 0xd2, 0x01, 0xbb, 0xa0, 0xc9, 0xa5,
	0x52, 0xa5, 0xca, 0xcc, 0x5a, 0x6f, 0x18, 0x08, 0x1e, 0x81, 0xe5, 0x06, 0xfe, 0x39, 0x23, 0xb1,
	0x60, 0xe2, 0x52, 0xa9, 0x53, 0x01, 0x8f, 0xc6, 0xe8, 0x39, 0x40, 0x16, 0x33, 0xe1, 0x0f, 0x13,
	0x16, 0x50, 0x17, 0xae, 0x93, 0xe5, 0xb2, 0x04, 0x1f, 0x49, 0xac, 0x64, 0x0a, 0xf2, 0xce, 0x37,
	0x82, 0x5e, 0xb9, 0x96, 0x29, 0xc8, 0x3b, 0xfd, 0x88, 0x5e, 0xc0, 0x6a, 0xc8, 0xd2, 0x40, 0x3e,
	0x5b, 0xfa, 0xf2, 0x75, 0xf4, 0xaa, 0x65, 0x98, 0x18, 0x08, 0x16, 0x62, 0x12, 0x59, 0xfd, 0x51,
	0xcf, 0x68, 0x1b, 0x2a, 0x56, 0x87, 0xc7, 0xba, 0x33, 0x69, 0x42, 0xbf, 0x18, 0x27, 0x2f, 0xe0,
	0x21, 0x55, 0xba, 0x53, 0x1e, 0x25, 0xa7, 0xce, 0x43, 0x8a, 0x36, 0x75, 0x72, 0x94, 0xdb, 0xd1,
	0x1f, 0xcd, 0xf4, 0x3c, 0x53, 0xae, 0xbb, 0x00, 0x82, 0x26, 0x91, 0x2f, 0xf7, 0x20, 0x55, 0x42,
	0x51, 0xc0, 0x65, 0x69, 0x79, 0x2d, 0x0d, 0xe8, 0x39, 0xa8, 0x81, 0xce, 0x2b, 0x9a, 0x2b, 0x46,
	0x5d, 0x9a, 0x44, 0xfa, 0xbb, 0x28, 0xcc, 0xd3, 0xce, 0x8f, 0x4b, 0xb6, 0x81, 0x5a, 0x54, 0x10,
	0x54, 0x87, 0x55, 0xab, 0x20, 0x24, 0x0c, 0x13, 0x9a, 0xa6, 0xaa, 0x81, 0x2a, 0x33, 0xcb, 0xa4,
	0xa6, 0x11, 0xb8, 0x6a, 0x28, 0x66, 0x8c, 0x3c, 0x70, 0x6c, 0x01, 0x8c, 0xa2, 0xe4, 0xaf, 0x8d,
	0xb2, 0x6a, 0x39, 0x36, 0xcc, 0x13, 0x58, 0x64, 0x82, 0x46, 0xa9, 0x5b, 0x50, 0x8a, 0x74, 0x77,
	0xfe, 0x39, 0x41, 0xd0, 0x08, 0x6b, 0xac, 0x94, 0x0a, 0xf9, 0x6e, 0xa9, 0x6a, 0xc8, 0x32, 0xd6,
	0x03, 0x95, 0x32, 0x6e, 0x9a, 0x4d, 0xa6, 0x8c, 0x0b, 0xf5, 0xb1, 0x18, 0x7d, 0x73, 0x23, 0x1a,
	0x71, 0xd5, 0x4e, 0x65, 0xbc, 0x6c, 0x8d, 0x2d, 0x1a, 0x71, 0xf4, 0x15, 0x2c, 0xb3, 0xf8, 0x82,
	0xb3, 0x80, 0xea, 0x6e, 0xbd, 0xfe, 0xb3, 0x5e, 0x31, 0x78, 0xdb, 0xe8, 0x61, 0x66, 0xa8, 0xa5,
	0xeb, 0x1b, 0x3d, 0xcc, 0x34, 0x6d, 0x46, 0x95, 0x96, 0x7f, 0x6a, 0x95, 0xca, 0x18, 0xa3, 0x24,
	0xe8, 0x18, 0x70, 0x7d, 0x0c, 0x9b, 0x02, 0x1d, 0xe3, 0xe7, 0xf7, 0xd9, 0x1f, 0x60, 0x59, 0x70,
	0x41, 0x06, 0x1f, 0xdd, 0x64, 0x15, 0x05, 0x37, 0xec, 0xc7, 0x50, 0x1c, 0xd2, 0x24, 0xe5, 0xb1,
	0xea, 0xb1, 0xd9, 0xbc, 0x23, 0x05, 0xc0, 0x06, 0x88, 0x9e, 0xc2, 0x52, 0xc0, 0xa3, 0x21, 0x89,
	0x2f, 0x55, 0xf3, 0xcd, 0x2e, 0xb5, 0xba, 0x46, 0x60, 0x0b, 0x95, 0x6d, 0xc5, 0x86, 0xa3, 0x1a,
	0xd5, 0x2d, 0x59, 0x66, 0x43, 0x5b, 0x81, 0x93, 0xb2, 0xe7, 0xfc, 0x14, 0xd9, 0x7b, 0x0c, 0xc5,
	0x90, 0x5e, 0x48, 0x59, 0x5b, 0x9b, 0xfb, 0x02, 0x0d, 0x05, 0xc0, 0x06, 0x28, 0x0f, 0x37, 0x41,
	0x96, 0x0a, 0x1e, 0xd1, 0x64, 0xfc, 0xd1, 0x06, 0x6b, 0x6a, 0x86, 0x4a, 0x40, 0x06, 0x24, 0xd0,
	0x87, 0x3e, 0x16, 0xba, 0xeb, 0x46, 0x40, 0xac, 0xad, 0x19, 0xee, 0xfc, 0x90, 0x83, 0x92, 0x5d,
	0x0d, 0xfa, 0x1a, 0x4a, 0xa9, 0x20, 0x71, 0x48, 0x12, 0xfd, 0x11, 0xac, 0xee, 0x3f, 0xf8, 0xc0,
	0xe2, 0x8f, 0x0d, 0x14, 0x8f, 0x48, 0xe8, 0x09, 0x2c, 0x28, 0x3d, 0xc9, 0xcf, 0x3d, 0x6b, 0x5b,
	0xb2, 0xd2, 0x14, 0x05, 0x96, 0x5d, 0x25, 0x0f, 0xdc, 0xe7, 0x52, 0x41, 0x94, 0x90, 0x15, 0x74,
	0x57, 0x59, 0xa3, 0x52, 0x33, 0x57, 0x26, 0x2b, 0x4b, 0x18, 0x4d, 0x4c, 0x9b, 0xda, 0xe1, 0x4e,
	0x06, 0x2b, 0xba, 0xa7, 0x8f, 0xb3, 0x28, 0x22, 0x7a, 0x27, 0x4d, 0x09, 0xe5, 0x3e, 0xf6, 0xdc,
	0xfe, 0x18, 0x8a, 0xf2, 0x64, 0x9b, 0xa5, 0x66, 0xe5, 0x9b, 0x73, 0xce, 0xc3, 0x59, 0x8a, 0x0d,
	0x70, 0xe7, 0x0b, 0x28, 0x37, 0x58, 0x44, 0x63, 0x75, 0x41, 0xd9, 0x80, 0xc5, 0xb7, 0x2c, 0x14,
	0x7d, 0x35, 0xe3, 0x22, 0xd6, 0x03, 0x74, 0x13, 0x8a, 0x7d, 0xca, 0x7a, 0x7d, 0x61, 0x4e, 0x0a,
	0x66, 0xb4, 0xf3, 0xd7, 0x12, 0x14, 0x75, 0x2a, 0xd1, 0x3e, 0xdc, 0x38, 0x4d, 0xf8, 0x5b, 0x79,
	0x02, 0x25, 0x41, 0x40, 0x87, 0xc2, 0xef, 0x53, 0x12, 0xd2, 0xc4, 0x9c, 0x41, 0xd6, 0x8d, 0xb3,
	0xa6, 0x7c, 0x07, 0xca, 0xa5, 0xd2, 0xce, 0x07, 0x3c, 0xf1, 0x43, 0x3a, 0x14, 0x7d, 0x13, 0x1b,
	0x94, 0xa9, 0x21, 0x2d, 0x32, 0xed, 0x7f, 0x22, 0x17, 0xc4, 0xa7, 0x31, 0x39, 0x1d, 0xd0, 0x50,
	0xed, 0x67, 0x09, 0x57, 0xa4, 0xcd, 0xd3, 0x26, 0x79, 0x7b, 0x90, 0x43, 0xfd, 0xad, 0x19, 0x01,
	0x17, 0x14, 0x70, 0x6d, 0xec, 0xb1, 0xf0, 0xad, 0x89, 0x83, 0xab, 0x16, 0xc4, 0xf1, 0xd9, 0xf4,
	0x29, 0x14, 0xd3, 0x20, 0xa1, 0x34, 0x56, 0x6a, 0x58, 0xd9, 0xbf, 0x33, 0x2b, 0xeb, 0x76, 0xa7,
	0xb0, 0xc1, 0xa2, 0x6f, 0xc0, 0xd1, 0x4f, 0x3e, 0xb9, 0x20, 0x6c, 0x20, 0xa7, 0x31, 0x4a, 0xf9,
	0x61, 0xfe, 0xaa, 0x66, 0xd5, 0x2c, 0x09, 0x7d, 0x0d, 0xcb, 0x6f, 0x59, 0x1c, 0xf2, 0xb7, 0x3e,
	0x8b, 0x63, 0x9a, 0x18, 0xcd, 0xfc, 0x70, 0x90, 0x8a, 0x66, 0x34, 0x25, 0x61, 0x22, 0x00, 0xcf,
	0x04, 0xb5, 0x37, 0xa2, 0x8f, 0x0a, 0xd0, 0x91, 0x04, 0xf4, 0x39, 0x6c, 0xc8, 0xfb, 0xdb, 0x5f,
	0x78, 0x4c, 0x7d, 0x7e, 0x76, 0x96, 0x52, 0xe1, 0x47, 0x2c, 0x4e, 0x95, 0x76, 0x2e, 0x62, 0x64,
	0x7d, 0x1d, 0xe5, 0x6a, 0xb1, 0x58, 0x5d, 0x5a, 0xd4, 0xa5, 0x83, 0xf4, 0xa8, 0x11, 0xc9, 0x32,
	0x2e, 0x4b, 0x4b, 0x4d, 0x1a, 0xae, 0x48, 0xcc, 0xf2, 0x55, 0x89, 0xf9, 0x0c, 0x56, 0x03, 0xce,
	0xcf, 0x19, 0x4d, 0x47, 0x89, 0x5b, 0x51, 0x89, 0xab, 0x1a, 0xb3, 0xcd, 0xda, 0x03, 0x58, 0x39,
	0x1b, 0x90, 0xb4, 0xef, 0xdb, 0x6b, 0xb5, 0xb9, 0xdb, 0x28, 0xe3, 0x89, 0xb9, 0x5b, 0x6f, 0x42,
	0x89, 0xa5, 0xbe, 0xe0, 0x59, 0xd0, 0x57, 0x6a, 0x56, 0xc2, 0x4b, 0x2c, 0xed, 0xca, 0x21, 0xaa,
	0x42, 0x9e, 0xa7, 0xe6, 0x58, 0x91, 0xe7, 0x6a, 0xd9, 0x3c, 0x1d, 0x05, 0x5b, 0xd3, 0xeb, 0xe2,
	0xa9, 0x8d, 0xe4, 0xc2, 0x92, 0x29, 0x57, 0x23, 0x45, 0x76, 0x28, 0x57, 0x6c, 0xab, 0xdc, 0xb2,
	0xb5, 0x14, 0x55, 0x8d, 0xd9, 0x86, 0xd8, 0x83, 0x75, 0xad, 0x6d, 0x7e, 0x44, 0xe2, 0xec, 0x8c,
	0x04, 0x22, 0x4b, 0x68, 0x62, 0xee, 0x01, 0x48, 0xbb, 0x5a, 0x13, 0x1e, 0xd9, 0x0b, 0x86, 0xa0,
	0xce, 0x57, 0x37, 0xb4, 0x04, 0x6a, 0x53, 0x5b, 0x9e, 0xb2, 0x3e, 0x85, 0xaa, 0x01, 0xd8, 0x99,
	0x6f, 0x2a, 0xcc, 0x8a, 0xb6, 0xda, 0x89, 0xb7, 0xa1, 0x72, 0xc6, 0xe2, 0x1e, 0x4d, 0x86, 0x09,
	0x8b, 0x85, 0x7b, 0x4b, 0x0b, 0xe5, 0x84, 0x09, 0x3d, 0x36, 0xd2, 0xe6, 0x2a, 0x81, 0xb8, 0x3b,
	0x57, 0x9d, 0x27, 0x84, 0x6d, 0x0b, 0x4a, 0x36, 0xf9, 0xee, 0xa6, 0xee, 0x1a, 0x3b, 0x7e, 0xd4,
	0x87, 0xea, 0xf8, 0x0c, 0xa5, 0x0e, 0xcc, 0x77, 0xc0, 0xad, 0x1f, 0xd4, 0xf0, 0x37, 0x9e, 0xdf,
	0xf2, 0xba, 0x35, 0xbf, 0xfb, 0xe6, 0xc8, 0xf3, 0x9b, 0xed, 0x93, 0xda, 0x61, 0xb3, 0xe1, 0x7c,
	0x82, 0x6e, 0xc3, 0xad, 0x29, 0xef, 0x71, 0xe7, 0x35, 0xae, 0x7b, 0x4e, 0x6e, 0xa6, 0xb3, 0x76,
	0x74, 0xe4, 0xb5, 0x1b, 0x4e, 0xfe, 0xd1, 0x0f, 0x39, 0x58, 0x9e, 0xfc, 0x73, 0x04, 0x6d, 0xc2,
	0x0d, 0x83, 0x6e, 0xb6, 0xbb, 0x5e, 0xbb, 0x3b, 0x31, 0xcb, 0x78, 0x0d, 0xc6, 0xd5, 0xf2, 0xba,
	0x07, 0x9d, 0x86, 0x5f, 0x6b, 0x34, 0x9c, 0x1c, 0xda, 0x86, 0x3b, 0x33, 0xbd, 0xd8, 0x7b, 0x89,
	0xbd, 0xe3, 0x03, 0x27, 0x8f, 0xee, 0xc3, 0xed, 0x99, 0x88, 0x13, 0x0f, 0x37, 0x5f, 0xbe, 0x71,
	0x0a, 0xd3, 0x73, 0xd7, 0x6b, 0x47, 0xdd, 0xd7, 0xd8, 0x73, 0x16, 0x90, 0x0b, 0x1b, 0xef, 0xbb,
	0xb0, 0xf7, 0xf2, 0x75, 0xbb, 0xe1, 0x2c, 0x3e, 0xfa, 0x7b, 0x0e, 0xd6, 0xa6, 0x6e, 0xd6, 0xe8,
	0x1e, 0x6c, 0x19, 0xbc, 0xd7, 0x3e, 0x69, 0xe2, 0x4e, 0xbb, 0xf5, 0xfe, 0xbb, 0xdc, 0x85, 0xcd,
	0x19, 0x7e, 0xec, 0x75, 0x6b, 0xcd, 0xc3, 0xf7, 0x5e, 0x66, 0xd2, 0xed, 0xd5, 0x3b, 0xad, 0x96,
	0x27, 0x77, 0x35, 0x3f, 0xb1, 0xab, 0x93, 0x88, 0x56, 0xa7, 0xdb, 0x71, 0x0a, 0x73, 0x66, 0xc7,
	0x5e, 0xdb, 0xfb, 0xb6, 0x76, 0xe8, 0x2c, 0x3c, 0xfa, 0x47, 0x0e, 0x60, 0x5c, 0x10, 0xe8, 0x16,
	0xac, 0x37, 0xbc, 0x93, 0x66, 0xdd, 0xbb, 0x9a, 0xd7, 0x9b, 0x80, 0x26, 0x1d, 0xad, 0xce, 0x8b,
	0xe6, 0xa1, 0x4c, 0xe9, 0x15, 0x7b, 0xb7, 0xf6, 0xe2, 0xd0, 0xeb, 0x3a, 0xf9, 0xab, 0x81, 0x1a,
	0xde, 0xf1, 0xab, 0x6e, 0xe7, 0xc8, 0x29, 0xc8, 0xed, 0x9b, 0x74, 0x7c, 0xeb, 0xd5, 0xb0, 0xe4,
	0x38, 0x0b, 0x57, 0x29, 0xf5, 0x4e, 0xfb, 0xb8, 0x73, 0xe8, 0x39, 0x8b, 0x57, 0x1d, 0x27, 0xde,
	0x41, 0xb3, 0x7e, 0xe8, 0x39, 0xc5, 0x17, 0xfc, 0xdf, 0xff, 0xb9, 0xf7, 0xc9, 0xbf, 0xfe, 0x77,
	0x2f, 0xf7, 0xdd, 0xd3, 0x1e, 0x13, 0xfd, 0xec, 0x74, 0x37, 0xe0, 0xd1, 0xde, 0xc4, 0x7f, 0x8a,
	0xf6, 0x2f, 0x4f, 0xf9, 0x11, 0xd8, 0x9b, 0xfa, 0xaf, 0xf1, 0xc7, 0xbc, 0x49, 0xd7, 0x01, 0xbb,
	0xa0, 0xdf, 0xd7, 0x95, 0xed, 0xbf, 0xf9, 0xad, 0x29, 0xdb, 0xf7, 0xb2, 0xf6, 0x43, 0x22, 0xc8,
	0x69, 0x51, 0x05, 0x7c, 0xf2, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xae, 0x43, 0x5d, 0x15, 0x83,
	0x15, 0x00, 0x00,
}
