// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: chargehive/chtype/enum.proto

package chtype

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	STATUS_INVALID Status = 0
	//Pre Setup 1-9
	STATUS_PENDING Status = 1
	//Setup 10-29
	STATUS_SETUP        Status = 10
	STATUS_PROVISIONING Status = 20
	//Active 30-49
	STATUS_ACTIVE Status = 30
	//Inactive 50-69
	STATUS_SUSPENDED Status = 50
	STATUS_CANCELLED Status = 60
	//Unavailable 70+
	STATUS_ARCHIVED Status = 70
	STATUS_DELETED  Status = 90
)

var Status_name = map[int32]string{
	0:  "STATUS_INVALID",
	1:  "STATUS_PENDING",
	10: "STATUS_SETUP",
	20: "STATUS_PROVISIONING",
	30: "STATUS_ACTIVE",
	50: "STATUS_SUSPENDED",
	60: "STATUS_CANCELLED",
	70: "STATUS_ARCHIVED",
	90: "STATUS_DELETED",
}

var Status_value = map[string]int32{
	"STATUS_INVALID":      0,
	"STATUS_PENDING":      1,
	"STATUS_SETUP":        10,
	"STATUS_PROVISIONING": 20,
	"STATUS_ACTIVE":       30,
	"STATUS_SUSPENDED":    50,
	"STATUS_CANCELLED":    60,
	"STATUS_ARCHIVED":     70,
	"STATUS_DELETED":      90,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_79326afc23833508, []int{0}
}

type ActorType int32

const (
	ACTOR_TYPE_INVALID           ActorType = 0
	ACTOR_TYPE_CONSUMER          ActorType = 1
	ACTOR_TYPE_MERCHANT          ActorType = 2
	ACTOR_TYPE_CHARGEHIVE        ActorType = 3
	ACTOR_TYPE_WALLET            ActorType = 4
	ACTOR_TYPE_CONNECTOR         ActorType = 5
	ACTOR_TYPE_PAYMENT_PROCESSOR ActorType = 6
	ACTOR_TYPE_PAYMENT_NETWORK   ActorType = 7
	ACTOR_TYPE_ACQUIRING_BANK    ActorType = 8
	ACTOR_TYPE_ISSUING_BANK      ActorType = 9
	ACTOR_TYPE_RECOVERY_AGENT    ActorType = 10
	ACTOR_TYPE_EXCHANGE          ActorType = 11
	ACTOR_TYPE_POLICY            ActorType = 12
)

var ActorType_name = map[int32]string{
	0:  "ACTOR_TYPE_INVALID",
	1:  "ACTOR_TYPE_CONSUMER",
	2:  "ACTOR_TYPE_MERCHANT",
	3:  "ACTOR_TYPE_CHARGEHIVE",
	4:  "ACTOR_TYPE_WALLET",
	5:  "ACTOR_TYPE_CONNECTOR",
	6:  "ACTOR_TYPE_PAYMENT_PROCESSOR",
	7:  "ACTOR_TYPE_PAYMENT_NETWORK",
	8:  "ACTOR_TYPE_ACQUIRING_BANK",
	9:  "ACTOR_TYPE_ISSUING_BANK",
	10: "ACTOR_TYPE_RECOVERY_AGENT",
	11: "ACTOR_TYPE_EXCHANGE",
	12: "ACTOR_TYPE_POLICY",
}

var ActorType_value = map[string]int32{
	"ACTOR_TYPE_INVALID":           0,
	"ACTOR_TYPE_CONSUMER":          1,
	"ACTOR_TYPE_MERCHANT":          2,
	"ACTOR_TYPE_CHARGEHIVE":        3,
	"ACTOR_TYPE_WALLET":            4,
	"ACTOR_TYPE_CONNECTOR":         5,
	"ACTOR_TYPE_PAYMENT_PROCESSOR": 6,
	"ACTOR_TYPE_PAYMENT_NETWORK":   7,
	"ACTOR_TYPE_ACQUIRING_BANK":    8,
	"ACTOR_TYPE_ISSUING_BANK":      9,
	"ACTOR_TYPE_RECOVERY_AGENT":    10,
	"ACTOR_TYPE_EXCHANGE":          11,
	"ACTOR_TYPE_POLICY":            12,
}

func (x ActorType) String() string {
	return proto.EnumName(ActorType_name, int32(x))
}

func (ActorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_79326afc23833508, []int{1}
}

type HandlerType int32

const (
	HANDLER_TYPE_INVALID     HandlerType = 0
	HANDLER_TYPE_WEB         HandlerType = 1
	HANDLER_TYPE_CLI         HandlerType = 2
	HANDLER_TYPE_API         HandlerType = 3
	HANDLER_TYPE_MOBILE      HandlerType = 4
	HANDLER_TYPE_PASSTHROUGH HandlerType = 5
)

var HandlerType_name = map[int32]string{
	0: "HANDLER_TYPE_INVALID",
	1: "HANDLER_TYPE_WEB",
	2: "HANDLER_TYPE_CLI",
	3: "HANDLER_TYPE_API",
	4: "HANDLER_TYPE_MOBILE",
	5: "HANDLER_TYPE_PASSTHROUGH",
}

var HandlerType_value = map[string]int32{
	"HANDLER_TYPE_INVALID":     0,
	"HANDLER_TYPE_WEB":         1,
	"HANDLER_TYPE_CLI":         2,
	"HANDLER_TYPE_API":         3,
	"HANDLER_TYPE_MOBILE":      4,
	"HANDLER_TYPE_PASSTHROUGH": 5,
}

func (x HandlerType) String() string {
	return proto.EnumName(HandlerType_name, int32(x))
}

func (HandlerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_79326afc23833508, []int{2}
}

type TransactionType int32

const (
	TRANSACTION_TYPE_INVALID   TransactionType = 0
	TRANSACTION_TYPE_AUTHORIZE TransactionType = 1
	TRANSACTION_TYPE_CAPTURE   TransactionType = 2
	TRANSACTION_TYPE_REFUND    TransactionType = 3
	TRANSACTION_TYPE_CANCEL    TransactionType = 4
	TRANSACTION_TYPE_DISPUTE   TransactionType = 5
	TRANSACTION_TYPE_VERIFY    TransactionType = 6
	TRANSACTION_TYPE_EXPIRED   TransactionType = 7
	TRANSACTION_TYPE_INTERNAL  TransactionType = 99
)

var TransactionType_name = map[int32]string{
	0:  "TRANSACTION_TYPE_INVALID",
	1:  "TRANSACTION_TYPE_AUTHORIZE",
	2:  "TRANSACTION_TYPE_CAPTURE",
	3:  "TRANSACTION_TYPE_REFUND",
	4:  "TRANSACTION_TYPE_CANCEL",
	5:  "TRANSACTION_TYPE_DISPUTE",
	6:  "TRANSACTION_TYPE_VERIFY",
	7:  "TRANSACTION_TYPE_EXPIRED",
	99: "TRANSACTION_TYPE_INTERNAL",
}

var TransactionType_value = map[string]int32{
	"TRANSACTION_TYPE_INVALID":   0,
	"TRANSACTION_TYPE_AUTHORIZE": 1,
	"TRANSACTION_TYPE_CAPTURE":   2,
	"TRANSACTION_TYPE_REFUND":    3,
	"TRANSACTION_TYPE_CANCEL":    4,
	"TRANSACTION_TYPE_DISPUTE":   5,
	"TRANSACTION_TYPE_VERIFY":    6,
	"TRANSACTION_TYPE_EXPIRED":   7,
	"TRANSACTION_TYPE_INTERNAL":  99,
}

func (x TransactionType) String() string {
	return proto.EnumName(TransactionType_name, int32(x))
}

func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_79326afc23833508, []int{3}
}

type TransactionSubType int32

const (
	TRANSACTION_SUB_TYPE_INVALID      TransactionSubType = 0
	TRANSACTION_SUB_TYPE_IDENTIFY     TransactionSubType = 1
	TRANSACTION_SUB_TYPE_CHALLENGE    TransactionSubType = 2
	TRANSACTION_SUB_TYPE_CAPTURE_AUTH TransactionSubType = 3
	TRANSACTION_SUB_TYPE_NONE         TransactionSubType = 4
)

var TransactionSubType_name = map[int32]string{
	0: "TRANSACTION_SUB_TYPE_INVALID",
	1: "TRANSACTION_SUB_TYPE_IDENTIFY",
	2: "TRANSACTION_SUB_TYPE_CHALLENGE",
	3: "TRANSACTION_SUB_TYPE_CAPTURE_AUTH",
	4: "TRANSACTION_SUB_TYPE_NONE",
}

var TransactionSubType_value = map[string]int32{
	"TRANSACTION_SUB_TYPE_INVALID":      0,
	"TRANSACTION_SUB_TYPE_IDENTIFY":     1,
	"TRANSACTION_SUB_TYPE_CHALLENGE":    2,
	"TRANSACTION_SUB_TYPE_CAPTURE_AUTH": 3,
	"TRANSACTION_SUB_TYPE_NONE":         4,
}

func (x TransactionSubType) String() string {
	return proto.EnumName(TransactionSubType_name, int32(x))
}

func (TransactionSubType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_79326afc23833508, []int{4}
}

type PaymentMethodType int32

const (
	PAYMENT_METHOD_TYPE_INVALID        PaymentMethodType = 0
	PAYMENT_METHOD_TYPE_CARD           PaymentMethodType = 1
	PAYMENT_METHOD_TYPE_DIGITALWALLET  PaymentMethodType = 2
	PAYMENT_METHOD_TYPE_DIRECTDEBIT    PaymentMethodType = 3
	PAYMENT_METHOD_TYPE_CRYPTOCURRENCY PaymentMethodType = 4
	PAYMENT_METHOD_TYPE_APPSTORE       PaymentMethodType = 5
)

var PaymentMethodType_name = map[int32]string{
	0: "PAYMENT_METHOD_TYPE_INVALID",
	1: "PAYMENT_METHOD_TYPE_CARD",
	2: "PAYMENT_METHOD_TYPE_DIGITALWALLET",
	3: "PAYMENT_METHOD_TYPE_DIRECTDEBIT",
	4: "PAYMENT_METHOD_TYPE_CRYPTOCURRENCY",
	5: "PAYMENT_METHOD_TYPE_APPSTORE",
}

var PaymentMethodType_value = map[string]int32{
	"PAYMENT_METHOD_TYPE_INVALID":        0,
	"PAYMENT_METHOD_TYPE_CARD":           1,
	"PAYMENT_METHOD_TYPE_DIGITALWALLET":  2,
	"PAYMENT_METHOD_TYPE_DIRECTDEBIT":    3,
	"PAYMENT_METHOD_TYPE_CRYPTOCURRENCY": 4,
	"PAYMENT_METHOD_TYPE_APPSTORE":       5,
}

func (x PaymentMethodType) String() string {
	return proto.EnumName(PaymentMethodType_name, int32(x))
}

func (PaymentMethodType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_79326afc23833508, []int{5}
}

type PaymentMethodProvider int32

const (
	PAYMENT_METHOD_PROVIDER_INVALID    PaymentMethodProvider = 0
	PAYMENT_METHOD_PROVIDER_FORM       PaymentMethodProvider = 1
	PAYMENT_METHOD_PROVIDER_PAYPAL     PaymentMethodProvider = 2
	PAYMENT_METHOD_PROVIDER_APPLEPAY   PaymentMethodProvider = 3
	PAYMENT_METHOD_PROVIDER_GOOGLEPAY  PaymentMethodProvider = 4
	PAYMENT_METHOD_PROVIDER_AMAZONPAY  PaymentMethodProvider = 5
	PAYMENT_METHOD_PROVIDER_IOS        PaymentMethodProvider = 6
	PAYMENT_METHOD_PROVIDER_GOOGLEPLAY PaymentMethodProvider = 7
)

var PaymentMethodProvider_name = map[int32]string{
	0: "PAYMENT_METHOD_PROVIDER_INVALID",
	1: "PAYMENT_METHOD_PROVIDER_FORM",
	2: "PAYMENT_METHOD_PROVIDER_PAYPAL",
	3: "PAYMENT_METHOD_PROVIDER_APPLEPAY",
	4: "PAYMENT_METHOD_PROVIDER_GOOGLEPAY",
	5: "PAYMENT_METHOD_PROVIDER_AMAZONPAY",
	6: "PAYMENT_METHOD_PROVIDER_IOS",
	7: "PAYMENT_METHOD_PROVIDER_GOOGLEPLAY",
}

var PaymentMethodProvider_value = map[string]int32{
	"PAYMENT_METHOD_PROVIDER_INVALID":    0,
	"PAYMENT_METHOD_PROVIDER_FORM":       1,
	"PAYMENT_METHOD_PROVIDER_PAYPAL":     2,
	"PAYMENT_METHOD_PROVIDER_APPLEPAY":   3,
	"PAYMENT_METHOD_PROVIDER_GOOGLEPAY":  4,
	"PAYMENT_METHOD_PROVIDER_AMAZONPAY":  5,
	"PAYMENT_METHOD_PROVIDER_IOS":        6,
	"PAYMENT_METHOD_PROVIDER_GOOGLEPLAY": 7,
}

func (x PaymentMethodProvider) String() string {
	return proto.EnumName(PaymentMethodProvider_name, int32(x))
}

func (PaymentMethodProvider) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_79326afc23833508, []int{6}
}

type PaymentMethodInputType int32

const (
	INPUT_TYPE_INVALID  PaymentMethodInputType = 0
	INPUT_TYPE_PHYSICAL PaymentMethodInputType = 1
	INPUT_TYPE_VIRTUAL  PaymentMethodInputType = 2
	INPUT_TYPE_PROXY    PaymentMethodInputType = 3
)

var PaymentMethodInputType_name = map[int32]string{
	0: "INPUT_TYPE_INVALID",
	1: "INPUT_TYPE_PHYSICAL",
	2: "INPUT_TYPE_VIRTUAL",
	3: "INPUT_TYPE_PROXY",
}

var PaymentMethodInputType_value = map[string]int32{
	"INPUT_TYPE_INVALID":  0,
	"INPUT_TYPE_PHYSICAL": 1,
	"INPUT_TYPE_VIRTUAL":  2,
	"INPUT_TYPE_PROXY":    3,
}

func (x PaymentMethodInputType) String() string {
	return proto.EnumName(PaymentMethodInputType_name, int32(x))
}

func (PaymentMethodInputType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_79326afc23833508, []int{7}
}

type ContractType int32

const (
	CONTRACT_TYPE_INVALID              ContractType = 0
	CONTRACT_TYPE_NONE                 ContractType = 1
	CONTRACT_TYPE_PAYMENT              ContractType = 2
	CONTRACT_TYPE_SUBSCRIPTION_INITIAL ContractType = 3
	CONTRACT_TYPE_SUBSCRIPTION_RENEWAL ContractType = 4
	CONTRACT_TYPE_ONECLICK             ContractType = 5
)

var ContractType_name = map[int32]string{
	0: "CONTRACT_TYPE_INVALID",
	1: "CONTRACT_TYPE_NONE",
	2: "CONTRACT_TYPE_PAYMENT",
	3: "CONTRACT_TYPE_SUBSCRIPTION_INITIAL",
	4: "CONTRACT_TYPE_SUBSCRIPTION_RENEWAL",
	5: "CONTRACT_TYPE_ONECLICK",
}

var ContractType_value = map[string]int32{
	"CONTRACT_TYPE_INVALID":              0,
	"CONTRACT_TYPE_NONE":                 1,
	"CONTRACT_TYPE_PAYMENT":              2,
	"CONTRACT_TYPE_SUBSCRIPTION_INITIAL": 3,
	"CONTRACT_TYPE_SUBSCRIPTION_RENEWAL": 4,
	"CONTRACT_TYPE_ONECLICK":             5,
}

func (x ContractType) String() string {
	return proto.EnumName(ContractType_name, int32(x))
}

func (ContractType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_79326afc23833508, []int{8}
}

type Environment int32

const (
	ENVIRONMENT_INVALID  Environment = 0
	ENVIRONMENT_BLACKBOX Environment = 1
	ENVIRONMENT_TEST     Environment = 2
	ENVIRONMENT_LIVE     Environment = 3
	ENVIRONMENT_MOCK     Environment = 4
)

var Environment_name = map[int32]string{
	0: "ENVIRONMENT_INVALID",
	1: "ENVIRONMENT_BLACKBOX",
	2: "ENVIRONMENT_TEST",
	3: "ENVIRONMENT_LIVE",
	4: "ENVIRONMENT_MOCK",
}

var Environment_value = map[string]int32{
	"ENVIRONMENT_INVALID":  0,
	"ENVIRONMENT_BLACKBOX": 1,
	"ENVIRONMENT_TEST":     2,
	"ENVIRONMENT_LIVE":     3,
	"ENVIRONMENT_MOCK":     4,
}

func (x Environment) String() string {
	return proto.EnumName(Environment_name, int32(x))
}

func (Environment) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_79326afc23833508, []int{9}
}

type ProductType int32

const (
	PRODUCT_TYPE_INVALID      ProductType = 0
	PRODUCT_TYPE_PRODUCT      ProductType = 1
	PRODUCT_TYPE_SERVICE      ProductType = 2
	PRODUCT_TYPE_SUBSCRIPTION ProductType = 3
)

var ProductType_name = map[int32]string{
	0: "PRODUCT_TYPE_INVALID",
	1: "PRODUCT_TYPE_PRODUCT",
	2: "PRODUCT_TYPE_SERVICE",
	3: "PRODUCT_TYPE_SUBSCRIPTION",
}

var ProductType_value = map[string]int32{
	"PRODUCT_TYPE_INVALID":      0,
	"PRODUCT_TYPE_PRODUCT":      1,
	"PRODUCT_TYPE_SERVICE":      2,
	"PRODUCT_TYPE_SUBSCRIPTION": 3,
}

func (x ProductType) String() string {
	return proto.EnumName(ProductType_name, int32(x))
}

func (ProductType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_79326afc23833508, []int{10}
}

type SKUType int32

const (
	SKU_TYPE_INVALID SKUType = 0
	SKU_TYPE_PRIMARY SKUType = 1
	SKU_TYPE_ADDON   SKUType = 2
	SKU_TYPE_UPSELL  SKUType = 3
)

var SKUType_name = map[int32]string{
	0: "SKU_TYPE_INVALID",
	1: "SKU_TYPE_PRIMARY",
	2: "SKU_TYPE_ADDON",
	3: "SKU_TYPE_UPSELL",
}

var SKUType_value = map[string]int32{
	"SKU_TYPE_INVALID": 0,
	"SKU_TYPE_PRIMARY": 1,
	"SKU_TYPE_ADDON":   2,
	"SKU_TYPE_UPSELL":  3,
}

func (x SKUType) String() string {
	return proto.EnumName(SKUType_name, int32(x))
}

func (SKUType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_79326afc23833508, []int{11}
}

type DeliveryType int32

const (
	DELIVERY_TYPE_INVALID  DeliveryType = 0
	DELIVERY_TYPE_NONE     DeliveryType = 1
	DELIVERY_TYPE_PHYSICAL DeliveryType = 2
	DELIVERY_TYPE_VIRTUAL  DeliveryType = 3
)

var DeliveryType_name = map[int32]string{
	0: "DELIVERY_TYPE_INVALID",
	1: "DELIVERY_TYPE_NONE",
	2: "DELIVERY_TYPE_PHYSICAL",
	3: "DELIVERY_TYPE_VIRTUAL",
}

var DeliveryType_value = map[string]int32{
	"DELIVERY_TYPE_INVALID":  0,
	"DELIVERY_TYPE_NONE":     1,
	"DELIVERY_TYPE_PHYSICAL": 2,
	"DELIVERY_TYPE_VIRTUAL":  3,
}

func (x DeliveryType) String() string {
	return proto.EnumName(DeliveryType_name, int32(x))
}

func (DeliveryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_79326afc23833508, []int{12}
}

type DeliveryStandard int32

const (
	DELIVERY_STANDARD_INVALID  DeliveryStandard = 0
	DELIVERY_STANDARD_SAME_DAY DeliveryStandard = 1
	DELIVERY_STANDARD_NEXT_DAY DeliveryStandard = 2
	DELIVERY_STANDARD_TWO_DAY  DeliveryStandard = 3
	DELIVERY_STANDARD_ECONOMY  DeliveryStandard = 4
	DELIVERY_STANDARD_OTHER    DeliveryStandard = 5
	DELIVERY_STANDARD_NONE     DeliveryStandard = 6
)

var DeliveryStandard_name = map[int32]string{
	0: "DELIVERY_STANDARD_INVALID",
	1: "DELIVERY_STANDARD_SAME_DAY",
	2: "DELIVERY_STANDARD_NEXT_DAY",
	3: "DELIVERY_STANDARD_TWO_DAY",
	4: "DELIVERY_STANDARD_ECONOMY",
	5: "DELIVERY_STANDARD_OTHER",
	6: "DELIVERY_STANDARD_NONE",
}

var DeliveryStandard_value = map[string]int32{
	"DELIVERY_STANDARD_INVALID":  0,
	"DELIVERY_STANDARD_SAME_DAY": 1,
	"DELIVERY_STANDARD_NEXT_DAY": 2,
	"DELIVERY_STANDARD_TWO_DAY":  3,
	"DELIVERY_STANDARD_ECONOMY":  4,
	"DELIVERY_STANDARD_OTHER":    5,
	"DELIVERY_STANDARD_NONE":     6,
}

func (x DeliveryStandard) String() string {
	return proto.EnumName(DeliveryStandard_name, int32(x))
}

func (DeliveryStandard) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_79326afc23833508, []int{13}
}

type TermType int32

const (
	TERM_TYPE_INVALID  TermType = 0
	TERM_TYPE_ONE_TIME TermType = 1
	TERM_TYPE_MINUTE   TermType = 3
	TERM_TYPE_DAY      TermType = 4
	TERM_TYPE_WEEK     TermType = 5
	TERM_TYPE_MONTH    TermType = 6
	TERM_TYPE_YEAR     TermType = 7
	TERM_TYPE_NONE     TermType = 8
)

var TermType_name = map[int32]string{
	0: "TERM_TYPE_INVALID",
	1: "TERM_TYPE_ONE_TIME",
	3: "TERM_TYPE_MINUTE",
	4: "TERM_TYPE_DAY",
	5: "TERM_TYPE_WEEK",
	6: "TERM_TYPE_MONTH",
	7: "TERM_TYPE_YEAR",
	8: "TERM_TYPE_NONE",
}

var TermType_value = map[string]int32{
	"TERM_TYPE_INVALID":  0,
	"TERM_TYPE_ONE_TIME": 1,
	"TERM_TYPE_MINUTE":   3,
	"TERM_TYPE_DAY":      4,
	"TERM_TYPE_WEEK":     5,
	"TERM_TYPE_MONTH":    6,
	"TERM_TYPE_YEAR":     7,
	"TERM_TYPE_NONE":     8,
}

func (x TermType) String() string {
	return proto.EnumName(TermType_name, int32(x))
}

func (TermType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_79326afc23833508, []int{14}
}

type FailureType int32

const (
	FAILURE_TYPE_INVALID  FailureType = 0
	FAILURE_TYPE_NONE     FailureType = 1
	FAILURE_TYPE_SOFT     FailureType = 2
	FAILURE_TYPE_HARD     FailureType = 3
	FAILURE_TYPE_RETRY    FailureType = 4
	FAILURE_TYPE_INTERNAL FailureType = 5
)

var FailureType_name = map[int32]string{
	0: "FAILURE_TYPE_INVALID",
	1: "FAILURE_TYPE_NONE",
	2: "FAILURE_TYPE_SOFT",
	3: "FAILURE_TYPE_HARD",
	4: "FAILURE_TYPE_RETRY",
	5: "FAILURE_TYPE_INTERNAL",
}

var FailureType_value = map[string]int32{
	"FAILURE_TYPE_INVALID":  0,
	"FAILURE_TYPE_NONE":     1,
	"FAILURE_TYPE_SOFT":     2,
	"FAILURE_TYPE_HARD":     3,
	"FAILURE_TYPE_RETRY":    4,
	"FAILURE_TYPE_INTERNAL": 5,
}

func (x FailureType) String() string {
	return proto.EnumName(FailureType_name, int32(x))
}

func (FailureType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_79326afc23833508, []int{15}
}

type TransactionResult int32

const (
	TRANSACTION_RESULT_INVALID         TransactionResult = 0
	TRANSACTION_RESULT_SUCCESS         TransactionResult = 1
	TRANSACTION_RESULT_DECLINED        TransactionResult = 2
	TRANSACTION_RESULT_VERIFY          TransactionResult = 3
	TRANSACTION_RESULT_PENDING         TransactionResult = 5
	TRANSACTION_RESULT_PENDING_SUCCESS TransactionResult = 6
	TRANSACTION_RESULT_RETRY           TransactionResult = 7
	TRANSACTION_RESULT_EXPIRED         TransactionResult = 8
	TRANSACTION_RESULT_PARTIAL_SUCCESS TransactionResult = 9
	TRANSACTION_RESULT_FAILURE         TransactionResult = 10
)

var TransactionResult_name = map[int32]string{
	0:  "TRANSACTION_RESULT_INVALID",
	1:  "TRANSACTION_RESULT_SUCCESS",
	2:  "TRANSACTION_RESULT_DECLINED",
	3:  "TRANSACTION_RESULT_VERIFY",
	5:  "TRANSACTION_RESULT_PENDING",
	6:  "TRANSACTION_RESULT_PENDING_SUCCESS",
	7:  "TRANSACTION_RESULT_RETRY",
	8:  "TRANSACTION_RESULT_EXPIRED",
	9:  "TRANSACTION_RESULT_PARTIAL_SUCCESS",
	10: "TRANSACTION_RESULT_FAILURE",
}

var TransactionResult_value = map[string]int32{
	"TRANSACTION_RESULT_INVALID":         0,
	"TRANSACTION_RESULT_SUCCESS":         1,
	"TRANSACTION_RESULT_DECLINED":        2,
	"TRANSACTION_RESULT_VERIFY":          3,
	"TRANSACTION_RESULT_PENDING":         5,
	"TRANSACTION_RESULT_PENDING_SUCCESS": 6,
	"TRANSACTION_RESULT_RETRY":           7,
	"TRANSACTION_RESULT_EXPIRED":         8,
	"TRANSACTION_RESULT_PARTIAL_SUCCESS": 9,
	"TRANSACTION_RESULT_FAILURE":         10,
}

func (x TransactionResult) String() string {
	return proto.EnumName(TransactionResult_name, int32(x))
}

func (TransactionResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_79326afc23833508, []int{16}
}

type VerificationStatus int32

const (
	VERIFICATION_STATUS_INVALID     VerificationStatus = 0
	VERIFICATION_STATUS_NOT_CHECKED VerificationStatus = 1
	VERIFICATION_STATUS_PASSED      VerificationStatus = 2
	VERIFICATION_STATUS_FAILED      VerificationStatus = 3
	VERIFICATION_STATUS_CONTINUE    VerificationStatus = 4
)

var VerificationStatus_name = map[int32]string{
	0: "VERIFICATION_STATUS_INVALID",
	1: "VERIFICATION_STATUS_NOT_CHECKED",
	2: "VERIFICATION_STATUS_PASSED",
	3: "VERIFICATION_STATUS_FAILED",
	4: "VERIFICATION_STATUS_CONTINUE",
}

var VerificationStatus_value = map[string]int32{
	"VERIFICATION_STATUS_INVALID":     0,
	"VERIFICATION_STATUS_NOT_CHECKED": 1,
	"VERIFICATION_STATUS_PASSED":      2,
	"VERIFICATION_STATUS_FAILED":      3,
	"VERIFICATION_STATUS_CONTINUE":    4,
}

func (x VerificationStatus) String() string {
	return proto.EnumName(VerificationStatus_name, int32(x))
}

func (VerificationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_79326afc23833508, []int{17}
}

type VerifyRequestType int32

const (
	VERIFY_REQUEST_TYPE_INVALID   VerifyRequestType = 0
	VERIFY_REQUEST_TYPE_IDENTIFY  VerifyRequestType = 1
	VERIFY_REQUEST_TYPE_CHALLENGE VerifyRequestType = 2
	VERIFY_REQUEST_TYPE_NONE      VerifyRequestType = 3
)

var VerifyRequestType_name = map[int32]string{
	0: "VERIFY_REQUEST_TYPE_INVALID",
	1: "VERIFY_REQUEST_TYPE_IDENTIFY",
	2: "VERIFY_REQUEST_TYPE_CHALLENGE",
	3: "VERIFY_REQUEST_TYPE_NONE",
}

var VerifyRequestType_value = map[string]int32{
	"VERIFY_REQUEST_TYPE_INVALID":   0,
	"VERIFY_REQUEST_TYPE_IDENTIFY":  1,
	"VERIFY_REQUEST_TYPE_CHALLENGE": 2,
	"VERIFY_REQUEST_TYPE_NONE":      3,
}

func (x VerifyRequestType) String() string {
	return proto.EnumName(VerifyRequestType_name, int32(x))
}

func (VerifyRequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_79326afc23833508, []int{18}
}

type Liability int32

const (
	LIABILITY_INVALID  Liability = 0
	LIABILITY_UNKNOWN  Liability = 1
	LIABILITY_MERCHANT Liability = 2
	LIABILITY_ISSUER   Liability = 3
)

var Liability_name = map[int32]string{
	0: "LIABILITY_INVALID",
	1: "LIABILITY_UNKNOWN",
	2: "LIABILITY_MERCHANT",
	3: "LIABILITY_ISSUER",
}

var Liability_value = map[string]int32{
	"LIABILITY_INVALID":  0,
	"LIABILITY_UNKNOWN":  1,
	"LIABILITY_MERCHANT": 2,
	"LIABILITY_ISSUER":   3,
}

func (x Liability) String() string {
	return proto.EnumName(Liability_name, int32(x))
}

func (Liability) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_79326afc23833508, []int{19}
}

type PlacementCapability int32

const (
	PLACEMENT_CAPABILITY_INVALID    PlacementCapability = 0
	PLACEMENT_CAPABILITY_CARD_FORM  PlacementCapability = 1
	PLACEMENT_CAPABILITY_APPLE_PAY  PlacementCapability = 2
	PLACEMENT_CAPABILITY_GOOGLE_PAY PlacementCapability = 3
	PLACEMENT_CAPABILITY_PAYPAL     PlacementCapability = 4
	PLACEMENT_CAPABILITY_TOKEN      PlacementCapability = 5
)

var PlacementCapability_name = map[int32]string{
	0: "PLACEMENT_CAPABILITY_INVALID",
	1: "PLACEMENT_CAPABILITY_CARD_FORM",
	2: "PLACEMENT_CAPABILITY_APPLE_PAY",
	3: "PLACEMENT_CAPABILITY_GOOGLE_PAY",
	4: "PLACEMENT_CAPABILITY_PAYPAL",
	5: "PLACEMENT_CAPABILITY_TOKEN",
}

var PlacementCapability_value = map[string]int32{
	"PLACEMENT_CAPABILITY_INVALID":    0,
	"PLACEMENT_CAPABILITY_CARD_FORM":  1,
	"PLACEMENT_CAPABILITY_APPLE_PAY":  2,
	"PLACEMENT_CAPABILITY_GOOGLE_PAY": 3,
	"PLACEMENT_CAPABILITY_PAYPAL":     4,
	"PLACEMENT_CAPABILITY_TOKEN":      5,
}

func (x PlacementCapability) String() string {
	return proto.EnumName(PlacementCapability_name, int32(x))
}

func (PlacementCapability) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_79326afc23833508, []int{20}
}

func init() {
	proto.RegisterEnum("chargehive.chtype.Status", Status_name, Status_value)
	golang_proto.RegisterEnum("chargehive.chtype.Status", Status_name, Status_value)
	proto.RegisterEnum("chargehive.chtype.ActorType", ActorType_name, ActorType_value)
	golang_proto.RegisterEnum("chargehive.chtype.ActorType", ActorType_name, ActorType_value)
	proto.RegisterEnum("chargehive.chtype.HandlerType", HandlerType_name, HandlerType_value)
	golang_proto.RegisterEnum("chargehive.chtype.HandlerType", HandlerType_name, HandlerType_value)
	proto.RegisterEnum("chargehive.chtype.TransactionType", TransactionType_name, TransactionType_value)
	golang_proto.RegisterEnum("chargehive.chtype.TransactionType", TransactionType_name, TransactionType_value)
	proto.RegisterEnum("chargehive.chtype.TransactionSubType", TransactionSubType_name, TransactionSubType_value)
	golang_proto.RegisterEnum("chargehive.chtype.TransactionSubType", TransactionSubType_name, TransactionSubType_value)
	proto.RegisterEnum("chargehive.chtype.PaymentMethodType", PaymentMethodType_name, PaymentMethodType_value)
	golang_proto.RegisterEnum("chargehive.chtype.PaymentMethodType", PaymentMethodType_name, PaymentMethodType_value)
	proto.RegisterEnum("chargehive.chtype.PaymentMethodProvider", PaymentMethodProvider_name, PaymentMethodProvider_value)
	golang_proto.RegisterEnum("chargehive.chtype.PaymentMethodProvider", PaymentMethodProvider_name, PaymentMethodProvider_value)
	proto.RegisterEnum("chargehive.chtype.PaymentMethodInputType", PaymentMethodInputType_name, PaymentMethodInputType_value)
	golang_proto.RegisterEnum("chargehive.chtype.PaymentMethodInputType", PaymentMethodInputType_name, PaymentMethodInputType_value)
	proto.RegisterEnum("chargehive.chtype.ContractType", ContractType_name, ContractType_value)
	golang_proto.RegisterEnum("chargehive.chtype.ContractType", ContractType_name, ContractType_value)
	proto.RegisterEnum("chargehive.chtype.Environment", Environment_name, Environment_value)
	golang_proto.RegisterEnum("chargehive.chtype.Environment", Environment_name, Environment_value)
	proto.RegisterEnum("chargehive.chtype.ProductType", ProductType_name, ProductType_value)
	golang_proto.RegisterEnum("chargehive.chtype.ProductType", ProductType_name, ProductType_value)
	proto.RegisterEnum("chargehive.chtype.SKUType", SKUType_name, SKUType_value)
	golang_proto.RegisterEnum("chargehive.chtype.SKUType", SKUType_name, SKUType_value)
	proto.RegisterEnum("chargehive.chtype.DeliveryType", DeliveryType_name, DeliveryType_value)
	golang_proto.RegisterEnum("chargehive.chtype.DeliveryType", DeliveryType_name, DeliveryType_value)
	proto.RegisterEnum("chargehive.chtype.DeliveryStandard", DeliveryStandard_name, DeliveryStandard_value)
	golang_proto.RegisterEnum("chargehive.chtype.DeliveryStandard", DeliveryStandard_name, DeliveryStandard_value)
	proto.RegisterEnum("chargehive.chtype.TermType", TermType_name, TermType_value)
	golang_proto.RegisterEnum("chargehive.chtype.TermType", TermType_name, TermType_value)
	proto.RegisterEnum("chargehive.chtype.FailureType", FailureType_name, FailureType_value)
	golang_proto.RegisterEnum("chargehive.chtype.FailureType", FailureType_name, FailureType_value)
	proto.RegisterEnum("chargehive.chtype.TransactionResult", TransactionResult_name, TransactionResult_value)
	golang_proto.RegisterEnum("chargehive.chtype.TransactionResult", TransactionResult_name, TransactionResult_value)
	proto.RegisterEnum("chargehive.chtype.VerificationStatus", VerificationStatus_name, VerificationStatus_value)
	golang_proto.RegisterEnum("chargehive.chtype.VerificationStatus", VerificationStatus_name, VerificationStatus_value)
	proto.RegisterEnum("chargehive.chtype.VerifyRequestType", VerifyRequestType_name, VerifyRequestType_value)
	golang_proto.RegisterEnum("chargehive.chtype.VerifyRequestType", VerifyRequestType_name, VerifyRequestType_value)
	proto.RegisterEnum("chargehive.chtype.Liability", Liability_name, Liability_value)
	golang_proto.RegisterEnum("chargehive.chtype.Liability", Liability_name, Liability_value)
	proto.RegisterEnum("chargehive.chtype.PlacementCapability", PlacementCapability_name, PlacementCapability_value)
	golang_proto.RegisterEnum("chargehive.chtype.PlacementCapability", PlacementCapability_name, PlacementCapability_value)
}

func init() { proto.RegisterFile("chargehive/chtype/enum.proto", fileDescriptor_79326afc23833508) }
func init() {
	golang_proto.RegisterFile("chargehive/chtype/enum.proto", fileDescriptor_79326afc23833508)
}

var fileDescriptor_79326afc23833508 = []byte{
	// 1700 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x58, 0x4d, 0x6f, 0x1b, 0xb9,
	0x19, 0xde, 0x91, 0x2c, 0x3b, 0xa1, 0xd3, 0x5d, 0x7a, 0x62, 0x3b, 0xb6, 0xe3, 0x38, 0xc9, 0x6e,
	0xdb, 0xc3, 0x00, 0x8d, 0x81, 0xb6, 0xc7, 0x5e, 0x28, 0xce, 0x6b, 0x8b, 0xd0, 0x88, 0x9c, 0x25,
	0x39, 0xb2, 0x15, 0x2c, 0x2a, 0x8c, 0xe5, 0x59, 0x5b, 0x80, 0x23, 0xb9, 0x8a, 0xe4, 0xd6, 0x3d,
	0xf6, 0x4f, 0xf4, 0xb8, 0xfd, 0x0f, 0xbd, 0x16, 0x68, 0x81, 0x5e, 0x8a, 0x9e, 0xfa, 0x17, 0xb6,
	0x45, 0x81, 0x9e, 0xfa, 0x1b, 0x16, 0x9c, 0xd1, 0xc7, 0x7c, 0x50, 0xb9, 0x49, 0xef, 0xf3, 0x90,
	0x2f, 0xdf, 0x67, 0x5e, 0x92, 0xcf, 0x0c, 0x3a, 0x1e, 0xdc, 0xc6, 0x93, 0x9b, 0xe4, 0x76, 0xf8,
	0x90, 0x9c, 0x0e, 0x6e, 0xa7, 0x8f, 0xf7, 0xc9, 0x69, 0x32, 0x9a, 0x7d, 0x78, 0x77, 0x3f, 0x19,
	0x4f, 0xc7, 0xee, 0xce, 0x0a, 0x7d, 0x97, 0xa1, 0x47, 0x3f, 0xbb, 0x19, 0x4e, 0x6f, 0x67, 0x57,
	0xef, 0x06, 0xe3, 0x0f, 0xa7, 0x37, 0xe3, 0x9b, 0xf1, 0x69, 0xca, 0xbc, 0x9a, 0x7d, 0x9b, 0xfe,
	0x4b, 0xff, 0xa4, 0xbf, 0xb2, 0x19, 0xbc, 0xbf, 0x3b, 0x68, 0x53, 0x4d, 0xe3, 0xe9, 0xec, 0xa3,
	0xeb, 0xa2, 0xcf, 0x95, 0x26, 0x3a, 0x52, 0x7d, 0xc6, 0xbb, 0x24, 0x60, 0x3e, 0xfe, 0x2c, 0x17,
	0x0b, 0x81, 0xfb, 0x8c, 0x9f, 0x63, 0xc7, 0xc5, 0xe8, 0xd9, 0x3c, 0xa6, 0x40, 0x47, 0x21, 0x46,
	0xee, 0x0b, 0xf4, 0x7c, 0xc1, 0x92, 0xa2, 0xcb, 0x14, 0x13, 0xdc, 0x50, 0x77, 0xdd, 0x1d, 0xf4,
	0xa3, 0x39, 0x40, 0xa8, 0x66, 0x5d, 0xc0, 0x27, 0xee, 0x2e, 0xc2, 0x8b, 0xd1, 0x91, 0x32, 0x93,
	0x82, 0x8f, 0x7f, 0x9e, 0x8b, 0x52, 0xc2, 0x29, 0x04, 0x01, 0xf8, 0xf8, 0x57, 0xee, 0x73, 0xf4,
	0xc5, 0x62, 0xb8, 0xa4, 0x2d, 0xd6, 0x05, 0x1f, 0x9f, 0xe5, 0x96, 0xe4, 0x43, 0x00, 0x1a, 0x7c,
	0xfc, 0xde, 0xfb, 0x7f, 0x0d, 0x3d, 0x25, 0x83, 0xe9, 0x78, 0xa2, 0x1f, 0xef, 0x13, 0x77, 0x1f,
	0xb9, 0x84, 0x6a, 0x21, 0xfb, 0xba, 0x17, 0x42, 0xae, 0x98, 0x17, 0xe8, 0x79, 0x2e, 0x4e, 0x05,
	0x57, 0x51, 0x07, 0x24, 0x76, 0x4a, 0x40, 0x07, 0x24, 0x6d, 0x11, 0xae, 0x71, 0xcd, 0x3d, 0x44,
	0x7b, 0xf9, 0x11, 0x2d, 0x22, 0xcf, 0xc1, 0xac, 0x03, 0xd7, 0xdd, 0x3d, 0xb4, 0x93, 0x83, 0x2e,
	0x48, 0x10, 0x80, 0xc6, 0x1b, 0xee, 0x01, 0xda, 0x2d, 0xe6, 0xe0, 0x60, 0xfe, 0xe2, 0x86, 0xfb,
	0x06, 0x1d, 0xe7, 0x90, 0x90, 0xf4, 0x3a, 0xc0, 0xb5, 0x11, 0x8c, 0x82, 0x52, 0x42, 0xe2, 0x4d,
	0xf7, 0x04, 0x1d, 0x59, 0x18, 0x1c, 0xf4, 0x85, 0x90, 0x6d, 0xbc, 0xe5, 0xbe, 0x42, 0x87, 0x39,
	0x9c, 0xd0, 0xaf, 0x23, 0x26, 0x19, 0x3f, 0xef, 0x37, 0x09, 0x6f, 0xe3, 0x27, 0xee, 0x4b, 0xf4,
	0x22, 0x5f, 0xb6, 0x52, 0xd1, 0x12, 0x7c, 0x5a, 0x1a, 0x2b, 0x81, 0x8a, 0x2e, 0xc8, 0x5e, 0x9f,
	0x9c, 0x03, 0xd7, 0xd9, 0x13, 0xcc, 0xc1, 0x70, 0x69, 0x04, 0x38, 0x07, 0xbc, 0x5d, 0x2a, 0x33,
	0x14, 0x01, 0xa3, 0x3d, 0xfc, 0xcc, 0xfb, 0x93, 0x83, 0xb6, 0x5b, 0xf1, 0xe8, 0xfa, 0x2e, 0xc9,
	0x24, 0x3f, 0x40, 0xbb, 0x2d, 0xc2, 0xfd, 0x00, 0x2a, 0xa2, 0xef, 0x22, 0x5c, 0x40, 0x2e, 0xa0,
	0x89, 0x9d, 0x4a, 0x94, 0x06, 0x0c, 0xd7, 0x2a, 0x51, 0x12, 0x32, 0x5c, 0x37, 0x6b, 0x2b, 0x44,
	0x3b, 0xa2, 0xc9, 0x02, 0xc0, 0x1b, 0xee, 0x31, 0x3a, 0x28, 0x00, 0x21, 0x51, 0x4a, 0xb7, 0xa4,
	0x88, 0xce, 0x5b, 0xb8, 0xe1, 0x7d, 0x57, 0x43, 0x5f, 0xe8, 0x49, 0x3c, 0xfa, 0x18, 0x0f, 0xa6,
	0xc3, 0xf1, 0x28, 0x5d, 0xe6, 0x31, 0x3a, 0xd0, 0x92, 0x70, 0x65, 0xba, 0x51, 0xf0, 0xf2, 0x52,
	0x4f, 0xd0, 0x51, 0x05, 0x25, 0x91, 0x6e, 0x09, 0xc9, 0xde, 0x03, 0x76, 0xac, 0xa3, 0x29, 0x09,
	0x75, 0x24, 0x01, 0xd7, 0x8c, 0xfc, 0x15, 0x54, 0xc2, 0x59, 0xc4, 0x7d, 0x5c, 0xb7, 0x82, 0x59,
	0xa7, 0x67, 0x75, 0x54, 0x40, 0x9f, 0xa9, 0x30, 0xd2, 0x80, 0x1b, 0xd6, 0xa1, 0x5d, 0x90, 0xec,
	0xac, 0x87, 0x37, 0xad, 0x43, 0xe1, 0x32, 0x64, 0x12, 0xfc, 0xac, 0x61, 0x2c, 0xe5, 0x6a, 0x90,
	0x9c, 0x04, 0x78, 0x60, 0xf6, 0xbe, 0x9b, 0x53, 0x48, 0xcd, 0xae, 0x52, 0x91, 0xde, 0xa0, 0xe3,
	0xfc, 0x28, 0x15, 0x35, 0xcb, 0x42, 0xbd, 0x45, 0xaf, 0xec, 0x0c, 0x1f, 0xb8, 0x36, 0x0b, 0x73,
	0xdc, 0x2f, 0xd1, 0x89, 0x95, 0x42, 0x5b, 0x66, 0xa7, 0x98, 0xde, 0xaa, 0xb9, 0x3f, 0x41, 0x6f,
	0xed, 0x9c, 0x4c, 0xd3, 0x54, 0x7b, 0x5c, 0x2f, 0x57, 0xb1, 0xa4, 0x71, 0xc1, 0x01, 0x6f, 0x78,
	0xff, 0x73, 0xd0, 0x4e, 0x18, 0x3f, 0x7e, 0x48, 0x46, 0xd3, 0x4e, 0x32, 0xbd, 0x1d, 0x5f, 0xa7,
	0x45, 0xbc, 0x46, 0x2f, 0x17, 0x1b, 0xa8, 0x03, 0xba, 0x25, 0xfc, 0x72, 0x0d, 0xc7, 0xe8, 0xc0,
	0x46, 0xa0, 0x44, 0xfa, 0xd8, 0x31, 0x4b, 0xb3, 0xa1, 0x3e, 0x3b, 0x67, 0x9a, 0x04, 0xf3, 0xdd,
	0x5e, 0x73, 0xbf, 0x42, 0xaf, 0xed, 0x34, 0x09, 0x54, 0xfb, 0xd0, 0x64, 0x1a, 0xd7, 0xdd, 0x9f,
	0xa2, 0x2f, 0xad, 0x99, 0x64, 0x2f, 0xd4, 0x82, 0x46, 0x52, 0x02, 0xa7, 0x3d, 0xbc, 0x61, 0x74,
	0xb7, 0xf1, 0x48, 0x18, 0x2a, 0x2d, 0x24, 0xe0, 0x86, 0xf7, 0xd7, 0x1a, 0xda, 0x2b, 0x94, 0x1a,
	0x4e, 0xc6, 0x0f, 0xc3, 0xeb, 0x64, 0x62, 0x59, 0x48, 0x7a, 0x12, 0xfb, 0x20, 0x73, 0x25, 0x57,
	0x13, 0x2c, 0x49, 0x67, 0x42, 0x76, 0xb2, 0xa7, 0xb6, 0x8e, 0x11, 0x92, 0x5e, 0x48, 0x02, 0x5c,
	0x73, 0x7f, 0x8c, 0xde, 0xac, 0xe3, 0x90, 0x30, 0x0c, 0x20, 0x24, 0x3d, 0x5c, 0xb7, 0x08, 0xb8,
	0x64, 0x9d, 0x0b, 0x71, 0x9e, 0xd1, 0x36, 0x3e, 0x45, 0x23, 0x1d, 0xf2, 0x5e, 0x70, 0x43, 0x6b,
	0x58, 0x9e, 0xe6, 0xaa, 0x3c, 0xa1, 0xf0, 0xa6, 0x45, 0xe3, 0x72, 0xba, 0x80, 0xf4, 0xf0, 0x96,
	0xf7, 0x5b, 0xb4, 0x5f, 0x10, 0x90, 0x8d, 0xee, 0x67, 0xd3, 0xc5, 0xa5, 0xc1, 0x78, 0x18, 0x69,
	0xcb, 0xa5, 0x91, 0x8b, 0x87, 0xad, 0x9e, 0x62, 0x94, 0x04, 0xd8, 0x29, 0x0d, 0xe8, 0x32, 0xa9,
	0xa3, 0x54, 0x9f, 0x5d, 0x84, 0xf3, 0x03, 0xa4, 0xb8, 0xec, 0xe1, 0xba, 0xf7, 0x0f, 0x07, 0x3d,
	0xa3, 0xe3, 0xd1, 0x74, 0x12, 0x0f, 0xb2, 0x7c, 0x87, 0x68, 0x8f, 0x0a, 0xae, 0x25, 0xa1, 0x95,
	0x94, 0xfb, 0xc8, 0x2d, 0x42, 0x69, 0xa7, 0x3b, 0xd5, 0x21, 0xf3, 0x92, 0x71, 0xcd, 0xd4, 0x5f,
	0x84, 0x54, 0xd4, 0x54, 0x54, 0xb2, 0x30, 0xdd, 0x32, 0x8c, 0x33, 0xcd, 0x48, 0x90, 0xf5, 0xe2,
	0x27, 0x78, 0x12, 0x38, 0x5c, 0x10, 0x73, 0x24, 0x1d, 0xa1, 0xfd, 0x22, 0x4f, 0x70, 0xa0, 0x01,
	0xa3, 0x6d, 0xdc, 0xf0, 0xfe, 0xe0, 0xa0, 0x6d, 0x18, 0x3d, 0x0c, 0x27, 0xe3, 0x91, 0x11, 0xd2,
	0x28, 0x04, 0xbc, 0xcb, 0xa4, 0xe0, 0xa9, 0xfe, 0xab, 0x3a, 0x0e, 0xd0, 0x6e, 0x1e, 0x68, 0x06,
	0x84, 0xb6, 0x9b, 0xe2, 0x32, 0x3b, 0xfe, 0xf3, 0x88, 0x06, 0xa5, 0x33, 0xe5, 0xf2, 0xd1, 0x20,
	0xbb, 0x68, 0x4b, 0xd1, 0x8e, 0xa0, 0x6d, 0xbc, 0xe1, 0xfd, 0x1e, 0x6d, 0x87, 0x93, 0xf1, 0xf5,
	0x6c, 0xae, 0xe6, 0x01, 0xda, 0x0d, 0xa5, 0xf0, 0xa3, 0xaa, 0x98, 0x65, 0x64, 0xfe, 0x07, 0x3b,
	0x15, 0x44, 0x81, 0xec, 0x32, 0x6a, 0x0e, 0xa6, 0x57, 0xe8, 0xb0, 0x88, 0xe4, 0x44, 0xc2, 0x75,
	0xef, 0xd7, 0x68, 0x4b, 0xb5, 0xa3, 0x34, 0xaf, 0xf1, 0x2d, 0xed, 0xc8, 0x72, 0xe7, 0x2d, 0xa3,
	0xa1, 0x64, 0x1d, 0x22, 0xcd, 0x91, 0x68, 0x8c, 0xcb, 0x22, 0x4a, 0x7c, 0x5f, 0x70, 0x5c, 0x4b,
	0x1d, 0xce, 0x22, 0x16, 0x85, 0x0a, 0x82, 0x00, 0xd7, 0xbd, 0xdf, 0xa1, 0x67, 0x7e, 0x72, 0x37,
	0x7c, 0x48, 0x26, 0x8f, 0x8b, 0x56, 0xf1, 0xc1, 0xa8, 0x21, 0x7b, 0x96, 0x56, 0x29, 0x42, 0xf3,
	0x56, 0x39, 0x42, 0xfb, 0xc5, 0xf8, 0xb2, 0x71, 0x6b, 0xd5, 0xe9, 0x16, 0xbd, 0x5b, 0x37, 0x67,
	0x29, 0x5e, 0xa4, 0x56, 0xd3, 0x78, 0x74, 0x1d, 0x4f, 0xae, 0x8d, 0x1a, 0x4b, 0xbe, 0xd2, 0x84,
	0xfb, 0x44, 0xfa, 0xc5, 0x5b, 0xb3, 0x0a, 0x2b, 0xd2, 0x81, 0xbe, 0x4f, 0x4c, 0xd9, 0x56, 0x9c,
	0xc3, 0xa5, 0x4e, 0xf1, 0x9a, 0x7d, 0x7a, 0x7d, 0x21, 0x52, 0xb8, 0x6e, 0x87, 0x81, 0x0a, 0x2e,
	0x3a, 0xe6, 0x00, 0x79, 0x89, 0x5e, 0x54, 0x61, 0xa1, 0x5b, 0x60, 0x2c, 0x57, 0x5e, 0x85, 0x55,
	0x6a, 0xa3, 0xd0, 0xa6, 0xf7, 0x67, 0x07, 0x3d, 0xd1, 0xc9, 0xe4, 0x43, 0xaa, 0xf0, 0x1e, 0xda,
	0xd1, 0x20, 0x3b, 0x16, 0x75, 0x57, 0x61, 0xc1, 0xa1, 0xaf, 0x59, 0x07, 0xb2, 0xf6, 0x5d, 0xc5,
	0x3b, 0x8c, 0x9b, 0x8b, 0xba, 0x6e, 0xcc, 0xee, 0x2a, 0xea, 0xa7, 0xc7, 0x9b, 0x8b, 0x3e, 0x5f,
	0x85, 0x2e, 0x00, 0xda, 0xb8, 0x61, 0x1e, 0x79, 0x6e, 0xb0, 0xe0, 0xba, 0x85, 0x37, 0x8b, 0xc4,
	0x1e, 0x10, 0x89, 0xb7, 0x8a, 0xb1, 0x74, 0xd5, 0x4f, 0xbc, 0xef, 0x1c, 0xb4, 0x7d, 0x16, 0x0f,
	0xef, 0x66, 0x93, 0x64, 0xd1, 0xf7, 0x67, 0x84, 0x05, 0xe6, 0xb6, 0x2c, 0xad, 0x7d, 0x0f, 0xed,
	0x14, 0x90, 0x79, 0x63, 0x94, 0xc3, 0x4a, 0x9c, 0x99, 0xad, 0x57, 0x0e, 0xb7, 0xcc, 0x35, 0x58,
	0x37, 0x02, 0x14, 0xc2, 0x12, 0xb4, 0x34, 0x75, 0x1d, 0xa2, 0xbd, 0x52, 0xda, 0xb9, 0xa9, 0x68,
	0x78, 0xdf, 0xd7, 0xd0, 0x4e, 0xce, 0x54, 0xc8, 0xe4, 0xe3, 0xec, 0x6e, 0x5a, 0xb6, 0x56, 0x12,
	0x54, 0x14, 0xe8, 0xf5, 0xd6, 0x6b, 0x8e, 0xab, 0x88, 0x1a, 0x73, 0x8c, 0x1d, 0x73, 0x01, 0x58,
	0x70, 0xdf, 0x9c, 0x49, 0x1c, 0xfc, 0xac, 0x8b, 0x2c, 0x84, 0xb9, 0x4f, 0xaa, 0xaf, 0x99, 0x7f,
	0xf1, 0x4e, 0xd3, 0x30, 0xe7, 0xe2, 0x7a, 0x7c, 0xb9, 0x8e, 0x8a, 0xdf, 0x9a, 0xf3, 0x32, 0x59,
	0xb6, 0xd6, 0x64, 0x59, 0xf8, 0xb1, 0x27, 0xeb, 0xb2, 0x10, 0x69, 0x4e, 0xe7, 0x65, 0x96, 0xa7,
	0x6b, 0xe6, 0x99, 0x2b, 0x8e, 0x91, 0xf7, 0x17, 0x07, 0xb9, 0xdd, 0x64, 0x32, 0xfc, 0x76, 0x38,
	0x88, 0x53, 0xe7, 0x96, 0xbd, 0xc0, 0xbd, 0x46, 0x2f, 0xd3, 0x82, 0x19, 0x25, 0x99, 0x53, 0x2a,
	0xbf, 0xcd, 0x7d, 0x85, 0x5e, 0xdb, 0x08, 0x5c, 0xe8, 0x3e, 0x6d, 0x01, 0x6d, 0x83, 0x9f, 0xed,
	0x57, 0x1b, 0xc9, 0x98, 0xeb, 0x54, 0xe9, 0x35, 0xb8, 0x59, 0x1d, 0x98, 0x9e, 0x79, 0x83, 0x8e,
	0x6d, 0xb8, 0xb9, 0x4e, 0x18, 0x8f, 0x8c, 0x63, 0xfb, 0xa3, 0x83, 0x76, 0xd2, 0xe5, 0x3f, 0xca,
	0xe4, 0x37, 0xb3, 0xe4, 0xe3, 0x74, 0xe1, 0xd8, 0xb2, 0xc7, 0xd5, 0x97, 0xf0, 0x75, 0x04, 0xaa,
	0x72, 0x92, 0x2f, 0x26, 0x2e, 0x13, 0x56, 0xa6, 0xf3, 0x2d, 0x7a, 0x65, 0x63, 0xe4, 0x3d, 0xe7,
	0x31, 0x3a, 0xb0, 0x51, 0xd2, 0xdd, 0x51, 0xf7, 0x6e, 0xd0, 0xd3, 0x60, 0x18, 0x5f, 0x0d, 0xef,
	0x86, 0xd3, 0x47, 0xb3, 0x27, 0x02, 0x46, 0x9a, 0x2c, 0x60, 0xba, 0x57, 0xdc, 0x58, 0xab, 0x70,
	0xc4, 0xdb, 0x5c, 0x5c, 0xf0, 0xcc, 0x0e, 0xac, 0xc2, 0xb9, 0x57, 0xc8, 0x5d, 0x84, 0x73, 0xb3,
	0x28, 0x15, 0x81, 0xc4, 0x75, 0xef, 0xbf, 0x0e, 0x7a, 0x1e, 0xde, 0xc5, 0x83, 0xc4, 0xdc, 0xa0,
	0x34, 0xbe, 0x5f, 0xe4, 0x34, 0x16, 0x2d, 0x20, 0x14, 0xd2, 0xab, 0x8e, 0x92, 0xb0, 0x9a, 0xde,
	0x58, 0x34, 0x1b, 0xc3, 0x18, 0xd7, 0xbc, 0x8d, 0xb3, 0x71, 0x52, 0x7f, 0x66, 0x5c, 0xc3, 0xdc,
	0xba, 0xda, 0x38, 0x99, 0x5d, 0xea, 0x67, 0x2e, 0xce, 0xf8, 0x2e, 0x1b, 0x69, 0x6e, 0x06, 0x37,
	0x4c, 0x33, 0x58, 0x09, 0x5a, 0xb4, 0x81, 0xe3, 0x46, 0x73, 0xfc, 0xaf, 0xef, 0x4f, 0x3e, 0xfb,
	0xdb, 0x7f, 0x4e, 0x9c, 0xf7, 0xbf, 0xcc, 0x7d, 0x97, 0xc8, 0x7d, 0xd3, 0x58, 0x7c, 0x90, 0xb8,
	0x8b, 0x47, 0x37, 0xa7, 0x95, 0x6f, 0x1d, 0xff, 0xac, 0xed, 0xd0, 0x34, 0xd6, 0x1a, 0x3e, 0x24,
	0xdf, 0xd0, 0x34, 0xf6, 0xef, 0xda, 0x51, 0x25, 0xf6, 0x4d, 0x27, 0x99, 0xc6, 0xd7, 0xf1, 0x34,
	0xbe, 0xda, 0x4c, 0x27, 0xfc, 0xc5, 0x0f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x04, 0x20, 0xa4,
	0x38, 0x11, 0x00, 0x00,
}
