// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: chargehive/chtype/fraud.proto

package chtype

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SuggestedAction int32

const (
	SUGGESTED_ACTION_INVALID       SuggestedAction = 0
	SUGGESTED_ACTION_NO_SUGGESTION SuggestedAction = 1
	SUGGESTED_ACTION_REVIEW        SuggestedAction = 2
	SUGGESTED_ACTION_ALLOW         SuggestedAction = 3
	SUGGESTED_ACTION_DENY          SuggestedAction = 4
)

var SuggestedAction_name = map[int32]string{
	0: "SUGGESTED_ACTION_INVALID",
	1: "SUGGESTED_ACTION_NO_SUGGESTION",
	2: "SUGGESTED_ACTION_REVIEW",
	3: "SUGGESTED_ACTION_ALLOW",
	4: "SUGGESTED_ACTION_DENY",
}

var SuggestedAction_value = map[string]int32{
	"SUGGESTED_ACTION_INVALID":       0,
	"SUGGESTED_ACTION_NO_SUGGESTION": 1,
	"SUGGESTED_ACTION_REVIEW":        2,
	"SUGGESTED_ACTION_ALLOW":         3,
	"SUGGESTED_ACTION_DENY":          4,
}

func (x SuggestedAction) String() string {
	return proto.EnumName(SuggestedAction_name, int32(x))
}

func (SuggestedAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_01129b4776a23f6b, []int{0}
}

type RiskLevel int32

const (
	RISK_LEVEL_INVALID     RiskLevel = 0
	RISK_LEVEL_NOT_RATED   RiskLevel = 1
	RISK_LEVEL_NEGLIGIBLE  RiskLevel = 10
	RISK_LEVEL_MINOR       RiskLevel = 30
	RISK_LEVEL_MODERATE    RiskLevel = 50
	RISK_LEVEL_SIGNIFICANT RiskLevel = 70
	RISK_LEVEL_SERVERE     RiskLevel = 90
)

var RiskLevel_name = map[int32]string{
	0:  "RISK_LEVEL_INVALID",
	1:  "RISK_LEVEL_NOT_RATED",
	10: "RISK_LEVEL_NEGLIGIBLE",
	30: "RISK_LEVEL_MINOR",
	50: "RISK_LEVEL_MODERATE",
	70: "RISK_LEVEL_SIGNIFICANT",
	90: "RISK_LEVEL_SERVERE",
}

var RiskLevel_value = map[string]int32{
	"RISK_LEVEL_INVALID":     0,
	"RISK_LEVEL_NOT_RATED":   1,
	"RISK_LEVEL_NEGLIGIBLE":  10,
	"RISK_LEVEL_MINOR":       30,
	"RISK_LEVEL_MODERATE":    50,
	"RISK_LEVEL_SIGNIFICANT": 70,
	"RISK_LEVEL_SERVERE":     90,
}

func (x RiskLevel) String() string {
	return proto.EnumName(RiskLevel_name, int32(x))
}

func (RiskLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_01129b4776a23f6b, []int{1}
}

type FraudFactor_On int32

const (
	FRAUD_FACTOR_ON_INVALID              FraudFactor_On = 0
	FRAUD_FACTOR_ON_ADDRESS              FraudFactor_On = 1
	FRAUD_FACTOR_ON_BROWSER              FraudFactor_On = 2
	FRAUD_FACTOR_ON_IP                   FraudFactor_On = 3
	FRAUD_FACTOR_ON_COUNTRY              FraudFactor_On = 4
	FRAUD_FACTOR_ON_STATE                FraudFactor_On = 5
	FRAUD_FACTOR_ON_CITY                 FraudFactor_On = 6
	FRAUD_FACTOR_ON_DEVICE               FraudFactor_On = 7
	FRAUD_FACTOR_ON_EMAIL                FraudFactor_On = 8
	FRAUD_FACTOR_ON_EMAIL_DOMAIN         FraudFactor_On = 9
	FRAUD_FACTOR_ON_DATE                 FraudFactor_On = 10
	FRAUD_FACTOR_ON_MERCHANT             FraudFactor_On = 11
	FRAUD_FACTOR_ON_ISSUER               FraudFactor_On = 12
	FRAUD_FACTOR_ON_BIN                  FraudFactor_On = 13
	FRAUD_FACTOR_ON_METHOD               FraudFactor_On = 14
	FRAUD_FACTOR_ON_CUSTOMER             FraudFactor_On = 15
	FRAUD_FACTOR_ON_AMOUNT               FraudFactor_On = 16
	FRAUD_FACTOR_ON_PHONE                FraudFactor_On = 17
	FRAUD_FACTOR_ON_LANGUAGE             FraudFactor_On = 18
	FRAUD_FACTOR_ON_DISTANCE_TO_BILLING  FraudFactor_On = 19
	FRAUD_FACTOR_ON_DISTANCE_TO_SHIPPING FraudFactor_On = 20
	FRAUD_FACTOR_ON_DISTANCE_TO_IP       FraudFactor_On = 21
	FRAUD_FACTOR_ON_OTHER                FraudFactor_On = 22
)

var FraudFactor_On_name = map[int32]string{
	0:  "FRAUD_FACTOR_ON_INVALID",
	1:  "FRAUD_FACTOR_ON_ADDRESS",
	2:  "FRAUD_FACTOR_ON_BROWSER",
	3:  "FRAUD_FACTOR_ON_IP",
	4:  "FRAUD_FACTOR_ON_COUNTRY",
	5:  "FRAUD_FACTOR_ON_STATE",
	6:  "FRAUD_FACTOR_ON_CITY",
	7:  "FRAUD_FACTOR_ON_DEVICE",
	8:  "FRAUD_FACTOR_ON_EMAIL",
	9:  "FRAUD_FACTOR_ON_EMAIL_DOMAIN",
	10: "FRAUD_FACTOR_ON_DATE",
	11: "FRAUD_FACTOR_ON_MERCHANT",
	12: "FRAUD_FACTOR_ON_ISSUER",
	13: "FRAUD_FACTOR_ON_BIN",
	14: "FRAUD_FACTOR_ON_METHOD",
	15: "FRAUD_FACTOR_ON_CUSTOMER",
	16: "FRAUD_FACTOR_ON_AMOUNT",
	17: "FRAUD_FACTOR_ON_PHONE",
	18: "FRAUD_FACTOR_ON_LANGUAGE",
	19: "FRAUD_FACTOR_ON_DISTANCE_TO_BILLING",
	20: "FRAUD_FACTOR_ON_DISTANCE_TO_SHIPPING",
	21: "FRAUD_FACTOR_ON_DISTANCE_TO_IP",
	22: "FRAUD_FACTOR_ON_OTHER",
}

var FraudFactor_On_value = map[string]int32{
	"FRAUD_FACTOR_ON_INVALID":              0,
	"FRAUD_FACTOR_ON_ADDRESS":              1,
	"FRAUD_FACTOR_ON_BROWSER":              2,
	"FRAUD_FACTOR_ON_IP":                   3,
	"FRAUD_FACTOR_ON_COUNTRY":              4,
	"FRAUD_FACTOR_ON_STATE":                5,
	"FRAUD_FACTOR_ON_CITY":                 6,
	"FRAUD_FACTOR_ON_DEVICE":               7,
	"FRAUD_FACTOR_ON_EMAIL":                8,
	"FRAUD_FACTOR_ON_EMAIL_DOMAIN":         9,
	"FRAUD_FACTOR_ON_DATE":                 10,
	"FRAUD_FACTOR_ON_MERCHANT":             11,
	"FRAUD_FACTOR_ON_ISSUER":               12,
	"FRAUD_FACTOR_ON_BIN":                  13,
	"FRAUD_FACTOR_ON_METHOD":               14,
	"FRAUD_FACTOR_ON_CUSTOMER":             15,
	"FRAUD_FACTOR_ON_AMOUNT":               16,
	"FRAUD_FACTOR_ON_PHONE":                17,
	"FRAUD_FACTOR_ON_LANGUAGE":             18,
	"FRAUD_FACTOR_ON_DISTANCE_TO_BILLING":  19,
	"FRAUD_FACTOR_ON_DISTANCE_TO_SHIPPING": 20,
	"FRAUD_FACTOR_ON_DISTANCE_TO_IP":       21,
	"FRAUD_FACTOR_ON_OTHER":                22,
}

func (x FraudFactor_On) String() string {
	return proto.EnumName(FraudFactor_On_name, int32(x))
}

func (FraudFactor_On) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_01129b4776a23f6b, []int{2, 0}
}

type FraudFactor_Factor int32

const (
	FRAUD_FACTOR_INVALID      FraudFactor_Factor = 0
	FRAUD_FACTOR_VERIFICATION FraudFactor_Factor = 1
	FRAUD_FACTOR_VALIDATION   FraudFactor_Factor = 2
	FRAUD_FACTOR_VELOCITY     FraudFactor_Factor = 3
	FRAUD_FACTOR_TRUST        FraudFactor_Factor = 4
	FRAUD_FACTOR_DURATION     FraudFactor_Factor = 5
	FRAUD_FACTOR_OTHER        FraudFactor_Factor = 6
)

var FraudFactor_Factor_name = map[int32]string{
	0: "FRAUD_FACTOR_INVALID",
	1: "FRAUD_FACTOR_VERIFICATION",
	2: "FRAUD_FACTOR_VALIDATION",
	3: "FRAUD_FACTOR_VELOCITY",
	4: "FRAUD_FACTOR_TRUST",
	5: "FRAUD_FACTOR_DURATION",
	6: "FRAUD_FACTOR_OTHER",
}

var FraudFactor_Factor_value = map[string]int32{
	"FRAUD_FACTOR_INVALID":      0,
	"FRAUD_FACTOR_VERIFICATION": 1,
	"FRAUD_FACTOR_VALIDATION":   2,
	"FRAUD_FACTOR_VELOCITY":     3,
	"FRAUD_FACTOR_TRUST":        4,
	"FRAUD_FACTOR_DURATION":     5,
	"FRAUD_FACTOR_OTHER":        6,
}

func (x FraudFactor_Factor) String() string {
	return proto.EnumName(FraudFactor_Factor_name, int32(x))
}

func (FraudFactor_Factor) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_01129b4776a23f6b, []int{2, 1}
}

type FraudResult struct {
	FraudCheckId         string                 `protobuf:"bytes,1,opt,name=fraud_check_id,json=fraudCheckId,proto3" json:"fraud_check_id,omitempty"`
	OverallScore         *FraudScore            `protobuf:"bytes,2,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"`
	SubScores            []*FraudScore          `protobuf:"bytes,3,rep,name=sub_scores,json=subScores,proto3" json:"sub_scores,omitempty"`
	SuggestedAction      SuggestedAction        `protobuf:"varint,4,opt,name=suggested_action,json=suggestedAction,proto3,enum=chargehive.chtype.SuggestedAction" json:"suggested_action,omitempty"`
	ScanTime             *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=scan_time,json=scanTime,proto3" json:"scan_time,omitempty"`
	ConnectorLibrary     string                 `protobuf:"bytes,6,opt,name=connector_library,json=connectorLibrary,proto3" json:"connector_library,omitempty"`
	AdditionalData       map[string]string      `protobuf:"bytes,7,rep,name=additional_data,json=additionalData,proto3" json:"additional_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	InfoLinks            map[string]string      `protobuf:"bytes,8,rep,name=info_links,json=infoLinks,proto3" json:"info_links,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *FraudResult) Reset()         { *m = FraudResult{} }
func (m *FraudResult) String() string { return proto.CompactTextString(m) }
func (*FraudResult) ProtoMessage()    {}
func (*FraudResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_01129b4776a23f6b, []int{0}
}
func (m *FraudResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FraudResult.Unmarshal(m, b)
}
func (m *FraudResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FraudResult.Marshal(b, m, deterministic)
}
func (m *FraudResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FraudResult.Merge(m, src)
}
func (m *FraudResult) XXX_Size() int {
	return xxx_messageInfo_FraudResult.Size(m)
}
func (m *FraudResult) XXX_DiscardUnknown() {
	xxx_messageInfo_FraudResult.DiscardUnknown(m)
}

var xxx_messageInfo_FraudResult proto.InternalMessageInfo

func (m *FraudResult) GetFraudCheckId() string {
	if m != nil {
		return m.FraudCheckId
	}
	return ""
}

func (m *FraudResult) GetOverallScore() *FraudScore {
	if m != nil {
		return m.OverallScore
	}
	return nil
}

func (m *FraudResult) GetSubScores() []*FraudScore {
	if m != nil {
		return m.SubScores
	}
	return nil
}

func (m *FraudResult) GetSuggestedAction() SuggestedAction {
	if m != nil {
		return m.SuggestedAction
	}
	return SUGGESTED_ACTION_INVALID
}

func (m *FraudResult) GetScanTime() *timestamppb.Timestamp {
	if m != nil {
		return m.ScanTime
	}
	return nil
}

func (m *FraudResult) GetConnectorLibrary() string {
	if m != nil {
		return m.ConnectorLibrary
	}
	return ""
}

func (m *FraudResult) GetAdditionalData() map[string]string {
	if m != nil {
		return m.AdditionalData
	}
	return nil
}

func (m *FraudResult) GetInfoLinks() map[string]string {
	if m != nil {
		return m.InfoLinks
	}
	return nil
}

type FraudScore struct {
	Score                float32           `protobuf:"fixed32,1,opt,name=score,proto3" json:"score,omitempty"`
	RiskLevel            RiskLevel         `protobuf:"varint,2,opt,name=risk_level,json=riskLevel,proto3,enum=chargehive.chtype.RiskLevel" json:"risk_level,omitempty"`
	Factor               *FraudFactor      `protobuf:"bytes,4,opt,name=factor,proto3" json:"factor,omitempty"`
	Summary              string            `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	Data                 map[string]string `protobuf:"bytes,7,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FraudScore) Reset()         { *m = FraudScore{} }
func (m *FraudScore) String() string { return proto.CompactTextString(m) }
func (*FraudScore) ProtoMessage()    {}
func (*FraudScore) Descriptor() ([]byte, []int) {
	return fileDescriptor_01129b4776a23f6b, []int{1}
}
func (m *FraudScore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FraudScore.Unmarshal(m, b)
}
func (m *FraudScore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FraudScore.Marshal(b, m, deterministic)
}
func (m *FraudScore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FraudScore.Merge(m, src)
}
func (m *FraudScore) XXX_Size() int {
	return xxx_messageInfo_FraudScore.Size(m)
}
func (m *FraudScore) XXX_DiscardUnknown() {
	xxx_messageInfo_FraudScore.DiscardUnknown(m)
}

var xxx_messageInfo_FraudScore proto.InternalMessageInfo

func (m *FraudScore) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *FraudScore) GetRiskLevel() RiskLevel {
	if m != nil {
		return m.RiskLevel
	}
	return RISK_LEVEL_INVALID
}

func (m *FraudScore) GetFactor() *FraudFactor {
	if m != nil {
		return m.Factor
	}
	return nil
}

func (m *FraudScore) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *FraudScore) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type FraudFactor struct {
	On                   FraudFactor_On     `protobuf:"varint,1,opt,name=on,proto3,enum=chargehive.chtype.FraudFactor_On" json:"on,omitempty"`
	Factor               FraudFactor_Factor `protobuf:"varint,2,opt,name=factor,proto3,enum=chargehive.chtype.FraudFactor_Factor" json:"factor,omitempty"`
	OtherOn              string             `protobuf:"bytes,3,opt,name=other_on,json=otherOn,proto3" json:"other_on,omitempty"`
	OtherFactor          string             `protobuf:"bytes,4,opt,name=other_factor,json=otherFactor,proto3" json:"other_factor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *FraudFactor) Reset()         { *m = FraudFactor{} }
func (m *FraudFactor) String() string { return proto.CompactTextString(m) }
func (*FraudFactor) ProtoMessage()    {}
func (*FraudFactor) Descriptor() ([]byte, []int) {
	return fileDescriptor_01129b4776a23f6b, []int{2}
}
func (m *FraudFactor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FraudFactor.Unmarshal(m, b)
}
func (m *FraudFactor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FraudFactor.Marshal(b, m, deterministic)
}
func (m *FraudFactor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FraudFactor.Merge(m, src)
}
func (m *FraudFactor) XXX_Size() int {
	return xxx_messageInfo_FraudFactor.Size(m)
}
func (m *FraudFactor) XXX_DiscardUnknown() {
	xxx_messageInfo_FraudFactor.DiscardUnknown(m)
}

var xxx_messageInfo_FraudFactor proto.InternalMessageInfo

func (m *FraudFactor) GetOn() FraudFactor_On {
	if m != nil {
		return m.On
	}
	return FRAUD_FACTOR_ON_INVALID
}

func (m *FraudFactor) GetFactor() FraudFactor_Factor {
	if m != nil {
		return m.Factor
	}
	return FRAUD_FACTOR_INVALID
}

func (m *FraudFactor) GetOtherOn() string {
	if m != nil {
		return m.OtherOn
	}
	return ""
}

func (m *FraudFactor) GetOtherFactor() string {
	if m != nil {
		return m.OtherFactor
	}
	return ""
}

func init() {
	proto.RegisterEnum("chargehive.chtype.SuggestedAction", SuggestedAction_name, SuggestedAction_value)
	golang_proto.RegisterEnum("chargehive.chtype.SuggestedAction", SuggestedAction_name, SuggestedAction_value)
	proto.RegisterEnum("chargehive.chtype.RiskLevel", RiskLevel_name, RiskLevel_value)
	golang_proto.RegisterEnum("chargehive.chtype.RiskLevel", RiskLevel_name, RiskLevel_value)
	proto.RegisterEnum("chargehive.chtype.FraudFactor_On", FraudFactor_On_name, FraudFactor_On_value)
	golang_proto.RegisterEnum("chargehive.chtype.FraudFactor_On", FraudFactor_On_name, FraudFactor_On_value)
	proto.RegisterEnum("chargehive.chtype.FraudFactor_Factor", FraudFactor_Factor_name, FraudFactor_Factor_value)
	golang_proto.RegisterEnum("chargehive.chtype.FraudFactor_Factor", FraudFactor_Factor_name, FraudFactor_Factor_value)
	proto.RegisterType((*FraudResult)(nil), "chargehive.chtype.FraudResult")
	golang_proto.RegisterType((*FraudResult)(nil), "chargehive.chtype.FraudResult")
	proto.RegisterMapType((map[string]string)(nil), "chargehive.chtype.FraudResult.AdditionalDataEntry")
	golang_proto.RegisterMapType((map[string]string)(nil), "chargehive.chtype.FraudResult.AdditionalDataEntry")
	proto.RegisterMapType((map[string]string)(nil), "chargehive.chtype.FraudResult.InfoLinksEntry")
	golang_proto.RegisterMapType((map[string]string)(nil), "chargehive.chtype.FraudResult.InfoLinksEntry")
	proto.RegisterType((*FraudScore)(nil), "chargehive.chtype.FraudScore")
	golang_proto.RegisterType((*FraudScore)(nil), "chargehive.chtype.FraudScore")
	proto.RegisterMapType((map[string]string)(nil), "chargehive.chtype.FraudScore.DataEntry")
	golang_proto.RegisterMapType((map[string]string)(nil), "chargehive.chtype.FraudScore.DataEntry")
	proto.RegisterType((*FraudFactor)(nil), "chargehive.chtype.FraudFactor")
	golang_proto.RegisterType((*FraudFactor)(nil), "chargehive.chtype.FraudFactor")
}

func init() { proto.RegisterFile("chargehive/chtype/fraud.proto", fileDescriptor_01129b4776a23f6b) }
func init() {
	golang_proto.RegisterFile("chargehive/chtype/fraud.proto", fileDescriptor_01129b4776a23f6b)
}

var fileDescriptor_01129b4776a23f6b = []byte{
	// 1114 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x17, 0x8d, 0x28, 0x4b, 0xb1, 0xae, 0x1d, 0x79, 0x3c, 0x51, 0x12, 0x46, 0x5f, 0xa2, 0xcf, 0x51,
	0x53, 0xc4, 0x48, 0x51, 0x09, 0x55, 0x8b, 0xa6, 0x68, 0xd2, 0x05, 0x2d, 0x8e, 0xa4, 0x41, 0x29,
	0xd2, 0x18, 0x52, 0x0a, 0x92, 0x06, 0x20, 0x28, 0x89, 0x96, 0x08, 0xcb, 0x64, 0x40, 0x52, 0x06,
	0xfc, 0x22, 0x7d, 0x85, 0x6c, 0xba, 0xeb, 0xb2, 0x9b, 0x2e, 0xba, 0xea, 0xaa, 0xaf, 0xd0, 0xf6,
	0x45, 0x8a, 0x19, 0x5a, 0xb6, 0x2c, 0x32, 0x36, 0xda, 0xdd, 0xdc, 0x7b, 0xce, 0x3d, 0x73, 0xff,
	0xf8, 0x03, 0x8f, 0xc7, 0x33, 0x27, 0x9c, 0xba, 0x33, 0xef, 0xd4, 0x6d, 0x8e, 0x67, 0xf1, 0xd9,
	0x7b, 0xb7, 0x79, 0x14, 0x3a, 0x8b, 0x49, 0xe3, 0x7d, 0x18, 0xc4, 0x01, 0xde, 0xbd, 0x84, 0x1b,
	0x09, 0x5c, 0xad, 0x4c, 0x83, 0x69, 0x20, 0xd0, 0x26, 0x3f, 0x25, 0xc4, 0xea, 0xff, 0xa7, 0x41,
	0x30, 0x9d, 0xbb, 0x4d, 0x61, 0x8d, 0x16, 0x47, 0xcd, 0xd8, 0x3b, 0x71, 0xa3, 0xd8, 0x39, 0x79,
	0x9f, 0x10, 0xea, 0x3f, 0x16, 0x60, 0xab, 0xc3, 0x95, 0x99, 0x1b, 0x2d, 0xe6, 0x31, 0x7e, 0x0a,
	0x65, 0x71, 0x91, 0x3d, 0x9e, 0xb9, 0xe3, 0x63, 0xdb, 0x9b, 0xc8, 0xb9, 0xbd, 0xdc, 0x7e, 0x89,
	0x6d, 0x0b, 0x6f, 0x9b, 0x3b, 0xe9, 0x04, 0x1f, 0xc0, 0x9d, 0xe0, 0xd4, 0x0d, 0x9d, 0xf9, 0xdc,
	0x8e, 0xc6, 0x41, 0xe8, 0xca, 0xd2, 0x5e, 0x6e, 0x7f, 0xab, 0xf5, 0xb8, 0x91, 0xca, 0xab, 0x21,
	0xc4, 0x4d, 0x4e, 0x62, 0xdb, 0xe7, 0x31, 0xc2, 0xc2, 0xaf, 0x00, 0xa2, 0xc5, 0x28, 0x89, 0x8f,
	0xe4, 0xfc, 0x5e, 0xfe, 0x66, 0x81, 0x52, 0xb4, 0x18, 0x89, 0x53, 0x84, 0xfb, 0x80, 0xa2, 0xc5,
	0x74, 0xea, 0x46, 0xb1, 0x3b, 0xb1, 0x9d, 0x71, 0xec, 0x05, 0xbe, 0xbc, 0xb1, 0x97, 0xdb, 0x2f,
	0xb7, 0xea, 0x19, 0x1a, 0xe6, 0x92, 0xaa, 0x08, 0x26, 0xdb, 0x89, 0xae, 0x3a, 0xf0, 0x0b, 0x28,
	0x45, 0x63, 0xc7, 0xb7, 0x79, 0x7b, 0xe4, 0x82, 0x28, 0xa6, 0xda, 0x48, 0x7a, 0xd7, 0x58, 0xf6,
	0xae, 0x61, 0x2d, 0x7b, 0xc7, 0x36, 0x39, 0x99, 0x9b, 0xf8, 0x33, 0xd8, 0x1d, 0x07, 0xbe, 0xef,
	0x8e, 0xe3, 0x20, 0xb4, 0xe7, 0xde, 0x28, 0x74, 0xc2, 0x33, 0xb9, 0x28, 0x5a, 0x86, 0x2e, 0x00,
	0x2d, 0xf1, 0xe3, 0x1f, 0x60, 0xc7, 0x99, 0x4c, 0x3c, 0x7e, 0xa3, 0x33, 0xb7, 0x27, 0x4e, 0xec,
	0xc8, 0xb7, 0x45, 0xdd, 0xad, 0x8f, 0xd5, 0x9d, 0x4c, 0xa5, 0xa1, 0x5c, 0x44, 0xa9, 0x4e, 0xec,
	0x10, 0x3f, 0x0e, 0xcf, 0x58, 0xd9, 0xb9, 0xe2, 0xc4, 0x1a, 0x80, 0xe7, 0x1f, 0x05, 0xf6, 0xdc,
	0xf3, 0x8f, 0x23, 0x79, 0x53, 0xe8, 0x7e, 0x7e, 0x83, 0x2e, 0xf5, 0x8f, 0x02, 0x8d, 0xf3, 0x13,
	0xc9, 0x92, 0xb7, 0xb4, 0xab, 0x0a, 0xdc, 0xcd, 0xb8, 0x14, 0x23, 0xc8, 0x1f, 0xbb, 0x67, 0xe7,
	0x3b, 0xc1, 0x8f, 0xb8, 0x02, 0x85, 0x53, 0x67, 0xbe, 0x48, 0x56, 0xa0, 0xc4, 0x12, 0xe3, 0x5b,
	0xe9, 0x9b, 0x5c, 0xf5, 0x15, 0x94, 0xaf, 0xea, 0xff, 0x9b, 0xe8, 0xfa, 0x07, 0x09, 0xe0, 0x72,
	0xf4, 0x9c, 0x98, 0x6c, 0x1a, 0x0f, 0x96, 0x58, 0x62, 0xe0, 0x97, 0x00, 0xa1, 0x17, 0x1d, 0xdb,
	0x73, 0xf7, 0xd4, 0x9d, 0x0b, 0x8d, 0x72, 0xeb, 0x51, 0x46, 0xcd, 0xcc, 0x8b, 0x8e, 0x35, 0xce,
	0x61, 0xa5, 0x70, 0x79, 0xc4, 0x5f, 0x43, 0xf1, 0xc8, 0xe1, 0xe3, 0x11, 0x8b, 0xb3, 0xd5, 0xaa,
	0x7d, 0xac, 0x59, 0x1d, 0xc1, 0x62, 0xe7, 0x6c, 0x2c, 0xc3, 0xed, 0x68, 0x71, 0x72, 0x72, 0x39,
	0xe8, 0xa5, 0x89, 0x5f, 0xc2, 0xc6, 0xca, 0x50, 0x9f, 0x5d, 0xbb, 0xcc, 0x8d, 0xcb, 0x49, 0x8a,
	0xa0, 0xea, 0x0b, 0x28, 0xfd, 0xa7, 0x3e, 0xd7, 0x7f, 0xde, 0x3c, 0x7f, 0x84, 0x93, 0x3c, 0xf1,
	0x17, 0x20, 0x05, 0xbe, 0x08, 0x2d, 0xb7, 0x9e, 0x5c, 0x5f, 0x53, 0xc3, 0xf0, 0x99, 0x14, 0xf8,
	0xf8, 0xbb, 0x8b, 0x56, 0x24, 0x3d, 0xfc, 0xf4, 0x86, 0xb0, 0xb5, 0x8e, 0x3c, 0x84, 0xcd, 0x20,
	0x9e, 0xb9, 0xa1, 0x1d, 0xf8, 0x72, 0x3e, 0x69, 0x89, 0xb0, 0x0d, 0x1f, 0x3f, 0x81, 0xed, 0x04,
	0x5a, 0x69, 0x75, 0x89, 0x6d, 0x09, 0x5f, 0xa2, 0x52, 0xff, 0xa9, 0x00, 0x92, 0xe1, 0xe3, 0xff,
	0xc1, 0x83, 0x0e, 0x53, 0x06, 0xaa, 0xdd, 0x51, 0xda, 0x96, 0xc1, 0x6c, 0x43, 0xb7, 0xa9, 0x3e,
	0x54, 0x34, 0xaa, 0xa2, 0x5b, 0x59, 0xa0, 0xa2, 0xaa, 0x8c, 0x98, 0x26, 0xca, 0x65, 0x81, 0x07,
	0xcc, 0x78, 0x6d, 0x12, 0x86, 0x24, 0x7c, 0x1f, 0x70, 0x4a, 0xf6, 0x10, 0xe5, 0xb3, 0x82, 0xda,
	0xc6, 0x40, 0xb7, 0xd8, 0x1b, 0xb4, 0x81, 0x1f, 0xc2, 0xbd, 0x75, 0xd0, 0xb4, 0x14, 0x8b, 0xa0,
	0x02, 0x96, 0xa1, 0x92, 0x8a, 0xa3, 0xd6, 0x1b, 0x54, 0xc4, 0x55, 0xb8, 0xbf, 0x8e, 0xa8, 0x64,
	0x48, 0xdb, 0x04, 0xdd, 0xce, 0x12, 0x24, 0x7d, 0x85, 0x6a, 0x68, 0x13, 0xef, 0xc1, 0xa3, 0x4c,
	0xc8, 0x56, 0x8d, 0xbe, 0x42, 0x75, 0x54, 0xca, 0xba, 0x52, 0xe5, 0xc9, 0x00, 0x7e, 0x04, 0xf2,
	0x3a, 0xd2, 0x27, 0xac, 0xdd, 0x53, 0x74, 0x0b, 0x6d, 0x65, 0x25, 0x44, 0x4d, 0x73, 0x40, 0x18,
	0xda, 0xc6, 0x0f, 0xe0, 0x6e, 0xaa, 0x67, 0x54, 0x47, 0x77, 0xb2, 0x82, 0xfa, 0xc4, 0xea, 0x19,
	0x2a, 0x2a, 0x67, 0x5d, 0xd7, 0x1e, 0x98, 0x96, 0xd1, 0x27, 0x0c, 0xed, 0x64, 0x45, 0x2a, 0x7d,
	0xde, 0x52, 0x84, 0xb2, 0xea, 0x3f, 0xec, 0x19, 0x3a, 0x41, 0xbb, 0x59, 0xa2, 0x9a, 0xa2, 0x77,
	0x07, 0x4a, 0x97, 0x20, 0x8c, 0x9f, 0xc1, 0x27, 0xa9, 0xda, 0xa9, 0x69, 0x29, 0x7a, 0x9b, 0xd8,
	0x96, 0x61, 0x1f, 0x50, 0x4d, 0xa3, 0x7a, 0x17, 0xdd, 0xc5, 0xfb, 0xf0, 0xf4, 0x3a, 0xa2, 0xd9,
	0xa3, 0x87, 0x87, 0x9c, 0x59, 0xc1, 0x75, 0xa8, 0x5d, 0xc7, 0xa4, 0x87, 0xe8, 0x5e, 0x56, 0xbe,
	0x86, 0xd5, 0x23, 0x0c, 0xdd, 0xaf, 0xff, 0x96, 0x83, 0x62, 0x67, 0xf9, 0x26, 0xb8, 0x3a, 0x98,
	0xcb, 0x7d, 0x7d, 0x0c, 0x0f, 0xaf, 0x20, 0x43, 0xc2, 0x68, 0x87, 0xb6, 0x15, 0x8b, 0x1a, 0x7a,
	0xc6, 0xc6, 0x8a, 0xb0, 0x04, 0x94, 0x52, 0x77, 0x0f, 0x89, 0x66, 0x88, 0x15, 0xcb, 0xa7, 0x96,
	0xd9, 0x62, 0x03, 0xd3, 0xca, 0xd8, 0x57, 0x75, 0xc0, 0x12, 0xb5, 0x42, 0x7a, 0xff, 0x45, 0x19,
	0xc5, 0xe7, 0x1f, 0x72, 0xb0, 0xb3, 0xf6, 0x59, 0xe4, 0xa3, 0x30, 0x07, 0xdd, 0x2e, 0x31, 0x2d,
	0xa2, 0xda, 0x4a, 0x9b, 0x2b, 0xac, 0xd4, 0x54, 0x87, 0x5a, 0x0a, 0xd5, 0x0d, 0xfb, 0xdc, 0x77,
	0x51, 0x58, 0x8a, 0xc3, 0xc8, 0x90, 0x92, 0xd7, 0x48, 0xe2, 0x0b, 0x92, 0x02, 0x15, 0x4d, 0x33,
	0x5e, 0xa3, 0x3c, 0xaf, 0x20, 0x85, 0xa9, 0x44, 0x7f, 0x83, 0x36, 0x9e, 0xff, 0x92, 0x83, 0xd2,
	0xc5, 0x0b, 0x9c, 0xd7, 0xc3, 0xa8, 0xf9, 0xbd, 0xad, 0x91, 0x21, 0xd1, 0x56, 0xb2, 0x93, 0xa1,
	0xb2, 0xe2, 0xd7, 0x0d, 0xcb, 0x66, 0x8a, 0x45, 0x54, 0x94, 0xe3, 0xd2, 0xab, 0x08, 0xe9, 0x6a,
	0xb4, 0x4b, 0x0f, 0x34, 0xfe, 0xfc, 0x54, 0x00, 0xad, 0x40, 0x7d, 0xaa, 0x1b, 0x0c, 0xd5, 0xf8,
	0xb3, 0xb1, 0xea, 0x35, 0x54, 0xc2, 0xa5, 0x50, 0x8b, 0x17, 0xb0, 0x02, 0x98, 0xb4, 0xab, 0x8b,
	0xa1, 0xea, 0x16, 0xea, 0xac, 0xe5, 0x65, 0x12, 0x36, 0x24, 0x8c, 0xa0, 0xb7, 0x07, 0xc1, 0x1f,
	0x7f, 0xd6, 0x6e, 0xfd, 0xfa, 0x77, 0x2d, 0xf7, 0xf6, 0xab, 0xa9, 0x17, 0xcf, 0x16, 0xa3, 0xc6,
	0x38, 0x38, 0x69, 0xae, 0xfc, 0xde, 0x2d, 0xff, 0xd9, 0xe6, 0x8e, 0x3f, 0x6d, 0xa6, 0x7e, 0xfb,
	0x7e, 0x97, 0x76, 0xdb, 0xc2, 0xd7, 0xf3, 0x4e, 0xdd, 0x77, 0x6d, 0xe1, 0xfb, 0x4b, 0xaa, 0xa6,
	0x7c, 0xef, 0xfa, 0x6e, 0xec, 0xf0, 0xef, 0xc8, 0xa8, 0x28, 0x04, 0xbf, 0xfc, 0x27, 0x00, 0x00,
	0xff, 0xff, 0x92, 0x4e, 0x2e, 0x35, 0x43, 0x0a, 0x00, 0x00,
}
