// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: chargehive/chtype/payment_method_schema.proto

package chtype

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PaymentMethodSchema int32

const (
	PAYMENT_METHOD_SCHEMA_INVALID        PaymentMethodSchema = 0
	PAYMENT_METHOD_SCHEMA_ENCRYPTED_CARD PaymentMethodSchema = 1
	PAYMENT_METHOD_SCHEMA_CARD           PaymentMethodSchema = 2
	PAYMENT_METHOD_SCHEMA_APPLE_PAY      PaymentMethodSchema = 3
	PAYMENT_METHOD_SCHEMA_GOOGLE_PAY     PaymentMethodSchema = 4
	PAYMENT_METHOD_SCHEMA_PAYPAL         PaymentMethodSchema = 5
)

var PaymentMethodSchema_name = map[int32]string{
	0: "PAYMENT_METHOD_SCHEMA_INVALID",
	1: "PAYMENT_METHOD_SCHEMA_ENCRYPTED_CARD",
	2: "PAYMENT_METHOD_SCHEMA_CARD",
	3: "PAYMENT_METHOD_SCHEMA_APPLE_PAY",
	4: "PAYMENT_METHOD_SCHEMA_GOOGLE_PAY",
	5: "PAYMENT_METHOD_SCHEMA_PAYPAL",
}

var PaymentMethodSchema_value = map[string]int32{
	"PAYMENT_METHOD_SCHEMA_INVALID":        0,
	"PAYMENT_METHOD_SCHEMA_ENCRYPTED_CARD": 1,
	"PAYMENT_METHOD_SCHEMA_CARD":           2,
	"PAYMENT_METHOD_SCHEMA_APPLE_PAY":      3,
	"PAYMENT_METHOD_SCHEMA_GOOGLE_PAY":     4,
	"PAYMENT_METHOD_SCHEMA_PAYPAL":         5,
}

func (x PaymentMethodSchema) String() string {
	return proto.EnumName(PaymentMethodSchema_name, int32(x))
}

func (PaymentMethodSchema) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_acf1a4ab3aa467b5, []int{0}
}

type PaymentMethodSchemaApplePay struct {
	SessionUrl           string   `protobuf:"bytes,1,opt,name=session_url,json=sessionUrl,proto3" json:"session_url,omitempty"`
	InitiativeContext    string   `protobuf:"bytes,2,opt,name=initiative_context,json=initiativeContext,proto3" json:"initiative_context,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Session              string   `protobuf:"bytes,4,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentMethodSchemaApplePay) Reset()         { *m = PaymentMethodSchemaApplePay{} }
func (m *PaymentMethodSchemaApplePay) String() string { return proto.CompactTextString(m) }
func (*PaymentMethodSchemaApplePay) ProtoMessage()    {}
func (*PaymentMethodSchemaApplePay) Descriptor() ([]byte, []int) {
	return fileDescriptor_acf1a4ab3aa467b5, []int{0}
}
func (m *PaymentMethodSchemaApplePay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethodSchemaApplePay.Unmarshal(m, b)
}
func (m *PaymentMethodSchemaApplePay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethodSchemaApplePay.Marshal(b, m, deterministic)
}
func (m *PaymentMethodSchemaApplePay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethodSchemaApplePay.Merge(m, src)
}
func (m *PaymentMethodSchemaApplePay) XXX_Size() int {
	return xxx_messageInfo_PaymentMethodSchemaApplePay.Size(m)
}
func (m *PaymentMethodSchemaApplePay) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethodSchemaApplePay.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethodSchemaApplePay proto.InternalMessageInfo

func (m *PaymentMethodSchemaApplePay) GetSessionUrl() string {
	if m != nil {
		return m.SessionUrl
	}
	return ""
}

func (m *PaymentMethodSchemaApplePay) GetInitiativeContext() string {
	if m != nil {
		return m.InitiativeContext
	}
	return ""
}

func (m *PaymentMethodSchemaApplePay) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *PaymentMethodSchemaApplePay) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

type PaymentMethodSchemaGooglePay struct {
	LowValueToken        string   `protobuf:"bytes,1,opt,name=low_value_token,json=lowValueToken,proto3" json:"low_value_token,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	CardDetails          string   `protobuf:"bytes,3,opt,name=card_details,json=cardDetails,proto3" json:"card_details,omitempty"`
	CardNetwork          string   `protobuf:"bytes,4,opt,name=card_network,json=cardNetwork,proto3" json:"card_network,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentMethodSchemaGooglePay) Reset()         { *m = PaymentMethodSchemaGooglePay{} }
func (m *PaymentMethodSchemaGooglePay) String() string { return proto.CompactTextString(m) }
func (*PaymentMethodSchemaGooglePay) ProtoMessage()    {}
func (*PaymentMethodSchemaGooglePay) Descriptor() ([]byte, []int) {
	return fileDescriptor_acf1a4ab3aa467b5, []int{1}
}
func (m *PaymentMethodSchemaGooglePay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethodSchemaGooglePay.Unmarshal(m, b)
}
func (m *PaymentMethodSchemaGooglePay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethodSchemaGooglePay.Marshal(b, m, deterministic)
}
func (m *PaymentMethodSchemaGooglePay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethodSchemaGooglePay.Merge(m, src)
}
func (m *PaymentMethodSchemaGooglePay) XXX_Size() int {
	return xxx_messageInfo_PaymentMethodSchemaGooglePay.Size(m)
}
func (m *PaymentMethodSchemaGooglePay) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethodSchemaGooglePay.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethodSchemaGooglePay proto.InternalMessageInfo

func (m *PaymentMethodSchemaGooglePay) GetLowValueToken() string {
	if m != nil {
		return m.LowValueToken
	}
	return ""
}

func (m *PaymentMethodSchemaGooglePay) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PaymentMethodSchemaGooglePay) GetCardDetails() string {
	if m != nil {
		return m.CardDetails
	}
	return ""
}

func (m *PaymentMethodSchemaGooglePay) GetCardNetwork() string {
	if m != nil {
		return m.CardNetwork
	}
	return ""
}

type PaymentMethodSchemaPayPal struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentMethodSchemaPayPal) Reset()         { *m = PaymentMethodSchemaPayPal{} }
func (m *PaymentMethodSchemaPayPal) String() string { return proto.CompactTextString(m) }
func (*PaymentMethodSchemaPayPal) ProtoMessage()    {}
func (*PaymentMethodSchemaPayPal) Descriptor() ([]byte, []int) {
	return fileDescriptor_acf1a4ab3aa467b5, []int{2}
}
func (m *PaymentMethodSchemaPayPal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethodSchemaPayPal.Unmarshal(m, b)
}
func (m *PaymentMethodSchemaPayPal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethodSchemaPayPal.Marshal(b, m, deterministic)
}
func (m *PaymentMethodSchemaPayPal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethodSchemaPayPal.Merge(m, src)
}
func (m *PaymentMethodSchemaPayPal) XXX_Size() int {
	return xxx_messageInfo_PaymentMethodSchemaPayPal.Size(m)
}
func (m *PaymentMethodSchemaPayPal) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethodSchemaPayPal.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethodSchemaPayPal proto.InternalMessageInfo

type PaymentMethodSchemaEncryptedCard struct {
	NameOnCard           []byte   `protobuf:"bytes,1,opt,name=name_on_card,json=nameOnCard,proto3" json:"name_on_card,omitempty"`
	Number               []byte   `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	ValidFromMonth       []byte   `protobuf:"bytes,3,opt,name=valid_from_month,json=validFromMonth,proto3" json:"valid_from_month,omitempty"`
	ValidFromYear        []byte   `protobuf:"bytes,4,opt,name=valid_from_year,json=validFromYear,proto3" json:"valid_from_year,omitempty"`
	ExpiryMonth          []byte   `protobuf:"bytes,5,opt,name=expiry_month,json=expiryMonth,proto3" json:"expiry_month,omitempty"`
	ExpiryYear           []byte   `protobuf:"bytes,6,opt,name=expiry_year,json=expiryYear,proto3" json:"expiry_year,omitempty"`
	IssueNumber          []byte   `protobuf:"bytes,7,opt,name=issue_number,json=issueNumber,proto3" json:"issue_number,omitempty"`
	TransportKeyId       string   `protobuf:"bytes,8,opt,name=transport_key_id,json=transportKeyId,proto3" json:"transport_key_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentMethodSchemaEncryptedCard) Reset()         { *m = PaymentMethodSchemaEncryptedCard{} }
func (m *PaymentMethodSchemaEncryptedCard) String() string { return proto.CompactTextString(m) }
func (*PaymentMethodSchemaEncryptedCard) ProtoMessage()    {}
func (*PaymentMethodSchemaEncryptedCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_acf1a4ab3aa467b5, []int{3}
}
func (m *PaymentMethodSchemaEncryptedCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethodSchemaEncryptedCard.Unmarshal(m, b)
}
func (m *PaymentMethodSchemaEncryptedCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethodSchemaEncryptedCard.Marshal(b, m, deterministic)
}
func (m *PaymentMethodSchemaEncryptedCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethodSchemaEncryptedCard.Merge(m, src)
}
func (m *PaymentMethodSchemaEncryptedCard) XXX_Size() int {
	return xxx_messageInfo_PaymentMethodSchemaEncryptedCard.Size(m)
}
func (m *PaymentMethodSchemaEncryptedCard) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethodSchemaEncryptedCard.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethodSchemaEncryptedCard proto.InternalMessageInfo

func (m *PaymentMethodSchemaEncryptedCard) GetNameOnCard() []byte {
	if m != nil {
		return m.NameOnCard
	}
	return nil
}

func (m *PaymentMethodSchemaEncryptedCard) GetNumber() []byte {
	if m != nil {
		return m.Number
	}
	return nil
}

func (m *PaymentMethodSchemaEncryptedCard) GetValidFromMonth() []byte {
	if m != nil {
		return m.ValidFromMonth
	}
	return nil
}

func (m *PaymentMethodSchemaEncryptedCard) GetValidFromYear() []byte {
	if m != nil {
		return m.ValidFromYear
	}
	return nil
}

func (m *PaymentMethodSchemaEncryptedCard) GetExpiryMonth() []byte {
	if m != nil {
		return m.ExpiryMonth
	}
	return nil
}

func (m *PaymentMethodSchemaEncryptedCard) GetExpiryYear() []byte {
	if m != nil {
		return m.ExpiryYear
	}
	return nil
}

func (m *PaymentMethodSchemaEncryptedCard) GetIssueNumber() []byte {
	if m != nil {
		return m.IssueNumber
	}
	return nil
}

func (m *PaymentMethodSchemaEncryptedCard) GetTransportKeyId() string {
	if m != nil {
		return m.TransportKeyId
	}
	return ""
}

type PaymentMethodSchemaCard struct {
	NameOnCard           string   `protobuf:"bytes,1,opt,name=name_on_card,json=nameOnCard,proto3" json:"name_on_card,omitempty"`
	ValidFromMonth       int32    `protobuf:"varint,2,opt,name=valid_from_month,json=validFromMonth,proto3" json:"valid_from_month,omitempty"`
	ValidFromYear        int32    `protobuf:"varint,3,opt,name=valid_from_year,json=validFromYear,proto3" json:"valid_from_year,omitempty"`
	ExpiryMonth          int32    `protobuf:"varint,4,opt,name=expiry_month,json=expiryMonth,proto3" json:"expiry_month,omitempty"`
	ExpiryYear           int32    `protobuf:"varint,5,opt,name=expiry_year,json=expiryYear,proto3" json:"expiry_year,omitempty"`
	IssueNumber          int32    `protobuf:"varint,6,opt,name=issue_number,json=issueNumber,proto3" json:"issue_number,omitempty"`
	Number               string   `protobuf:"bytes,7,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentMethodSchemaCard) Reset()         { *m = PaymentMethodSchemaCard{} }
func (m *PaymentMethodSchemaCard) String() string { return proto.CompactTextString(m) }
func (*PaymentMethodSchemaCard) ProtoMessage()    {}
func (*PaymentMethodSchemaCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_acf1a4ab3aa467b5, []int{4}
}
func (m *PaymentMethodSchemaCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethodSchemaCard.Unmarshal(m, b)
}
func (m *PaymentMethodSchemaCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethodSchemaCard.Marshal(b, m, deterministic)
}
func (m *PaymentMethodSchemaCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethodSchemaCard.Merge(m, src)
}
func (m *PaymentMethodSchemaCard) XXX_Size() int {
	return xxx_messageInfo_PaymentMethodSchemaCard.Size(m)
}
func (m *PaymentMethodSchemaCard) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethodSchemaCard.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethodSchemaCard proto.InternalMessageInfo

func (m *PaymentMethodSchemaCard) GetNameOnCard() string {
	if m != nil {
		return m.NameOnCard
	}
	return ""
}

func (m *PaymentMethodSchemaCard) GetValidFromMonth() int32 {
	if m != nil {
		return m.ValidFromMonth
	}
	return 0
}

func (m *PaymentMethodSchemaCard) GetValidFromYear() int32 {
	if m != nil {
		return m.ValidFromYear
	}
	return 0
}

func (m *PaymentMethodSchemaCard) GetExpiryMonth() int32 {
	if m != nil {
		return m.ExpiryMonth
	}
	return 0
}

func (m *PaymentMethodSchemaCard) GetExpiryYear() int32 {
	if m != nil {
		return m.ExpiryYear
	}
	return 0
}

func (m *PaymentMethodSchemaCard) GetIssueNumber() int32 {
	if m != nil {
		return m.IssueNumber
	}
	return 0
}

func (m *PaymentMethodSchemaCard) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func init() {
	proto.RegisterEnum("chargehive.chtype.PaymentMethodSchema", PaymentMethodSchema_name, PaymentMethodSchema_value)
	golang_proto.RegisterEnum("chargehive.chtype.PaymentMethodSchema", PaymentMethodSchema_name, PaymentMethodSchema_value)
	proto.RegisterType((*PaymentMethodSchemaApplePay)(nil), "chargehive.chtype.PaymentMethodSchemaApplePay")
	golang_proto.RegisterType((*PaymentMethodSchemaApplePay)(nil), "chargehive.chtype.PaymentMethodSchemaApplePay")
	proto.RegisterType((*PaymentMethodSchemaGooglePay)(nil), "chargehive.chtype.PaymentMethodSchemaGooglePay")
	golang_proto.RegisterType((*PaymentMethodSchemaGooglePay)(nil), "chargehive.chtype.PaymentMethodSchemaGooglePay")
	proto.RegisterType((*PaymentMethodSchemaPayPal)(nil), "chargehive.chtype.PaymentMethodSchemaPayPal")
	golang_proto.RegisterType((*PaymentMethodSchemaPayPal)(nil), "chargehive.chtype.PaymentMethodSchemaPayPal")
	proto.RegisterType((*PaymentMethodSchemaEncryptedCard)(nil), "chargehive.chtype.PaymentMethodSchemaEncryptedCard")
	golang_proto.RegisterType((*PaymentMethodSchemaEncryptedCard)(nil), "chargehive.chtype.PaymentMethodSchemaEncryptedCard")
	proto.RegisterType((*PaymentMethodSchemaCard)(nil), "chargehive.chtype.PaymentMethodSchemaCard")
	golang_proto.RegisterType((*PaymentMethodSchemaCard)(nil), "chargehive.chtype.PaymentMethodSchemaCard")
}

func init() {
	proto.RegisterFile("chargehive/chtype/payment_method_schema.proto", fileDescriptor_acf1a4ab3aa467b5)
}
func init() {
	golang_proto.RegisterFile("chargehive/chtype/payment_method_schema.proto", fileDescriptor_acf1a4ab3aa467b5)
}

var fileDescriptor_acf1a4ab3aa467b5 = []byte{
	// 685 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x51, 0x4e, 0x13, 0x41,
	0x1c, 0xc6, 0x69, 0xa1, 0x45, 0xa6, 0x05, 0xcb, 0x68, 0xb4, 0x02, 0x42, 0xa9, 0xc4, 0x10, 0x13,
	0xe8, 0x83, 0x5e, 0x60, 0x6d, 0x2b, 0x10, 0x69, 0xbb, 0x29, 0x95, 0xa4, 0x86, 0x64, 0x32, 0xdd,
	0x1d, 0xda, 0x09, 0xbb, 0x33, 0x9b, 0xd9, 0x69, 0x61, 0xef, 0xe0, 0x15, 0xbc, 0x82, 0x57, 0xd0,
	0x67, 0x9f, 0xbc, 0x82, 0x7a, 0x00, 0xaf, 0x60, 0xf6, 0x3f, 0x4b, 0xa9, 0x61, 0x45, 0xdf, 0xf6,
	0xff, 0xcd, 0x2f, 0xdf, 0x7c, 0xff, 0x6f, 0x93, 0x41, 0x7b, 0xce, 0x88, 0xaa, 0x21, 0x1b, 0xf1,
	0x09, 0xab, 0x39, 0x23, 0x1d, 0x05, 0xac, 0x16, 0xd0, 0xc8, 0x67, 0x42, 0x13, 0x9f, 0xe9, 0x91,
	0x74, 0x49, 0xe8, 0x8c, 0x98, 0x4f, 0xf7, 0x03, 0x25, 0xb5, 0xc4, 0xab, 0x37, 0xf8, 0xbe, 0xc1,
	0xd7, 0xf6, 0x86, 0x5c, 0x8f, 0xc6, 0x83, 0x7d, 0x47, 0xfa, 0xb5, 0xa1, 0x1c, 0xca, 0x1a, 0x90,
	0x83, 0xf1, 0x39, 0x4c, 0x30, 0xc0, 0x97, 0x71, 0xa8, 0x7e, 0xcc, 0xa0, 0x75, 0xdb, 0xdc, 0xd0,
	0x82, 0x0b, 0x4e, 0xc0, 0xdf, 0x0a, 0x02, 0x8f, 0xd9, 0x34, 0xc2, 0x5b, 0xa8, 0x10, 0xb2, 0x30,
	0xe4, 0x52, 0x90, 0xb1, 0xf2, 0xca, 0x99, 0x4a, 0x66, 0x77, 0xa9, 0x8b, 0x12, 0xe9, 0x9d, 0xf2,
	0xf0, 0x1e, 0xc2, 0x5c, 0x70, 0xcd, 0xa9, 0xe6, 0x13, 0x46, 0x1c, 0x29, 0x34, 0xbb, 0xd2, 0xe5,
	0x2c, 0x70, 0xab, 0x37, 0x27, 0x75, 0x73, 0x80, 0x1f, 0xa2, 0x9c, 0x96, 0x17, 0x4c, 0x94, 0xe7,
	0x81, 0x30, 0x03, 0x2e, 0xa3, 0xc5, 0xc4, 0xb2, 0xbc, 0x00, 0xfa, 0xf5, 0x58, 0xfd, 0x94, 0x41,
	0x1b, 0x29, 0xf9, 0x0e, 0xa4, 0x1c, 0x9a, 0x80, 0xcf, 0xd1, 0x7d, 0x4f, 0x5e, 0x92, 0x09, 0xf5,
	0xc6, 0x8c, 0x18, 0x6b, 0x13, 0x72, 0xd9, 0x93, 0x97, 0xa7, 0xb1, 0xda, 0x83, 0x2b, 0x2a, 0xa8,
	0xe0, 0xb2, 0xd0, 0x51, 0x3c, 0xd0, 0xf1, 0x35, 0x26, 0xe0, 0xac, 0x84, 0xb7, 0x51, 0xd1, 0xa1,
	0xca, 0x25, 0x2e, 0xd3, 0x94, 0x7b, 0x61, 0x92, 0xb0, 0x10, 0x6b, 0x0d, 0x23, 0x4d, 0x11, 0xc1,
	0xf4, 0xa5, 0x54, 0x17, 0x49, 0x58, 0x40, 0xda, 0x46, 0xaa, 0xae, 0xa3, 0x27, 0x29, 0x79, 0x6d,
	0x1a, 0xd9, 0xd4, 0xab, 0x7e, 0xce, 0xa2, 0x4a, 0xca, 0x69, 0x53, 0x38, 0x2a, 0x0a, 0x34, 0x73,
	0xeb, 0x54, 0xb9, 0xb8, 0x82, 0x8a, 0x82, 0xfa, 0x8c, 0x48, 0x41, 0x62, 0x63, 0x58, 0xa7, 0xd8,
	0x45, 0xb1, 0xd6, 0x11, 0x40, 0x3c, 0x42, 0x79, 0x31, 0xf6, 0x07, 0x4c, 0xc1, 0x1a, 0xc5, 0x6e,
	0x32, 0xe1, 0x5d, 0x54, 0x9a, 0x50, 0x8f, 0xbb, 0xe4, 0x5c, 0x49, 0x9f, 0xf8, 0x52, 0xe8, 0x11,
	0x6c, 0x51, 0xec, 0xae, 0x80, 0xfe, 0x46, 0x49, 0xbf, 0x15, 0xab, 0x71, 0x6b, 0x33, 0x64, 0xc4,
	0xa8, 0x82, 0x5d, 0x8a, 0xdd, 0xe5, 0x29, 0xd8, 0x67, 0x54, 0xc5, 0x0b, 0xb3, 0xab, 0x80, 0xab,
	0x28, 0x71, 0xcb, 0x01, 0x54, 0x30, 0x9a, 0xb1, 0xda, 0x42, 0xc9, 0x68, 0x6c, 0xf2, 0x26, 0xad,
	0x91, 0xae, 0x3d, 0x78, 0x18, 0x8e, 0x19, 0x49, 0x32, 0x2f, 0x1a, 0x0f, 0xd0, 0xda, 0xd3, 0xe0,
	0x5a, 0x51, 0x11, 0x06, 0x52, 0x69, 0x72, 0xc1, 0x22, 0xc2, 0xdd, 0xf2, 0x3d, 0xe8, 0x76, 0x65,
	0xaa, 0xbf, 0x65, 0xd1, 0x91, 0x5b, 0xfd, 0x90, 0x45, 0x8f, 0x53, 0x1a, 0xfc, 0x6b, 0x71, 0x4b,
	0x7f, 0x14, 0x97, 0x56, 0x50, 0x5c, 0x61, 0xee, 0x7f, 0x0a, 0x9a, 0x07, 0xf0, 0x1f, 0x05, 0x2d,
	0x00, 0x74, 0x57, 0x41, 0x39, 0x20, 0xee, 0x2a, 0x28, 0x6f, 0x3c, 0x66, 0x0b, 0xba, 0xf9, 0xe3,
	0x8b, 0xb0, 0x54, 0x32, 0xbd, 0xf8, 0x95, 0x41, 0x0f, 0x52, 0xea, 0xc0, 0xdb, 0xe8, 0xa9, 0x6d,
	0xf5, 0x5b, 0xcd, 0x76, 0x8f, 0xb4, 0x9a, 0xbd, 0xc3, 0x4e, 0x83, 0x9c, 0xd4, 0x0f, 0x9b, 0x2d,
	0x8b, 0x1c, 0xb5, 0x4f, 0xad, 0xe3, 0xa3, 0x46, 0x69, 0x0e, 0xef, 0xa2, 0x9d, 0x74, 0xa4, 0xd9,
	0xae, 0x77, 0xfb, 0x76, 0xaf, 0xd9, 0x20, 0x75, 0xab, 0xdb, 0x28, 0x65, 0xf0, 0x26, 0x5a, 0x4b,
	0x27, 0xe1, 0x3c, 0x8b, 0x9f, 0xa1, 0xad, 0xf4, 0x73, 0xcb, 0xb6, 0x8f, 0x9b, 0xc4, 0xb6, 0xfa,
	0xa5, 0x79, 0xbc, 0x83, 0x2a, 0xe9, 0xd0, 0x41, 0xa7, 0x73, 0x90, 0x50, 0x0b, 0xb8, 0x82, 0x36,
	0xd2, 0x29, 0xdb, 0xea, 0xdb, 0xd6, 0x71, 0x29, 0xf7, 0x5a, 0x7e, 0xfb, 0xbe, 0x39, 0xf7, 0xe5,
	0xe7, 0x66, 0xe6, 0xfd, 0xab, 0x99, 0x97, 0x6e, 0xe6, 0xd9, 0xbc, 0x7e, 0xe2, 0x3c, 0x2a, 0x86,
	0xb5, 0x5b, 0xcf, 0xe9, 0xd7, 0xec, 0x6a, 0x1d, 0xb4, 0x43, 0x3e, 0x61, 0x67, 0x75, 0xd0, 0x7e,
	0x64, 0xd7, 0x6e, 0x69, 0x67, 0x2d, 0xa6, 0xa9, 0x4b, 0x35, 0x1d, 0xe4, 0xc1, 0xf0, 0xe5, 0xef,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x80, 0xf3, 0xc2, 0x09, 0x9b, 0x05, 0x00, 0x00,
}
