// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: chargehive/chtype/payment_method.proto

package chtype

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PaymentMethodUpdateReason int32

const (
	PAYMENT_METHOD_UPDATE_REASON_INVALID                PaymentMethodUpdateReason = 0
	PAYMENT_METHOD_UPDATE_REASON_ACCOUNT_CLOSED         PaymentMethodUpdateReason = 1
	PAYMENT_METHOD_UPDATE_REASON_NEW_EXPIRY_DATE        PaymentMethodUpdateReason = 2
	PAYMENT_METHOD_UPDATE_REASON_NEW_ACCOUNT_NUMBER     PaymentMethodUpdateReason = 3
	PAYMENT_METHOD_UPDATE_REASON_NEW_ACCOUNT_AND_EXPIRY PaymentMethodUpdateReason = 4
	PAYMENT_METHOD_UPDATE_REASON_NO_CHANGE              PaymentMethodUpdateReason = 5
)

var PaymentMethodUpdateReason_name = map[int32]string{
	0: "PAYMENT_METHOD_UPDATE_REASON_INVALID",
	1: "PAYMENT_METHOD_UPDATE_REASON_ACCOUNT_CLOSED",
	2: "PAYMENT_METHOD_UPDATE_REASON_NEW_EXPIRY_DATE",
	3: "PAYMENT_METHOD_UPDATE_REASON_NEW_ACCOUNT_NUMBER",
	4: "PAYMENT_METHOD_UPDATE_REASON_NEW_ACCOUNT_AND_EXPIRY",
	5: "PAYMENT_METHOD_UPDATE_REASON_NO_CHANGE",
}

var PaymentMethodUpdateReason_value = map[string]int32{
	"PAYMENT_METHOD_UPDATE_REASON_INVALID":                0,
	"PAYMENT_METHOD_UPDATE_REASON_ACCOUNT_CLOSED":         1,
	"PAYMENT_METHOD_UPDATE_REASON_NEW_EXPIRY_DATE":        2,
	"PAYMENT_METHOD_UPDATE_REASON_NEW_ACCOUNT_NUMBER":     3,
	"PAYMENT_METHOD_UPDATE_REASON_NEW_ACCOUNT_AND_EXPIRY": 4,
	"PAYMENT_METHOD_UPDATE_REASON_NO_CHANGE":              5,
}

func (x PaymentMethodUpdateReason) String() string {
	return proto.EnumName(PaymentMethodUpdateReason_name, int32(x))
}

func (PaymentMethodUpdateReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7e9f0d4a8cee9c1c, []int{0}
}

type PaymentMethodVerificationItemType int32

const (
	PAYMENT_METHOD_VERIFICATION_ITEM_TYPE_INVALID            PaymentMethodVerificationItemType = 0
	PAYMENT_METHOD_VERIFICATION_ITEM_TYPE_CVV                PaymentMethodVerificationItemType = 1
	PAYMENT_METHOD_VERIFICATION_ITEM_TYPE_DEVICE_DETAILS     PaymentMethodVerificationItemType = 2
	PAYMENT_METHOD_VERIFICATION_ITEM_TYPE_IDENTIFY_RESPONSE  PaymentMethodVerificationItemType = 3
	PAYMENT_METHOD_VERIFICATION_ITEM_TYPE_CHALLENGE_RESPONSE PaymentMethodVerificationItemType = 4
	PAYMENT_METHOD_VERIFICATION_ITEM_TYPE_NAMED              PaymentMethodVerificationItemType = 5
)

var PaymentMethodVerificationItemType_name = map[int32]string{
	0: "PAYMENT_METHOD_VERIFICATION_ITEM_TYPE_INVALID",
	1: "PAYMENT_METHOD_VERIFICATION_ITEM_TYPE_CVV",
	2: "PAYMENT_METHOD_VERIFICATION_ITEM_TYPE_DEVICE_DETAILS",
	3: "PAYMENT_METHOD_VERIFICATION_ITEM_TYPE_IDENTIFY_RESPONSE",
	4: "PAYMENT_METHOD_VERIFICATION_ITEM_TYPE_CHALLENGE_RESPONSE",
	5: "PAYMENT_METHOD_VERIFICATION_ITEM_TYPE_NAMED",
}

var PaymentMethodVerificationItemType_value = map[string]int32{
	"PAYMENT_METHOD_VERIFICATION_ITEM_TYPE_INVALID":            0,
	"PAYMENT_METHOD_VERIFICATION_ITEM_TYPE_CVV":                1,
	"PAYMENT_METHOD_VERIFICATION_ITEM_TYPE_DEVICE_DETAILS":     2,
	"PAYMENT_METHOD_VERIFICATION_ITEM_TYPE_IDENTIFY_RESPONSE":  3,
	"PAYMENT_METHOD_VERIFICATION_ITEM_TYPE_CHALLENGE_RESPONSE": 4,
	"PAYMENT_METHOD_VERIFICATION_ITEM_TYPE_NAMED":              5,
}

func (x PaymentMethodVerificationItemType) String() string {
	return proto.EnumName(PaymentMethodVerificationItemType_name, int32(x))
}

func (PaymentMethodVerificationItemType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7e9f0d4a8cee9c1c, []int{1}
}

type PaymentMethod struct {
	Schema               PaymentMethodSchema    `protobuf:"varint,1,opt,name=schema,proto3,enum=chargehive.chtype.PaymentMethodSchema" json:"schema,omitempty"`
	Json                 []byte                 `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`
	Type                 PaymentMethodType      `protobuf:"varint,3,opt,name=type,proto3,enum=chargehive.chtype.PaymentMethodType" json:"type,omitempty"`
	Provider             PaymentMethodProvider  `protobuf:"varint,4,opt,name=provider,proto3,enum=chargehive.chtype.PaymentMethodProvider" json:"provider,omitempty"`
	InputType            PaymentMethodInputType `protobuf:"varint,5,opt,name=inputType,proto3,enum=chargehive.chtype.PaymentMethodInputType" json:"inputType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PaymentMethod) Reset()         { *m = PaymentMethod{} }
func (m *PaymentMethod) String() string { return proto.CompactTextString(m) }
func (*PaymentMethod) ProtoMessage()    {}
func (*PaymentMethod) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e9f0d4a8cee9c1c, []int{0}
}
func (m *PaymentMethod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethod.Unmarshal(m, b)
}
func (m *PaymentMethod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethod.Marshal(b, m, deterministic)
}
func (m *PaymentMethod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethod.Merge(m, src)
}
func (m *PaymentMethod) XXX_Size() int {
	return xxx_messageInfo_PaymentMethod.Size(m)
}
func (m *PaymentMethod) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethod.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethod proto.InternalMessageInfo

func (m *PaymentMethod) GetSchema() PaymentMethodSchema {
	if m != nil {
		return m.Schema
	}
	return PAYMENT_METHOD_SCHEMA_INVALID
}

func (m *PaymentMethod) GetJson() []byte {
	if m != nil {
		return m.Json
	}
	return nil
}

func (m *PaymentMethod) GetType() PaymentMethodType {
	if m != nil {
		return m.Type
	}
	return PAYMENT_METHOD_TYPE_INVALID
}

func (m *PaymentMethod) GetProvider() PaymentMethodProvider {
	if m != nil {
		return m.Provider
	}
	return PAYMENT_METHOD_PROVIDER_INVALID
}

func (m *PaymentMethod) GetInputType() PaymentMethodInputType {
	if m != nil {
		return m.InputType
	}
	return INPUT_TYPE_INVALID
}

type PaymentMethodVerificationItem struct {
	Type                 PaymentMethodVerificationItemType `protobuf:"varint,1,opt,name=type,proto3,enum=chargehive.chtype.PaymentMethodVerificationItemType" json:"type,omitempty"`
	Value                []byte                            `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TransportKeyId       string                            `protobuf:"bytes,4,opt,name=transport_key_id,json=transportKeyId,proto3" json:"transport_key_id,omitempty"`
	IsError              bool                              `protobuf:"varint,5,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	Name                 string                            `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *PaymentMethodVerificationItem) Reset()         { *m = PaymentMethodVerificationItem{} }
func (m *PaymentMethodVerificationItem) String() string { return proto.CompactTextString(m) }
func (*PaymentMethodVerificationItem) ProtoMessage()    {}
func (*PaymentMethodVerificationItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e9f0d4a8cee9c1c, []int{1}
}
func (m *PaymentMethodVerificationItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethodVerificationItem.Unmarshal(m, b)
}
func (m *PaymentMethodVerificationItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethodVerificationItem.Marshal(b, m, deterministic)
}
func (m *PaymentMethodVerificationItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethodVerificationItem.Merge(m, src)
}
func (m *PaymentMethodVerificationItem) XXX_Size() int {
	return xxx_messageInfo_PaymentMethodVerificationItem.Size(m)
}
func (m *PaymentMethodVerificationItem) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethodVerificationItem.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethodVerificationItem proto.InternalMessageInfo

func (m *PaymentMethodVerificationItem) GetType() PaymentMethodVerificationItemType {
	if m != nil {
		return m.Type
	}
	return PAYMENT_METHOD_VERIFICATION_ITEM_TYPE_INVALID
}

func (m *PaymentMethodVerificationItem) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *PaymentMethodVerificationItem) GetTransportKeyId() string {
	if m != nil {
		return m.TransportKeyId
	}
	return ""
}

func (m *PaymentMethodVerificationItem) GetIsError() bool {
	if m != nil {
		return m.IsError
	}
	return false
}

func (m *PaymentMethodVerificationItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PaymentMethodInfo struct {
	TokenId              string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PaymentScheme        string                 `protobuf:"bytes,3,opt,name=payment_scheme,json=paymentScheme,proto3" json:"payment_scheme,omitempty"`
	ValidFrom            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	Expiry               *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Type                 PaymentMethodType      `protobuf:"varint,6,opt,name=type,proto3,enum=chargehive.chtype.PaymentMethodType" json:"type,omitempty"`
	Info                 map[string]string      `protobuf:"bytes,7,rep,name=info,proto3" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Provider             PaymentMethodProvider  `protobuf:"varint,8,opt,name=provider,proto3,enum=chargehive.chtype.PaymentMethodProvider" json:"provider,omitempty"`
	InputType            PaymentMethodInputType `protobuf:"varint,9,opt,name=inputType,proto3,enum=chargehive.chtype.PaymentMethodInputType" json:"inputType,omitempty"`
	Status               Status                 `protobuf:"varint,10,opt,name=status,proto3,enum=chargehive.chtype.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PaymentMethodInfo) Reset()         { *m = PaymentMethodInfo{} }
func (m *PaymentMethodInfo) String() string { return proto.CompactTextString(m) }
func (*PaymentMethodInfo) ProtoMessage()    {}
func (*PaymentMethodInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e9f0d4a8cee9c1c, []int{2}
}
func (m *PaymentMethodInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethodInfo.Unmarshal(m, b)
}
func (m *PaymentMethodInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethodInfo.Marshal(b, m, deterministic)
}
func (m *PaymentMethodInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethodInfo.Merge(m, src)
}
func (m *PaymentMethodInfo) XXX_Size() int {
	return xxx_messageInfo_PaymentMethodInfo.Size(m)
}
func (m *PaymentMethodInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethodInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethodInfo proto.InternalMessageInfo

func (m *PaymentMethodInfo) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

func (m *PaymentMethodInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PaymentMethodInfo) GetPaymentScheme() string {
	if m != nil {
		return m.PaymentScheme
	}
	return ""
}

func (m *PaymentMethodInfo) GetValidFrom() *timestamppb.Timestamp {
	if m != nil {
		return m.ValidFrom
	}
	return nil
}

func (m *PaymentMethodInfo) GetExpiry() *timestamppb.Timestamp {
	if m != nil {
		return m.Expiry
	}
	return nil
}

func (m *PaymentMethodInfo) GetType() PaymentMethodType {
	if m != nil {
		return m.Type
	}
	return PAYMENT_METHOD_TYPE_INVALID
}

func (m *PaymentMethodInfo) GetInfo() map[string]string {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *PaymentMethodInfo) GetProvider() PaymentMethodProvider {
	if m != nil {
		return m.Provider
	}
	return PAYMENT_METHOD_PROVIDER_INVALID
}

func (m *PaymentMethodInfo) GetInputType() PaymentMethodInputType {
	if m != nil {
		return m.InputType
	}
	return INPUT_TYPE_INVALID
}

func (m *PaymentMethodInfo) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return STATUS_INVALID
}

func init() {
	proto.RegisterEnum("chargehive.chtype.PaymentMethodUpdateReason", PaymentMethodUpdateReason_name, PaymentMethodUpdateReason_value)
	golang_proto.RegisterEnum("chargehive.chtype.PaymentMethodUpdateReason", PaymentMethodUpdateReason_name, PaymentMethodUpdateReason_value)
	proto.RegisterEnum("chargehive.chtype.PaymentMethodVerificationItemType", PaymentMethodVerificationItemType_name, PaymentMethodVerificationItemType_value)
	golang_proto.RegisterEnum("chargehive.chtype.PaymentMethodVerificationItemType", PaymentMethodVerificationItemType_name, PaymentMethodVerificationItemType_value)
	proto.RegisterType((*PaymentMethod)(nil), "chargehive.chtype.PaymentMethod")
	golang_proto.RegisterType((*PaymentMethod)(nil), "chargehive.chtype.PaymentMethod")
	proto.RegisterType((*PaymentMethodVerificationItem)(nil), "chargehive.chtype.PaymentMethodVerificationItem")
	golang_proto.RegisterType((*PaymentMethodVerificationItem)(nil), "chargehive.chtype.PaymentMethodVerificationItem")
	proto.RegisterType((*PaymentMethodInfo)(nil), "chargehive.chtype.PaymentMethodInfo")
	golang_proto.RegisterType((*PaymentMethodInfo)(nil), "chargehive.chtype.PaymentMethodInfo")
	proto.RegisterMapType((map[string]string)(nil), "chargehive.chtype.PaymentMethodInfo.InfoEntry")
	golang_proto.RegisterMapType((map[string]string)(nil), "chargehive.chtype.PaymentMethodInfo.InfoEntry")
}

func init() {
	proto.RegisterFile("chargehive/chtype/payment_method.proto", fileDescriptor_7e9f0d4a8cee9c1c)
}
func init() {
	golang_proto.RegisterFile("chargehive/chtype/payment_method.proto", fileDescriptor_7e9f0d4a8cee9c1c)
}

var fileDescriptor_7e9f0d4a8cee9c1c = []byte{
	// 854 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x5d, 0x6f, 0xe3, 0x44,
	0x14, 0x5d, 0x3b, 0x69, 0xda, 0xdc, 0x65, 0x2b, 0x77, 0xc4, 0x43, 0x1a, 0xc1, 0x52, 0xaa, 0xa5,
	0xca, 0x16, 0xea, 0xb0, 0x6d, 0xa5, 0x96, 0x0f, 0x21, 0xb9, 0xf6, 0xb4, 0xb1, 0x48, 0x9c, 0x68,
	0xe2, 0x06, 0x8a, 0x56, 0xb2, 0xdc, 0x64, 0x92, 0x98, 0xd6, 0x1e, 0xcb, 0x99, 0x44, 0xe4, 0x3f,
	0xf1, 0x23, 0x10, 0x8f, 0x3c, 0xc1, 0x1b, 0xaf, 0xc0, 0x23, 0x7f, 0x02, 0x79, 0xec, 0x24, 0x4d,
	0xbb, 0xd4, 0x01, 0xed, 0x4b, 0x32, 0xf7, 0xfa, 0x9c, 0x73, 0x3f, 0x7c, 0xe4, 0x81, 0xbd, 0xee,
	0xd0, 0x8d, 0x06, 0x74, 0xe8, 0x4d, 0x68, 0xb5, 0x3b, 0xe4, 0xd3, 0x90, 0x56, 0x43, 0x77, 0xea,
	0xd3, 0x80, 0x3b, 0x3e, 0xe5, 0x43, 0xd6, 0x53, 0xc3, 0x88, 0x71, 0x86, 0xb6, 0x16, 0x38, 0x35,
	0xc1, 0x95, 0x0f, 0x06, 0x1e, 0x1f, 0x8e, 0xaf, 0xd5, 0x2e, 0xf3, 0xab, 0x03, 0x36, 0x60, 0x55,
	0x81, 0xbc, 0x1e, 0xf7, 0x45, 0x24, 0x02, 0x71, 0x4a, 0x14, 0xca, 0xef, 0x3d, 0xac, 0x44, 0x83,
	0xb1, 0x9f, 0x3e, 0x3d, 0xc8, 0xea, 0xc3, 0x19, 0x75, 0x87, 0xd4, 0x77, 0x53, 0xf8, 0x07, 0x03,
	0xc6, 0x06, 0xb7, 0x74, 0x51, 0x92, 0x7b, 0x3e, 0x1d, 0x71, 0xd7, 0x0f, 0x13, 0xc0, 0xee, 0x8f,
	0x32, 0x3c, 0x6b, 0x25, 0x02, 0x0d, 0xc1, 0x47, 0x5f, 0x41, 0x21, 0x91, 0x28, 0x49, 0x3b, 0x52,
	0x65, 0xf3, 0x70, 0x4f, 0x7d, 0x30, 0x92, 0xba, 0xc4, 0x68, 0x0b, 0x34, 0x49, 0x59, 0x08, 0x41,
	0xfe, 0xfb, 0x11, 0x0b, 0x4a, 0xf2, 0x8e, 0x54, 0x79, 0x87, 0x88, 0x33, 0x3a, 0x85, 0x7c, 0xcc,
	0x2b, 0xe5, 0x84, 0xe2, 0x8b, 0x2c, 0x45, 0x7b, 0x1a, 0x52, 0x22, 0x18, 0xc8, 0x80, 0x8d, 0x30,
	0x62, 0x13, 0xaf, 0x47, 0xa3, 0x52, 0x5e, 0xb0, 0x2b, 0x59, 0xec, 0x56, 0x8a, 0x27, 0x73, 0x26,
	0xba, 0x80, 0xa2, 0x17, 0x84, 0x63, 0x1e, 0x0b, 0x97, 0xd6, 0x84, 0xcc, 0xcb, 0x2c, 0x19, 0x73,
	0x46, 0x20, 0x0b, 0xee, 0xee, 0xef, 0x12, 0xbc, 0xbf, 0x84, 0xea, 0xd0, 0xc8, 0xeb, 0x7b, 0x5d,
	0x97, 0x7b, 0x2c, 0x30, 0x39, 0xf5, 0x51, 0x2d, 0x1d, 0x35, 0x59, 0xde, 0x71, 0x56, 0x95, 0xfb,
	0xfc, 0x3b, 0xa3, 0xbf, 0x0b, 0x6b, 0x13, 0xf7, 0x76, 0x4c, 0xd3, 0x4d, 0x26, 0x01, 0xaa, 0x80,
	0xc2, 0x23, 0x37, 0x18, 0x85, 0x2c, 0xe2, 0xce, 0x0d, 0x9d, 0x3a, 0x5e, 0x4f, 0x2c, 0xa6, 0x48,
	0x36, 0xe7, 0xf9, 0xaf, 0xe9, 0xd4, 0xec, 0xa1, 0x6d, 0xd8, 0xf0, 0x46, 0x0e, 0x8d, 0x22, 0x16,
	0x89, 0x99, 0x37, 0xc8, 0xba, 0x37, 0xc2, 0x71, 0x18, 0xbf, 0xa3, 0xc0, 0xf5, 0x69, 0xa9, 0x20,
	0x88, 0xe2, 0xbc, 0xfb, 0x5b, 0x1e, 0xb6, 0xee, 0x2d, 0xa0, 0xcf, 0x62, 0x11, 0xce, 0x6e, 0x68,
	0x10, 0x97, 0x91, 0x04, 0x7a, 0x5d, 0xc4, 0x66, 0x6f, 0x2e, 0x22, 0x2f, 0x44, 0xd0, 0x47, 0xb0,
	0x39, 0xb3, 0xa3, 0xb0, 0x43, 0xf2, 0xca, 0x8b, 0xe4, 0x59, 0x9a, 0x15, 0x5e, 0xa1, 0xe8, 0x33,
	0x80, 0x89, 0x7b, 0xeb, 0xf5, 0x9c, 0x7e, 0xc4, 0x7c, 0xd1, 0xfe, 0xd3, 0xc3, 0xb2, 0x9a, 0x78,
	0x55, 0x9d, 0x79, 0x55, 0xb5, 0x67, 0x5e, 0x25, 0x45, 0x81, 0x3e, 0x8f, 0x98, 0x8f, 0x0e, 0xa1,
	0x40, 0x7f, 0x08, 0xbd, 0x68, 0x2a, 0x66, 0x7a, 0x9c, 0x96, 0x22, 0xe7, 0xf6, 0x2b, 0xfc, 0x67,
	0xfb, 0x9d, 0x41, 0xde, 0x0b, 0xfa, 0xac, 0xb4, 0xbe, 0x93, 0xab, 0x3c, 0x3d, 0x54, 0xb3, 0x3d,
	0xd3, 0x67, 0x6a, 0xfc, 0x83, 0x03, 0x1e, 0x4d, 0x89, 0xe0, 0x2e, 0x59, 0x78, 0xe3, 0xed, 0x58,
	0xb8, 0xf8, 0xff, 0x2d, 0x8c, 0x5e, 0x41, 0x61, 0xc4, 0x5d, 0x3e, 0x1e, 0x95, 0x40, 0xa8, 0x6c,
	0xbf, 0x41, 0xa5, 0x2d, 0x00, 0x24, 0x05, 0x96, 0x4f, 0xa0, 0x38, 0x1f, 0x0a, 0x29, 0x90, 0xbb,
	0xa1, 0xd3, 0xd4, 0x0c, 0xf1, 0x71, 0xd9, 0xa8, 0xc5, 0xd4, 0xa8, 0x9f, 0xcb, 0xa7, 0xd2, 0xfe,
	0xcf, 0x32, 0x6c, 0x2f, 0x75, 0x74, 0x19, 0xf6, 0x5c, 0x4e, 0x09, 0x75, 0xe3, 0xaf, 0x42, 0x05,
	0x5e, 0xb4, 0xb4, 0xab, 0x06, 0xb6, 0x6c, 0xa7, 0x81, 0xed, 0x5a, 0xd3, 0x70, 0x2e, 0x5b, 0x86,
	0x66, 0x63, 0x87, 0x60, 0xad, 0xdd, 0xb4, 0x1c, 0xd3, 0xea, 0x68, 0x75, 0xd3, 0x50, 0x9e, 0xa0,
	0x2a, 0x7c, 0xfc, 0x28, 0x52, 0xd3, 0xf5, 0xe6, 0xa5, 0x65, 0x3b, 0x7a, 0xbd, 0xd9, 0xc6, 0x86,
	0x22, 0xa1, 0x4f, 0xe1, 0x93, 0x47, 0x09, 0x16, 0xfe, 0xc6, 0xc1, 0xdf, 0xb6, 0x4c, 0x72, 0xe5,
	0xc4, 0x69, 0x45, 0x46, 0x47, 0x50, 0xcd, 0x64, 0xcc, 0xca, 0x58, 0x97, 0x8d, 0x33, 0x4c, 0x94,
	0x1c, 0x3a, 0x81, 0xa3, 0x95, 0x49, 0x9a, 0x65, 0xa4, 0x25, 0x95, 0x3c, 0xda, 0x87, 0xbd, 0xc7,
	0x89, 0x4d, 0x47, 0xaf, 0x69, 0xd6, 0x05, 0x56, 0xd6, 0xf6, 0xff, 0x96, 0xe1, 0xc3, 0xcc, 0x6f,
	0x06, 0x7a, 0x05, 0x07, 0xf7, 0x14, 0x3b, 0x98, 0x98, 0xe7, 0xa6, 0xae, 0xd9, 0x66, 0xbc, 0x4b,
	0x1b, 0x37, 0x1c, 0xfb, 0xaa, 0x85, 0xef, 0x6c, 0xf5, 0x00, 0x5e, 0xae, 0x46, 0xd1, 0x3b, 0x1d,
	0x45, 0x42, 0xa7, 0x70, 0xbc, 0x1a, 0xdc, 0xc0, 0x1d, 0x53, 0x8f, 0xff, 0x6c, 0xcd, 0xac, 0xb7,
	0x15, 0x19, 0x7d, 0x01, 0x27, 0x2b, 0xf6, 0x66, 0x60, 0xcb, 0x36, 0xcf, 0xaf, 0x1c, 0x82, 0xdb,
	0xad, 0xa6, 0xd5, 0xc6, 0x4a, 0x0e, 0x7d, 0x09, 0xa7, 0x2b, 0x76, 0x59, 0xd3, 0xea, 0x75, 0x6c,
	0x5d, 0xe0, 0x05, 0x3b, 0xff, 0x06, 0xe7, 0xfc, 0x0b, 0xdb, 0xd2, 0x1a, 0xd8, 0x50, 0xd6, 0xce,
	0xd8, 0xaf, 0x7f, 0x3c, 0x7f, 0xf2, 0xd3, 0x5f, 0xcf, 0xa5, 0xef, 0x8e, 0xef, 0xdc, 0xdb, 0x77,
	0x6e, 0xdd, 0xd9, 0x85, 0x7d, 0xeb, 0x06, 0x83, 0xea, 0x83, 0xdb, 0xf8, 0x17, 0x79, 0x4b, 0x17,
	0xb9, 0x9a, 0x37, 0xa1, 0xaf, 0x75, 0x91, 0xfb, 0x53, 0x2e, 0x3f, 0xc8, 0xbd, 0x6e, 0x50, 0xee,
	0xf6, 0x5c, 0xee, 0x5e, 0x17, 0x84, 0xe0, 0xd1, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa9, 0xca,
	0x84, 0x4b, 0x62, 0x08, 0x00, 0x00,
}
