// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: chargehive/chtype/response_codes.proto

package chtype

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ResponseCategory int32

const (
	RESPONSE_CATEGORY_INVALID       ResponseCategory = 0
	RESPONSE_CATEGORY_CHARGE        ResponseCategory = 1
	RESPONSE_CATEGORY_METHOD        ResponseCategory = 2
	RESPONSE_CATEGORY_PERSON        ResponseCategory = 3
	RESPONSE_CATEGORY_CONFIGURATION ResponseCategory = 4
	RESPONSE_CATEGORY_CONNECTIVITY  ResponseCategory = 5
	RESPONSE_CATEGORY_FRAUD         ResponseCategory = 6
	RESPONSE_CATEGORY_VERIFICATION  ResponseCategory = 7
	RESPONSE_CATEGORY_PROCESSING    ResponseCategory = 8
	RESPONSE_CATEGORY_UNKNOWN       ResponseCategory = 9
	RESPONSE_CATEGORY_REQUEST       ResponseCategory = 10
)

var ResponseCategory_name = map[int32]string{
	0:  "RESPONSE_CATEGORY_INVALID",
	1:  "RESPONSE_CATEGORY_CHARGE",
	2:  "RESPONSE_CATEGORY_METHOD",
	3:  "RESPONSE_CATEGORY_PERSON",
	4:  "RESPONSE_CATEGORY_CONFIGURATION",
	5:  "RESPONSE_CATEGORY_CONNECTIVITY",
	6:  "RESPONSE_CATEGORY_FRAUD",
	7:  "RESPONSE_CATEGORY_VERIFICATION",
	8:  "RESPONSE_CATEGORY_PROCESSING",
	9:  "RESPONSE_CATEGORY_UNKNOWN",
	10: "RESPONSE_CATEGORY_REQUEST",
}

var ResponseCategory_value = map[string]int32{
	"RESPONSE_CATEGORY_INVALID":       0,
	"RESPONSE_CATEGORY_CHARGE":        1,
	"RESPONSE_CATEGORY_METHOD":        2,
	"RESPONSE_CATEGORY_PERSON":        3,
	"RESPONSE_CATEGORY_CONFIGURATION": 4,
	"RESPONSE_CATEGORY_CONNECTIVITY":  5,
	"RESPONSE_CATEGORY_FRAUD":         6,
	"RESPONSE_CATEGORY_VERIFICATION":  7,
	"RESPONSE_CATEGORY_PROCESSING":    8,
	"RESPONSE_CATEGORY_UNKNOWN":       9,
	"RESPONSE_CATEGORY_REQUEST":       10,
}

func (x ResponseCategory) String() string {
	return proto.EnumName(ResponseCategory_name, int32(x))
}

func (ResponseCategory) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4443886604600d4e, []int{0}
}

type ResponseError int32

const (
	RESPONSE_ERROR_INVALID         ResponseError = 0
	RESPONSE_ERROR_NONE            ResponseError = 1
	RESPONSE_ERROR_AVAILABLE_FUNDS ResponseError = 2
	RESPONSE_ERROR_PAYLOAD         ResponseError = 3
	RESPONSE_ERROR_LIMIT           ResponseError = 4
	RESPONSE_ERROR_EXPIRED         ResponseError = 5
	RESPONSE_ERROR_UNAVAILABLE     ResponseError = 6
	RESPONSE_ERROR_UNSUPPORTED     ResponseError = 7
	RESPONSE_ERROR_LOST            ResponseError = 8
	RESPONSE_ERROR_STOLEN          ResponseError = 9
	RESPONSE_ERROR_FRAUD           ResponseError = 10
	RESPONSE_ERROR_PICKUP          ResponseError = 11
	RESPONSE_ERROR_VELOCITY        ResponseError = 12
	RESPONSE_ERROR_ADDRESS         ResponseError = 13
	RESPONSE_ERROR_DUPLICATE       ResponseError = 14
	RESPONSE_ERROR_TIMEOUT         ResponseError = 15
	RESPONSE_ERROR_NOT_FOUND       ResponseError = 16
	RESPONSE_ERROR_DISPUTED        ResponseError = 17
	RESPONSE_ERROR_PERMISSION      ResponseError = 18
	RESPONSE_ERROR_DECLINE         ResponseError = 19
	RESPONSE_ERROR_USER_INPUT      ResponseError = 20
	RESPONSE_ERROR_USER_DEVICE     ResponseError = 21
	RESPONSE_ERROR_ALREADY_DONE    ResponseError = 22
	RESPONSE_ERROR_RETRY           ResponseError = 23
	RESPONSE_ERROR_QUEUED          ResponseError = 24
	RESPONSE_ERROR_SYSTEM          ResponseError = 25
	RESPONSE_ERROR_UNKNOWN         ResponseError = 26
	RESPONSE_ERROR_NOT_READY       ResponseError = 27
	RESPONSE_ERROR_DISABLED        ResponseError = 28
	RESPONSE_ERROR_CVV             ResponseError = 29
)

var ResponseError_name = map[int32]string{
	0:  "RESPONSE_ERROR_INVALID",
	1:  "RESPONSE_ERROR_NONE",
	2:  "RESPONSE_ERROR_AVAILABLE_FUNDS",
	3:  "RESPONSE_ERROR_PAYLOAD",
	4:  "RESPONSE_ERROR_LIMIT",
	5:  "RESPONSE_ERROR_EXPIRED",
	6:  "RESPONSE_ERROR_UNAVAILABLE",
	7:  "RESPONSE_ERROR_UNSUPPORTED",
	8:  "RESPONSE_ERROR_LOST",
	9:  "RESPONSE_ERROR_STOLEN",
	10: "RESPONSE_ERROR_FRAUD",
	11: "RESPONSE_ERROR_PICKUP",
	12: "RESPONSE_ERROR_VELOCITY",
	13: "RESPONSE_ERROR_ADDRESS",
	14: "RESPONSE_ERROR_DUPLICATE",
	15: "RESPONSE_ERROR_TIMEOUT",
	16: "RESPONSE_ERROR_NOT_FOUND",
	17: "RESPONSE_ERROR_DISPUTED",
	18: "RESPONSE_ERROR_PERMISSION",
	19: "RESPONSE_ERROR_DECLINE",
	20: "RESPONSE_ERROR_USER_INPUT",
	21: "RESPONSE_ERROR_USER_DEVICE",
	22: "RESPONSE_ERROR_ALREADY_DONE",
	23: "RESPONSE_ERROR_RETRY",
	24: "RESPONSE_ERROR_QUEUED",
	25: "RESPONSE_ERROR_SYSTEM",
	26: "RESPONSE_ERROR_UNKNOWN",
	27: "RESPONSE_ERROR_NOT_READY",
	28: "RESPONSE_ERROR_DISABLED",
	29: "RESPONSE_ERROR_CVV",
}

var ResponseError_value = map[string]int32{
	"RESPONSE_ERROR_INVALID":         0,
	"RESPONSE_ERROR_NONE":            1,
	"RESPONSE_ERROR_AVAILABLE_FUNDS": 2,
	"RESPONSE_ERROR_PAYLOAD":         3,
	"RESPONSE_ERROR_LIMIT":           4,
	"RESPONSE_ERROR_EXPIRED":         5,
	"RESPONSE_ERROR_UNAVAILABLE":     6,
	"RESPONSE_ERROR_UNSUPPORTED":     7,
	"RESPONSE_ERROR_LOST":            8,
	"RESPONSE_ERROR_STOLEN":          9,
	"RESPONSE_ERROR_FRAUD":           10,
	"RESPONSE_ERROR_PICKUP":          11,
	"RESPONSE_ERROR_VELOCITY":        12,
	"RESPONSE_ERROR_ADDRESS":         13,
	"RESPONSE_ERROR_DUPLICATE":       14,
	"RESPONSE_ERROR_TIMEOUT":         15,
	"RESPONSE_ERROR_NOT_FOUND":       16,
	"RESPONSE_ERROR_DISPUTED":        17,
	"RESPONSE_ERROR_PERMISSION":      18,
	"RESPONSE_ERROR_DECLINE":         19,
	"RESPONSE_ERROR_USER_INPUT":      20,
	"RESPONSE_ERROR_USER_DEVICE":     21,
	"RESPONSE_ERROR_ALREADY_DONE":    22,
	"RESPONSE_ERROR_RETRY":           23,
	"RESPONSE_ERROR_QUEUED":          24,
	"RESPONSE_ERROR_SYSTEM":          25,
	"RESPONSE_ERROR_UNKNOWN":         26,
	"RESPONSE_ERROR_NOT_READY":       27,
	"RESPONSE_ERROR_DISABLED":        28,
	"RESPONSE_ERROR_CVV":             29,
}

func (x ResponseError) String() string {
	return proto.EnumName(ResponseError_name, int32(x))
}

func (ResponseError) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4443886604600d4e, []int{1}
}

type ResponseCode int32

const (
	//Invalid response code
	RESPONSE_CODE_INVALID ResponseCode = 0
	//Generic Informational Response
	RESPONSE_CODE_INFO ResponseCode = 1000
	//Success Response
	RESPONSE_CODE_OK ResponseCode = 2000
	//Partial Success Response
	RESPONSE_CODE_OK_PARTIAL ResponseCode = 2100
	//3D Secure, Pending, Come back later
	RESPONSE_CODE_REDIRECT ResponseCode = 3000
	//Request is still processing, check back later
	RESPONSE_CODE_REDIRECT_STILL_PROCESSING ResponseCode = 3010
	//Issue with the client request
	RESPONSE_CODE_CLIENT ResponseCode = 4000
	//Invalid request payload
	RESPONSE_CODE_CLIENT_PAYLOAD ResponseCode = 4100
	//Invalid amount in request payload
	RESPONSE_CODE_CLIENT_PAYLOAD_AMOUNT ResponseCode = 4110
	//Invalid card data in request payload
	RESPONSE_CODE_CLIENT_PAYLOAD_CARD ResponseCode = 4120
	//Invalid card number in request payload
	RESPONSE_CODE_CLIENT_PAYLOAD_CARD_NUMBER ResponseCode = 4130
	//Invalid card date in request payload
	RESPONSE_CODE_CLIENT_PAYLOAD_CARD_DATE ResponseCode = 4140
	//Invalid card CVV in request payload
	RESPONSE_CODE_CLIENT_PAYLOAD_CARD_CVV ResponseCode = 4150
	//Invalid card type in request payload
	RESPONSE_CODE_CLIENT_PAYLOAD_CARD_TYPE ResponseCode = 4160
	//Invalid address data in request payload
	RESPONSE_CODE_CLIENT_PAYLOAD_ADDRESS ResponseCode = 4170
	//Invalid zip data in request payload
	RESPONSE_CODE_CLIENT_PAYLOAD_ZIP ResponseCode = 4180
	//Invalid currency data in request payload
	RESPONSE_CODE_CLIENT_PAYLOAD_CURRENCY ResponseCode = 4190
	//Error with payment method source
	RESPONSE_CODE_CLIENT_PAYMENT_METHOD ResponseCode = 4300
	//Payment method has insufficient funds
	RESPONSE_CODE_CLIENT_PAYMENT_METHOD_FUNDS ResponseCode = 4310
	//Payment method has reached an amount or frequency limit
	RESPONSE_CODE_CLIENT_PAYMENT_METHOD_LIMIT ResponseCode = 4320
	//Payment method does not allow this request
	RESPONSE_CODE_CLIENT_PAYMENT_METHOD_NOT_PERMITTED ResponseCode = 4330
	//Transaction declined due to security issues
	RESPONSE_CODE_CLIENT_SECURITY ResponseCode = 4500
	//Transaction likely fraudulent
	RESPONSE_CODE_CLIENT_SECURITY_FRAUD ResponseCode = 4510
	//Payment card may be lost
	RESPONSE_CODE_CLIENT_SECURITY_LOST ResponseCode = 4520
	//Payment card may be stolen
	RESPONSE_CODE_CLIENT_SECURITY_STOLEN ResponseCode = 4530
	//Payment card should be retrieved from the customer
	RESPONSE_CODE_CLIENT_SECURITY_PICKUP ResponseCode = 4540
	//Customer should contact their payment method provider
	RESPONSE_CODE_CLIENT_SECURITY_CONTACT_ISSUER ResponseCode = 4550
	//Transaction suspected of fraud
	RESPONSE_CODE_CLIENT_SECURITY_SUSPECTED_FRAUD ResponseCode = 4560
	//Velocity fraud check failed
	RESPONSE_CODE_CLIENT_SECURITY_VELOCITY ResponseCode = 4570
	//AVS fraud check failed
	RESPONSE_CODE_CLIENT_SECURITY_AVS ResponseCode = 4580
	//CVV security check failed
	RESPONSE_CODE_CLIENT_SECURITY_CVV ResponseCode = 4590
	//Issues with the processing the transaction or associated transactions
	RESPONSE_CODE_CLIENT_TRANS ResponseCode = 4700
	//Generic decline from payment method
	RESPONSE_CODE_CLIENT_TRANS_DECLINED ResponseCode = 4710
	//Generic failure of payment method
	RESPONSE_CODE_CLIENT_TRANS_FAILED ResponseCode = 4720
	//Cannot complete transaction as not authorised or unable to complete
	RESPONSE_CODE_CLIENT_TRANS_PERMISSION ResponseCode = 4730
	//Transaction or associated transaction cannot be found
	RESPONSE_CODE_CLIENT_TRANS_NOT_FOUND ResponseCode = 4740
	//This transaction has already been sent
	RESPONSE_CODE_CLIENT_TRANS_DUPLICATE ResponseCode = 4750
	//Payment method provider suggests the transaction be reattempted
	RESPONSE_CODE_CLIENT_TRANS_RETRY ResponseCode = 4760
	//Transaction or associated transaction has expired and cannot complete
	RESPONSE_CODE_CLIENT_TRANS_EXPIRED ResponseCode = 4770
	//Transaction or associated transaction is disputed/part of a chargeback
	RESPONSE_CODE_CLIENT_TRANS_DISPUTE ResponseCode = 4780
	//Payment method provider did not response in time
	RESPONSE_CODE_CLIENT_TRANS_TIMEOUT ResponseCode = 4790
	//Operation has already been completed
	RESPONSE_CODE_CLIENT_TRANS_ALREADY_DONE ResponseCode = 4800
	//Cannot complete operation now, but may be ready later
	RESPONSE_CODE_CLIENT_TRANS_NOT_READY ResponseCode = 4810
	//Connector does not support this payment method
	RESPONSE_CODE_CLIENT_TRANS_PAYMENT_METHOD ResponseCode = 4820
	//Amount or volume exceeds some limit
	RESPONSE_CODE_CLIENT_TRANS_EXCEEDS_LIMIT ResponseCode = 4830
	//3D Secure issues
	RESPONSE_CODE_CLIENT_3DSEC ResponseCode = 4900
	//3D Secure Authentication required
	RESPONSE_CODE_CLIENT_3DSEC_AUTHENTICATION ResponseCode = 4910
	//Issues with the connector
	RESPONSE_CODE_CONN ResponseCode = 5000
	//Internal ChargeHive error
	RESPONSE_CODE_CONN_CHARGEHIVE ResponseCode = 5010
	//Connector misconfiguration or authentication error
	RESPONSE_CODE_CONN_CONFIG_AUTH ResponseCode = 5500
	//Connector does not exist
	RESPONSE_CODE_CONN_INVALID ResponseCode = 5510
	//Cannot communicate with connector service
	RESPONSE_CODE_CONN_UNAVAILABLE ResponseCode = 5520
	//Internal error from connector
	RESPONSE_CODE_CONN_ERROR ResponseCode = 5530
	//Connector rate or amount limit has been reached
	RESPONSE_CODE_CONN_LIMIT_EXCEEDED ResponseCode = 5540
	//Connector, or connector account does not support this type of request
	RESPONSE_CODE_CONN_UNSUPPORTED_METHOD ResponseCode = 5550
	//Connection with the connector has timed out
	RESPONSE_CODE_CONN_TIMEOUT ResponseCode = 5570
	//Unknown error, if received, this should be remapped to a propper code
	RESPONSE_CODE_UNKNOWN ResponseCode = 5990
)

var ResponseCode_name = map[int32]string{
	0:    "RESPONSE_CODE_INVALID",
	1000: "RESPONSE_CODE_INFO",
	2000: "RESPONSE_CODE_OK",
	2100: "RESPONSE_CODE_OK_PARTIAL",
	3000: "RESPONSE_CODE_REDIRECT",
	3010: "RESPONSE_CODE_REDIRECT_STILL_PROCESSING",
	4000: "RESPONSE_CODE_CLIENT",
	4100: "RESPONSE_CODE_CLIENT_PAYLOAD",
	4110: "RESPONSE_CODE_CLIENT_PAYLOAD_AMOUNT",
	4120: "RESPONSE_CODE_CLIENT_PAYLOAD_CARD",
	4130: "RESPONSE_CODE_CLIENT_PAYLOAD_CARD_NUMBER",
	4140: "RESPONSE_CODE_CLIENT_PAYLOAD_CARD_DATE",
	4150: "RESPONSE_CODE_CLIENT_PAYLOAD_CARD_CVV",
	4160: "RESPONSE_CODE_CLIENT_PAYLOAD_CARD_TYPE",
	4170: "RESPONSE_CODE_CLIENT_PAYLOAD_ADDRESS",
	4180: "RESPONSE_CODE_CLIENT_PAYLOAD_ZIP",
	4190: "RESPONSE_CODE_CLIENT_PAYLOAD_CURRENCY",
	4300: "RESPONSE_CODE_CLIENT_PAYMENT_METHOD",
	4310: "RESPONSE_CODE_CLIENT_PAYMENT_METHOD_FUNDS",
	4320: "RESPONSE_CODE_CLIENT_PAYMENT_METHOD_LIMIT",
	4330: "RESPONSE_CODE_CLIENT_PAYMENT_METHOD_NOT_PERMITTED",
	4500: "RESPONSE_CODE_CLIENT_SECURITY",
	4510: "RESPONSE_CODE_CLIENT_SECURITY_FRAUD",
	4520: "RESPONSE_CODE_CLIENT_SECURITY_LOST",
	4530: "RESPONSE_CODE_CLIENT_SECURITY_STOLEN",
	4540: "RESPONSE_CODE_CLIENT_SECURITY_PICKUP",
	4550: "RESPONSE_CODE_CLIENT_SECURITY_CONTACT_ISSUER",
	4560: "RESPONSE_CODE_CLIENT_SECURITY_SUSPECTED_FRAUD",
	4570: "RESPONSE_CODE_CLIENT_SECURITY_VELOCITY",
	4580: "RESPONSE_CODE_CLIENT_SECURITY_AVS",
	4590: "RESPONSE_CODE_CLIENT_SECURITY_CVV",
	4700: "RESPONSE_CODE_CLIENT_TRANS",
	4710: "RESPONSE_CODE_CLIENT_TRANS_DECLINED",
	4720: "RESPONSE_CODE_CLIENT_TRANS_FAILED",
	4730: "RESPONSE_CODE_CLIENT_TRANS_PERMISSION",
	4740: "RESPONSE_CODE_CLIENT_TRANS_NOT_FOUND",
	4750: "RESPONSE_CODE_CLIENT_TRANS_DUPLICATE",
	4760: "RESPONSE_CODE_CLIENT_TRANS_RETRY",
	4770: "RESPONSE_CODE_CLIENT_TRANS_EXPIRED",
	4780: "RESPONSE_CODE_CLIENT_TRANS_DISPUTE",
	4790: "RESPONSE_CODE_CLIENT_TRANS_TIMEOUT",
	4800: "RESPONSE_CODE_CLIENT_TRANS_ALREADY_DONE",
	4810: "RESPONSE_CODE_CLIENT_TRANS_NOT_READY",
	4820: "RESPONSE_CODE_CLIENT_TRANS_PAYMENT_METHOD",
	4830: "RESPONSE_CODE_CLIENT_TRANS_EXCEEDS_LIMIT",
	4900: "RESPONSE_CODE_CLIENT_3DSEC",
	4910: "RESPONSE_CODE_CLIENT_3DSEC_AUTHENTICATION",
	5000: "RESPONSE_CODE_CONN",
	5010: "RESPONSE_CODE_CONN_CHARGEHIVE",
	5500: "RESPONSE_CODE_CONN_CONFIG_AUTH",
	5510: "RESPONSE_CODE_CONN_INVALID",
	5520: "RESPONSE_CODE_CONN_UNAVAILABLE",
	5530: "RESPONSE_CODE_CONN_ERROR",
	5540: "RESPONSE_CODE_CONN_LIMIT_EXCEEDED",
	5550: "RESPONSE_CODE_CONN_UNSUPPORTED_METHOD",
	5570: "RESPONSE_CODE_CONN_TIMEOUT",
	5990: "RESPONSE_CODE_UNKNOWN",
}

var ResponseCode_value = map[string]int32{
	"RESPONSE_CODE_INVALID":                             0,
	"RESPONSE_CODE_INFO":                                1000,
	"RESPONSE_CODE_OK":                                  2000,
	"RESPONSE_CODE_OK_PARTIAL":                          2100,
	"RESPONSE_CODE_REDIRECT":                            3000,
	"RESPONSE_CODE_REDIRECT_STILL_PROCESSING":           3010,
	"RESPONSE_CODE_CLIENT":                              4000,
	"RESPONSE_CODE_CLIENT_PAYLOAD":                      4100,
	"RESPONSE_CODE_CLIENT_PAYLOAD_AMOUNT":               4110,
	"RESPONSE_CODE_CLIENT_PAYLOAD_CARD":                 4120,
	"RESPONSE_CODE_CLIENT_PAYLOAD_CARD_NUMBER":          4130,
	"RESPONSE_CODE_CLIENT_PAYLOAD_CARD_DATE":            4140,
	"RESPONSE_CODE_CLIENT_PAYLOAD_CARD_CVV":             4150,
	"RESPONSE_CODE_CLIENT_PAYLOAD_CARD_TYPE":            4160,
	"RESPONSE_CODE_CLIENT_PAYLOAD_ADDRESS":              4170,
	"RESPONSE_CODE_CLIENT_PAYLOAD_ZIP":                  4180,
	"RESPONSE_CODE_CLIENT_PAYLOAD_CURRENCY":             4190,
	"RESPONSE_CODE_CLIENT_PAYMENT_METHOD":               4300,
	"RESPONSE_CODE_CLIENT_PAYMENT_METHOD_FUNDS":         4310,
	"RESPONSE_CODE_CLIENT_PAYMENT_METHOD_LIMIT":         4320,
	"RESPONSE_CODE_CLIENT_PAYMENT_METHOD_NOT_PERMITTED": 4330,
	"RESPONSE_CODE_CLIENT_SECURITY":                     4500,
	"RESPONSE_CODE_CLIENT_SECURITY_FRAUD":               4510,
	"RESPONSE_CODE_CLIENT_SECURITY_LOST":                4520,
	"RESPONSE_CODE_CLIENT_SECURITY_STOLEN":              4530,
	"RESPONSE_CODE_CLIENT_SECURITY_PICKUP":              4540,
	"RESPONSE_CODE_CLIENT_SECURITY_CONTACT_ISSUER":      4550,
	"RESPONSE_CODE_CLIENT_SECURITY_SUSPECTED_FRAUD":     4560,
	"RESPONSE_CODE_CLIENT_SECURITY_VELOCITY":            4570,
	"RESPONSE_CODE_CLIENT_SECURITY_AVS":                 4580,
	"RESPONSE_CODE_CLIENT_SECURITY_CVV":                 4590,
	"RESPONSE_CODE_CLIENT_TRANS":                        4700,
	"RESPONSE_CODE_CLIENT_TRANS_DECLINED":               4710,
	"RESPONSE_CODE_CLIENT_TRANS_FAILED":                 4720,
	"RESPONSE_CODE_CLIENT_TRANS_PERMISSION":             4730,
	"RESPONSE_CODE_CLIENT_TRANS_NOT_FOUND":              4740,
	"RESPONSE_CODE_CLIENT_TRANS_DUPLICATE":              4750,
	"RESPONSE_CODE_CLIENT_TRANS_RETRY":                  4760,
	"RESPONSE_CODE_CLIENT_TRANS_EXPIRED":                4770,
	"RESPONSE_CODE_CLIENT_TRANS_DISPUTE":                4780,
	"RESPONSE_CODE_CLIENT_TRANS_TIMEOUT":                4790,
	"RESPONSE_CODE_CLIENT_TRANS_ALREADY_DONE":           4800,
	"RESPONSE_CODE_CLIENT_TRANS_NOT_READY":              4810,
	"RESPONSE_CODE_CLIENT_TRANS_PAYMENT_METHOD":         4820,
	"RESPONSE_CODE_CLIENT_TRANS_EXCEEDS_LIMIT":          4830,
	"RESPONSE_CODE_CLIENT_3DSEC":                        4900,
	"RESPONSE_CODE_CLIENT_3DSEC_AUTHENTICATION":         4910,
	"RESPONSE_CODE_CONN":                                5000,
	"RESPONSE_CODE_CONN_CHARGEHIVE":                     5010,
	"RESPONSE_CODE_CONN_CONFIG_AUTH":                    5500,
	"RESPONSE_CODE_CONN_INVALID":                        5510,
	"RESPONSE_CODE_CONN_UNAVAILABLE":                    5520,
	"RESPONSE_CODE_CONN_ERROR":                          5530,
	"RESPONSE_CODE_CONN_LIMIT_EXCEEDED":                 5540,
	"RESPONSE_CODE_CONN_UNSUPPORTED_METHOD":             5550,
	"RESPONSE_CODE_CONN_TIMEOUT":                        5570,
	"RESPONSE_CODE_UNKNOWN":                             5990,
}

func (x ResponseCode) String() string {
	return proto.EnumName(ResponseCode_name, int32(x))
}

func (ResponseCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4443886604600d4e, []int{2}
}

type ResponseDetail struct {
	ResponseCode         string            `protobuf:"bytes,1,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	ConsumerMessage      string            `protobuf:"bytes,2,opt,name=consumer_message,json=consumerMessage,proto3" json:"consumer_message,omitempty"`
	MerchantMessage      string            `protobuf:"bytes,3,opt,name=merchant_message,json=merchantMessage,proto3" json:"merchant_message,omitempty"`
	FailureType          FailureType       `protobuf:"varint,4,opt,name=failure_type,json=failureType,proto3,enum=chargehive.chtype.FailureType" json:"failure_type,omitempty"`
	Category             ResponseCategory  `protobuf:"varint,5,opt,name=category,proto3,enum=chargehive.chtype.ResponseCategory" json:"category,omitempty"`
	ErrorType            ResponseError     `protobuf:"varint,6,opt,name=error_type,json=errorType,proto3,enum=chargehive.chtype.ResponseError" json:"error_type,omitempty"`
	ErrorProperties      map[string]string `protobuf:"bytes,7,rep,name=error_properties,json=errorProperties,proto3" json:"error_properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	OriginatingCode      string            `protobuf:"bytes,8,opt,name=originating_code,json=originatingCode,proto3" json:"originating_code,omitempty"`
	SpecificErrors       []*ResponseDetail `protobuf:"bytes,9,rep,name=specific_errors,json=specificErrors,proto3" json:"specific_errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ResponseDetail) Reset()         { *m = ResponseDetail{} }
func (m *ResponseDetail) String() string { return proto.CompactTextString(m) }
func (*ResponseDetail) ProtoMessage()    {}
func (*ResponseDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_4443886604600d4e, []int{0}
}
func (m *ResponseDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseDetail.Unmarshal(m, b)
}
func (m *ResponseDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseDetail.Marshal(b, m, deterministic)
}
func (m *ResponseDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseDetail.Merge(m, src)
}
func (m *ResponseDetail) XXX_Size() int {
	return xxx_messageInfo_ResponseDetail.Size(m)
}
func (m *ResponseDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseDetail proto.InternalMessageInfo

func (m *ResponseDetail) GetResponseCode() string {
	if m != nil {
		return m.ResponseCode
	}
	return ""
}

func (m *ResponseDetail) GetConsumerMessage() string {
	if m != nil {
		return m.ConsumerMessage
	}
	return ""
}

func (m *ResponseDetail) GetMerchantMessage() string {
	if m != nil {
		return m.MerchantMessage
	}
	return ""
}

func (m *ResponseDetail) GetFailureType() FailureType {
	if m != nil {
		return m.FailureType
	}
	return FAILURE_TYPE_INVALID
}

func (m *ResponseDetail) GetCategory() ResponseCategory {
	if m != nil {
		return m.Category
	}
	return RESPONSE_CATEGORY_INVALID
}

func (m *ResponseDetail) GetErrorType() ResponseError {
	if m != nil {
		return m.ErrorType
	}
	return RESPONSE_ERROR_INVALID
}

func (m *ResponseDetail) GetErrorProperties() map[string]string {
	if m != nil {
		return m.ErrorProperties
	}
	return nil
}

func (m *ResponseDetail) GetOriginatingCode() string {
	if m != nil {
		return m.OriginatingCode
	}
	return ""
}

func (m *ResponseDetail) GetSpecificErrors() []*ResponseDetail {
	if m != nil {
		return m.SpecificErrors
	}
	return nil
}

func init() {
	proto.RegisterEnum("chargehive.chtype.ResponseCategory", ResponseCategory_name, ResponseCategory_value)
	golang_proto.RegisterEnum("chargehive.chtype.ResponseCategory", ResponseCategory_name, ResponseCategory_value)
	proto.RegisterEnum("chargehive.chtype.ResponseError", ResponseError_name, ResponseError_value)
	golang_proto.RegisterEnum("chargehive.chtype.ResponseError", ResponseError_name, ResponseError_value)
	proto.RegisterEnum("chargehive.chtype.ResponseCode", ResponseCode_name, ResponseCode_value)
	golang_proto.RegisterEnum("chargehive.chtype.ResponseCode", ResponseCode_name, ResponseCode_value)
	proto.RegisterType((*ResponseDetail)(nil), "chargehive.chtype.ResponseDetail")
	golang_proto.RegisterType((*ResponseDetail)(nil), "chargehive.chtype.ResponseDetail")
	proto.RegisterMapType((map[string]string)(nil), "chargehive.chtype.ResponseDetail.ErrorPropertiesEntry")
	golang_proto.RegisterMapType((map[string]string)(nil), "chargehive.chtype.ResponseDetail.ErrorPropertiesEntry")
}

func init() {
	proto.RegisterFile("chargehive/chtype/response_codes.proto", fileDescriptor_4443886604600d4e)
}
func init() {
	golang_proto.RegisterFile("chargehive/chtype/response_codes.proto", fileDescriptor_4443886604600d4e)
}

var fileDescriptor_4443886604600d4e = []byte{
	// 1552 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x98, 0x4f, 0x68, 0x1b, 0x47,
	0x17, 0xc0, 0xe3, 0xff, 0xf6, 0xc4, 0xb1, 0x9f, 0x27, 0x8e, 0xad, 0x28, 0xfe, 0x23, 0x5b, 0x96,
	0xed, 0xd8, 0x89, 0x4c, 0x92, 0x8f, 0xf0, 0xf1, 0x5d, 0xc2, 0x7a, 0x77, 0x64, 0xef, 0x17, 0x69,
	0x77, 0x33, 0x3b, 0xab, 0xef, 0x53, 0x08, 0x08, 0x45, 0x59, 0xcb, 0xa2, 0xb6, 0x64, 0x24, 0x39,
	0xe0, 0x7b, 0x28, 0x3d, 0x85, 0x52, 0x7a, 0x08, 0x3d, 0x94, 0x12, 0x72, 0xe8, 0x21, 0xe4, 0x50,
	0x4a, 0xe8, 0xa1, 0x87, 0x90, 0x43, 0x0f, 0xa1, 0x87, 0x1c, 0x42, 0x0f, 0xa5, 0x84, 0xfe, 0x23,
	0x94, 0x16, 0x42, 0x7b, 0xe8, 0xa5, 0xf4, 0x50, 0xf6, 0x9f, 0xbc, 0x92, 0x66, 0x25, 0x9d, 0xa4,
	0x9d, 0xf7, 0x7b, 0x6f, 0xde, 0xbc, 0x79, 0xf3, 0xde, 0xec, 0xa2, 0xe5, 0xfc, 0x6e, 0xae, 0x52,
	0x30, 0x77, 0x8b, 0x77, 0xcd, 0x8d, 0xfc, 0x6e, 0xed, 0xe8, 0xc0, 0xdc, 0xa8, 0x98, 0xd5, 0x83,
	0x72, 0xa9, 0x6a, 0x66, 0xf3, 0xe5, 0x3b, 0x66, 0x35, 0x7e, 0x50, 0x29, 0xd7, 0xca, 0x78, 0xe2,
	0x98, 0x8b, 0x3b, 0x5c, 0xf8, 0x62, 0xa1, 0x58, 0xdb, 0x3d, 0xbc, 0x1d, 0xcf, 0x97, 0xf7, 0x37,
	0x0a, 0xe5, 0x42, 0x79, 0xc3, 0x26, 0x6f, 0x1f, 0xee, 0xd8, 0x4f, 0xf6, 0x83, 0xfd, 0xcf, 0xb1,
	0x10, 0x9e, 0x69, 0x9d, 0xc9, 0x2c, 0x1d, 0xee, 0x3b, 0xd2, 0xc5, 0xb7, 0xfd, 0x68, 0x8c, 0xba,
	0x13, 0x4b, 0x66, 0x2d, 0x57, 0xdc, 0xc3, 0x51, 0x74, 0xaa, 0xc1, 0x95, 0x50, 0x4f, 0xa4, 0x67,
	0x75, 0x84, 0x8e, 0x7a, 0x83, 0x62, 0xf9, 0x8e, 0x89, 0xcf, 0x23, 0xc8, 0x97, 0x4b, 0xd5, 0xc3,
	0x7d, 0xb3, 0x92, 0xdd, 0x37, 0xab, 0xd5, 0x5c, 0xc1, 0x0c, 0xf5, 0xda, 0xdc, 0xb8, 0x37, 0x9e,
	0x72, 0x86, 0x2d, 0x74, 0xdf, 0xac, 0xe4, 0x77, 0x73, 0xa5, 0x5a, 0x1d, 0xed, 0x73, 0x50, 0x6f,
	0xdc, 0x43, 0x05, 0x34, 0xba, 0x93, 0x2b, 0xee, 0x1d, 0x56, 0xcc, 0xac, 0xe5, 0x68, 0xa8, 0x3f,
	0xd2, 0xb3, 0x3a, 0x76, 0x79, 0x2e, 0xde, 0x12, 0x84, 0x78, 0xc2, 0xc1, 0xd8, 0xd1, 0x81, 0x49,
	0x4f, 0xee, 0x1c, 0x3f, 0xe0, 0x6b, 0x68, 0x38, 0x9f, 0xab, 0x99, 0x85, 0x72, 0xe5, 0x28, 0x34,
	0x60, 0xab, 0x47, 0x39, 0xea, 0xde, 0x92, 0x45, 0x17, 0xa5, 0x75, 0x25, 0x7c, 0x0d, 0x21, 0xb3,
	0x52, 0x29, 0x57, 0x1c, 0x0f, 0x06, 0x6d, 0x13, 0x91, 0x36, 0x26, 0x88, 0x05, 0xd3, 0x11, 0x5b,
	0xc7, 0xf6, 0x20, 0x87, 0xc0, 0x31, 0x70, 0x50, 0x29, 0x1f, 0x98, 0x95, 0x5a, 0xd1, 0xac, 0x86,
	0x86, 0x22, 0x7d, 0xab, 0x27, 0x2f, 0x5f, 0x6d, 0x63, 0xc6, 0x09, 0x7e, 0xdc, 0xb6, 0xa6, 0xd5,
	0x15, 0x49, 0xa9, 0x56, 0x39, 0xa2, 0xe3, 0x66, 0xe3, 0xa8, 0x15, 0xd2, 0x72, 0xa5, 0x58, 0x28,
	0x96, 0x72, 0xb5, 0x62, 0xa9, 0xe0, 0xec, 0xd2, 0xb0, 0x13, 0x52, 0xdf, 0xb8, 0xbd, 0x51, 0xff,
	0x45, 0xe3, 0xd5, 0x03, 0x33, 0x5f, 0xdc, 0x29, 0xe6, 0xb3, 0xb6, 0x99, 0x6a, 0x68, 0xc4, 0x76,
	0x66, 0xa1, 0xa3, 0x33, 0x74, 0xcc, 0xd3, 0xb4, 0xbd, 0xaa, 0x86, 0x37, 0xd1, 0x24, 0xcf, 0x3f,
	0x0c, 0xa8, 0xef, 0x1d, 0xf3, 0xc8, 0xcd, 0x13, 0xeb, 0x2f, 0x9e, 0x44, 0x03, 0x77, 0x73, 0x7b,
	0x87, 0x5e, 0x4e, 0x38, 0x0f, 0xff, 0xe9, 0xfd, 0x77, 0xcf, 0xda, 0x9f, 0xbd, 0x08, 0x9a, 0xa3,
	0x8f, 0x67, 0xd1, 0x59, 0x4a, 0x74, 0x4d, 0x55, 0x74, 0x92, 0x15, 0x05, 0x46, 0xb6, 0x54, 0x9a,
	0xc9, 0xca, 0x4a, 0x5a, 0x48, 0xca, 0x12, 0x9c, 0xc0, 0x33, 0x28, 0xd4, 0x2a, 0x16, 0xb7, 0x05,
	0xba, 0x45, 0xa0, 0x87, 0x2f, 0x4d, 0x11, 0xb6, 0xad, 0x4a, 0xd0, 0xcb, 0x97, 0x6a, 0x84, 0xea,
	0xaa, 0x02, 0x7d, 0x38, 0x8a, 0xe6, 0x39, 0x96, 0x55, 0x25, 0x21, 0x6f, 0x19, 0x54, 0x60, 0xb2,
	0xaa, 0x40, 0x3f, 0x5e, 0x44, 0x73, 0x5c, 0x48, 0x21, 0x22, 0x93, 0xd3, 0x32, 0xcb, 0xc0, 0x00,
	0x3e, 0x87, 0xa6, 0x5b, 0x99, 0x04, 0x15, 0x0c, 0x09, 0x06, 0xf9, 0x06, 0xd2, 0x84, 0xca, 0x09,
	0x59, 0x74, 0x26, 0x19, 0xc2, 0x11, 0x34, 0xc3, 0xf1, 0x93, 0xaa, 0x22, 0xd1, 0x75, 0x59, 0xd9,
	0x82, 0x61, 0x7e, 0x90, 0x0c, 0xe5, 0xba, 0xa2, 0xfe, 0x4f, 0x81, 0x11, 0xbe, 0x98, 0x92, 0x1b,
	0x06, 0xd1, 0x19, 0xa0, 0xb5, 0xdf, 0x06, 0xd1, 0xa9, 0x86, 0x94, 0xc5, 0x61, 0x34, 0x55, 0x57,
	0x20, 0x94, 0xaa, 0xd4, 0x17, 0xf1, 0x69, 0x74, 0xba, 0x49, 0xa6, 0xa8, 0x8a, 0x15, 0x6c, 0xff,
	0x52, 0x1c, 0x81, 0x90, 0x16, 0xe4, 0xa4, 0xb0, 0x99, 0x24, 0xd9, 0x84, 0xa1, 0x48, 0x3a, 0xf4,
	0x72, 0x0c, 0x6b, 0x42, 0x26, 0xa9, 0x0a, 0x12, 0xf4, 0xe1, 0x10, 0x9a, 0x6c, 0x92, 0x25, 0xe5,
	0x94, 0xcc, 0xa0, 0x9f, 0xa3, 0x45, 0xfe, 0xaf, 0xc9, 0x94, 0x48, 0x30, 0x80, 0xe7, 0x50, 0xb8,
	0x49, 0x66, 0x28, 0xf5, 0x79, 0x61, 0x90, 0x2b, 0xd7, 0x0d, 0x4d, 0x53, 0x29, 0x23, 0x12, 0x0c,
	0x71, 0x96, 0x93, 0x54, 0x75, 0x06, 0xc3, 0xf8, 0x2c, 0x3a, 0xd3, 0x24, 0xd0, 0x99, 0x9a, 0x24,
	0x56, 0x3c, 0x5b, 0x3d, 0x75, 0xb6, 0x13, 0x71, 0x94, 0x34, 0x59, 0xbc, 0x6e, 0x68, 0x70, 0xb2,
	0x21, 0x0d, 0x1c, 0x51, 0x9a, 0x24, 0x55, 0xd1, 0xca, 0x91, 0x51, 0xce, 0x0a, 0x05, 0x49, 0xa2,
	0x44, 0xd7, 0xe1, 0x54, 0x43, 0x9a, 0x3a, 0x32, 0xc9, 0xd0, 0x92, 0x56, 0x7a, 0x10, 0x18, 0xe3,
	0x68, 0x32, 0x39, 0x45, 0x54, 0x83, 0xc1, 0x38, 0x47, 0x53, 0x51, 0x59, 0x36, 0xa1, 0x1a, 0x8a,
	0x04, 0xc0, 0x71, 0x48, 0x92, 0x75, 0xcd, 0xb0, 0xc2, 0x32, 0xd1, 0x90, 0x32, 0xee, 0x42, 0x08,
	0x4d, 0xc9, 0xba, 0x6e, 0xa5, 0x24, 0xe6, 0xcc, 0x2a, 0x11, 0x31, 0x29, 0x2b, 0x04, 0x4e, 0x73,
	0x54, 0x0d, 0x9d, 0x58, 0x19, 0xa4, 0x19, 0x0c, 0x26, 0x79, 0x1b, 0x62, 0x89, 0x25, 0x92, 0x96,
	0x45, 0x02, 0x67, 0xf0, 0x3c, 0x3a, 0xd7, 0x1c, 0x8a, 0x24, 0x25, 0x82, 0x94, 0xc9, 0x4a, 0x56,
	0x9e, 0x4d, 0x71, 0xa2, 0x4f, 0x09, 0xa3, 0x19, 0x98, 0xe6, 0x44, 0xff, 0x86, 0x41, 0x0c, 0x22,
	0x41, 0x88, 0xb7, 0x9b, 0x19, 0x9d, 0x91, 0x14, 0x9c, 0xe5, 0xac, 0xc5, 0x3b, 0x39, 0xe1, 0x80,
	0x08, 0xda, 0xee, 0xc0, 0x39, 0x7e, 0x04, 0xad, 0xbc, 0x93, 0x60, 0x06, 0x4f, 0x21, 0xdc, 0x24,
	0x14, 0xd3, 0x69, 0x98, 0x5d, 0xfb, 0x63, 0x02, 0x8d, 0x52, 0x7f, 0xbf, 0xf4, 0xbb, 0x26, 0xaa,
	0x12, 0x69, 0x38, 0x6b, 0xb8, 0x59, 0x94, 0x50, 0xe1, 0x97, 0x21, 0x7c, 0x06, 0x41, 0xa3, 0x40,
	0xbd, 0x0e, 0x2f, 0xc7, 0xf1, 0xac, 0xbf, 0xa2, 0x39, 0xc3, 0x59, 0x4d, 0xa0, 0x4c, 0x16, 0x92,
	0xf0, 0xb9, 0xb5, 0xe3, 0x53, 0x8d, 0x62, 0x4a, 0x24, 0x99, 0x12, 0x91, 0xc1, 0x17, 0xd3, 0xf8,
	0x02, 0x5a, 0xe1, 0x0b, 0xb3, 0x3a, 0x93, 0x93, 0x49, 0x7f, 0xc1, 0x79, 0x6e, 0x85, 0x7a, 0xb2,
	0x91, 0x16, 0x93, 0x32, 0x51, 0x18, 0x7c, 0x32, 0x8f, 0x17, 0xfc, 0xe5, 0xea, 0x58, 0x54, 0x3f,
	0xe9, 0xf7, 0x22, 0x78, 0x15, 0x45, 0xdb, 0x21, 0x59, 0x21, 0xa5, 0x1a, 0x0a, 0x83, 0xfb, 0x11,
	0xbc, 0x8c, 0x16, 0xda, 0x92, 0xa2, 0x40, 0x25, 0x78, 0x10, 0xc1, 0x17, 0xd1, 0x6a, 0x47, 0x2e,
	0xab, 0x18, 0xa9, 0x4d, 0x42, 0xe1, 0x61, 0x04, 0xaf, 0xa3, 0xe5, 0xce, 0xb8, 0x64, 0x9d, 0xb0,
	0xc7, 0x11, 0xbc, 0x86, 0x62, 0x9d, 0x61, 0x6b, 0x73, 0x9f, 0x76, 0x69, 0x98, 0x65, 0x34, 0x02,
	0xcf, 0x22, 0xf8, 0x3c, 0x5a, 0x6a, 0x1f, 0x06, 0xb7, 0x06, 0xbc, 0x88, 0xe0, 0x18, 0x8a, 0xb4,
	0x45, 0x6f, 0xca, 0x1a, 0xbc, 0xea, 0xc2, 0x55, 0x83, 0x52, 0xa2, 0x88, 0x19, 0x78, 0xdd, 0x76,
	0x13, 0x52, 0xd6, 0xaf, 0xdb, 0x27, 0xbf, 0x5e, 0xc0, 0x71, 0x74, 0xbe, 0x0b, 0xd2, 0x2d, 0xf2,
	0xdf, 0x74, 0xcd, 0x3b, 0xe5, 0xfd, 0xfb, 0x05, 0x7c, 0x15, 0x5d, 0xea, 0x86, 0xb7, 0x8e, 0x9e,
	0x5d, 0x85, 0x98, 0x55, 0xa3, 0x7e, 0x5d, 0xc0, 0x8b, 0x68, 0x96, 0xab, 0xa7, 0x13, 0xd1, 0xa0,
	0x56, 0x61, 0xfd, 0x30, 0x1a, 0xb8, 0x4a, 0x8f, 0x71, 0x4b, 0xf7, 0xc7, 0x51, 0xbc, 0x82, 0x16,
	0xdb, 0x93, 0x76, 0x63, 0xf8, 0x34, 0x1a, 0xb8, 0x6d, 0x75, 0xd0, 0x6d, 0x14, 0x9f, 0x75, 0x81,
	0xba, 0xed, 0xe1, 0xcb, 0x28, 0xbe, 0x84, 0x2e, 0xb4, 0x47, 0x45, 0x55, 0x61, 0x82, 0xc8, 0xb2,
	0xb2, 0xae, 0x1b, 0x84, 0xc2, 0x57, 0x51, 0x7c, 0x19, 0x5d, 0xec, 0xe0, 0x88, 0xa1, 0x6b, 0x44,
	0x64, 0x44, 0x72, 0x57, 0xf9, 0x32, 0x1a, 0x98, 0xa0, 0x75, 0x9d, 0x7a, 0x57, 0xfa, 0x36, 0x1a,
	0x78, 0xfa, 0xea, 0xb0, 0x90, 0xd6, 0xe1, 0xe7, 0x2e, 0x38, 0xeb, 0x74, 0xbc, 0x8d, 0xe2, 0x79,
	0x5f, 0xed, 0xf7, 0x73, 0x8c, 0x0a, 0x8a, 0x0e, 0xdf, 0x2d, 0x05, 0xee, 0x96, 0x0d, 0x78, 0x3d,
	0x46, 0x82, 0x37, 0x4b, 0x81, 0x53, 0x3a, 0x64, 0x42, 0x90, 0xad, 0x2a, 0xfc, 0xfb, 0x52, 0xe0,
	0x89, 0x70, 0x38, 0x5f, 0x53, 0xfb, 0x6b, 0x29, 0x70, 0xb7, 0x1c, 0xf6, 0xb8, 0x77, 0xde, 0x8b,
	0x75, 0x40, 0x8f, 0x1b, 0xf4, 0xfd, 0x58, 0xe0, 0xd1, 0x75, 0x50, 0xa7, 0x77, 0x3d, 0x88, 0x05,
	0xa6, 0x9f, 0x83, 0x79, 0x17, 0x9e, 0x87, 0x9d, 0x40, 0xb7, 0x87, 0xc3, 0xe3, 0x4e, 0xa0, 0x77,
	0x4d, 0x78, 0x1a, 0x6b, 0x2d, 0xfd, 0x0d, 0x60, 0x43, 0xfb, 0x7d, 0x16, 0xeb, 0x22, 0x4a, 0x4e,
	0x7f, 0x7c, 0x11, 0x0b, 0x2c, 0x04, 0x6e, 0xf0, 0x1b, 0x0b, 0xcd, 0xab, 0x58, 0x60, 0x15, 0xf7,
	0x62, 0x20, 0x12, 0x22, 0xe9, 0x6e, 0xdd, 0x78, 0x1d, 0x0b, 0x4c, 0xa7, 0x2b, 0x92, 0x4e, 0x44,
	0x78, 0xb4, 0x1c, 0x38, 0xbf, 0x0d, 0x64, 0x05, 0x83, 0x6d, 0x13, 0x85, 0x79, 0x17, 0xed, 0x27,
	0xcb, 0xad, 0xfd, 0xd6, 0xba, 0xca, 0xc3, 0x7b, 0x2b, 0x9c, 0x4a, 0xa3, 0x2a, 0x8a, 0xfb, 0x9e,
	0xb1, 0x2d, 0xa7, 0x09, 0x7c, 0xb0, 0x82, 0xa3, 0xfe, 0xab, 0xfc, 0x31, 0x63, 0xbf, 0x31, 0xd8,
	0x73, 0xc1, 0xdf, 0x6b, 0x1c, 0x97, 0x2d, 0xc8, 0xeb, 0xf8, 0xef, 0xae, 0x07, 0x58, 0xf1, 0xdf,
	0x69, 0xdf, 0x5f, 0x6f, 0xed, 0xf3, 0x36, 0x64, 0xdf, 0x32, 0xe0, 0xa3, 0x75, 0xce, 0xd9, 0xb0,
	0xc4, 0x76, 0xd8, 0xdc, 0x20, 0x12, 0x09, 0x1e, 0xad, 0x73, 0xce, 0x86, 0x33, 0x57, 0xfd, 0x7e,
	0xec, 0x6d, 0xcd, 0x93, 0xf5, 0x00, 0xc7, 0xbd, 0x24, 0x7a, 0xbe, 0x8e, 0xc3, 0xcd, 0xd7, 0x18,
	0xef, 0x16, 0xf5, 0x26, 0xbe, 0x59, 0x7e, 0xf9, 0xc3, 0xdc, 0x89, 0x67, 0x3f, 0xcd, 0xf5, 0xdc,
	0xfc, 0x97, 0xef, 0x0b, 0x85, 0xef, 0xeb, 0x83, 0xf7, 0x69, 0x62, 0x2f, 0x57, 0x2a, 0x6c, 0xb4,
	0x7c, 0x95, 0x78, 0xd1, 0x3b, 0x21, 0xda, 0x63, 0xdb, 0xc5, 0xbb, 0xe6, 0x2d, 0xd1, 0x1e, 0xfb,
	0xb1, 0x37, 0xdc, 0x32, 0x76, 0x2b, 0x65, 0xd6, 0x72, 0x77, 0x72, 0xb5, 0xdc, 0xed, 0x41, 0xdb,
	0xe0, 0x95, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x95, 0x77, 0x13, 0x44, 0x4c, 0x11, 0x00, 0x00,
}
