// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: chargehive/chtype/transaction.proto

package chtype

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Transaction struct {
	TokenId                   string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	TransactionId             string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Details                   []*TransactionDetail   `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
	PaymentType               PaymentMethodType      `protobuf:"varint,4,opt,name=payment_type,json=paymentType,proto3,enum=chargehive.chtype.PaymentMethodType" json:"payment_type,omitempty"`
	PaymentScheme             string                 `protobuf:"bytes,5,opt,name=payment_scheme,json=paymentScheme,proto3" json:"payment_scheme,omitempty"`
	TransactionType           TransactionType        `protobuf:"varint,6,opt,name=transaction_type,json=transactionType,proto3,enum=chargehive.chtype.TransactionType" json:"transaction_type,omitempty"`
	RequestAmount             *Amount                `protobuf:"bytes,7,opt,name=request_amount,json=requestAmount,proto3" json:"request_amount,omitempty"`
	TransactedAmount          *Amount                `protobuf:"bytes,8,opt,name=transacted_amount,json=transactedAmount,proto3" json:"transacted_amount,omitempty"`
	Contract                  ContractType           `protobuf:"varint,9,opt,name=contract,proto3,enum=chargehive.chtype.ContractType" json:"contract,omitempty"`
	StatementDescriptor       string                 `protobuf:"bytes,10,opt,name=statement_descriptor,json=statementDescriptor,proto3" json:"statement_descriptor,omitempty"`
	Result                    TransactionResult      `protobuf:"varint,11,opt,name=result,proto3,enum=chargehive.chtype.TransactionResult" json:"result,omitempty"`
	VerifyRequest             *VerifyRequestData     `protobuf:"bytes,12,opt,name=verify_request,json=verifyRequest,proto3" json:"verify_request,omitempty"`
	FailureType               FailureType            `protobuf:"varint,13,opt,name=failure_type,json=failureType,proto3,enum=chargehive.chtype.FailureType" json:"failure_type,omitempty"`
	Arn                       string                 `protobuf:"bytes,14,opt,name=arn,proto3" json:"arn,omitempty"`
	Verified                  VerificationStatus     `protobuf:"varint,15,opt,name=verified,proto3,enum=chargehive.chtype.VerificationStatus" json:"verified,omitempty"`
	Liability                 Liability              `protobuf:"varint,16,opt,name=liability,proto3,enum=chargehive.chtype.Liability" json:"liability,omitempty"`
	AttemptDetail             *AttemptDetail         `protobuf:"bytes,17,opt,name=attempt_detail,json=attemptDetail,proto3" json:"attempt_detail,omitempty"`
	FraudResults              []*FraudResult         `protobuf:"bytes,18,rep,name=fraud_results,json=fraudResults,proto3" json:"fraud_results,omitempty"`
	Response                  *ResponseDetail        `protobuf:"bytes,19,opt,name=response,proto3" json:"response,omitempty"`
	SourceTransactionId       string                 `protobuf:"bytes,20,opt,name=source_transaction_id,json=sourceTransactionId,proto3" json:"source_transaction_id,omitempty"`
	PaymentMethodId           string                 `protobuf:"bytes,21,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	TransactionSubType        TransactionSubType     `protobuf:"varint,22,opt,name=transaction_sub_type,json=transactionSubType,proto3,enum=chargehive.chtype.TransactionSubType" json:"transaction_sub_type,omitempty"`
	AncillaryTransactions     []*Transaction         `protobuf:"bytes,23,rep,name=ancillary_transactions,json=ancillaryTransactions,proto3" json:"ancillary_transactions,omitempty"`
	RequestedConnectorId      string                 `protobuf:"bytes,24,opt,name=requested_connector_id,json=requestedConnectorId,proto3" json:"requested_connector_id,omitempty"`
	RequestedConnectorLibrary string                 `protobuf:"bytes,25,opt,name=requested_connector_library,json=requestedConnectorLibrary,proto3" json:"requested_connector_library,omitempty"`
	TransactionTime           *timestamppb.Timestamp `protobuf:"bytes,26,opt,name=transaction_time,json=transactionTime,proto3" json:"transaction_time,omitempty"`
	PaymentProvider           PaymentMethodProvider  `protobuf:"varint,27,opt,name=payment_provider,json=paymentProvider,proto3,enum=chargehive.chtype.PaymentMethodProvider" json:"payment_provider,omitempty"`
	PaymentInputType          PaymentMethodInputType `protobuf:"varint,28,opt,name=payment_input_type,json=paymentInputType,proto3,enum=chargehive.chtype.PaymentMethodInputType" json:"payment_input_type,omitempty"`
	AuthCode                  string                 `protobuf:"bytes,29,opt,name=auth_code,json=authCode,proto3" json:"auth_code,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}               `json:"-"`
	XXX_unrecognized          []byte                 `json:"-"`
	XXX_sizecache             int32                  `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf8aa08fd543022, []int{0}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

func (m *Transaction) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

func (m *Transaction) GetDetails() []*TransactionDetail {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *Transaction) GetPaymentType() PaymentMethodType {
	if m != nil {
		return m.PaymentType
	}
	return PAYMENT_METHOD_TYPE_INVALID
}

func (m *Transaction) GetPaymentScheme() string {
	if m != nil {
		return m.PaymentScheme
	}
	return ""
}

func (m *Transaction) GetTransactionType() TransactionType {
	if m != nil {
		return m.TransactionType
	}
	return TRANSACTION_TYPE_INVALID
}

func (m *Transaction) GetRequestAmount() *Amount {
	if m != nil {
		return m.RequestAmount
	}
	return nil
}

func (m *Transaction) GetTransactedAmount() *Amount {
	if m != nil {
		return m.TransactedAmount
	}
	return nil
}

func (m *Transaction) GetContract() ContractType {
	if m != nil {
		return m.Contract
	}
	return CONTRACT_TYPE_INVALID
}

func (m *Transaction) GetStatementDescriptor() string {
	if m != nil {
		return m.StatementDescriptor
	}
	return ""
}

func (m *Transaction) GetResult() TransactionResult {
	if m != nil {
		return m.Result
	}
	return TRANSACTION_RESULT_INVALID
}

func (m *Transaction) GetVerifyRequest() *VerifyRequestData {
	if m != nil {
		return m.VerifyRequest
	}
	return nil
}

func (m *Transaction) GetFailureType() FailureType {
	if m != nil {
		return m.FailureType
	}
	return FAILURE_TYPE_INVALID
}

func (m *Transaction) GetArn() string {
	if m != nil {
		return m.Arn
	}
	return ""
}

func (m *Transaction) GetVerified() VerificationStatus {
	if m != nil {
		return m.Verified
	}
	return VERIFICATION_STATUS_INVALID
}

func (m *Transaction) GetLiability() Liability {
	if m != nil {
		return m.Liability
	}
	return LIABILITY_INVALID
}

func (m *Transaction) GetAttemptDetail() *AttemptDetail {
	if m != nil {
		return m.AttemptDetail
	}
	return nil
}

func (m *Transaction) GetFraudResults() []*FraudResult {
	if m != nil {
		return m.FraudResults
	}
	return nil
}

func (m *Transaction) GetResponse() *ResponseDetail {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *Transaction) GetSourceTransactionId() string {
	if m != nil {
		return m.SourceTransactionId
	}
	return ""
}

func (m *Transaction) GetPaymentMethodId() string {
	if m != nil {
		return m.PaymentMethodId
	}
	return ""
}

func (m *Transaction) GetTransactionSubType() TransactionSubType {
	if m != nil {
		return m.TransactionSubType
	}
	return TRANSACTION_SUB_TYPE_INVALID
}

func (m *Transaction) GetAncillaryTransactions() []*Transaction {
	if m != nil {
		return m.AncillaryTransactions
	}
	return nil
}

func (m *Transaction) GetRequestedConnectorId() string {
	if m != nil {
		return m.RequestedConnectorId
	}
	return ""
}

func (m *Transaction) GetRequestedConnectorLibrary() string {
	if m != nil {
		return m.RequestedConnectorLibrary
	}
	return ""
}

func (m *Transaction) GetTransactionTime() *timestamppb.Timestamp {
	if m != nil {
		return m.TransactionTime
	}
	return nil
}

func (m *Transaction) GetPaymentProvider() PaymentMethodProvider {
	if m != nil {
		return m.PaymentProvider
	}
	return PAYMENT_METHOD_PROVIDER_INVALID
}

func (m *Transaction) GetPaymentInputType() PaymentMethodInputType {
	if m != nil {
		return m.PaymentInputType
	}
	return INPUT_TYPE_INVALID
}

func (m *Transaction) GetAuthCode() string {
	if m != nil {
		return m.AuthCode
	}
	return ""
}

type TransactionDetail struct {
	ActorId              string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ActorVersion         string                 `protobuf:"bytes,2,opt,name=actor_version,json=actorVersion,proto3" json:"actor_version,omitempty"`
	ActorType            ActorType              `protobuf:"varint,3,opt,name=actor_type,json=actorType,proto3,enum=chargehive.chtype.ActorType" json:"actor_type,omitempty"`
	TransactionId        string                 `protobuf:"bytes,4,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	RequestedAmount      *Amount                `protobuf:"bytes,5,opt,name=requested_amount,json=requestedAmount,proto3" json:"requested_amount,omitempty"`
	ProcessedAmount      *Amount                `protobuf:"bytes,6,opt,name=processed_amount,json=processedAmount,proto3" json:"processed_amount,omitempty"`
	FeeEstimate          *Amount                `protobuf:"bytes,7,opt,name=fee_estimate,json=feeEstimate,proto3" json:"fee_estimate,omitempty"`
	FeeActual            *Amount                `protobuf:"bytes,8,opt,name=fee_actual,json=feeActual,proto3" json:"fee_actual,omitempty"`
	StartTime            *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	WasSuccessful        bool                   `protobuf:"varint,11,opt,name=was_successful,json=wasSuccessful,proto3" json:"was_successful,omitempty"`
	Environment          Environment            `protobuf:"varint,13,opt,name=environment,proto3,enum=chargehive.chtype.Environment" json:"environment,omitempty"`
	Response             *ResponseDetail        `protobuf:"bytes,14,opt,name=response,proto3" json:"response,omitempty"`
	VerificationResult   *VerificationResult    `protobuf:"bytes,15,opt,name=verification_result,json=verificationResult,proto3" json:"verification_result,omitempty"`
	AdditionalData       map[string]string      `protobuf:"bytes,16,rep,name=additional_data,json=additionalData,proto3" json:"additional_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	AuthorizationCode    string                 `protobuf:"bytes,17,opt,name=authorization_code,json=authorizationCode,proto3" json:"authorization_code,omitempty"`
	Liability            Liability              `protobuf:"varint,18,opt,name=liability,proto3,enum=chargehive.chtype.Liability" json:"liability,omitempty"`
	ConnectorLibrary     string                 `protobuf:"bytes,19,opt,name=connector_library,json=connectorLibrary,proto3" json:"connector_library,omitempty"`
	ConnectorId          string                 `protobuf:"bytes,20,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"`
	Primary              bool                   `protobuf:"varint,21,opt,name=primary,proto3" json:"primary,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TransactionDetail) Reset()         { *m = TransactionDetail{} }
func (m *TransactionDetail) String() string { return proto.CompactTextString(m) }
func (*TransactionDetail) ProtoMessage()    {}
func (*TransactionDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf8aa08fd543022, []int{1}
}
func (m *TransactionDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionDetail.Unmarshal(m, b)
}
func (m *TransactionDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionDetail.Marshal(b, m, deterministic)
}
func (m *TransactionDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionDetail.Merge(m, src)
}
func (m *TransactionDetail) XXX_Size() int {
	return xxx_messageInfo_TransactionDetail.Size(m)
}
func (m *TransactionDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionDetail.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionDetail proto.InternalMessageInfo

func (m *TransactionDetail) GetActorId() string {
	if m != nil {
		return m.ActorId
	}
	return ""
}

func (m *TransactionDetail) GetActorVersion() string {
	if m != nil {
		return m.ActorVersion
	}
	return ""
}

func (m *TransactionDetail) GetActorType() ActorType {
	if m != nil {
		return m.ActorType
	}
	return ACTOR_TYPE_INVALID
}

func (m *TransactionDetail) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

func (m *TransactionDetail) GetRequestedAmount() *Amount {
	if m != nil {
		return m.RequestedAmount
	}
	return nil
}

func (m *TransactionDetail) GetProcessedAmount() *Amount {
	if m != nil {
		return m.ProcessedAmount
	}
	return nil
}

func (m *TransactionDetail) GetFeeEstimate() *Amount {
	if m != nil {
		return m.FeeEstimate
	}
	return nil
}

func (m *TransactionDetail) GetFeeActual() *Amount {
	if m != nil {
		return m.FeeActual
	}
	return nil
}

func (m *TransactionDetail) GetStartTime() *timestamppb.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *TransactionDetail) GetEndTime() *timestamppb.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *TransactionDetail) GetWasSuccessful() bool {
	if m != nil {
		return m.WasSuccessful
	}
	return false
}

func (m *TransactionDetail) GetEnvironment() Environment {
	if m != nil {
		return m.Environment
	}
	return ENVIRONMENT_INVALID
}

func (m *TransactionDetail) GetResponse() *ResponseDetail {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *TransactionDetail) GetVerificationResult() *VerificationResult {
	if m != nil {
		return m.VerificationResult
	}
	return nil
}

func (m *TransactionDetail) GetAdditionalData() map[string]string {
	if m != nil {
		return m.AdditionalData
	}
	return nil
}

func (m *TransactionDetail) GetAuthorizationCode() string {
	if m != nil {
		return m.AuthorizationCode
	}
	return ""
}

func (m *TransactionDetail) GetLiability() Liability {
	if m != nil {
		return m.Liability
	}
	return LIABILITY_INVALID
}

func (m *TransactionDetail) GetConnectorLibrary() string {
	if m != nil {
		return m.ConnectorLibrary
	}
	return ""
}

func (m *TransactionDetail) GetConnectorId() string {
	if m != nil {
		return m.ConnectorId
	}
	return ""
}

func (m *TransactionDetail) GetPrimary() bool {
	if m != nil {
		return m.Primary
	}
	return false
}

type VerifyRequestData struct {
	Type                 VerifyRequestType `protobuf:"varint,1,opt,name=type,proto3,enum=chargehive.chtype.VerifyRequestType" json:"type,omitempty"`
	Data                 map[string]string `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ConnectorLibrary     string            `protobuf:"bytes,3,opt,name=connector_library,json=connectorLibrary,proto3" json:"connector_library,omitempty"`
	Environment          Environment       `protobuf:"varint,4,opt,name=environment,proto3,enum=chargehive.chtype.Environment" json:"environment,omitempty"`
	Required             bool              `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *VerifyRequestData) Reset()         { *m = VerifyRequestData{} }
func (m *VerifyRequestData) String() string { return proto.CompactTextString(m) }
func (*VerifyRequestData) ProtoMessage()    {}
func (*VerifyRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf8aa08fd543022, []int{2}
}
func (m *VerifyRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRequestData.Unmarshal(m, b)
}
func (m *VerifyRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRequestData.Marshal(b, m, deterministic)
}
func (m *VerifyRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRequestData.Merge(m, src)
}
func (m *VerifyRequestData) XXX_Size() int {
	return xxx_messageInfo_VerifyRequestData.Size(m)
}
func (m *VerifyRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRequestData proto.InternalMessageInfo

func (m *VerifyRequestData) GetType() VerifyRequestType {
	if m != nil {
		return m.Type
	}
	return VERIFY_REQUEST_TYPE_INVALID
}

func (m *VerifyRequestData) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *VerifyRequestData) GetConnectorLibrary() string {
	if m != nil {
		return m.ConnectorLibrary
	}
	return ""
}

func (m *VerifyRequestData) GetEnvironment() Environment {
	if m != nil {
		return m.Environment
	}
	return ENVIRONMENT_INVALID
}

func (m *VerifyRequestData) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

type ThreeDSResult struct {
	Eci                  string                 `protobuf:"bytes,1,opt,name=eci,proto3" json:"eci,omitempty"`
	Cavv                 string                 `protobuf:"bytes,2,opt,name=cavv,proto3" json:"cavv,omitempty"`
	Xid                  string                 `protobuf:"bytes,3,opt,name=xid,proto3" json:"xid,omitempty"`
	Enrollment           string                 `protobuf:"bytes,4,opt,name=enrollment,proto3" json:"enrollment,omitempty"`
	Result               string                 `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	SignatureStatus      string                 `protobuf:"bytes,6,opt,name=signature_status,json=signatureStatus,proto3" json:"signature_status,omitempty"`
	ServerTransactionId  string                 `protobuf:"bytes,7,opt,name=server_transaction_id,json=serverTransactionId,proto3" json:"server_transaction_id,omitempty"`
	Status               string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	MajorVersion         int32                  `protobuf:"varint,9,opt,name=major_version,json=majorVersion,proto3" json:"major_version,omitempty"`
	Version              string                 `protobuf:"bytes,10,opt,name=version,proto3" json:"version,omitempty"`
	PaReq                string                 `protobuf:"bytes,11,opt,name=pa_req,json=paReq,proto3" json:"pa_req,omitempty"`
	AcsUrl               string                 `protobuf:"bytes,12,opt,name=acs_url,json=acsUrl,proto3" json:"acs_url,omitempty"`
	PaRes                string                 `protobuf:"bytes,13,opt,name=pa_res,json=paRes,proto3" json:"pa_res,omitempty"`
	Id                   string                 `protobuf:"bytes,14,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp            *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Liability            Liability              `protobuf:"varint,16,opt,name=liability,proto3,enum=chargehive.chtype.Liability" json:"liability,omitempty"`
	SdkResponse          string                 `protobuf:"bytes,17,opt,name=sdk_response,json=sdkResponse,proto3" json:"sdk_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ThreeDSResult) Reset()         { *m = ThreeDSResult{} }
func (m *ThreeDSResult) String() string { return proto.CompactTextString(m) }
func (*ThreeDSResult) ProtoMessage()    {}
func (*ThreeDSResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf8aa08fd543022, []int{3}
}
func (m *ThreeDSResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreeDSResult.Unmarshal(m, b)
}
func (m *ThreeDSResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreeDSResult.Marshal(b, m, deterministic)
}
func (m *ThreeDSResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreeDSResult.Merge(m, src)
}
func (m *ThreeDSResult) XXX_Size() int {
	return xxx_messageInfo_ThreeDSResult.Size(m)
}
func (m *ThreeDSResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreeDSResult.DiscardUnknown(m)
}

var xxx_messageInfo_ThreeDSResult proto.InternalMessageInfo

func (m *ThreeDSResult) GetEci() string {
	if m != nil {
		return m.Eci
	}
	return ""
}

func (m *ThreeDSResult) GetCavv() string {
	if m != nil {
		return m.Cavv
	}
	return ""
}

func (m *ThreeDSResult) GetXid() string {
	if m != nil {
		return m.Xid
	}
	return ""
}

func (m *ThreeDSResult) GetEnrollment() string {
	if m != nil {
		return m.Enrollment
	}
	return ""
}

func (m *ThreeDSResult) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *ThreeDSResult) GetSignatureStatus() string {
	if m != nil {
		return m.SignatureStatus
	}
	return ""
}

func (m *ThreeDSResult) GetServerTransactionId() string {
	if m != nil {
		return m.ServerTransactionId
	}
	return ""
}

func (m *ThreeDSResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ThreeDSResult) GetMajorVersion() int32 {
	if m != nil {
		return m.MajorVersion
	}
	return 0
}

func (m *ThreeDSResult) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ThreeDSResult) GetPaReq() string {
	if m != nil {
		return m.PaReq
	}
	return ""
}

func (m *ThreeDSResult) GetAcsUrl() string {
	if m != nil {
		return m.AcsUrl
	}
	return ""
}

func (m *ThreeDSResult) GetPaRes() string {
	if m != nil {
		return m.PaRes
	}
	return ""
}

func (m *ThreeDSResult) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ThreeDSResult) GetTimestamp() *timestamppb.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *ThreeDSResult) GetLiability() Liability {
	if m != nil {
		return m.Liability
	}
	return LIABILITY_INVALID
}

func (m *ThreeDSResult) GetSdkResponse() string {
	if m != nil {
		return m.SdkResponse
	}
	return ""
}

type VerificationResult struct {
	AddressVerificationResult string         `protobuf:"bytes,1,opt,name=address_verification_result,json=addressVerificationResult,proto3" json:"address_verification_result,omitempty"`
	CvvVerificationResult     string         `protobuf:"bytes,2,opt,name=cvv_verification_result,json=cvvVerificationResult,proto3" json:"cvv_verification_result,omitempty"`
	FraudResult               string         `protobuf:"bytes,3,opt,name=fraud_result,json=fraudResult,proto3" json:"fraud_result,omitempty"`
	ThreedsResult             *ThreeDSResult `protobuf:"bytes,5,opt,name=threeds_result,json=threedsResult,proto3" json:"threeds_result,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}       `json:"-"`
	XXX_unrecognized          []byte         `json:"-"`
	XXX_sizecache             int32          `json:"-"`
}

func (m *VerificationResult) Reset()         { *m = VerificationResult{} }
func (m *VerificationResult) String() string { return proto.CompactTextString(m) }
func (*VerificationResult) ProtoMessage()    {}
func (*VerificationResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf8aa08fd543022, []int{4}
}
func (m *VerificationResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerificationResult.Unmarshal(m, b)
}
func (m *VerificationResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerificationResult.Marshal(b, m, deterministic)
}
func (m *VerificationResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerificationResult.Merge(m, src)
}
func (m *VerificationResult) XXX_Size() int {
	return xxx_messageInfo_VerificationResult.Size(m)
}
func (m *VerificationResult) XXX_DiscardUnknown() {
	xxx_messageInfo_VerificationResult.DiscardUnknown(m)
}

var xxx_messageInfo_VerificationResult proto.InternalMessageInfo

func (m *VerificationResult) GetAddressVerificationResult() string {
	if m != nil {
		return m.AddressVerificationResult
	}
	return ""
}

func (m *VerificationResult) GetCvvVerificationResult() string {
	if m != nil {
		return m.CvvVerificationResult
	}
	return ""
}

func (m *VerificationResult) GetFraudResult() string {
	if m != nil {
		return m.FraudResult
	}
	return ""
}

func (m *VerificationResult) GetThreedsResult() *ThreeDSResult {
	if m != nil {
		return m.ThreedsResult
	}
	return nil
}

type AttemptDetail struct {
	ChargeTransactionNumber  int64    `protobuf:"varint,1,opt,name=ChargeTransactionNumber,proto3" json:"ChargeTransactionNumber,omitempty"`
	ChargeAttemptNumber      int64    `protobuf:"varint,2,opt,name=ChargeAttemptNumber,proto3" json:"ChargeAttemptNumber,omitempty"`
	AttemptTransactionNumber int64    `protobuf:"varint,3,opt,name=AttemptTransactionNumber,proto3" json:"AttemptTransactionNumber,omitempty"`
	AttemptMethodCascade     int64    `protobuf:"varint,4,opt,name=AttemptMethodCascade,proto3" json:"AttemptMethodCascade,omitempty"`
	AttemptConnectorCascade  int64    `protobuf:"varint,5,opt,name=AttemptConnectorCascade,proto3" json:"AttemptConnectorCascade,omitempty"`
	IsPrimaryMethod          bool     `protobuf:"varint,6,opt,name=IsPrimaryMethod,proto3" json:"IsPrimaryMethod,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *AttemptDetail) Reset()         { *m = AttemptDetail{} }
func (m *AttemptDetail) String() string { return proto.CompactTextString(m) }
func (*AttemptDetail) ProtoMessage()    {}
func (*AttemptDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf8aa08fd543022, []int{5}
}
func (m *AttemptDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttemptDetail.Unmarshal(m, b)
}
func (m *AttemptDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttemptDetail.Marshal(b, m, deterministic)
}
func (m *AttemptDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttemptDetail.Merge(m, src)
}
func (m *AttemptDetail) XXX_Size() int {
	return xxx_messageInfo_AttemptDetail.Size(m)
}
func (m *AttemptDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_AttemptDetail.DiscardUnknown(m)
}

var xxx_messageInfo_AttemptDetail proto.InternalMessageInfo

func (m *AttemptDetail) GetChargeTransactionNumber() int64 {
	if m != nil {
		return m.ChargeTransactionNumber
	}
	return 0
}

func (m *AttemptDetail) GetChargeAttemptNumber() int64 {
	if m != nil {
		return m.ChargeAttemptNumber
	}
	return 0
}

func (m *AttemptDetail) GetAttemptTransactionNumber() int64 {
	if m != nil {
		return m.AttemptTransactionNumber
	}
	return 0
}

func (m *AttemptDetail) GetAttemptMethodCascade() int64 {
	if m != nil {
		return m.AttemptMethodCascade
	}
	return 0
}

func (m *AttemptDetail) GetAttemptConnectorCascade() int64 {
	if m != nil {
		return m.AttemptConnectorCascade
	}
	return 0
}

func (m *AttemptDetail) GetIsPrimaryMethod() bool {
	if m != nil {
		return m.IsPrimaryMethod
	}
	return false
}

func init() {
	proto.RegisterType((*Transaction)(nil), "chargehive.chtype.Transaction")
	golang_proto.RegisterType((*Transaction)(nil), "chargehive.chtype.Transaction")
	proto.RegisterType((*TransactionDetail)(nil), "chargehive.chtype.TransactionDetail")
	golang_proto.RegisterType((*TransactionDetail)(nil), "chargehive.chtype.TransactionDetail")
	proto.RegisterMapType((map[string]string)(nil), "chargehive.chtype.TransactionDetail.AdditionalDataEntry")
	golang_proto.RegisterMapType((map[string]string)(nil), "chargehive.chtype.TransactionDetail.AdditionalDataEntry")
	proto.RegisterType((*VerifyRequestData)(nil), "chargehive.chtype.VerifyRequestData")
	golang_proto.RegisterType((*VerifyRequestData)(nil), "chargehive.chtype.VerifyRequestData")
	proto.RegisterMapType((map[string]string)(nil), "chargehive.chtype.VerifyRequestData.DataEntry")
	golang_proto.RegisterMapType((map[string]string)(nil), "chargehive.chtype.VerifyRequestData.DataEntry")
	proto.RegisterType((*ThreeDSResult)(nil), "chargehive.chtype.ThreeDSResult")
	golang_proto.RegisterType((*ThreeDSResult)(nil), "chargehive.chtype.ThreeDSResult")
	proto.RegisterType((*VerificationResult)(nil), "chargehive.chtype.VerificationResult")
	golang_proto.RegisterType((*VerificationResult)(nil), "chargehive.chtype.VerificationResult")
	proto.RegisterType((*AttemptDetail)(nil), "chargehive.chtype.AttemptDetail")
	golang_proto.RegisterType((*AttemptDetail)(nil), "chargehive.chtype.AttemptDetail")
}

func init() {
	proto.RegisterFile("chargehive/chtype/transaction.proto", fileDescriptor_7bf8aa08fd543022)
}
func init() {
	golang_proto.RegisterFile("chargehive/chtype/transaction.proto", fileDescriptor_7bf8aa08fd543022)
}

var fileDescriptor_7bf8aa08fd543022 = []byte{
	// 1726 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0xdd, 0x72, 0x23, 0x47,
	0x15, 0xc6, 0x92, 0x7f, 0xa4, 0xa3, 0x1f, 0x4b, 0xed, 0x9f, 0x1d, 0x6b, 0x37, 0xbb, 0x5e, 0x87,
	0xa5, 0x1c, 0x28, 0x64, 0xe2, 0x04, 0x30, 0x9b, 0x40, 0xad, 0x63, 0x6f, 0x82, 0x8b, 0x2c, 0xb5,
	0x35, 0x76, 0x36, 0x55, 0x54, 0xaa, 0x54, 0xad, 0x99, 0x96, 0xd4, 0x78, 0x34, 0xa3, 0xed, 0xee,
	0x99, 0x20, 0x9e, 0x81, 0xd7, 0xa0, 0x8a, 0xc7, 0xe0, 0x9a, 0x1b, 0xb8, 0xe1, 0x01, 0x80, 0x97,
	0xe0, 0x92, 0xea, 0xd3, 0x3d, 0xa3, 0x91, 0x35, 0x5a, 0xed, 0x92, 0xbb, 0xe9, 0x73, 0xbe, 0xef,
	0x4c, 0xff, 0x9c, 0xfe, 0xce, 0x99, 0x81, 0xf7, 0xbd, 0x11, 0x15, 0x43, 0x36, 0xe2, 0x09, 0x3b,
	0xf1, 0x46, 0x6a, 0x3a, 0x61, 0x27, 0x4a, 0xd0, 0x50, 0x52, 0x4f, 0xf1, 0x28, 0xec, 0x4e, 0x44,
	0xa4, 0x22, 0xd2, 0x9e, 0x81, 0xba, 0x06, 0xd4, 0x79, 0xb4, 0xc8, 0x1b, 0xb2, 0x90, 0x09, 0xee,
	0x19, 0x4e, 0xe7, 0xc1, 0x22, 0x80, 0x85, 0xf1, 0xd8, 0x7a, 0xdf, 0x5b, 0xf4, 0x0e, 0x04, 0x8d,
	0x7d, 0xeb, 0xfe, 0xc1, 0xa2, 0x5b, 0x30, 0x39, 0x89, 0x42, 0xc9, 0x7a, 0x5e, 0xe4, 0x33, 0x69,
	0x71, 0x1f, 0x0f, 0xb9, 0x1a, 0xc5, 0xfd, 0xae, 0x17, 0x8d, 0x4f, 0x86, 0xd1, 0x30, 0x3a, 0x41,
	0x73, 0x3f, 0x1e, 0x3c, 0x4b, 0x3e, 0xec, 0x7e, 0xd4, 0x3d, 0x45, 0x23, 0xda, 0xf0, 0xc9, 0xb2,
	0x1e, 0x0d, 0xa3, 0x68, 0x18, 0xb0, 0x0c, 0x7c, 0xa2, 0xf8, 0x98, 0x49, 0x45, 0xc7, 0x13, 0x03,
	0x38, 0xfa, 0x53, 0x13, 0x6a, 0x37, 0xb3, 0x5d, 0x20, 0x07, 0x50, 0x51, 0xd1, 0x2d, 0x0b, 0x7b,
	0xdc, 0x77, 0xd6, 0x0e, 0xd7, 0x8e, 0xab, 0xee, 0x16, 0x8e, 0xaf, 0x7c, 0xf2, 0x04, 0x9a, 0xb9,
	0xfd, 0xd2, 0x80, 0x12, 0x02, 0x1a, 0x39, 0xeb, 0x95, 0x4f, 0x7e, 0x05, 0x5b, 0x3e, 0x53, 0x94,
	0x07, 0xd2, 0x29, 0x1f, 0x96, 0x8f, 0x6b, 0xa7, 0xdf, 0xef, 0x2e, 0xec, 0x69, 0x37, 0xf7, 0xca,
	0x4b, 0x04, 0xbb, 0x29, 0x89, 0x7c, 0x01, 0xf5, 0x09, 0x9d, 0x8e, 0x59, 0xa8, 0x7a, 0x1a, 0xea,
	0xac, 0x1f, 0xae, 0x1d, 0x37, 0x0b, 0x83, 0xbc, 0x34, 0xb0, 0x17, 0x4c, 0x8d, 0x22, 0xff, 0x66,
	0x3a, 0x61, 0x6e, 0xcd, 0x32, 0xf5, 0x40, 0xcf, 0x37, 0x0d, 0x24, 0xbd, 0x11, 0x1b, 0x33, 0x67,
	0xc3, 0xcc, 0xd7, 0x5a, 0xaf, 0xd1, 0x48, 0x5e, 0x40, 0x2b, 0xbf, 0x2c, 0x7c, 0xe7, 0x26, 0xbe,
	0xf3, 0xe8, 0xcd, 0x13, 0xc7, 0x37, 0x6e, 0xab, 0x79, 0x03, 0x79, 0x06, 0x4d, 0xc1, 0x5e, 0xc7,
	0x4c, 0xaa, 0x1e, 0x1d, 0x47, 0x71, 0xa8, 0x9c, 0xad, 0xc3, 0xb5, 0xe3, 0xda, 0xe9, 0x41, 0x41,
	0xb0, 0x73, 0x04, 0xb8, 0x0d, 0x4b, 0x30, 0x43, 0xf2, 0x39, 0xb4, 0xd3, 0xa0, 0xcc, 0x4f, 0x83,
	0x54, 0x56, 0x05, 0x69, 0xcd, 0x38, 0x36, 0xce, 0x27, 0x50, 0xf1, 0xa2, 0x50, 0x09, 0xea, 0x29,
	0xa7, 0x8a, 0x0b, 0x7a, 0x54, 0x40, 0xbf, 0xb0, 0x10, 0x5c, 0x4d, 0x46, 0x20, 0x1f, 0xc2, 0xae,
	0x54, 0x54, 0x31, 0xdc, 0x3e, 0x9f, 0x49, 0x4f, 0xf0, 0x89, 0x8a, 0x84, 0x03, 0xb8, 0x85, 0x3b,
	0x99, 0xef, 0x32, 0x73, 0x91, 0x4f, 0x61, 0x53, 0x30, 0x19, 0x07, 0xca, 0xa9, 0x2d, 0x3d, 0xb2,
	0xdc, 0xf6, 0xb9, 0x88, 0x75, 0x2d, 0x87, 0xfc, 0x06, 0x9a, 0x09, 0x13, 0x7c, 0x30, 0xed, 0xd9,
	0xdd, 0x70, 0xea, 0xb8, 0xe4, 0xa2, 0x28, 0xaf, 0x10, 0xe8, 0x1a, 0xdc, 0x25, 0x55, 0xd4, 0x6d,
	0x24, 0x79, 0x13, 0x39, 0x87, 0xfa, 0x80, 0xf2, 0x20, 0x16, 0xcc, 0x9c, 0x67, 0x03, 0x27, 0xf4,
	0xb0, 0x20, 0xd4, 0xe7, 0x06, 0x66, 0xb2, 0x67, 0x30, 0x1b, 0x90, 0x16, 0x94, 0xa9, 0x08, 0x9d,
	0x26, 0xae, 0x57, 0x3f, 0x92, 0x73, 0xa8, 0xe0, 0x5b, 0x38, 0xf3, 0x9d, 0x6d, 0x0c, 0xf8, 0x64,
	0xd9, 0xdc, 0xb8, 0x47, 0xf5, 0x12, 0xaf, 0x15, 0x55, 0xb1, 0x74, 0x33, 0x1a, 0x79, 0x0a, 0xd5,
	0x80, 0xd3, 0x3e, 0x0f, 0xb8, 0x9a, 0x3a, 0x2d, 0x8c, 0xf1, 0xa0, 0x20, 0xc6, 0x97, 0x29, 0xc6,
	0x9d, 0xc1, 0xc9, 0x17, 0xd0, 0xa4, 0x4a, 0xb1, 0xf1, 0x44, 0x9f, 0x87, 0xbe, 0x2a, 0x4e, 0x1b,
	0x37, 0xe8, 0xb0, 0x28, 0x27, 0x0c, 0xd0, 0x5e, 0xad, 0x06, 0xcd, 0x0f, 0xc9, 0x05, 0x34, 0x50,
	0x80, 0x7a, 0x66, 0xe7, 0xa5, 0x43, 0xf0, 0x9a, 0x16, 0xee, 0x8e, 0xc6, 0xd9, 0x83, 0xaa, 0x0f,
	0x66, 0x03, 0x49, 0x7e, 0x09, 0x95, 0x54, 0xa6, 0x9c, 0x1d, 0x9c, 0xc7, 0xe3, 0x02, 0xbe, 0x6b,
	0x21, 0x76, 0x22, 0x19, 0x85, 0x9c, 0xc2, 0x9e, 0x8c, 0x62, 0xe1, 0xb1, 0xde, 0x1d, 0x49, 0xd9,
	0xb5, 0xf9, 0x85, 0xce, 0x9b, 0x39, 0x61, 0xf9, 0x21, 0xb4, 0xd3, 0xfb, 0x3c, 0xc6, 0x2b, 0xaf,
	0xf1, 0x7b, 0x88, 0xdf, 0x9e, 0xe4, 0xa5, 0xe0, 0xca, 0x27, 0x5f, 0xc3, 0x6e, 0x3e, 0xb0, 0x8c,
	0xfb, 0x26, 0x11, 0xf6, 0x97, 0x9e, 0x5b, 0xee, 0x5d, 0xd7, 0x71, 0x1f, 0xf3, 0x81, 0xa8, 0x05,
	0x1b, 0xf9, 0x0a, 0xf6, 0x69, 0xe8, 0xf1, 0x20, 0xa0, 0x62, 0x9a, 0x9f, 0xbb, 0x74, 0xee, 0x2d,
	0xdd, 0xc5, 0x7c, 0xd2, 0xef, 0x65, 0xec, 0x9c, 0x55, 0x92, 0x8f, 0x61, 0xdf, 0xa6, 0x3d, 0xf3,
	0x7b, 0x5e, 0x14, 0x86, 0xcc, 0x53, 0x91, 0xd0, 0x0b, 0x74, 0x70, 0x81, 0xbb, 0x99, 0xf7, 0x22,
	0x75, 0xa2, 0xd4, 0xde, 0x2f, 0x62, 0x05, 0xbc, 0x2f, 0xa8, 0x98, 0x3a, 0x07, 0x48, 0x3d, 0x58,
	0xa4, 0x7e, 0x69, 0x00, 0xe4, 0xf9, 0x1d, 0xe9, 0xe3, 0x63, 0xe6, 0x74, 0xf0, 0x30, 0x3b, 0x5d,
	0x53, 0x38, 0xba, 0x69, 0xe1, 0xe8, 0xde, 0xa4, 0x85, 0x63, 0x5e, 0xf2, 0xf8, 0x98, 0x91, 0x6b,
	0x68, 0xa5, 0x07, 0x33, 0x11, 0x51, 0xc2, 0x7d, 0x26, 0x9c, 0xfb, 0xb8, 0xd1, 0xc7, 0xab, 0x54,
	0xfb, 0xa5, 0xc5, 0x67, 0x27, 0x98, 0x1a, 0xc8, 0xd7, 0x40, 0xd2, 0xa0, 0x3c, 0x9c, 0xc4, 0xb6,
	0x18, 0x3c, 0xc0, 0xb0, 0x1f, 0xac, 0x0a, 0x7b, 0xa5, 0x19, 0x78, 0x86, 0xe9, 0xcc, 0x32, 0x0b,
	0xb9, 0x0f, 0x55, 0x1a, 0xab, 0x11, 0x16, 0x57, 0xe7, 0x3d, 0xdc, 0xa2, 0x8a, 0x36, 0x5c, 0x44,
	0x3e, 0x3b, 0xfa, 0x4b, 0x15, 0xda, 0x0b, 0xb5, 0x49, 0x17, 0x45, 0x9a, 0x9e, 0x87, 0x2d, 0x8a,
	0xd4, 0x1e, 0xc1, 0xfb, 0xd0, 0x30, 0xae, 0x84, 0x09, 0xc9, 0xa3, 0xd0, 0xd6, 0xc4, 0x3a, 0x1a,
	0x5f, 0x19, 0x1b, 0xf9, 0x04, 0xc0, 0x80, 0x70, 0x0d, 0xe5, 0xa5, 0xf7, 0xfe, 0x5c, 0x83, 0x70,
	0xda, 0x55, 0x9a, 0x3e, 0x16, 0x94, 0xdd, 0xf5, 0xa2, 0xb2, 0x7b, 0x09, 0xad, 0x59, 0x2e, 0xd8,
	0xa2, 0xb1, 0xb1, 0xaa, 0x68, 0x6c, 0x67, 0x14, 0x5b, 0x33, 0x2e, 0xa1, 0x35, 0x11, 0x91, 0xc7,
	0xa4, 0x9c, 0x45, 0xd9, 0x5c, 0x19, 0x25, 0xa3, 0xd8, 0x28, 0x9f, 0x42, 0x7d, 0xc0, 0x58, 0x8f,
	0x49, 0xc5, 0xc7, 0x54, 0xb1, 0xd5, 0x15, 0xb0, 0x36, 0x60, 0xec, 0xb9, 0x45, 0x93, 0x33, 0x00,
	0xcd, 0xa6, 0x9e, 0x8a, 0x69, 0xb0, 0xba, 0xf0, 0x55, 0x07, 0x8c, 0x9d, 0x23, 0x96, 0xfc, 0x02,
	0x40, 0x2a, 0x2a, 0x94, 0xc9, 0xe4, 0xea, 0xca, 0x4c, 0xae, 0x22, 0x1a, 0x73, 0xf8, 0xa7, 0x50,
	0x61, 0xa1, 0x6f, 0x88, 0xb0, 0x92, 0xb8, 0xc5, 0x42, 0x1f, 0x69, 0x4f, 0xa0, 0xf9, 0x2d, 0x95,
	0x3d, 0x19, 0x7b, 0x7a, 0x03, 0x06, 0x71, 0x80, 0xb5, 0xaf, 0xe2, 0x36, 0xbe, 0xa5, 0xf2, 0x3a,
	0x33, 0x92, 0x67, 0x50, 0x63, 0x61, 0xc2, 0x45, 0x14, 0xea, 0x5c, 0x7c, 0x43, 0x39, 0x7a, 0x3e,
	0x43, 0xb9, 0x79, 0xca, 0x9c, 0xde, 0x36, 0xdf, 0x5d, 0x6f, 0x5f, 0xc1, 0x4e, 0x92, 0x2b, 0x4c,
	0x56, 0xfa, 0xb1, 0x8c, 0xd5, 0x56, 0x96, 0x31, 0x5b, 0x00, 0x48, 0xb2, 0x60, 0x23, 0x14, 0xb6,
	0xa9, 0xef, 0x73, 0x6d, 0xa1, 0x41, 0xcf, 0xa7, 0x8a, 0x3a, 0x2d, 0xd4, 0xc1, 0xb3, 0xb7, 0x69,
	0xfa, 0xba, 0xe7, 0x19, 0x57, 0x57, 0xf1, 0xe7, 0xa1, 0x12, 0x53, 0xb7, 0x49, 0xe7, 0x8c, 0xe4,
	0xc7, 0x40, 0xf4, 0xf5, 0x8c, 0x04, 0xff, 0xa3, 0x99, 0x3b, 0x5e, 0xdc, 0x36, 0xde, 0x81, 0xf6,
	0x9c, 0x47, 0xdf, 0xe0, 0xf9, 0x12, 0x4b, 0xde, 0xad, 0xc4, 0xfe, 0x08, 0xda, 0x8b, 0x2a, 0xba,
	0x83, 0x6f, 0x6a, 0x79, 0x77, 0xc5, 0xf3, 0x31, 0xd4, 0xe7, 0x84, 0xda, 0x54, 0xae, 0x9a, 0x97,
	0xd3, 0x67, 0x07, 0xb6, 0x26, 0x82, 0x8f, 0x75, 0x94, 0x3d, 0x4c, 0x8b, 0x74, 0xd8, 0x39, 0x87,
	0x9d, 0x82, 0xb5, 0xeb, 0xa6, 0xe3, 0x96, 0x4d, 0xad, 0xc6, 0xe8, 0x47, 0xb2, 0x0b, 0x1b, 0x09,
	0x0d, 0x62, 0x66, 0x75, 0xc5, 0x0c, 0x9e, 0x96, 0xce, 0xd6, 0x8e, 0xfe, 0x59, 0x82, 0xf6, 0x42,
	0x23, 0x44, 0xce, 0x60, 0x1d, 0x45, 0x66, 0x6d, 0x69, 0x0b, 0x36, 0xc7, 0x41, 0xb1, 0x41, 0x06,
	0xf9, 0x0c, 0xd6, 0xf1, 0xfc, 0x4a, 0x78, 0x7e, 0xdd, 0xb7, 0x69, 0xbb, 0xba, 0xb3, 0x53, 0x43,
	0x6e, 0xf1, 0x06, 0x96, 0x97, 0x6c, 0xe0, 0x9d, 0x4b, 0xb1, 0xfe, 0xee, 0x97, 0xa2, 0xa3, 0x2f,
	0xc5, 0xeb, 0x98, 0x0b, 0xe6, 0xa3, 0xd6, 0x55, 0xdc, 0x6c, 0xdc, 0xf9, 0x39, 0x54, 0xff, 0xbf,
	0x7d, 0xfd, 0xf3, 0x3a, 0x34, 0x6e, 0x46, 0x82, 0xb1, 0xcb, 0x6b, 0x9b, 0xe4, 0x2d, 0x28, 0x33,
	0x8f, 0xa7, 0x6c, 0xe6, 0x71, 0x42, 0x60, 0xdd, 0xa3, 0x49, 0x62, 0xc9, 0xf8, 0xac, 0x51, 0x7f,
	0xe0, 0xbe, 0x5d, 0xad, 0x7e, 0x24, 0x0f, 0x01, 0x58, 0x28, 0xa2, 0x20, 0xc8, 0xd6, 0x57, 0x75,
	0x73, 0x16, 0xb2, 0x9f, 0x35, 0xcc, 0xe6, 0xc3, 0x24, 0x6d, 0x85, 0x3f, 0x80, 0x96, 0xe4, 0xc3,
	0x90, 0x2a, 0xdd, 0xbf, 0x4a, 0xec, 0x21, 0x51, 0x84, 0xab, 0xee, 0x76, 0x66, 0x37, 0xad, 0x25,
	0xf6, 0x51, 0x4c, 0x24, 0x4c, 0xdc, 0xed, 0xa3, 0xb6, 0x6c, 0x1f, 0x85, 0xce, 0xf9, 0x3e, 0x6a,
	0x1f, 0x36, 0x6d, 0xd0, 0x8a, 0x79, 0xad, 0x19, 0xe9, 0x52, 0x36, 0xa6, 0xbf, 0xcf, 0x95, 0x32,
	0x2d, 0xa0, 0x1b, 0x6e, 0x1d, 0x8d, 0x69, 0x29, 0x73, 0x60, 0x2b, 0x75, 0x9b, 0x4f, 0x81, 0x74,
	0x48, 0xf6, 0x60, 0x73, 0x42, 0x75, 0xf3, 0x8e, 0x12, 0x58, 0x75, 0x37, 0x26, 0xd4, 0x65, 0xaf,
	0xc9, 0x3d, 0xd8, 0xa2, 0x9e, 0xec, 0xc5, 0x22, 0xc0, 0x86, 0xbe, 0xea, 0x6e, 0x52, 0x4f, 0x7e,
	0x25, 0x82, 0x0c, 0x2f, 0x51, 0x0e, 0x2d, 0x5e, 0x92, 0x26, 0x94, 0xb8, 0x6f, 0xdb, 0xee, 0x12,
	0xf7, 0xc9, 0x19, 0x54, 0xb3, 0x6f, 0x56, 0xab, 0x57, 0x6f, 0x94, 0xf4, 0x0c, 0xfc, 0x9d, 0x9a,
	0xed, 0xc7, 0x50, 0x97, 0xfe, 0x6d, 0x2f, 0x93, 0x5c, 0x23, 0x37, 0x35, 0xe9, 0xdf, 0xa6, 0x12,
	0x7b, 0xf4, 0xdf, 0x35, 0x20, 0x8b, 0x2a, 0xa9, 0x7b, 0x32, 0xea, 0xfb, 0x82, 0x49, 0xd9, 0x2b,
	0x52, 0x5c, 0x93, 0x44, 0x07, 0x16, 0x52, 0xc0, 0xff, 0x19, 0xdc, 0xf3, 0x92, 0xa4, 0x90, 0x6b,
	0xb2, 0x6d, 0xcf, 0x4b, 0x92, 0x02, 0xde, 0x63, 0xa8, 0xe7, 0xbb, 0x7a, 0x9b, 0x87, 0xb5, 0x5c,
	0xd3, 0xae, 0xbf, 0x20, 0x94, 0x4e, 0x6c, 0x5f, 0xf6, 0x72, 0x79, 0x57, 0xfc, 0x05, 0x31, 0x77,
	0x03, 0xdc, 0x86, 0xe5, 0x99, 0xe1, 0xd1, 0xdf, 0x4b, 0xd0, 0x98, 0xfb, 0xc4, 0x20, 0x67, 0x70,
	0xef, 0x02, 0x63, 0xe4, 0x52, 0xed, 0xb7, 0xf1, 0xb8, 0xcf, 0x04, 0xae, 0xb8, 0xec, 0x2e, 0x73,
	0x93, 0x9f, 0xc0, 0x8e, 0x71, 0xd9, 0x80, 0x96, 0x55, 0x42, 0x56, 0x91, 0x8b, 0x3c, 0x05, 0xc7,
	0x1a, 0x16, 0x5f, 0x56, 0x46, 0xda, 0x52, 0x3f, 0x39, 0x85, 0x5d, 0xeb, 0x33, 0x8d, 0xe2, 0x05,
	0x95, 0x1e, 0xf5, 0xcd, 0x4f, 0x86, 0xb2, 0x5b, 0xe8, 0xd3, 0x6b, 0xb3, 0xf6, 0xac, 0x81, 0x4e,
	0x69, 0x1b, 0x66, 0x6d, 0x4b, 0xdc, 0xe4, 0x18, 0xb6, 0xaf, 0xe4, 0x4b, 0x23, 0xf9, 0x26, 0x26,
	0xde, 0xe3, 0x8a, 0x7b, 0xd7, 0xfc, 0x59, 0xf4, 0x8f, 0x7f, 0x3d, 0xfc, 0xde, 0x5f, 0xff, 0xf3,
	0x70, 0xed, 0x77, 0xf9, 0xff, 0x3c, 0xb9, 0x5f, 0x43, 0xe9, 0x9f, 0x9d, 0x80, 0x86, 0xc3, 0x93,
	0x85, 0x5f, 0x46, 0x7f, 0x2b, 0xb5, 0xcd, 0x4e, 0xfd, 0x9a, 0x27, 0xec, 0x9b, 0x0b, 0xb4, 0xfd,
	0xbb, 0xd4, 0x59, 0xb0, 0x7d, 0xf3, 0x82, 0x29, 0xaa, 0x95, 0xba, 0xbf, 0x89, 0x01, 0x3f, 0xfa,
	0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0b, 0xff, 0xfb, 0x1a, 0x15, 0x13, 0x00, 0x00,
}
