<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chargehive/chtype/payment_method.proto

namespace ChargeHive\Chtype;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>chargehive.chtype.PaymentMethodVerificationItem</code>
 */
class PaymentMethodVerificationItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.chargehive.chtype.PaymentMethodVerificationItemType type = 1;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>bytes value = 2;</code>
     */
    protected $value = '';
    /**
     * Generated from protobuf field <code>string transport_key_id = 4;</code>
     */
    protected $transport_key_id = '';
    /**
     * Generated from protobuf field <code>bool is_error = 5;</code>
     */
    protected $is_error = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type string $value
     *     @type string $transport_key_id
     *     @type bool $is_error
     * }
     */
    public function __construct($data = NULL) {
        \ChargeHive\Chtype\Metadata\PaymentMethod::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.chargehive.chtype.PaymentMethodVerificationItemType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.chargehive.chtype.PaymentMethodVerificationItemType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \ChargeHive\Chtype\PaymentMethodVerificationItemType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes value = 2;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>bytes value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string transport_key_id = 4;</code>
     * @return string
     */
    public function getTransportKeyId()
    {
        return $this->transport_key_id;
    }

    /**
     * Generated from protobuf field <code>string transport_key_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTransportKeyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->transport_key_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_error = 5;</code>
     * @return bool
     */
    public function getIsError()
    {
        return $this->is_error;
    }

    /**
     * Generated from protobuf field <code>bool is_error = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsError($var)
    {
        GPBUtil::checkBool($var);
        $this->is_error = $var;

        return $this;
    }

}

