// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: contact.proto

package chtype

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Address struct {
	LineOne              string   `protobuf:"bytes,1,opt,name=line_one,json=lineOne,proto3" json:"line_one,omitempty"`
	LineTwo              string   `protobuf:"bytes,2,opt,name=line_two,json=lineTwo,proto3" json:"line_two,omitempty"`
	LineThree            string   `protobuf:"bytes,3,opt,name=line_three,json=lineThree,proto3" json:"line_three,omitempty"`
	Town                 string   `protobuf:"bytes,4,opt,name=town,proto3" json:"town,omitempty"`
	County               string   `protobuf:"bytes,5,opt,name=county,proto3" json:"county,omitempty"`
	Country              string   `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	PostalCode           string   `protobuf:"bytes,7,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Fao                  string   `protobuf:"bytes,8,opt,name=fao,proto3" json:"fao,omitempty"`
	CompanyName          string   `protobuf:"bytes,9,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{0}
}
func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetLineOne() string {
	if m != nil {
		return m.LineOne
	}
	return ""
}

func (m *Address) GetLineTwo() string {
	if m != nil {
		return m.LineTwo
	}
	return ""
}

func (m *Address) GetLineThree() string {
	if m != nil {
		return m.LineThree
	}
	return ""
}

func (m *Address) GetTown() string {
	if m != nil {
		return m.Town
	}
	return ""
}

func (m *Address) GetCounty() string {
	if m != nil {
		return m.County
	}
	return ""
}

func (m *Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Address) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

func (m *Address) GetFao() string {
	if m != nil {
		return m.Fao
	}
	return ""
}

func (m *Address) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

type Company struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Company) Reset()         { *m = Company{} }
func (m *Company) String() string { return proto.CompactTextString(m) }
func (*Company) ProtoMessage()    {}
func (*Company) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{1}
}
func (m *Company) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Company.Unmarshal(m, b)
}
func (m *Company) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Company.Marshal(b, m, deterministic)
}
func (m *Company) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Company.Merge(m, src)
}
func (m *Company) XXX_Size() int {
	return xxx_messageInfo_Company.Size(m)
}
func (m *Company) XXX_DiscardUnknown() {
	xxx_messageInfo_Company.DiscardUnknown(m)
}

var xxx_messageInfo_Company proto.InternalMessageInfo

func (m *Company) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Company) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Company) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type Person struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	FullName             string   `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Language             string   `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{2}
}
func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Person) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Person) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Person) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Person) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func init() {
	proto.RegisterType((*Address)(nil), "chtype.Address")
	golang_proto.RegisterType((*Address)(nil), "chtype.Address")
	proto.RegisterType((*Company)(nil), "chtype.Company")
	golang_proto.RegisterType((*Company)(nil), "chtype.Company")
	proto.RegisterType((*Person)(nil), "chtype.Person")
	golang_proto.RegisterType((*Person)(nil), "chtype.Person")
}

func init() { proto.RegisterFile("contact.proto", fileDescriptor_a5036fff2565fb15) }
func init() { golang_proto.RegisterFile("contact.proto", fileDescriptor_a5036fff2565fb15) }

var fileDescriptor_a5036fff2565fb15 = []byte{
	// 394 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4d, 0x8e, 0xd4, 0x30,
	0x10, 0x85, 0x09, 0x33, 0x9d, 0x9f, 0x6a, 0x90, 0x90, 0x85, 0x90, 0x19, 0xc4, 0x00, 0xbd, 0x82,
	0x05, 0xd3, 0x8b, 0x39, 0x01, 0xcc, 0xbe, 0x41, 0x08, 0xb1, 0x60, 0xd3, 0x72, 0x3b, 0x95, 0x1f,
	0xc9, 0x71, 0x45, 0x8e, 0x43, 0x2b, 0xb7, 0xe3, 0x00, 0x2c, 0xb8, 0x02, 0xe2, 0x16, 0xac, 0x90,
	0xcb, 0x49, 0x03, 0x42, 0x9a, 0x5d, 0xbd, 0xf7, 0xc5, 0x95, 0x57, 0xa5, 0x82, 0xfb, 0x9a, 0xac,
	0x57, 0xda, 0x5f, 0xf5, 0x8e, 0x3c, 0x89, 0x54, 0x37, 0x7e, 0xea, 0xf1, 0xe2, 0x75, 0xdd, 0xfa,
	0x66, 0x3c, 0x5c, 0x69, 0xea, 0xb6, 0x35, 0xd5, 0xb4, 0x65, 0x7c, 0x18, 0x2b, 0x56, 0x2c, 0xb8,
	0x8a, 0xcf, 0x36, 0xbf, 0x12, 0xc8, 0xde, 0x94, 0xa5, 0xc3, 0x61, 0x10, 0x8f, 0x21, 0x37, 0xad,
	0xc5, 0x3d, 0x59, 0x94, 0xc9, 0xf3, 0xe4, 0x65, 0xf1, 0x21, 0x0b, 0xfa, 0x9d, 0xc5, 0x13, 0xf2,
	0x47, 0x92, 0x77, 0xff, 0xa0, 0x8f, 0x47, 0x12, 0x4f, 0x01, 0x22, 0x6a, 0x1c, 0xa2, 0x3c, 0x63,
	0x58, 0x30, 0x0c, 0x86, 0x10, 0x70, 0xee, 0xe9, 0x68, 0xe5, 0x39, 0x03, 0xae, 0xc5, 0x23, 0x48,
	0x35, 0x8d, 0xd6, 0x4f, 0x72, 0xc5, 0xee, 0xac, 0x84, 0x84, 0x8c, 0x2b, 0x37, 0xc9, 0x34, 0xfe,
	0x64, 0x96, 0xe2, 0x19, 0xac, 0x7b, 0x1a, 0xbc, 0x32, 0x7b, 0x4d, 0x25, 0xca, 0x8c, 0x29, 0x44,
	0xeb, 0x86, 0x4a, 0x14, 0x0f, 0xe0, 0xac, 0x52, 0x24, 0x73, 0x06, 0xa1, 0x14, 0x2f, 0xe0, 0x9e,
	0xa6, 0xae, 0x57, 0x76, 0xda, 0x5b, 0xd5, 0xa1, 0x2c, 0x18, 0xad, 0x67, 0x6f, 0xa7, 0x3a, 0xdc,
	0x7c, 0x82, 0xec, 0x26, 0xca, 0x10, 0x93, 0xbf, 0x8a, 0x73, 0x73, 0x2d, 0x1e, 0xc2, 0x0a, 0x3b,
	0xd5, 0x9a, 0x79, 0xe2, 0x28, 0x42, 0xdf, 0xbe, 0x21, 0x8b, 0x7b, 0x3b, 0x76, 0x07, 0x74, 0xf3,
	0xc4, 0x6b, 0xf6, 0x76, 0x6c, 0x6d, 0xbe, 0x25, 0x90, 0xbe, 0x47, 0x37, 0x90, 0x0d, 0x3d, 0x7c,
	0xeb, 0xcd, 0xd2, 0x38, 0x8a, 0xb0, 0xb3, 0xaa, 0x75, 0x83, 0x8f, 0xc9, 0x62, 0xfb, 0x82, 0x9d,
	0x90, 0x4b, 0x3c, 0x81, 0xc2, 0xa8, 0x85, 0xc6, 0xfe, 0x79, 0x30, 0x16, 0x58, 0x8d, 0xc6, 0x44,
	0x18, 0xb7, 0x9a, 0x07, 0x63, 0xf7, 0x4f, 0xe4, 0xd5, 0x6d, 0x91, 0xd3, 0xff, 0x22, 0x8b, 0x0b,
	0xc8, 0x8d, 0xb2, 0xf5, 0xa8, 0xea, 0x65, 0xbb, 0x27, 0xfd, 0xf6, 0xfa, 0xfb, 0x8f, 0xcb, 0x3b,
	0x5f, 0x7f, 0x5e, 0x26, 0x9f, 0x5f, 0xfd, 0x75, 0x5c, 0xba, 0x51, 0xae, 0xc6, 0xa6, 0xfd, 0x82,
	0xdb, 0xe5, 0xaa, 0xc2, 0x8b, 0x6d, 0xbc, 0xc3, 0x43, 0xca, 0xe6, 0xf5, 0xef, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x8f, 0xc1, 0xf0, 0x17, 0xa7, 0x02, 0x00, 0x00,
}
