// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: country_codes.proto

package chtype

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

//ISO 3166 Country Code
type CountryCode int32

const (
	COUNTRY_CODE_INVALID                                      CountryCode = 0
	COUNTRY_CODE_GLOBAL                                       CountryCode = 999
	COUNTRY_CODE_AFGHANISTAN                                  CountryCode = 4
	COUNTRY_CODE_ALAND_ISLANDS                                CountryCode = 248
	COUNTRY_CODE_ALBANIA                                      CountryCode = 8
	COUNTRY_CODE_ALGERIA                                      CountryCode = 12
	COUNTRY_CODE_AMERICAN_SAMOA                               CountryCode = 14
	COUNTRY_CODE_ANDORRA                                      CountryCode = 16
	COUNTRY_CODE_ANGOLA                                       CountryCode = 20
	COUNTRY_CODE_ANGUILLA                                     CountryCode = 660
	COUNTRY_CODE_ANTARCTICA                                   CountryCode = 10
	COUNTRY_CODE_ANTIGUA_AND_BARBUDA                          CountryCode = 28
	COUNTRY_CODE_ARGENTINA                                    CountryCode = 26
	COUNTRY_CODE_ARMENIA                                      CountryCode = 41
	COUNTRY_CODE_ARUBA                                        CountryCode = 533
	COUNTRY_CODE_AUSTRALIA                                    CountryCode = 30
	COUNTRY_CODE_AUSTRIA                                      CountryCode = 32
	COUNTRY_CODE_AZERBAIJAN                                   CountryCode = 25
	COUNTRY_CODE_BAHAMAS                                      CountryCode = 36
	COUNTRY_CODE_BAHRAIN                                      CountryCode = 48
	COUNTRY_CODE_BANGLADESH                                   CountryCode = 40
	COUNTRY_CODE_BARBADOS                                     CountryCode = 42
	COUNTRY_CODE_BELARUS                                      CountryCode = 112
	COUNTRY_CODE_BELGIUM                                      CountryCode = 46
	COUNTRY_CODE_BELIZE                                       CountryCode = 84
	COUNTRY_CODE_BENIN                                        CountryCode = 204
	COUNTRY_CODE_BERMUDA                                      CountryCode = 60
	COUNTRY_CODE_BHUTAN                                       CountryCode = 52
	COUNTRY_CODE_BOLIVIA                                      CountryCode = 68
	COUNTRY_CODE_BONAIRE_SINT_EUSTATIUS_SABA                  CountryCode = 535
	COUNTRY_CODE_BOSNIA_AND_HERZEGOVINA                       CountryCode = 56
	COUNTRY_CODE_BOTSWANA                                     CountryCode = 58
	COUNTRY_CODE_BOUVET_ISLAND                                CountryCode = 74
	COUNTRY_CODE_BRAZIL                                       CountryCode = 62
	COUNTRY_CODE_BRITISH_INDIAN_OCEAN_TERRITORY               CountryCode = 86
	COUNTRY_CODE_BRUNEI_DARUSSALAM                            CountryCode = 96
	COUNTRY_CODE_BULGARIA                                     CountryCode = 100
	COUNTRY_CODE_BURKINA_FASO                                 CountryCode = 854
	COUNTRY_CODE_BURUNDI                                      CountryCode = 108
	COUNTRY_CODE_CAPE_VERDE                                   CountryCode = 132
	COUNTRY_CODE_CAMBODIA                                     CountryCode = 116
	COUNTRY_CODE_CAMEROON                                     CountryCode = 120
	COUNTRY_CODE_CANADA                                       CountryCode = 124
	COUNTRY_CODE_CAYMAN_ISLANDS                               CountryCode = 136
	COUNTRY_CODE_CENTRAL_AFRICAN_REPUBLIC                     CountryCode = 140
	COUNTRY_CODE_CHAD                                         CountryCode = 148
	COUNTRY_CODE_CHILE                                        CountryCode = 152
	COUNTRY_CODE_CHINA                                        CountryCode = 156
	COUNTRY_CODE_CHRISTMAS_ISLAND                             CountryCode = 162
	COUNTRY_CODE_COCOS_ISLANDS                                CountryCode = 166
	COUNTRY_CODE_COLOMBIA                                     CountryCode = 170
	COUNTRY_CODE_COMOROS                                      CountryCode = 174
	COUNTRY_CODE_CONGO                                        CountryCode = 178
	COUNTRY_CODE_CONGO_DEMOCRATIC_REPUBLIC                    CountryCode = 180
	COUNTRY_CODE_COOK_ISLANDS                                 CountryCode = 184
	COUNTRY_CODE_COSTA_RICA                                   CountryCode = 188
	COUNTRY_CODE_COTE_DIVOIRE                                 CountryCode = 384
	COUNTRY_CODE_CROATIA                                      CountryCode = 191
	COUNTRY_CODE_CUBA                                         CountryCode = 192
	COUNTRY_CODE_CURACAO                                      CountryCode = 531
	COUNTRY_CODE_CYPRUS                                       CountryCode = 196
	COUNTRY_CODE_CZECH_REPUBLIC                               CountryCode = 203
	COUNTRY_CODE_DENMARK                                      CountryCode = 208
	COUNTRY_CODE_DJIBOUTI                                     CountryCode = 262
	COUNTRY_CODE_DOMINICA                                     CountryCode = 212
	COUNTRY_CODE_DOMINICAN_REPUBLIC                           CountryCode = 214
	COUNTRY_CODE_ECUADOR                                      CountryCode = 218
	COUNTRY_CODE_EGYPT                                        CountryCode = 818
	COUNTRY_CODE_EL_SALVADOR                                  CountryCode = 222
	COUNTRY_CODE_EQUATORIAL_GUINEA                            CountryCode = 226
	COUNTRY_CODE_ERITREA                                      CountryCode = 232
	COUNTRY_CODE_ESTONIA                                      CountryCode = 233
	COUNTRY_CODE_SWAZILAND                                    CountryCode = 748
	COUNTRY_CODE_ETHIOPIA                                     CountryCode = 231
	COUNTRY_CODE_FALKLAND_ISLANDS                             CountryCode = 238
	COUNTRY_CODE_FAROE_ISLANDS                                CountryCode = 234
	COUNTRY_CODE_FIJI                                         CountryCode = 242
	COUNTRY_CODE_FINLAND                                      CountryCode = 246
	COUNTRY_CODE_FRANCE                                       CountryCode = 250
	COUNTRY_CODE_FRENCH_GUIANA                                CountryCode = 254
	COUNTRY_CODE_FRENCH_POLYNESIA                             CountryCode = 258
	COUNTRY_CODE_FRENCH_SOUTHERN_TERRITORIES                  CountryCode = 260
	COUNTRY_CODE_GABON                                        CountryCode = 266
	COUNTRY_CODE_GAMBIA                                       CountryCode = 270
	COUNTRY_CODE_GEORGIA                                      CountryCode = 268
	COUNTRY_CODE_GERMANY                                      CountryCode = 276
	COUNTRY_CODE_GHANA                                        CountryCode = 288
	COUNTRY_CODE_GIBRALTAR                                    CountryCode = 292
	COUNTRY_CODE_GREECE                                       CountryCode = 300
	COUNTRY_CODE_GREENLAND                                    CountryCode = 304
	COUNTRY_CODE_GRENADA                                      CountryCode = 308
	COUNTRY_CODE_GUADELOUPE                                   CountryCode = 312
	COUNTRY_CODE_GUAM                                         CountryCode = 316
	COUNTRY_CODE_GUATEMALA                                    CountryCode = 320
	COUNTRY_CODE_GUERNSEY                                     CountryCode = 831
	COUNTRY_CODE_GUINEA                                       CountryCode = 324
	COUNTRY_CODE_GUINEA_BISSAU                                CountryCode = 624
	COUNTRY_CODE_GUYANA                                       CountryCode = 328
	COUNTRY_CODE_HAITI                                        CountryCode = 332
	COUNTRY_CODE_HEARD_ISLAND_AND_MCDONALD_ISLANDS            CountryCode = 334
	COUNTRY_CODE_HOLY_SEE                                     CountryCode = 336
	COUNTRY_CODE_HONDURAS                                     CountryCode = 340
	COUNTRY_CODE_HONG_KONG                                    CountryCode = 344
	COUNTRY_CODE_HUNGARY                                      CountryCode = 348
	COUNTRY_CODE_ICELAND                                      CountryCode = 352
	COUNTRY_CODE_INDIA                                        CountryCode = 356
	COUNTRY_CODE_INDONESIA                                    CountryCode = 360
	COUNTRY_CODE_IRAN                                         CountryCode = 364
	COUNTRY_CODE_IRAQ                                         CountryCode = 368
	COUNTRY_CODE_IRELAND                                      CountryCode = 372
	COUNTRY_CODE_ISLE_OF_MAN                                  CountryCode = 833
	COUNTRY_CODE_ISRAEL                                       CountryCode = 376
	COUNTRY_CODE_ITALY                                        CountryCode = 380
	COUNTRY_CODE_JAMAICA                                      CountryCode = 388
	COUNTRY_CODE_JAPAN                                        CountryCode = 392
	COUNTRY_CODE_JERSEY                                       CountryCode = 832
	COUNTRY_CODE_JORDAN                                       CountryCode = 400
	COUNTRY_CODE_KAZAKHSTAN                                   CountryCode = 398
	COUNTRY_CODE_KENYA                                        CountryCode = 404
	COUNTRY_CODE_KIRIBATI                                     CountryCode = 296
	COUNTRY_CODE_KOREA_DEMOCRATIC_PEOPLES_REPUBLIC            CountryCode = 408
	COUNTRY_CODE_KOREA_REPUBLIC                               CountryCode = 410
	COUNTRY_CODE_KUWAIT                                       CountryCode = 414
	COUNTRY_CODE_KYRGYZSTAN                                   CountryCode = 417
	COUNTRY_CODE_LAO_PDR                                      CountryCode = 418
	COUNTRY_CODE_LATVIA                                       CountryCode = 428
	COUNTRY_CODE_LEBANON                                      CountryCode = 422
	COUNTRY_CODE_LESOTHO                                      CountryCode = 426
	COUNTRY_CODE_LIBERIA                                      CountryCode = 430
	COUNTRY_CODE_LIBYA                                        CountryCode = 434
	COUNTRY_CODE_LIECHTENSTEIN                                CountryCode = 438
	COUNTRY_CODE_LITHUANIA                                    CountryCode = 440
	COUNTRY_CODE_LUXEMBOURG                                   CountryCode = 442
	COUNTRY_CODE_MACAO                                        CountryCode = 446
	COUNTRY_CODE_MADAGASCAR                                   CountryCode = 450
	COUNTRY_CODE_MALAWI                                       CountryCode = 454
	COUNTRY_CODE_MALAYSIA                                     CountryCode = 458
	COUNTRY_CODE_MALDIVES                                     CountryCode = 462
	COUNTRY_CODE_MALI                                         CountryCode = 466
	COUNTRY_CODE_MALTA                                        CountryCode = 470
	COUNTRY_CODE_MARSHALL_ISLANDS                             CountryCode = 584
	COUNTRY_CODE_MARTINIQUE                                   CountryCode = 474
	COUNTRY_CODE_MAURITANIA                                   CountryCode = 478
	COUNTRY_CODE_MAURITIUS                                    CountryCode = 480
	COUNTRY_CODE_MAYOTTE                                      CountryCode = 175
	COUNTRY_CODE_MEXICO                                       CountryCode = 484
	COUNTRY_CODE_MICRONESIA                                   CountryCode = 583
	COUNTRY_CODE_MOLDOVA                                      CountryCode = 498
	COUNTRY_CODE_MONACO                                       CountryCode = 492
	COUNTRY_CODE_MONGOLIA                                     CountryCode = 496
	COUNTRY_CODE_MONTENEGRO                                   CountryCode = 499
	COUNTRY_CODE_MONTSERRAT                                   CountryCode = 500
	COUNTRY_CODE_MOROCCO                                      CountryCode = 504
	COUNTRY_CODE_MOZAMBIQUE                                   CountryCode = 508
	COUNTRY_CODE_MYANMAR                                      CountryCode = 104
	COUNTRY_CODE_NAMIBIA                                      CountryCode = 516
	COUNTRY_CODE_NAURU                                        CountryCode = 520
	COUNTRY_CODE_NEPAL                                        CountryCode = 524
	COUNTRY_CODE_NETHERLANDS                                  CountryCode = 528
	COUNTRY_CODE_NEW_CALEDONIA                                CountryCode = 540
	COUNTRY_CODE_NEW_ZEALAND                                  CountryCode = 554
	COUNTRY_CODE_NICARAGUA                                    CountryCode = 558
	COUNTRY_CODE_NIGER                                        CountryCode = 562
	COUNTRY_CODE_NIGERIA                                      CountryCode = 566
	COUNTRY_CODE_NIUE                                         CountryCode = 570
	COUNTRY_CODE_NORFOLK_ISLAND                               CountryCode = 574
	COUNTRY_CODE_MACEDONIA                                    CountryCode = 807
	COUNTRY_CODE_NORTHERN_MARIANA_ISLANDS                     CountryCode = 580
	COUNTRY_CODE_NORWAY                                       CountryCode = 578
	COUNTRY_CODE_OMAN                                         CountryCode = 512
	COUNTRY_CODE_PAKISTAN                                     CountryCode = 586
	COUNTRY_CODE_PALAU                                        CountryCode = 585
	COUNTRY_CODE_PALESTINIAN_TERRITORY                        CountryCode = 275
	COUNTRY_CODE_PANAMA                                       CountryCode = 591
	COUNTRY_CODE_PAPUA_NEW_GUINEA                             CountryCode = 598
	COUNTRY_CODE_PARAGUAY                                     CountryCode = 600
	COUNTRY_CODE_PERU                                         CountryCode = 604
	COUNTRY_CODE_PHILIPPINES                                  CountryCode = 608
	COUNTRY_CODE_PITCAIRN                                     CountryCode = 612
	COUNTRY_CODE_POLAND                                       CountryCode = 616
	COUNTRY_CODE_PORTUGAL                                     CountryCode = 620
	COUNTRY_CODE_PUERTO_RICO                                  CountryCode = 630
	COUNTRY_CODE_QATAR                                        CountryCode = 634
	COUNTRY_CODE_REUNION                                      CountryCode = 638
	COUNTRY_CODE_ROMANIA                                      CountryCode = 642
	COUNTRY_CODE_RUSSIAN_FEDERATION                           CountryCode = 643
	COUNTRY_CODE_RWANDA                                       CountryCode = 646
	COUNTRY_CODE_SAINT_BARTHELEMY                             CountryCode = 652
	COUNTRY_CODE_SAINT_HELENA                                 CountryCode = 654
	COUNTRY_CODE_SAINT_KITTS_AND_NEVIS                        CountryCode = 659
	COUNTRY_CODE_SAINT_LUCIA                                  CountryCode = 662
	COUNTRY_CODE_SAINT_MARTIN                                 CountryCode = 663
	COUNTRY_CODE_SAINT_PIERRE_AND_MIQUELON                    CountryCode = 666
	COUNTRY_CODE_SAINT_VINCENT_AND_GRENADINES                 CountryCode = 670
	COUNTRY_CODE_SAMOA                                        CountryCode = 882
	COUNTRY_CODE_SAN_MARINO                                   CountryCode = 674
	COUNTRY_CODE_SAO_TOME_AND_PRINCIPE                        CountryCode = 678
	COUNTRY_CODE_SAUDI_ARABIA                                 CountryCode = 682
	COUNTRY_CODE_SENEGAL                                      CountryCode = 686
	COUNTRY_CODE_SERBIA                                       CountryCode = 688
	COUNTRY_CODE_SEYCHELLES                                   CountryCode = 690
	COUNTRY_CODE_SIERRA_LEONE                                 CountryCode = 694
	COUNTRY_CODE_SINGAPORE                                    CountryCode = 702
	COUNTRY_CODE_SINT_MAARTEN                                 CountryCode = 534
	COUNTRY_CODE_SLOVAKIA                                     CountryCode = 703
	COUNTRY_CODE_SLOVENIA                                     CountryCode = 705
	COUNTRY_CODE_SOLOMON_ISLANDS                              CountryCode = 90
	COUNTRY_CODE_SOMALIA                                      CountryCode = 706
	COUNTRY_CODE_SOUTH_AFRICA                                 CountryCode = 710
	COUNTRY_CODE_SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS CountryCode = 239
	COUNTRY_CODE_SOUTH_SUDAN                                  CountryCode = 728
	COUNTRY_CODE_SPAIN                                        CountryCode = 724
	COUNTRY_CODE_SRI_LANKA                                    CountryCode = 144
	COUNTRY_CODE_SUDAN                                        CountryCode = 729
	COUNTRY_CODE_SURINAME                                     CountryCode = 740
	COUNTRY_CODE_SVALBARD_AND_JAN_MAYEN_ISLANDS               CountryCode = 744
	COUNTRY_CODE_SWEDEN                                       CountryCode = 752
	COUNTRY_CODE_SWITZERLAND                                  CountryCode = 756
	COUNTRY_CODE_SYRIAN_ARAB_REPUBLIC                         CountryCode = 760
	COUNTRY_CODE_TAIWAN                                       CountryCode = 158
	COUNTRY_CODE_TAJIKISTAN                                   CountryCode = 762
	COUNTRY_CODE_TANZANIA                                     CountryCode = 834
	COUNTRY_CODE_THAILAND                                     CountryCode = 764
	COUNTRY_CODE_TIMOR_LESTE                                  CountryCode = 626
	COUNTRY_CODE_TOGO                                         CountryCode = 768
	COUNTRY_CODE_TOKELAU                                      CountryCode = 772
	COUNTRY_CODE_TONGA                                        CountryCode = 776
	COUNTRY_CODE_TRINIDAD_AND_TOBAGO                          CountryCode = 780
	COUNTRY_CODE_TUNISIA                                      CountryCode = 788
	COUNTRY_CODE_TURKEY                                       CountryCode = 792
	COUNTRY_CODE_TURKMENISTAN                                 CountryCode = 795
	COUNTRY_CODE_TURKS_AND_CAICOS_ISLANDS                     CountryCode = 796
	COUNTRY_CODE_TUVALU                                       CountryCode = 798
	COUNTRY_CODE_UGANDA                                       CountryCode = 800
	COUNTRY_CODE_UKRAINE                                      CountryCode = 804
	COUNTRY_CODE_UNITED_ARAB_EMIRATES                         CountryCode = 784
	COUNTRY_CODE_UNITED_KINGDOM                               CountryCode = 826
	COUNTRY_CODE_UNITED_STATES_MINOR_OUTLYING_ISLANDS         CountryCode = 581
	COUNTRY_CODE_UNITED_STATES_OF_AMERICA                     CountryCode = 840
	COUNTRY_CODE_URUGUAY                                      CountryCode = 858
	COUNTRY_CODE_UZBEKISTAN                                   CountryCode = 860
	COUNTRY_CODE_VANUATU                                      CountryCode = 548
	COUNTRY_CODE_VENEZUELA                                    CountryCode = 862
	COUNTRY_CODE_VIET_NAM                                     CountryCode = 704
	COUNTRY_CODE_BRITISH_VIRGIN_ISLANDS                       CountryCode = 92
	COUNTRY_CODE_VIRGIN_ISLANDS                               CountryCode = 850
	COUNTRY_CODE_WALLIS_AND_FUTUNA_ISLANDS                    CountryCode = 876
	COUNTRY_CODE_WESTERN_SAHARA                               CountryCode = 732
	COUNTRY_CODE_YEMEN                                        CountryCode = 887
	COUNTRY_CODE_ZAMBIA                                       CountryCode = 894
	COUNTRY_CODE_ZIMBABWE                                     CountryCode = 716
)

var CountryCode_name = map[int32]string{
	0:   "COUNTRY_CODE_INVALID",
	999: "COUNTRY_CODE_GLOBAL",
	4:   "COUNTRY_CODE_AFGHANISTAN",
	248: "COUNTRY_CODE_ALAND_ISLANDS",
	8:   "COUNTRY_CODE_ALBANIA",
	12:  "COUNTRY_CODE_ALGERIA",
	14:  "COUNTRY_CODE_AMERICAN_SAMOA",
	16:  "COUNTRY_CODE_ANDORRA",
	20:  "COUNTRY_CODE_ANGOLA",
	660: "COUNTRY_CODE_ANGUILLA",
	10:  "COUNTRY_CODE_ANTARCTICA",
	28:  "COUNTRY_CODE_ANTIGUA_AND_BARBUDA",
	26:  "COUNTRY_CODE_ARGENTINA",
	41:  "COUNTRY_CODE_ARMENIA",
	533: "COUNTRY_CODE_ARUBA",
	30:  "COUNTRY_CODE_AUSTRALIA",
	32:  "COUNTRY_CODE_AUSTRIA",
	25:  "COUNTRY_CODE_AZERBAIJAN",
	36:  "COUNTRY_CODE_BAHAMAS",
	48:  "COUNTRY_CODE_BAHRAIN",
	40:  "COUNTRY_CODE_BANGLADESH",
	42:  "COUNTRY_CODE_BARBADOS",
	112: "COUNTRY_CODE_BELARUS",
	46:  "COUNTRY_CODE_BELGIUM",
	84:  "COUNTRY_CODE_BELIZE",
	204: "COUNTRY_CODE_BENIN",
	60:  "COUNTRY_CODE_BERMUDA",
	52:  "COUNTRY_CODE_BHUTAN",
	68:  "COUNTRY_CODE_BOLIVIA",
	535: "COUNTRY_CODE_BONAIRE_SINT_EUSTATIUS_SABA",
	56:  "COUNTRY_CODE_BOSNIA_AND_HERZEGOVINA",
	58:  "COUNTRY_CODE_BOTSWANA",
	74:  "COUNTRY_CODE_BOUVET_ISLAND",
	62:  "COUNTRY_CODE_BRAZIL",
	86:  "COUNTRY_CODE_BRITISH_INDIAN_OCEAN_TERRITORY",
	96:  "COUNTRY_CODE_BRUNEI_DARUSSALAM",
	100: "COUNTRY_CODE_BULGARIA",
	854: "COUNTRY_CODE_BURKINA_FASO",
	108: "COUNTRY_CODE_BURUNDI",
	132: "COUNTRY_CODE_CAPE_VERDE",
	116: "COUNTRY_CODE_CAMBODIA",
	120: "COUNTRY_CODE_CAMEROON",
	124: "COUNTRY_CODE_CANADA",
	136: "COUNTRY_CODE_CAYMAN_ISLANDS",
	140: "COUNTRY_CODE_CENTRAL_AFRICAN_REPUBLIC",
	148: "COUNTRY_CODE_CHAD",
	152: "COUNTRY_CODE_CHILE",
	156: "COUNTRY_CODE_CHINA",
	162: "COUNTRY_CODE_CHRISTMAS_ISLAND",
	166: "COUNTRY_CODE_COCOS_ISLANDS",
	170: "COUNTRY_CODE_COLOMBIA",
	174: "COUNTRY_CODE_COMOROS",
	178: "COUNTRY_CODE_CONGO",
	180: "COUNTRY_CODE_CONGO_DEMOCRATIC_REPUBLIC",
	184: "COUNTRY_CODE_COOK_ISLANDS",
	188: "COUNTRY_CODE_COSTA_RICA",
	384: "COUNTRY_CODE_COTE_DIVOIRE",
	191: "COUNTRY_CODE_CROATIA",
	192: "COUNTRY_CODE_CUBA",
	531: "COUNTRY_CODE_CURACAO",
	196: "COUNTRY_CODE_CYPRUS",
	203: "COUNTRY_CODE_CZECH_REPUBLIC",
	208: "COUNTRY_CODE_DENMARK",
	262: "COUNTRY_CODE_DJIBOUTI",
	212: "COUNTRY_CODE_DOMINICA",
	214: "COUNTRY_CODE_DOMINICAN_REPUBLIC",
	218: "COUNTRY_CODE_ECUADOR",
	818: "COUNTRY_CODE_EGYPT",
	222: "COUNTRY_CODE_EL_SALVADOR",
	226: "COUNTRY_CODE_EQUATORIAL_GUINEA",
	232: "COUNTRY_CODE_ERITREA",
	233: "COUNTRY_CODE_ESTONIA",
	748: "COUNTRY_CODE_SWAZILAND",
	231: "COUNTRY_CODE_ETHIOPIA",
	238: "COUNTRY_CODE_FALKLAND_ISLANDS",
	234: "COUNTRY_CODE_FAROE_ISLANDS",
	242: "COUNTRY_CODE_FIJI",
	246: "COUNTRY_CODE_FINLAND",
	250: "COUNTRY_CODE_FRANCE",
	254: "COUNTRY_CODE_FRENCH_GUIANA",
	258: "COUNTRY_CODE_FRENCH_POLYNESIA",
	260: "COUNTRY_CODE_FRENCH_SOUTHERN_TERRITORIES",
	266: "COUNTRY_CODE_GABON",
	270: "COUNTRY_CODE_GAMBIA",
	268: "COUNTRY_CODE_GEORGIA",
	276: "COUNTRY_CODE_GERMANY",
	288: "COUNTRY_CODE_GHANA",
	292: "COUNTRY_CODE_GIBRALTAR",
	300: "COUNTRY_CODE_GREECE",
	304: "COUNTRY_CODE_GREENLAND",
	308: "COUNTRY_CODE_GRENADA",
	312: "COUNTRY_CODE_GUADELOUPE",
	316: "COUNTRY_CODE_GUAM",
	320: "COUNTRY_CODE_GUATEMALA",
	831: "COUNTRY_CODE_GUERNSEY",
	324: "COUNTRY_CODE_GUINEA",
	624: "COUNTRY_CODE_GUINEA_BISSAU",
	328: "COUNTRY_CODE_GUYANA",
	332: "COUNTRY_CODE_HAITI",
	334: "COUNTRY_CODE_HEARD_ISLAND_AND_MCDONALD_ISLANDS",
	336: "COUNTRY_CODE_HOLY_SEE",
	340: "COUNTRY_CODE_HONDURAS",
	344: "COUNTRY_CODE_HONG_KONG",
	348: "COUNTRY_CODE_HUNGARY",
	352: "COUNTRY_CODE_ICELAND",
	356: "COUNTRY_CODE_INDIA",
	360: "COUNTRY_CODE_INDONESIA",
	364: "COUNTRY_CODE_IRAN",
	368: "COUNTRY_CODE_IRAQ",
	372: "COUNTRY_CODE_IRELAND",
	833: "COUNTRY_CODE_ISLE_OF_MAN",
	376: "COUNTRY_CODE_ISRAEL",
	380: "COUNTRY_CODE_ITALY",
	388: "COUNTRY_CODE_JAMAICA",
	392: "COUNTRY_CODE_JAPAN",
	832: "COUNTRY_CODE_JERSEY",
	400: "COUNTRY_CODE_JORDAN",
	398: "COUNTRY_CODE_KAZAKHSTAN",
	404: "COUNTRY_CODE_KENYA",
	296: "COUNTRY_CODE_KIRIBATI",
	408: "COUNTRY_CODE_KOREA_DEMOCRATIC_PEOPLES_REPUBLIC",
	410: "COUNTRY_CODE_KOREA_REPUBLIC",
	414: "COUNTRY_CODE_KUWAIT",
	417: "COUNTRY_CODE_KYRGYZSTAN",
	418: "COUNTRY_CODE_LAO_PDR",
	428: "COUNTRY_CODE_LATVIA",
	422: "COUNTRY_CODE_LEBANON",
	426: "COUNTRY_CODE_LESOTHO",
	430: "COUNTRY_CODE_LIBERIA",
	434: "COUNTRY_CODE_LIBYA",
	438: "COUNTRY_CODE_LIECHTENSTEIN",
	440: "COUNTRY_CODE_LITHUANIA",
	442: "COUNTRY_CODE_LUXEMBOURG",
	446: "COUNTRY_CODE_MACAO",
	450: "COUNTRY_CODE_MADAGASCAR",
	454: "COUNTRY_CODE_MALAWI",
	458: "COUNTRY_CODE_MALAYSIA",
	462: "COUNTRY_CODE_MALDIVES",
	466: "COUNTRY_CODE_MALI",
	470: "COUNTRY_CODE_MALTA",
	584: "COUNTRY_CODE_MARSHALL_ISLANDS",
	474: "COUNTRY_CODE_MARTINIQUE",
	478: "COUNTRY_CODE_MAURITANIA",
	480: "COUNTRY_CODE_MAURITIUS",
	175: "COUNTRY_CODE_MAYOTTE",
	484: "COUNTRY_CODE_MEXICO",
	583: "COUNTRY_CODE_MICRONESIA",
	498: "COUNTRY_CODE_MOLDOVA",
	492: "COUNTRY_CODE_MONACO",
	496: "COUNTRY_CODE_MONGOLIA",
	499: "COUNTRY_CODE_MONTENEGRO",
	500: "COUNTRY_CODE_MONTSERRAT",
	504: "COUNTRY_CODE_MOROCCO",
	508: "COUNTRY_CODE_MOZAMBIQUE",
	104: "COUNTRY_CODE_MYANMAR",
	516: "COUNTRY_CODE_NAMIBIA",
	520: "COUNTRY_CODE_NAURU",
	524: "COUNTRY_CODE_NEPAL",
	528: "COUNTRY_CODE_NETHERLANDS",
	540: "COUNTRY_CODE_NEW_CALEDONIA",
	554: "COUNTRY_CODE_NEW_ZEALAND",
	558: "COUNTRY_CODE_NICARAGUA",
	562: "COUNTRY_CODE_NIGER",
	566: "COUNTRY_CODE_NIGERIA",
	570: "COUNTRY_CODE_NIUE",
	574: "COUNTRY_CODE_NORFOLK_ISLAND",
	807: "COUNTRY_CODE_MACEDONIA",
	580: "COUNTRY_CODE_NORTHERN_MARIANA_ISLANDS",
	578: "COUNTRY_CODE_NORWAY",
	512: "COUNTRY_CODE_OMAN",
	586: "COUNTRY_CODE_PAKISTAN",
	585: "COUNTRY_CODE_PALAU",
	275: "COUNTRY_CODE_PALESTINIAN_TERRITORY",
	591: "COUNTRY_CODE_PANAMA",
	598: "COUNTRY_CODE_PAPUA_NEW_GUINEA",
	600: "COUNTRY_CODE_PARAGUAY",
	604: "COUNTRY_CODE_PERU",
	608: "COUNTRY_CODE_PHILIPPINES",
	612: "COUNTRY_CODE_PITCAIRN",
	616: "COUNTRY_CODE_POLAND",
	620: "COUNTRY_CODE_PORTUGAL",
	630: "COUNTRY_CODE_PUERTO_RICO",
	634: "COUNTRY_CODE_QATAR",
	638: "COUNTRY_CODE_REUNION",
	642: "COUNTRY_CODE_ROMANIA",
	643: "COUNTRY_CODE_RUSSIAN_FEDERATION",
	646: "COUNTRY_CODE_RWANDA",
	652: "COUNTRY_CODE_SAINT_BARTHELEMY",
	654: "COUNTRY_CODE_SAINT_HELENA",
	659: "COUNTRY_CODE_SAINT_KITTS_AND_NEVIS",
	662: "COUNTRY_CODE_SAINT_LUCIA",
	663: "COUNTRY_CODE_SAINT_MARTIN",
	666: "COUNTRY_CODE_SAINT_PIERRE_AND_MIQUELON",
	670: "COUNTRY_CODE_SAINT_VINCENT_AND_GRENADINES",
	882: "COUNTRY_CODE_SAMOA",
	674: "COUNTRY_CODE_SAN_MARINO",
	678: "COUNTRY_CODE_SAO_TOME_AND_PRINCIPE",
	682: "COUNTRY_CODE_SAUDI_ARABIA",
	686: "COUNTRY_CODE_SENEGAL",
	688: "COUNTRY_CODE_SERBIA",
	690: "COUNTRY_CODE_SEYCHELLES",
	694: "COUNTRY_CODE_SIERRA_LEONE",
	702: "COUNTRY_CODE_SINGAPORE",
	534: "COUNTRY_CODE_SINT_MAARTEN",
	703: "COUNTRY_CODE_SLOVAKIA",
	705: "COUNTRY_CODE_SLOVENIA",
	90:  "COUNTRY_CODE_SOLOMON_ISLANDS",
	706: "COUNTRY_CODE_SOMALIA",
	710: "COUNTRY_CODE_SOUTH_AFRICA",
	239: "COUNTRY_CODE_SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS",
	728: "COUNTRY_CODE_SOUTH_SUDAN",
	724: "COUNTRY_CODE_SPAIN",
	144: "COUNTRY_CODE_SRI_LANKA",
	729: "COUNTRY_CODE_SUDAN",
	740: "COUNTRY_CODE_SURINAME",
	744: "COUNTRY_CODE_SVALBARD_AND_JAN_MAYEN_ISLANDS",
	752: "COUNTRY_CODE_SWEDEN",
	756: "COUNTRY_CODE_SWITZERLAND",
	760: "COUNTRY_CODE_SYRIAN_ARAB_REPUBLIC",
	158: "COUNTRY_CODE_TAIWAN",
	762: "COUNTRY_CODE_TAJIKISTAN",
	834: "COUNTRY_CODE_TANZANIA",
	764: "COUNTRY_CODE_THAILAND",
	626: "COUNTRY_CODE_TIMOR_LESTE",
	768: "COUNTRY_CODE_TOGO",
	772: "COUNTRY_CODE_TOKELAU",
	776: "COUNTRY_CODE_TONGA",
	780: "COUNTRY_CODE_TRINIDAD_AND_TOBAGO",
	788: "COUNTRY_CODE_TUNISIA",
	792: "COUNTRY_CODE_TURKEY",
	795: "COUNTRY_CODE_TURKMENISTAN",
	796: "COUNTRY_CODE_TURKS_AND_CAICOS_ISLANDS",
	798: "COUNTRY_CODE_TUVALU",
	800: "COUNTRY_CODE_UGANDA",
	804: "COUNTRY_CODE_UKRAINE",
	784: "COUNTRY_CODE_UNITED_ARAB_EMIRATES",
	826: "COUNTRY_CODE_UNITED_KINGDOM",
	581: "COUNTRY_CODE_UNITED_STATES_MINOR_OUTLYING_ISLANDS",
	840: "COUNTRY_CODE_UNITED_STATES_OF_AMERICA",
	858: "COUNTRY_CODE_URUGUAY",
	860: "COUNTRY_CODE_UZBEKISTAN",
	548: "COUNTRY_CODE_VANUATU",
	862: "COUNTRY_CODE_VENEZUELA",
	704: "COUNTRY_CODE_VIET_NAM",
	92:  "COUNTRY_CODE_BRITISH_VIRGIN_ISLANDS",
	850: "COUNTRY_CODE_VIRGIN_ISLANDS",
	876: "COUNTRY_CODE_WALLIS_AND_FUTUNA_ISLANDS",
	732: "COUNTRY_CODE_WESTERN_SAHARA",
	887: "COUNTRY_CODE_YEMEN",
	894: "COUNTRY_CODE_ZAMBIA",
	716: "COUNTRY_CODE_ZIMBABWE",
}

var CountryCode_value = map[string]int32{
	"COUNTRY_CODE_INVALID":                                      0,
	"COUNTRY_CODE_GLOBAL":                                       999,
	"COUNTRY_CODE_AFGHANISTAN":                                  4,
	"COUNTRY_CODE_ALAND_ISLANDS":                                248,
	"COUNTRY_CODE_ALBANIA":                                      8,
	"COUNTRY_CODE_ALGERIA":                                      12,
	"COUNTRY_CODE_AMERICAN_SAMOA":                               14,
	"COUNTRY_CODE_ANDORRA":                                      16,
	"COUNTRY_CODE_ANGOLA":                                       20,
	"COUNTRY_CODE_ANGUILLA":                                     660,
	"COUNTRY_CODE_ANTARCTICA":                                   10,
	"COUNTRY_CODE_ANTIGUA_AND_BARBUDA":                          28,
	"COUNTRY_CODE_ARGENTINA":                                    26,
	"COUNTRY_CODE_ARMENIA":                                      41,
	"COUNTRY_CODE_ARUBA":                                        533,
	"COUNTRY_CODE_AUSTRALIA":                                    30,
	"COUNTRY_CODE_AUSTRIA":                                      32,
	"COUNTRY_CODE_AZERBAIJAN":                                   25,
	"COUNTRY_CODE_BAHAMAS":                                      36,
	"COUNTRY_CODE_BAHRAIN":                                      48,
	"COUNTRY_CODE_BANGLADESH":                                   40,
	"COUNTRY_CODE_BARBADOS":                                     42,
	"COUNTRY_CODE_BELARUS":                                      112,
	"COUNTRY_CODE_BELGIUM":                                      46,
	"COUNTRY_CODE_BELIZE":                                       84,
	"COUNTRY_CODE_BENIN":                                        204,
	"COUNTRY_CODE_BERMUDA":                                      60,
	"COUNTRY_CODE_BHUTAN":                                       52,
	"COUNTRY_CODE_BOLIVIA":                                      68,
	"COUNTRY_CODE_BONAIRE_SINT_EUSTATIUS_SABA":                  535,
	"COUNTRY_CODE_BOSNIA_AND_HERZEGOVINA":                       56,
	"COUNTRY_CODE_BOTSWANA":                                     58,
	"COUNTRY_CODE_BOUVET_ISLAND":                                74,
	"COUNTRY_CODE_BRAZIL":                                       62,
	"COUNTRY_CODE_BRITISH_INDIAN_OCEAN_TERRITORY":               86,
	"COUNTRY_CODE_BRUNEI_DARUSSALAM":                            96,
	"COUNTRY_CODE_BULGARIA":                                     100,
	"COUNTRY_CODE_BURKINA_FASO":                                 854,
	"COUNTRY_CODE_BURUNDI":                                      108,
	"COUNTRY_CODE_CAPE_VERDE":                                   132,
	"COUNTRY_CODE_CAMBODIA":                                     116,
	"COUNTRY_CODE_CAMEROON":                                     120,
	"COUNTRY_CODE_CANADA":                                       124,
	"COUNTRY_CODE_CAYMAN_ISLANDS":                               136,
	"COUNTRY_CODE_CENTRAL_AFRICAN_REPUBLIC":                     140,
	"COUNTRY_CODE_CHAD":                                         148,
	"COUNTRY_CODE_CHILE":                                        152,
	"COUNTRY_CODE_CHINA":                                        156,
	"COUNTRY_CODE_CHRISTMAS_ISLAND":                             162,
	"COUNTRY_CODE_COCOS_ISLANDS":                                166,
	"COUNTRY_CODE_COLOMBIA":                                     170,
	"COUNTRY_CODE_COMOROS":                                      174,
	"COUNTRY_CODE_CONGO":                                        178,
	"COUNTRY_CODE_CONGO_DEMOCRATIC_REPUBLIC":                    180,
	"COUNTRY_CODE_COOK_ISLANDS":                                 184,
	"COUNTRY_CODE_COSTA_RICA":                                   188,
	"COUNTRY_CODE_COTE_DIVOIRE":                                 384,
	"COUNTRY_CODE_CROATIA":                                      191,
	"COUNTRY_CODE_CUBA":                                         192,
	"COUNTRY_CODE_CURACAO":                                      531,
	"COUNTRY_CODE_CYPRUS":                                       196,
	"COUNTRY_CODE_CZECH_REPUBLIC":                               203,
	"COUNTRY_CODE_DENMARK":                                      208,
	"COUNTRY_CODE_DJIBOUTI":                                     262,
	"COUNTRY_CODE_DOMINICA":                                     212,
	"COUNTRY_CODE_DOMINICAN_REPUBLIC":                           214,
	"COUNTRY_CODE_ECUADOR":                                      218,
	"COUNTRY_CODE_EGYPT":                                        818,
	"COUNTRY_CODE_EL_SALVADOR":                                  222,
	"COUNTRY_CODE_EQUATORIAL_GUINEA":                            226,
	"COUNTRY_CODE_ERITREA":                                      232,
	"COUNTRY_CODE_ESTONIA":                                      233,
	"COUNTRY_CODE_SWAZILAND":                                    748,
	"COUNTRY_CODE_ETHIOPIA":                                     231,
	"COUNTRY_CODE_FALKLAND_ISLANDS":                             238,
	"COUNTRY_CODE_FAROE_ISLANDS":                                234,
	"COUNTRY_CODE_FIJI":                                         242,
	"COUNTRY_CODE_FINLAND":                                      246,
	"COUNTRY_CODE_FRANCE":                                       250,
	"COUNTRY_CODE_FRENCH_GUIANA":                                254,
	"COUNTRY_CODE_FRENCH_POLYNESIA":                             258,
	"COUNTRY_CODE_FRENCH_SOUTHERN_TERRITORIES":                  260,
	"COUNTRY_CODE_GABON":                                        266,
	"COUNTRY_CODE_GAMBIA":                                       270,
	"COUNTRY_CODE_GEORGIA":                                      268,
	"COUNTRY_CODE_GERMANY":                                      276,
	"COUNTRY_CODE_GHANA":                                        288,
	"COUNTRY_CODE_GIBRALTAR":                                    292,
	"COUNTRY_CODE_GREECE":                                       300,
	"COUNTRY_CODE_GREENLAND":                                    304,
	"COUNTRY_CODE_GRENADA":                                      308,
	"COUNTRY_CODE_GUADELOUPE":                                   312,
	"COUNTRY_CODE_GUAM":                                         316,
	"COUNTRY_CODE_GUATEMALA":                                    320,
	"COUNTRY_CODE_GUERNSEY":                                     831,
	"COUNTRY_CODE_GUINEA":                                       324,
	"COUNTRY_CODE_GUINEA_BISSAU":                                624,
	"COUNTRY_CODE_GUYANA":                                       328,
	"COUNTRY_CODE_HAITI":                                        332,
	"COUNTRY_CODE_HEARD_ISLAND_AND_MCDONALD_ISLANDS":            334,
	"COUNTRY_CODE_HOLY_SEE":                                     336,
	"COUNTRY_CODE_HONDURAS":                                     340,
	"COUNTRY_CODE_HONG_KONG":                                    344,
	"COUNTRY_CODE_HUNGARY":                                      348,
	"COUNTRY_CODE_ICELAND":                                      352,
	"COUNTRY_CODE_INDIA":                                        356,
	"COUNTRY_CODE_INDONESIA":                                    360,
	"COUNTRY_CODE_IRAN":                                         364,
	"COUNTRY_CODE_IRAQ":                                         368,
	"COUNTRY_CODE_IRELAND":                                      372,
	"COUNTRY_CODE_ISLE_OF_MAN":                                  833,
	"COUNTRY_CODE_ISRAEL":                                       376,
	"COUNTRY_CODE_ITALY":                                        380,
	"COUNTRY_CODE_JAMAICA":                                      388,
	"COUNTRY_CODE_JAPAN":                                        392,
	"COUNTRY_CODE_JERSEY":                                       832,
	"COUNTRY_CODE_JORDAN":                                       400,
	"COUNTRY_CODE_KAZAKHSTAN":                                   398,
	"COUNTRY_CODE_KENYA":                                        404,
	"COUNTRY_CODE_KIRIBATI":                                     296,
	"COUNTRY_CODE_KOREA_DEMOCRATIC_PEOPLES_REPUBLIC":            408,
	"COUNTRY_CODE_KOREA_REPUBLIC":                               410,
	"COUNTRY_CODE_KUWAIT":                                       414,
	"COUNTRY_CODE_KYRGYZSTAN":                                   417,
	"COUNTRY_CODE_LAO_PDR":                                      418,
	"COUNTRY_CODE_LATVIA":                                       428,
	"COUNTRY_CODE_LEBANON":                                      422,
	"COUNTRY_CODE_LESOTHO":                                      426,
	"COUNTRY_CODE_LIBERIA":                                      430,
	"COUNTRY_CODE_LIBYA":                                        434,
	"COUNTRY_CODE_LIECHTENSTEIN":                                438,
	"COUNTRY_CODE_LITHUANIA":                                    440,
	"COUNTRY_CODE_LUXEMBOURG":                                   442,
	"COUNTRY_CODE_MACAO":                                        446,
	"COUNTRY_CODE_MADAGASCAR":                                   450,
	"COUNTRY_CODE_MALAWI":                                       454,
	"COUNTRY_CODE_MALAYSIA":                                     458,
	"COUNTRY_CODE_MALDIVES":                                     462,
	"COUNTRY_CODE_MALI":                                         466,
	"COUNTRY_CODE_MALTA":                                        470,
	"COUNTRY_CODE_MARSHALL_ISLANDS":                             584,
	"COUNTRY_CODE_MARTINIQUE":                                   474,
	"COUNTRY_CODE_MAURITANIA":                                   478,
	"COUNTRY_CODE_MAURITIUS":                                    480,
	"COUNTRY_CODE_MAYOTTE":                                      175,
	"COUNTRY_CODE_MEXICO":                                       484,
	"COUNTRY_CODE_MICRONESIA":                                   583,
	"COUNTRY_CODE_MOLDOVA":                                      498,
	"COUNTRY_CODE_MONACO":                                       492,
	"COUNTRY_CODE_MONGOLIA":                                     496,
	"COUNTRY_CODE_MONTENEGRO":                                   499,
	"COUNTRY_CODE_MONTSERRAT":                                   500,
	"COUNTRY_CODE_MOROCCO":                                      504,
	"COUNTRY_CODE_MOZAMBIQUE":                                   508,
	"COUNTRY_CODE_MYANMAR":                                      104,
	"COUNTRY_CODE_NAMIBIA":                                      516,
	"COUNTRY_CODE_NAURU":                                        520,
	"COUNTRY_CODE_NEPAL":                                        524,
	"COUNTRY_CODE_NETHERLANDS":                                  528,
	"COUNTRY_CODE_NEW_CALEDONIA":                                540,
	"COUNTRY_CODE_NEW_ZEALAND":                                  554,
	"COUNTRY_CODE_NICARAGUA":                                    558,
	"COUNTRY_CODE_NIGER":                                        562,
	"COUNTRY_CODE_NIGERIA":                                      566,
	"COUNTRY_CODE_NIUE":                                         570,
	"COUNTRY_CODE_NORFOLK_ISLAND":                               574,
	"COUNTRY_CODE_MACEDONIA":                                    807,
	"COUNTRY_CODE_NORTHERN_MARIANA_ISLANDS":                     580,
	"COUNTRY_CODE_NORWAY":                                       578,
	"COUNTRY_CODE_OMAN":                                         512,
	"COUNTRY_CODE_PAKISTAN":                                     586,
	"COUNTRY_CODE_PALAU":                                        585,
	"COUNTRY_CODE_PALESTINIAN_TERRITORY":                        275,
	"COUNTRY_CODE_PANAMA":                                       591,
	"COUNTRY_CODE_PAPUA_NEW_GUINEA":                             598,
	"COUNTRY_CODE_PARAGUAY":                                     600,
	"COUNTRY_CODE_PERU":                                         604,
	"COUNTRY_CODE_PHILIPPINES":                                  608,
	"COUNTRY_CODE_PITCAIRN":                                     612,
	"COUNTRY_CODE_POLAND":                                       616,
	"COUNTRY_CODE_PORTUGAL":                                     620,
	"COUNTRY_CODE_PUERTO_RICO":                                  630,
	"COUNTRY_CODE_QATAR":                                        634,
	"COUNTRY_CODE_REUNION":                                      638,
	"COUNTRY_CODE_ROMANIA":                                      642,
	"COUNTRY_CODE_RUSSIAN_FEDERATION":                           643,
	"COUNTRY_CODE_RWANDA":                                       646,
	"COUNTRY_CODE_SAINT_BARTHELEMY":                             652,
	"COUNTRY_CODE_SAINT_HELENA":                                 654,
	"COUNTRY_CODE_SAINT_KITTS_AND_NEVIS":                        659,
	"COUNTRY_CODE_SAINT_LUCIA":                                  662,
	"COUNTRY_CODE_SAINT_MARTIN":                                 663,
	"COUNTRY_CODE_SAINT_PIERRE_AND_MIQUELON":                    666,
	"COUNTRY_CODE_SAINT_VINCENT_AND_GRENADINES":                 670,
	"COUNTRY_CODE_SAMOA":                                        882,
	"COUNTRY_CODE_SAN_MARINO":                                   674,
	"COUNTRY_CODE_SAO_TOME_AND_PRINCIPE":                        678,
	"COUNTRY_CODE_SAUDI_ARABIA":                                 682,
	"COUNTRY_CODE_SENEGAL":                                      686,
	"COUNTRY_CODE_SERBIA":                                       688,
	"COUNTRY_CODE_SEYCHELLES":                                   690,
	"COUNTRY_CODE_SIERRA_LEONE":                                 694,
	"COUNTRY_CODE_SINGAPORE":                                    702,
	"COUNTRY_CODE_SINT_MAARTEN":                                 534,
	"COUNTRY_CODE_SLOVAKIA":                                     703,
	"COUNTRY_CODE_SLOVENIA":                                     705,
	"COUNTRY_CODE_SOLOMON_ISLANDS":                              90,
	"COUNTRY_CODE_SOMALIA":                                      706,
	"COUNTRY_CODE_SOUTH_AFRICA":                                 710,
	"COUNTRY_CODE_SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS": 239,
	"COUNTRY_CODE_SOUTH_SUDAN":                                  728,
	"COUNTRY_CODE_SPAIN":                                        724,
	"COUNTRY_CODE_SRI_LANKA":                                    144,
	"COUNTRY_CODE_SUDAN":                                        729,
	"COUNTRY_CODE_SURINAME":                                     740,
	"COUNTRY_CODE_SVALBARD_AND_JAN_MAYEN_ISLANDS":               744,
	"COUNTRY_CODE_SWEDEN":                                       752,
	"COUNTRY_CODE_SWITZERLAND":                                  756,
	"COUNTRY_CODE_SYRIAN_ARAB_REPUBLIC":                         760,
	"COUNTRY_CODE_TAIWAN":                                       158,
	"COUNTRY_CODE_TAJIKISTAN":                                   762,
	"COUNTRY_CODE_TANZANIA":                                     834,
	"COUNTRY_CODE_THAILAND":                                     764,
	"COUNTRY_CODE_TIMOR_LESTE":                                  626,
	"COUNTRY_CODE_TOGO":                                         768,
	"COUNTRY_CODE_TOKELAU":                                      772,
	"COUNTRY_CODE_TONGA":                                        776,
	"COUNTRY_CODE_TRINIDAD_AND_TOBAGO":                          780,
	"COUNTRY_CODE_TUNISIA":                                      788,
	"COUNTRY_CODE_TURKEY":                                       792,
	"COUNTRY_CODE_TURKMENISTAN":                                 795,
	"COUNTRY_CODE_TURKS_AND_CAICOS_ISLANDS":                     796,
	"COUNTRY_CODE_TUVALU":                                       798,
	"COUNTRY_CODE_UGANDA":                                       800,
	"COUNTRY_CODE_UKRAINE":                                      804,
	"COUNTRY_CODE_UNITED_ARAB_EMIRATES":                         784,
	"COUNTRY_CODE_UNITED_KINGDOM":                               826,
	"COUNTRY_CODE_UNITED_STATES_MINOR_OUTLYING_ISLANDS":         581,
	"COUNTRY_CODE_UNITED_STATES_OF_AMERICA":                     840,
	"COUNTRY_CODE_URUGUAY":                                      858,
	"COUNTRY_CODE_UZBEKISTAN":                                   860,
	"COUNTRY_CODE_VANUATU":                                      548,
	"COUNTRY_CODE_VENEZUELA":                                    862,
	"COUNTRY_CODE_VIET_NAM":                                     704,
	"COUNTRY_CODE_BRITISH_VIRGIN_ISLANDS":                       92,
	"COUNTRY_CODE_VIRGIN_ISLANDS":                               850,
	"COUNTRY_CODE_WALLIS_AND_FUTUNA_ISLANDS":                    876,
	"COUNTRY_CODE_WESTERN_SAHARA":                               732,
	"COUNTRY_CODE_YEMEN":                                        887,
	"COUNTRY_CODE_ZAMBIA":                                       894,
	"COUNTRY_CODE_ZIMBABWE":                                     716,
}

func (x CountryCode) String() string {
	return proto.EnumName(CountryCode_name, int32(x))
}

func (CountryCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb83ccbc9827a888, []int{0}
}

func init() {
	proto.RegisterEnum("chtype.CountryCode", CountryCode_name, CountryCode_value)
	golang_proto.RegisterEnum("chtype.CountryCode", CountryCode_name, CountryCode_value)
}

func init() { proto.RegisterFile("country_codes.proto", fileDescriptor_bb83ccbc9827a888) }
func init() { golang_proto.RegisterFile("country_codes.proto", fileDescriptor_bb83ccbc9827a888) }

var fileDescriptor_bb83ccbc9827a888 = []byte{
	// 2696 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x59, 0x7d, 0xa8, 0x5d, 0x55,
	0x76, 0xf7, 0xbe, 0x77, 0xef, 0x6d, 0xb9, 0x2d, 0x65, 0xf5, 0x68, 0xfd, 0x88, 0x31, 0xa6, 0x7e,
	0x7f, 0x60, 0x62, 0xb1, 0x94, 0x56, 0x8a, 0xb0, 0xee, 0x39, 0xeb, 0x9d, 0xbb, 0xde, 0xdd, 0x67,
	0xef, 0x9b, 0x7d, 0xf6, 0xbe, 0xcf, 0x7b, 0x29, 0x9c, 0x6a, 0x4c, 0x13, 0xc1, 0xfa, 0xc4, 0xc6,
	0x52, 0xa1, 0x7f, 0x48, 0x1b, 0x24, 0x94, 0x20, 0x01, 0x53, 0x15, 0x2b, 0xc1, 0x8a, 0xd8, 0x22,
	0x92, 0x91, 0x20, 0x22, 0x22, 0x1a, 0x83, 0xe3, 0x38, 0x8e, 0x38, 0x22, 0x12, 0x1c, 0x09, 0xe2,
	0xcc, 0x64, 0x30, 0x33, 0x84, 0x99, 0x90, 0x11, 0x27, 0x88, 0xc8, 0xb0, 0xcf, 0x79, 0x79, 0x2f,
	0xef, 0xae, 0x3d, 0x7f, 0x25, 0xef, 0xfe, 0xf6, 0xda, 0xeb, 0xe3, 0xb7, 0xf6, 0x5a, 0x6b, 0xef,
	0xd3, 0xbb, 0x70, 0xfb, 0xf2, 0x43, 0xf7, 0xef, 0x7e, 0xf0, 0xe1, 0x6a, 0xfb, 0xf2, 0x3d, 0x3b,
	0xfe, 0x65, 0xcb, 0x03, 0x0f, 0x2e, 0xef, 0x5e, 0x4e, 0xba, 0xdb, 0x77, 0xed, 0x7e, 0xf8, 0x81,
	0x1d, 0x1b, 0x6e, 0xd9, 0x79, 0xef, 0xee, 0x5d, 0x0f, 0xdd, 0xbd, 0x65, 0xfb, 0xf2, 0x3f, 0x6f,
	0xdd, 0xb9, 0xbc, 0x73, 0x79, 0x6b, 0x0d, 0xdf, 0xfd, 0xd0, 0x3f, 0xd5, 0x7f, 0xd5, 0x7f, 0xd4,
	0xff, 0x6b, 0xc4, 0x6e, 0xfa, 0xc5, 0xed, 0xbd, 0x3f, 0x49, 0x9b, 0xed, 0xd2, 0xe5, 0x7b, 0x76,
	0x24, 0x97, 0xf6, 0x2e, 0x4a, 0x8d, 0xd7, 0xce, 0x4e, 0xaa, 0xd4, 0x64, 0x54, 0xb1, 0x1e, 0xa3,
	0xe2, 0x0c, 0x2e, 0x48, 0x2e, 0xed, 0x5d, 0xb8, 0x0e, 0xc9, 0x95, 0xe9, 0xa3, 0x82, 0x2f, 0xff,
	0x28, 0xd9, 0xd8, 0xbb, 0x74, 0x1d, 0x82, 0x0b, 0xf9, 0x00, 0x35, 0x97, 0x0e, 0x35, 0xb4, 0x93,
	0x2b, 0x7b, 0x1b, 0xd6, 0xa3, 0x0a, 0x75, 0x56, 0x71, 0x19, 0xfe, 0x29, 0xe1, 0x6c, 0x4b, 0xa8,
	0x44, 0xd5, 0x47, 0xcd, 0x08, 0x7f, 0x1c, 0x41, 0x72, 0xb2, 0x8c, 0xf0, 0xa7, 0xc9, 0x95, 0xbd,
	0xcb, 0xd7, 0x23, 0x05, 0x59, 0x4e, 0x51, 0x57, 0x25, 0x16, 0x06, 0xe1, 0xcf, 0xa4, 0xa8, 0xce,
	0x8c, 0xb5, 0x08, 0x90, 0x5c, 0x32, 0xe3, 0x07, 0xea, 0xdc, 0x28, 0x84, 0x8b, 0x92, 0x0d, 0xbd,
	0xbf, 0x98, 0x05, 0x3c, 0x2b, 0x85, 0x70, 0xa0, 0x93, 0x5c, 0xde, 0xbb, 0x64, 0x06, 0x73, 0x68,
	0x53, 0xc7, 0x29, 0x42, 0x2f, 0xb9, 0xa6, 0xb7, 0x79, 0x16, 0xe4, 0xdc, 0x63, 0xd0, 0x59, 0xf5,
	0xd1, 0xf6, 0x7d, 0x86, 0xb0, 0x31, 0xd9, 0xd0, 0xbb, 0x78, 0xfd, 0x2a, 0x9b, 0x93, 0x76, 0xac,
	0x11, 0x36, 0x48, 0x6b, 0x6d, 0x41, 0x21, 0x04, 0x37, 0x26, 0x97, 0xf4, 0x92, 0x19, 0xc4, 0xf7,
	0x11, 0xfe, 0xbb, 0x2d, 0xb7, 0xf3, 0xa5, 0xb3, 0xa8, 0x18, 0x61, 0x93, 0xdc, 0x2e, 0x60, 0x8c,
	0xb0, 0x59, 0xfa, 0x31, 0x25, 0xdb, 0x47, 0x5e, 0x44, 0x0d, 0x97, 0x09, 0xb1, 0x3e, 0x0e, 0xb0,
	0xc0, 0x12, 0xae, 0x89, 0x21, 0x16, 0x59, 0xc3, 0xad, 0x62, 0xc3, 0x3e, 0xea, 0x5c, 0x61, 0x46,
	0xe5, 0x00, 0x6e, 0x48, 0x2e, 0x9b, 0x89, 0x68, 0x08, 0x06, 0x66, 0xa6, 0x84, 0x9b, 0xe4, 0x8e,
	0xa4, 0xd0, 0xfa, 0x12, 0x1e, 0x88, 0x21, 0x39, 0xfb, 0x02, 0xb6, 0x08, 0xe6, 0xfa, 0xa4, 0x78,
	0x4a, 0xe0, 0x44, 0x90, 0xfa, 0xa4, 0x59, 0xc3, 0x07, 0xad, 0xc8, 0x5e, 0xb6, 0x08, 0x6c, 0xfc,
	0xbd, 0xdc, 0x6b, 0xe0, 0x43, 0xba, 0xfe, 0xb5, 0x14, 0x31, 0x8a, 0xc7, 0x8c, 0x90, 0x25, 0xb7,
	0xf4, 0x6e, 0x98, 0x41, 0x34, 0xb2, 0xa5, 0xaa, 0x64, 0xed, 0x2a, 0xf2, 0xa5, 0x43, 0xc7, 0xbe,
	0xac, 0x4a, 0xec, 0x23, 0x3c, 0xd9, 0x4e, 0xae, 0xef, 0x5d, 0x3d, 0xb3, 0xbc, 0xd4, 0xdc, 0x24,
	0xc5, 0x80, 0xec, 0x94, 0x72, 0x33, 0x0e, 0xe4, 0xff, 0xad, 0x8c, 0x92, 0x71, 0xe5, 0x12, 0x6a,
	0x84, 0xdb, 0x93, 0x4d, 0x33, 0x67, 0xa7, 0x6f, 0xfc, 0x98, 0xdc, 0xca, 0xe1, 0x81, 0x45, 0xe9,
	0x85, 0xc5, 0x29, 0x2b, 0xb8, 0x23, 0xd9, 0xda, 0xbb, 0x79, 0x06, 0x60, 0xc7, 0xe5, 0xa0, 0x62,
	0x9d, 0x31, 0xea, 0xca, 0xa4, 0x84, 0xba, 0x72, 0x64, 0x2d, 0x3b, 0x63, 0x27, 0x30, 0x4e, 0xae,
	0xea, 0x6d, 0x9a, 0x11, 0xf0, 0x9a, 0xb8, 0xca, 0x02, 0x29, 0x25, 0x2a, 0x2c, 0xe0, 0x1f, 0xa5,
	0xa1, 0x5e, 0xe5, 0x18, 0xf2, 0xea, 0x9e, 0x64, 0x53, 0xef, 0xb2, 0x19, 0xc8, 0x0e, 0x59, 0x63,
	0xb5, 0x80, 0xa5, 0x81, 0x63, 0x5d, 0x19, 0x55, 0x6f, 0xbd, 0xce, 0x18, 0xee, 0x4b, 0x36, 0xce,
	0x24, 0x50, 0x8a, 0x23, 0xaa, 0xc6, 0x64, 0x33, 0x82, 0x3d, 0x2d, 0xa1, 0x32, 0xc5, 0xa2, 0x6f,
	0x32, 0x46, 0xd8, 0x1d, 0x83, 0xc8, 0x1a, 0xa3, 0xe1, 0xdf, 0x44, 0x58, 0x52, 0xd4, 0x98, 0x21,
	0xfc, 0x7b, 0xb2, 0x79, 0xa6, 0x6c, 0xa4, 0x38, 0x29, 0x50, 0xaf, 0x16, 0xa3, 0xbd, 0xad, 0xe4,
	0xa6, 0xde, 0xb5, 0xeb, 0x57, 0x90, 0x0e, 0xc7, 0xaa, 0xc2, 0x85, 0xa6, 0xbe, 0x58, 0x1a, 0xf9,
	0xbe, 0xe2, 0x14, 0xf6, 0xb5, 0x92, 0x8b, 0x7b, 0x7f, 0xbe, 0x7e, 0xed, 0x00, 0x33, 0x38, 0xd0,
	0x12, 0xe9, 0x98, 0x0e, 0x58, 0x11, 0x3c, 0x15, 0x05, 0x34, 0xc2, 0x33, 0xad, 0xe4, 0xaa, 0xde,
	0x15, 0x33, 0x80, 0xe5, 0xd2, 0x15, 0x58, 0x9e, 0xa3, 0xfa, 0xb9, 0x96, 0xa8, 0xa3, 0xa9, 0x49,
	0x4d, 0xb9, 0x6a, 0xfa, 0x0b, 0x2d, 0x51, 0xbf, 0x52, 0xa3, 0x4c, 0xd1, 0x67, 0x84, 0x17, 0x43,
	0x1c, 0x2f, 0x9a, 0xc1, 0x0a, 0x63, 0x4d, 0x09, 0x87, 0x22, 0x46, 0x19, 0x9d, 0x1b, 0x38, 0xdc,
	0x4a, 0x6e, 0xee, 0x5d, 0x27, 0x81, 0x2a, 0xa3, 0xc2, 0xa4, 0x16, 0x1d, 0xa7, 0x6b, 0xb1, 0x78,
	0xa5, 0x25, 0x12, 0x20, 0x35, 0x66, 0xb8, 0x6a, 0xdc, 0x6b, 0x2d, 0x49, 0xb3, 0x29, 0x1d, 0x56,
	0x21, 0xa6, 0xf0, 0x46, 0x4c, 0xda, 0x51, 0x95, 0xf1, 0xd8, 0xb0, 0x25, 0x78, 0x64, 0x5e, 0x9a,
	0x6f, 0x0d, 0x3a, 0x46, 0x78, 0x2b, 0x42, 0x42, 0xa8, 0x8f, 0x47, 0x22, 0x1e, 0x7b, 0x8b, 0x29,
	0x1a, 0x78, 0xbc, 0x2d, 0x3a, 0x59, 0x3a, 0x19, 0x85, 0xd2, 0xf3, 0x4e, 0x4b, 0xe6, 0xc7, 0x94,
	0xd2, 0xc1, 0x9a, 0x9f, 0x3f, 0x92, 0xdb, 0x66, 0xa4, 0x0b, 0xb4, 0x43, 0xf8, 0x48, 0xc6, 0x3f,
	0x5b, 0xe4, 0xbe, 0xf1, 0x8e, 0xe1, 0xd1, 0x39, 0x89, 0x99, 0x82, 0x75, 0x70, 0xfe, 0x93, 0x56,
	0x72, 0x4d, 0xef, 0xca, 0x28, 0x76, 0x5e, 0xb2, 0x1d, 0x93, 0x8a, 0x29, 0xf5, 0x98, 0x19, 0x0b,
	0x9f, 0x49, 0x06, 0x29, 0x9f, 0x8c, 0x1c, 0x1c, 0xee, 0x26, 0x57, 0xcc, 0x34, 0x66, 0x52, 0x55,
	0x89, 0x6a, 0x5c, 0xcb, 0x7d, 0xde, 0x4a, 0xae, 0x9e, 0x39, 0xf3, 0xb4, 0xcd, 0xa3, 0x33, 0x96,
	0x51, 0x55, 0xb9, 0x67, 0x4d, 0x08, 0x3f, 0x8b, 0xe8, 0xb5, 0xec, 0x2c, 0x21, 0x9c, 0x8c, 0x40,
	0xa5, 0x33, 0xa1, 0x6b, 0xfd, 0xb2, 0x95, 0x5c, 0x3e, 0xd3, 0x9d, 0xca, 0xa5, 0x50, 0x98, 0x42,
	0x26, 0x9f, 0xea, 0x88, 0x60, 0x90, 0x1b, 0xb0, 0x19, 0x31, 0xc2, 0x97, 0xf2, 0x24, 0x2c, 0xa0,
	0x1a, 0xae, 0x1b, 0x18, 0x7e, 0x2d, 0x4f, 0xc2, 0x02, 0x5a, 0x43, 0xab, 0x0b, 0x7e, 0x25, 0x73,
	0x62, 0x81, 0x17, 0x19, 0xce, 0x48, 0x83, 0x17, 0x58, 0xd7, 0x36, 0x7d, 0xdd, 0x12, 0x39, 0xb1,
	0x60, 0x51, 0xa7, 0x04, 0xdf, 0x44, 0xb4, 0x59, 0xd2, 0xe9, 0x20, 0x44, 0x28, 0xd4, 0xe8, 0xef,
	0x22, 0x26, 0x37, 0x0b, 0x46, 0x46, 0x4d, 0x34, 0x95, 0x8c, 0xf0, 0x1f, 0x73, 0xa2, 0x77, 0xac,
	0xac, 0x29, 0x8d, 0x77, 0x03, 0xb2, 0x6b, 0xa5, 0x98, 0xa9, 0x84, 0x3d, 0x73, 0x82, 0xd1, 0x1c,
	0xfb, 0x46, 0xc3, 0x7f, 0xcd, 0xc9, 0x21, 0x0c, 0xeb, 0x13, 0xfe, 0xd8, 0x9c, 0xf0, 0x2d, 0x27,
	0x63, 0x73, 0x46, 0xd8, 0x17, 0x83, 0x6c, 0x81, 0x7a, 0x02, 0x07, 0x22, 0x8a, 0x06, 0xc1, 0xa9,
	0x67, 0xe7, 0x04, 0x81, 0x39, 0xf7, 0x2d, 0x2a, 0x87, 0x16, 0x9e, 0x8f, 0x58, 0x61, 0x89, 0x52,
	0x82, 0x97, 0x22, 0x62, 0x96, 0xa8, 0x89, 0xf1, 0xcb, 0x11, 0x3b, 0x2c, 0xd5, 0x75, 0xf9, 0x95,
	0x39, 0x51, 0x1e, 0x72, 0x8f, 0x19, 0x29, 0xe3, 0x47, 0x04, 0xaf, 0xcd, 0x09, 0x3e, 0x73, 0x8f,
	0x05, 0xbc, 0x11, 0xd1, 0xe6, 0xd1, 0x51, 0x81, 0x0a, 0xe1, 0x88, 0x3c, 0x72, 0xb9, 0x27, 0xab,
	0x4b, 0x9a, 0xc0, 0x5b, 0x5d, 0xe9, 0x40, 0x93, 0xee, 0xef, 0xcc, 0x09, 0xb6, 0x1b, 0xa4, 0xea,
	0x73, 0x59, 0xa2, 0x87, 0xd3, 0xed, 0x88, 0xe8, 0x24, 0x84, 0xec, 0x3d, 0x19, 0xcb, 0x01, 0xb2,
	0x63, 0xf8, 0x60, 0x2e, 0xb9, 0xad, 0xb7, 0x65, 0x3d, 0x40, 0x68, 0xcf, 0x25, 0x74, 0x3d, 0x0f,
	0x14, 0x69, 0x66, 0x34, 0xaa, 0xb5, 0x24, 0xff, 0x50, 0x9a, 0x3f, 0x30, 0x6a, 0x52, 0x95, 0x44,
	0xf0, 0x51, 0x0c, 0xd3, 0x99, 0xb7, 0x58, 0xc2, 0x27, 0x32, 0x26, 0x03, 0xa3, 0xf3, 0x6a, 0x68,
	0x74, 0x0e, 0x9f, 0x4a, 0x06, 0x06, 0x5e, 0xe7, 0x68, 0x27, 0x70, 0x5c, 0x42, 0x9c, 0x52, 0xcd,
	0xdb, 0x17, 0xd2, 0xb1, 0x7a, 0x88, 0x80, 0x13, 0x52, 0x17, 0xeb, 0xcc, 0x34, 0x29, 0x7f, 0x52,
	0x92, 0xc6, 0x16, 0x35, 0x9c, 0x8a, 0xfe, 0xbe, 0x0d, 0x4e, 0x47, 0x0c, 0xb0, 0x8d, 0x01, 0x5f,
	0xcd, 0x89, 0x3a, 0xc6, 0xa5, 0xa2, 0xca, 0x2c, 0x54, 0x05, 0x6a, 0x78, 0x5b, 0xb2, 0xc9, 0xa5,
	0x45, 0x52, 0x70, 0x36, 0x62, 0xb9, 0x43, 0x35, 0x81, 0x6f, 0xa5, 0xb2, 0x45, 0x2c, 0x30, 0x94,
	0xe3, 0x3d, 0xf3, 0x42, 0x66, 0x11, 0x47, 0xa8, 0x61, 0xef, 0xbc, 0x50, 0xb3, 0x48, 0x36, 0xa4,
	0xd3, 0x11, 0x69, 0xc0, 0xa2, 0xb1, 0x19, 0x6a, 0xd8, 0x3f, 0x2f, 0xf2, 0x7a, 0x88, 0x53, 0x1c,
	0x0e, 0xea, 0x9b, 0xd1, 0x63, 0x52, 0xd5, 0x90, 0xf4, 0x04, 0xe1, 0xc0, 0xbc, 0x20, 0x78, 0xc8,
	0x96, 0xfb, 0xe8, 0x18, 0xfe, 0x5f, 0x66, 0xd3, 0xd0, 0x58, 0xc2, 0xf3, 0xdb, 0xf2, 0x88, 0xcc,
	0x48, 0x51, 0xb9, 0xd6, 0x3d, 0x9e, 0x9a, 0x17, 0x8d, 0xad, 0x11, 0x5a, 0x5d, 0xf1, 0xb4, 0xf4,
	0x6e, 0xe8, 0x97, 0x90, 0x1d, 0x1c, 0x8c, 0xf8, 0x30, 0xb1, 0xf9, 0x64, 0x5a, 0xfb, 0xf0, 0xbf,
	0xb2, 0x35, 0x2b, 0x34, 0xd5, 0x28, 0xb3, 0xf0, 0x9c, 0xdc, 0x52, 0xa1, 0x0b, 0x93, 0xf4, 0x4b,
	0x11, 0x21, 0xea, 0xa3, 0x36, 0x1a, 0x5e, 0x88, 0x41, 0xa5, 0x71, 0x03, 0x03, 0x2f, 0x46, 0x20,
	0xee, 0xd7, 0xd7, 0xc1, 0x43, 0x32, 0x92, 0x8a, 0xfb, 0x13, 0x84, 0xc3, 0xf3, 0xe2, 0x3c, 0x2b,
	0xa6, 0x74, 0xe0, 0x48, 0x97, 0x8e, 0x58, 0xc3, 0xab, 0xf3, 0x22, 0x87, 0x15, 0xbb, 0x81, 0xaf,
	0xef, 0x9f, 0xaf, 0x49, 0xd7, 0x95, 0xbf, 0x93, 0x8a, 0xbe, 0xf1, 0x36, 0x87, 0xd7, 0xa5, 0xd2,
	0xa2, 0x1e, 0x30, 0xde, 0x94, 0x62, 0x05, 0x66, 0x98, 0x63, 0x99, 0xa2, 0x85, 0xa3, 0x32, 0x2c,
	0xa1, 0x60, 0x2d, 0x31, 0xbc, 0x2b, 0x69, 0x0f, 0xc8, 0x24, 0x1c, 0xa7, 0xf7, 0xa3, 0x58, 0xc6,
	0x63, 0x2a, 0xe1, 0xc3, 0x79, 0x71, 0xa4, 0x0a, 0x54, 0x0c, 0x1f, 0xc7, 0x0c, 0x54, 0x0e, 0xe1,
	0xd8, 0xbc, 0x68, 0x59, 0x05, 0xda, 0x72, 0x80, 0x4a, 0xad, 0x16, 0xa0, 0xf7, 0xda, 0x11, 0x27,
	0xac, 0x63, 0xcd, 0xdb, 0x3c, 0xc1, 0x67, 0x31, 0x17, 0xbd, 0x65, 0x57, 0xc7, 0xed, 0x73, 0x19,
	0xd4, 0x06, 0x65, 0x5f, 0xc2, 0x17, 0x92, 0xc6, 0x02, 0x27, 0xc6, 0x39, 0x82, 0xef, 0xc9, 0x2e,
	0x5c, 0xd0, 0x9d, 0x9c, 0x1a, 0x38, 0x11, 0xd1, 0xc7, 0xa9, 0x5d, 0xa9, 0x35, 0x3f, 0x68, 0xcb,
	0x2d, 0x8d, 0xca, 0xcc, 0x18, 0xe1, 0x4c, 0x24, 0xda, 0x46, 0x63, 0x6a, 0xe0, 0x54, 0x24, 0xa2,
	0x61, 0xbe, 0x0d, 0x17, 0xe8, 0xd3, 0x11, 0x75, 0x46, 0x3b, 0xd2, 0x94, 0x5b, 0x03, 0xbf, 0x8d,
	0xa3, 0x25, 0x59, 0x8b, 0x0e, 0xbe, 0x8a, 0xf8, 0x67, 0xac, 0x49, 0x53, 0x03, 0x67, 0x63, 0x82,
	0xd3, 0xd0, 0xc0, 0x43, 0x4c, 0xbf, 0x9d, 0x17, 0x97, 0xa4, 0x62, 0x82, 0x61, 0xb8, 0x84, 0x5d,
	0x62, 0x4b, 0x8d, 0x05, 0x87, 0xbe, 0xbf, 0xa7, 0x2d, 0x38, 0xd6, 0xe8, 0xad, 0x87, 0xbd, 0x11,
	0x80, 0x46, 0xa8, 0x60, 0x5f, 0x5b, 0x54, 0x53, 0x4d, 0x61, 0x06, 0x69, 0x78, 0xdf, 0x2f, 0xdf,
	0x6b, 0x34, 0x2d, 0x55, 0x29, 0x2a, 0xca, 0xea, 0xd9, 0xee, 0x99, 0x98, 0xfc, 0x52, 0x35, 0xa5,
	0xfa, 0x59, 0x07, 0x5e, 0x6c, 0x0b, 0xee, 0xc3, 0x28, 0x6b, 0x31, 0xf7, 0x08, 0x87, 0x22, 0x46,
	0x71, 0x4e, 0x16, 0x0e, 0x4b, 0x06, 0x6b, 0x80, 0x11, 0x5e, 0x6d, 0x8b, 0xec, 0xd6, 0xec, 0x09,
	0x5e, 0x6f, 0x8b, 0x9a, 0xa6, 0x8d, 0x5d, 0x30, 0xea, 0xdc, 0xad, 0x03, 0xde, 0x6c, 0x47, 0xd2,
	0x30, 0x5d, 0x71, 0xe3, 0xff, 0xba, 0xe2, 0xa6, 0xa7, 0x8d, 0x6d, 0x66, 0xb1, 0x22, 0xdc, 0x69,
	0x35, 0xae, 0x9e, 0x85, 0x77, 0x64, 0xd3, 0xd7, 0xc6, 0x2e, 0xe1, 0x04, 0x8e, 0x4a, 0xe3, 0x4c,
	0xe8, 0x49, 0x8f, 0xb4, 0x45, 0x72, 0x8d, 0x70, 0xd8, 0x3c, 0x88, 0xbd, 0x2f, 0x83, 0x30, 0x42,
	0x85, 0x1e, 0x7e, 0xd8, 0x4e, 0xae, 0xef, 0x5d, 0x35, 0x0b, 0x50, 0x19, 0x0e, 0xdd, 0xba, 0xcb,
	0xfa, 0xe3, 0x72, 0x00, 0x1b, 0xa1, 0xc6, 0x02, 0xe1, 0xc7, 0x6d, 0x71, 0xb2, 0x47, 0x38, 0xf2,
	0x58, 0x53, 0xb4, 0x32, 0xe3, 0x1c, 0x8b, 0xd9, 0x56, 0xf3, 0x33, 0x81, 0x4f, 0xa5, 0x3f, 0x23,
	0xb2, 0x1e, 0x8e, 0x4b, 0xd2, 0x47, 0x03, 0x56, 0x3c, 0x1a, 0xb1, 0xa6, 0x12, 0xbe, 0x88, 0x6c,
	0xc9, 0x2e, 0x45, 0xb6, 0x1a, 0x4e, 0xc8, 0xe0, 0x8d, 0x4c, 0xcd, 0xcf, 0xc9, 0x88, 0x94, 0xb1,
	0xce, 0xe7, 0xa8, 0xe0, 0x54, 0x44, 0xa1, 0x27, 0xeb, 0x4c, 0xb8, 0x31, 0x1a, 0xf8, 0x5a, 0xc6,
	0x70, 0x1b, 0x86, 0xd9, 0xf4, 0x1b, 0x99, 0x48, 0x96, 0xbc, 0x66, 0xa3, 0xe1, 0xbb, 0x08, 0x14,
	0xc8, 0x0a, 0xf3, 0x79, 0x47, 0xdc, 0xc1, 0xac, 0x2f, 0xcb, 0x10, 0xf5, 0x05, 0xca, 0x28, 0x74,
	0x55, 0xa3, 0xe1, 0x3f, 0x3b, 0xc2, 0x13, 0xbb, 0x84, 0x3a, 0x43, 0x78, 0xb4, 0x23, 0xc2, 0x5e,
	0x22, 0x6b, 0x57, 0xf5, 0x31, 0xa4, 0x94, 0xa2, 0x62, 0x02, 0xfb, 0x3a, 0xe2, 0x92, 0xdb, 0xac,
	0x09, 0xb8, 0x46, 0x78, 0xac, 0x23, 0xd8, 0x6f, 0xf0, 0x21, 0x3b, 0x57, 0xd6, 0x53, 0xa2, 0xa6,
	0x31, 0x97, 0xf0, 0x78, 0x47, 0x84, 0xa6, 0x59, 0xa8, 0x7c, 0xca, 0x08, 0x4f, 0xfc, 0x21, 0x3d,
	0x4d, 0xf9, 0x86, 0x27, 0x3b, 0xe2, 0x5e, 0xdf, 0xe0, 0x23, 0x26, 0x6b, 0xa9, 0x19, 0x47, 0x43,
	0x41, 0x52, 0x46, 0xc3, 0xd3, 0x9d, 0x64, 0x4b, 0xef, 0xc6, 0xc8, 0xe2, 0x31, 0xeb, 0x94, 0xb4,
	0xab, 0x57, 0x37, 0x53, 0x7c, 0x9d, 0x08, 0x07, 0x3b, 0x82, 0x97, 0xe6, 0x3d, 0xf6, 0x4c, 0x57,
	0x94, 0xbe, 0x12, 0x9b, 0x93, 0xa6, 0x0d, 0x3c, 0x17, 0xf3, 0xdd, 0x54, 0xce, 0x14, 0x8d, 0x3d,
	0x23, 0xcb, 0x3a, 0xe5, 0x11, 0xc1, 0x0b, 0x31, 0xe7, 0x7c, 0xc6, 0x15, 0x5a, 0xac, 0x1f, 0x3a,
	0x3a, 0x82, 0xe3, 0x32, 0x54, 0x6d, 0x54, 0x70, 0x48, 0xb2, 0x57, 0x92, 0x0d, 0x42, 0x2f, 0x77,
	0xa4, 0x6d, 0x34, 0x49, 0x07, 0xa4, 0x14, 0x95, 0x70, 0x38, 0xa2, 0x32, 0x44, 0x0a, 0x2b, 0x45,
	0x46, 0x13, 0xbc, 0xda, 0x91, 0x77, 0x5d, 0xd6, 0x39, 0x8e, 0x8c, 0x25, 0x78, 0x33, 0x26, 0x5c,
	0x73, 0x81, 0xd6, 0x91, 0x86, 0x27, 0xe4, 0x11, 0x28, 0x95, 0x19, 0xe3, 0x90, 0x11, 0xde, 0xea,
	0x44, 0xb1, 0xfa, 0x59, 0xf8, 0xed, 0x4e, 0xb2, 0xb9, 0xb7, 0x71, 0x3d, 0x66, 0x94, 0x29, 0xcc,
	0xda, 0x53, 0xd6, 0x54, 0x46, 0xc2, 0x14, 0xf5, 0xf3, 0xf0, 0xd1, 0x88, 0x51, 0xe1, 0x1a, 0xba,
	0xf2, 0xc4, 0x05, 0xef, 0x76, 0x92, 0x3b, 0x7a, 0x7f, 0x17, 0xc1, 0x57, 0x6e, 0x94, 0x35, 0x25,
	0x6e, 0x70, 0xee, 0xd7, 0x12, 0x75, 0xb6, 0xc4, 0xe9, 0x60, 0x55, 0xf3, 0x6f, 0x5a, 0x32, 0x41,
	0x9b, 0x95, 0x3e, 0x0c, 0xc5, 0x9f, 0x46, 0x72, 0x64, 0x84, 0xac, 0xe1, 0x93, 0x48, 0x24, 0x2d,
	0x57, 0x0a, 0xf5, 0x10, 0x61, 0xbf, 0x7c, 0xe5, 0x68, 0xb6, 0xfb, 0x49, 0x24, 0x4c, 0xde, 0xb2,
	0xc6, 0x82, 0xe0, 0x44, 0x27, 0xb9, 0x75, 0xe6, 0x1d, 0xb4, 0x1c, 0xa3, 0xea, 0x87, 0xdb, 0x57,
	0x70, 0x62, 0xb1, 0x4e, 0xc1, 0x09, 0xad, 0x45, 0xed, 0x64, 0x24, 0x4b, 0x96, 0x28, 0x23, 0x0d,
	0xa7, 0x23, 0xc7, 0x6e, 0x89, 0xdd, 0xb4, 0x69, 0x9c, 0xf0, 0x55, 0x27, 0xb9, 0xae, 0xf7, 0x97,
	0xeb, 0xe1, 0x49, 0x68, 0x23, 0x75, 0x6a, 0xae, 0x0d, 0xda, 0x67, 0xa5, 0x02, 0x87, 0xbc, 0x84,
	0x1a, 0x0e, 0xca, 0x37, 0x32, 0x87, 0x8b, 0xbc, 0xd2, 0x35, 0xbe, 0x91, 0x6e, 0x3a, 0xd4, 0xd3,
	0xba, 0x7c, 0x1d, 0xed, 0x4a, 0x6c, 0x80, 0xcd, 0x6b, 0xcb, 0xb7, 0xd2, 0x6c, 0xc7, 0x85, 0xb1,
	0x61, 0xac, 0x76, 0x04, 0x67, 0x64, 0xc1, 0x77, 0x26, 0x37, 0xf0, 0x48, 0x57, 0xa4, 0x8f, 0x33,
	0x43, 0x0a, 0x6d, 0x6a, 0x4f, 0x57, 0x30, 0xe1, 0x8c, 0xce, 0x11, 0xf6, 0x76, 0x93, 0x6b, 0x67,
	0x3e, 0x84, 0x38, 0xcb, 0x9a, 0x33, 0x6c, 0xa2, 0xed, 0x4c, 0x1f, 0x73, 0x03, 0xfb, 0x22, 0x5b,
	0x7b, 0xcd, 0x61, 0x90, 0x3b, 0x20, 0x6f, 0x52, 0xce, 0xdb, 0x21, 0x4d, 0xe0, 0xa9, 0xae, 0xc8,
	0xd9, 0x80, 0x14, 0xb4, 0xf2, 0x95, 0xe9, 0x7f, 0x64, 0x3b, 0x0f, 0x78, 0x53, 0x37, 0x53, 0xe4,
	0xf3, 0x5f, 0x4a, 0x9f, 0x89, 0x69, 0x19, 0xa3, 0xf2, 0x70, 0x50, 0x22, 0x3e, 0xaf, 0x2b, 0xfc,
	0xb3, 0xd2, 0x68, 0x3f, 0xb4, 0xc8, 0x9a, 0xe0, 0xf9, 0xae, 0x60, 0xde, 0x6b, 0x76, 0x94, 0x35,
	0xcc, 0x53, 0xc1, 0x16, 0x1d, 0x95, 0xb0, 0xbf, 0x2b, 0x06, 0x96, 0x95, 0x75, 0x43, 0xd6, 0x79,
	0x66, 0x0a, 0x78, 0xbd, 0x9b, 0xfc, 0x4d, 0xef, 0xaf, 0x62, 0x2b, 0x4a, 0x17, 0xb6, 0xa8, 0x0a,
	0xd6, 0xc6, 0x56, 0xc6, 0x3b, 0x35, 0x61, 0x9d, 0xaf, 0x3a, 0xf4, 0xfd, 0xb6, 0x70, 0x7e, 0xbd,
	0x9c, 0x59, 0x38, 0xf7, 0x7d, 0x0c, 0xde, 0x8b, 0x38, 0x62, 0x7d, 0xdd, 0xfc, 0x3f, 0x93, 0x35,
	0xda, 0x4f, 0xfb, 0xb4, 0x92, 0x80, 0xc7, 0xa5, 0xe0, 0x18, 0xb5, 0x47, 0xe7, 0xe1, 0x79, 0x39,
	0x68, 0x8d, 0x49, 0xd3, 0xd4, 0x93, 0x42, 0xf8, 0x5c, 0x26, 0xe7, 0x98, 0xc9, 0x85, 0x09, 0x16,
	0x8e, 0x74, 0xe4, 0x47, 0x92, 0x95, 0xef, 0x14, 0x63, 0xb6, 0x39, 0xaf, 0x9d, 0xcb, 0x7f, 0x10,
	0xb1, 0x9b, 0x59, 0xf0, 0x71, 0x57, 0xb4, 0xb5, 0x25, 0x54, 0x8a, 0x9b, 0x0c, 0x58, 0xf0, 0xce,
	0x9f, 0x37, 0xd0, 0x9d, 0x92, 0x54, 0x2c, 0x85, 0xe3, 0x60, 0x75, 0x55, 0xe2, 0x00, 0x2d, 0xc2,
	0x71, 0x59, 0xa4, 0x26, 0x54, 0x90, 0x86, 0xdf, 0xc9, 0x14, 0x99, 0x36, 0x4f, 0x70, 0xdf, 0x49,
	0x47, 0xa7, 0x5c, 0xf4, 0xb1, 0xbf, 0x44, 0xf0, 0x41, 0xa7, 0x7f, 0xdb, 0x47, 0x3f, 0xdd, 0x74,
	0xc1, 0x91, 0x9f, 0x6f, 0x6a, 0x4d, 0x6f, 0x3c, 0xef, 0x03, 0xed, 0xf6, 0x5d, 0x77, 0x3d, 0xb8,
	0x73, 0xc7, 0xae, 0x7b, 0xff, 0x75, 0xc7, 0xd6, 0x73, 0x5f, 0x66, 0xef, 0xbb, 0xeb, 0xfe, 0x9d,
	0x5b, 0x9b, 0x6f, 0xb9, 0x77, 0x77, 0xeb, 0x1f, 0x6f, 0xfb, 0x7d, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xa8, 0xd2, 0xf7, 0xeb, 0xf1, 0x1d, 0x00, 0x00,
}
