// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: transaction.proto

package chtype

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Transaction struct {
	TokenId              string               `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	TransactionId        string               `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Details              []*TransactionDetail `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
	PaymentType          PaymentMethodType    `protobuf:"varint,4,opt,name=payment_type,json=paymentType,proto3,enum=chtype.PaymentMethodType" json:"payment_type,omitempty"`
	PaymentScheme        string               `protobuf:"bytes,5,opt,name=payment_scheme,json=paymentScheme,proto3" json:"payment_scheme,omitempty"`
	TransactionType      TransactionType      `protobuf:"varint,6,opt,name=transaction_type,json=transactionType,proto3,enum=chtype.TransactionType" json:"transaction_type,omitempty"`
	RequestAmount        *Amount              `protobuf:"bytes,7,opt,name=request_amount,json=requestAmount,proto3" json:"request_amount,omitempty"`
	TransactedAmount     *Amount              `protobuf:"bytes,8,opt,name=transacted_amount,json=transactedAmount,proto3" json:"transacted_amount,omitempty"`
	Contract             ContractType         `protobuf:"varint,9,opt,name=contract,proto3,enum=chtype.ContractType" json:"contract,omitempty"`
	StatementDescriptor  string               `protobuf:"bytes,10,opt,name=statement_descriptor,json=statementDescriptor,proto3" json:"statement_descriptor,omitempty"`
	Result               TransactionResult    `protobuf:"varint,11,opt,name=result,proto3,enum=chtype.TransactionResult" json:"result,omitempty"`
	VerifyRequest        *VerifyRequestData   `protobuf:"bytes,12,opt,name=verify_request,json=verifyRequest,proto3" json:"verify_request,omitempty"`
	FailureType          FailureType          `protobuf:"varint,13,opt,name=failure_type,json=failureType,proto3,enum=chtype.FailureType" json:"failure_type,omitempty"`
	Arn                  string               `protobuf:"bytes,15,opt,name=arn,proto3" json:"arn,omitempty"`
	Verified             VerificationStatus   `protobuf:"varint,16,opt,name=verified,proto3,enum=chtype.VerificationStatus" json:"verified,omitempty"`
	Liability            Liability            `protobuf:"varint,17,opt,name=liability,proto3,enum=chtype.Liability" json:"liability,omitempty"`
	AttemptDetail        *AttemptDetail       `protobuf:"bytes,19,opt,name=attempt_detail,json=attemptDetail,proto3" json:"attempt_detail,omitempty"`
	FraudResults         []*FraudResult       `protobuf:"bytes,20,rep,name=fraud_results,json=fraudResults,proto3" json:"fraud_results,omitempty"`
	Response             *ResponseDetail      `protobuf:"bytes,21,opt,name=response,proto3" json:"response,omitempty"`
	SourceTransactionId  string               `protobuf:"bytes,22,opt,name=source_transaction_id,json=sourceTransactionId,proto3" json:"source_transaction_id,omitempty"`
	PaymentMethodId      string               `protobuf:"bytes,23,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

func (m *Transaction) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

func (m *Transaction) GetDetails() []*TransactionDetail {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *Transaction) GetPaymentType() PaymentMethodType {
	if m != nil {
		return m.PaymentType
	}
	return PAYMENT_METHOD_TYPE_INVALID
}

func (m *Transaction) GetPaymentScheme() string {
	if m != nil {
		return m.PaymentScheme
	}
	return ""
}

func (m *Transaction) GetTransactionType() TransactionType {
	if m != nil {
		return m.TransactionType
	}
	return TRANSACTION_TYPE_INVALID
}

func (m *Transaction) GetRequestAmount() *Amount {
	if m != nil {
		return m.RequestAmount
	}
	return nil
}

func (m *Transaction) GetTransactedAmount() *Amount {
	if m != nil {
		return m.TransactedAmount
	}
	return nil
}

func (m *Transaction) GetContract() ContractType {
	if m != nil {
		return m.Contract
	}
	return CONTRACT_TYPE_INVALID
}

func (m *Transaction) GetStatementDescriptor() string {
	if m != nil {
		return m.StatementDescriptor
	}
	return ""
}

func (m *Transaction) GetResult() TransactionResult {
	if m != nil {
		return m.Result
	}
	return TRANSACTION_RESULT_INVALID
}

func (m *Transaction) GetVerifyRequest() *VerifyRequestData {
	if m != nil {
		return m.VerifyRequest
	}
	return nil
}

func (m *Transaction) GetFailureType() FailureType {
	if m != nil {
		return m.FailureType
	}
	return FAILURE_TYPE_INVALID
}

func (m *Transaction) GetArn() string {
	if m != nil {
		return m.Arn
	}
	return ""
}

func (m *Transaction) GetVerified() VerificationStatus {
	if m != nil {
		return m.Verified
	}
	return VERIFICATION_STATUS_INVALID
}

func (m *Transaction) GetLiability() Liability {
	if m != nil {
		return m.Liability
	}
	return LIABILITY_INVALID
}

func (m *Transaction) GetAttemptDetail() *AttemptDetail {
	if m != nil {
		return m.AttemptDetail
	}
	return nil
}

func (m *Transaction) GetFraudResults() []*FraudResult {
	if m != nil {
		return m.FraudResults
	}
	return nil
}

func (m *Transaction) GetResponse() *ResponseDetail {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *Transaction) GetSourceTransactionId() string {
	if m != nil {
		return m.SourceTransactionId
	}
	return ""
}

func (m *Transaction) GetPaymentMethodId() string {
	if m != nil {
		return m.PaymentMethodId
	}
	return ""
}

type TransactionDetail struct {
	ActorId              string               `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ActorVersion         string               `protobuf:"bytes,2,opt,name=actor_version,json=actorVersion,proto3" json:"actor_version,omitempty"`
	ActorType            ActorType            `protobuf:"varint,3,opt,name=actor_type,json=actorType,proto3,enum=chtype.ActorType" json:"actor_type,omitempty"`
	TransactionId        string               `protobuf:"bytes,4,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	RequestedAmount      *Amount              `protobuf:"bytes,5,opt,name=requested_amount,json=requestedAmount,proto3" json:"requested_amount,omitempty"`
	ProcessedAmount      *Amount              `protobuf:"bytes,6,opt,name=processed_amount,json=processedAmount,proto3" json:"processed_amount,omitempty"`
	FeeEstimate          *Amount              `protobuf:"bytes,7,opt,name=fee_estimate,json=feeEstimate,proto3" json:"fee_estimate,omitempty"`
	FeeActual            *Amount              `protobuf:"bytes,8,opt,name=fee_actual,json=feeActual,proto3" json:"fee_actual,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              *timestamp.Timestamp `protobuf:"bytes,10,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	WasSuccessful        bool                 `protobuf:"varint,11,opt,name=was_successful,json=wasSuccessful,proto3" json:"was_successful,omitempty"`
	FailureType          FailureType          `protobuf:"varint,12,opt,name=failure_type,json=failureType,proto3,enum=chtype.FailureType" json:"failure_type,omitempty"`
	Environment          Environment          `protobuf:"varint,15,opt,name=environment,proto3,enum=chtype.Environment" json:"environment,omitempty"`
	VerificationResult   *VerificationResult  `protobuf:"bytes,16,opt,name=verification_result,json=verificationResult,proto3" json:"verification_result,omitempty"`
	AdditionalData       map[string]string    `protobuf:"bytes,17,rep,name=additional_data,json=additionalData,proto3" json:"additional_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	AuthorizationCode    string               `protobuf:"bytes,18,opt,name=authorization_code,json=authorizationCode,proto3" json:"authorization_code,omitempty"`
	Liability            Liability            `protobuf:"varint,19,opt,name=liability,proto3,enum=chtype.Liability" json:"liability,omitempty"`
	ConnectorLibrary     string               `protobuf:"bytes,20,opt,name=connector_library,json=connectorLibrary,proto3" json:"connector_library,omitempty"`
	Response             []*ResponseDetail    `protobuf:"bytes,21,rep,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TransactionDetail) Reset()         { *m = TransactionDetail{} }
func (m *TransactionDetail) String() string { return proto.CompactTextString(m) }
func (*TransactionDetail) ProtoMessage()    {}
func (*TransactionDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{1}
}
func (m *TransactionDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionDetail.Unmarshal(m, b)
}
func (m *TransactionDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionDetail.Marshal(b, m, deterministic)
}
func (m *TransactionDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionDetail.Merge(m, src)
}
func (m *TransactionDetail) XXX_Size() int {
	return xxx_messageInfo_TransactionDetail.Size(m)
}
func (m *TransactionDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionDetail.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionDetail proto.InternalMessageInfo

func (m *TransactionDetail) GetActorId() string {
	if m != nil {
		return m.ActorId
	}
	return ""
}

func (m *TransactionDetail) GetActorVersion() string {
	if m != nil {
		return m.ActorVersion
	}
	return ""
}

func (m *TransactionDetail) GetActorType() ActorType {
	if m != nil {
		return m.ActorType
	}
	return ACTOR_TYPE_INVALID
}

func (m *TransactionDetail) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

func (m *TransactionDetail) GetRequestedAmount() *Amount {
	if m != nil {
		return m.RequestedAmount
	}
	return nil
}

func (m *TransactionDetail) GetProcessedAmount() *Amount {
	if m != nil {
		return m.ProcessedAmount
	}
	return nil
}

func (m *TransactionDetail) GetFeeEstimate() *Amount {
	if m != nil {
		return m.FeeEstimate
	}
	return nil
}

func (m *TransactionDetail) GetFeeActual() *Amount {
	if m != nil {
		return m.FeeActual
	}
	return nil
}

func (m *TransactionDetail) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *TransactionDetail) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *TransactionDetail) GetWasSuccessful() bool {
	if m != nil {
		return m.WasSuccessful
	}
	return false
}

func (m *TransactionDetail) GetFailureType() FailureType {
	if m != nil {
		return m.FailureType
	}
	return FAILURE_TYPE_INVALID
}

func (m *TransactionDetail) GetEnvironment() Environment {
	if m != nil {
		return m.Environment
	}
	return ENVIRONMENT_INVALID
}

func (m *TransactionDetail) GetVerificationResult() *VerificationResult {
	if m != nil {
		return m.VerificationResult
	}
	return nil
}

func (m *TransactionDetail) GetAdditionalData() map[string]string {
	if m != nil {
		return m.AdditionalData
	}
	return nil
}

func (m *TransactionDetail) GetAuthorizationCode() string {
	if m != nil {
		return m.AuthorizationCode
	}
	return ""
}

func (m *TransactionDetail) GetLiability() Liability {
	if m != nil {
		return m.Liability
	}
	return LIABILITY_INVALID
}

func (m *TransactionDetail) GetConnectorLibrary() string {
	if m != nil {
		return m.ConnectorLibrary
	}
	return ""
}

func (m *TransactionDetail) GetResponse() []*ResponseDetail {
	if m != nil {
		return m.Response
	}
	return nil
}

type VerifyRequestData struct {
	Type                 VerifyRequestType `protobuf:"varint,1,opt,name=type,proto3,enum=chtype.VerifyRequestType" json:"type,omitempty"`
	Data                 map[string]string `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ConnectorLibrary     string            `protobuf:"bytes,3,opt,name=connector_library,json=connectorLibrary,proto3" json:"connector_library,omitempty"`
	Environment          Environment       `protobuf:"varint,4,opt,name=environment,proto3,enum=chtype.Environment" json:"environment,omitempty"`
	Required             bool              `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *VerifyRequestData) Reset()         { *m = VerifyRequestData{} }
func (m *VerifyRequestData) String() string { return proto.CompactTextString(m) }
func (*VerifyRequestData) ProtoMessage()    {}
func (*VerifyRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{2}
}
func (m *VerifyRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRequestData.Unmarshal(m, b)
}
func (m *VerifyRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRequestData.Marshal(b, m, deterministic)
}
func (m *VerifyRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRequestData.Merge(m, src)
}
func (m *VerifyRequestData) XXX_Size() int {
	return xxx_messageInfo_VerifyRequestData.Size(m)
}
func (m *VerifyRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRequestData proto.InternalMessageInfo

func (m *VerifyRequestData) GetType() VerifyRequestType {
	if m != nil {
		return m.Type
	}
	return VERIFY_REQUEST_TYPE_INVALID
}

func (m *VerifyRequestData) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *VerifyRequestData) GetConnectorLibrary() string {
	if m != nil {
		return m.ConnectorLibrary
	}
	return ""
}

func (m *VerifyRequestData) GetEnvironment() Environment {
	if m != nil {
		return m.Environment
	}
	return ENVIRONMENT_INVALID
}

func (m *VerifyRequestData) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

type ThreeDSResult struct {
	Eci                  string               `protobuf:"bytes,1,opt,name=eci,proto3" json:"eci,omitempty"`
	Cavv                 string               `protobuf:"bytes,2,opt,name=cavv,proto3" json:"cavv,omitempty"`
	Xid                  string               `protobuf:"bytes,3,opt,name=xid,proto3" json:"xid,omitempty"`
	Enrollment           string               `protobuf:"bytes,4,opt,name=enrollment,proto3" json:"enrollment,omitempty"`
	Result               string               `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	SignatureStatus      string               `protobuf:"bytes,6,opt,name=signature_status,json=signatureStatus,proto3" json:"signature_status,omitempty"`
	ServerTransactionId  string               `protobuf:"bytes,7,opt,name=server_transaction_id,json=serverTransactionId,proto3" json:"server_transaction_id,omitempty"`
	Status               string               `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	MajorVersion         int32                `protobuf:"varint,9,opt,name=major_version,json=majorVersion,proto3" json:"major_version,omitempty"`
	Version              string               `protobuf:"bytes,10,opt,name=version,proto3" json:"version,omitempty"`
	PaReq                string               `protobuf:"bytes,11,opt,name=pa_req,json=paReq,proto3" json:"pa_req,omitempty"`
	AcsUrl               string               `protobuf:"bytes,12,opt,name=acs_url,json=acsUrl,proto3" json:"acs_url,omitempty"`
	PaRes                string               `protobuf:"bytes,13,opt,name=pa_res,json=paRes,proto3" json:"pa_res,omitempty"`
	Id                   string               `protobuf:"bytes,14,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,15,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Liability            Liability            `protobuf:"varint,16,opt,name=liability,proto3,enum=chtype.Liability" json:"liability,omitempty"`
	SdkResponse          string               `protobuf:"bytes,17,opt,name=sdk_response,json=sdkResponse,proto3" json:"sdk_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ThreeDSResult) Reset()         { *m = ThreeDSResult{} }
func (m *ThreeDSResult) String() string { return proto.CompactTextString(m) }
func (*ThreeDSResult) ProtoMessage()    {}
func (*ThreeDSResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{3}
}
func (m *ThreeDSResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreeDSResult.Unmarshal(m, b)
}
func (m *ThreeDSResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreeDSResult.Marshal(b, m, deterministic)
}
func (m *ThreeDSResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreeDSResult.Merge(m, src)
}
func (m *ThreeDSResult) XXX_Size() int {
	return xxx_messageInfo_ThreeDSResult.Size(m)
}
func (m *ThreeDSResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreeDSResult.DiscardUnknown(m)
}

var xxx_messageInfo_ThreeDSResult proto.InternalMessageInfo

func (m *ThreeDSResult) GetEci() string {
	if m != nil {
		return m.Eci
	}
	return ""
}

func (m *ThreeDSResult) GetCavv() string {
	if m != nil {
		return m.Cavv
	}
	return ""
}

func (m *ThreeDSResult) GetXid() string {
	if m != nil {
		return m.Xid
	}
	return ""
}

func (m *ThreeDSResult) GetEnrollment() string {
	if m != nil {
		return m.Enrollment
	}
	return ""
}

func (m *ThreeDSResult) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *ThreeDSResult) GetSignatureStatus() string {
	if m != nil {
		return m.SignatureStatus
	}
	return ""
}

func (m *ThreeDSResult) GetServerTransactionId() string {
	if m != nil {
		return m.ServerTransactionId
	}
	return ""
}

func (m *ThreeDSResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ThreeDSResult) GetMajorVersion() int32 {
	if m != nil {
		return m.MajorVersion
	}
	return 0
}

func (m *ThreeDSResult) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ThreeDSResult) GetPaReq() string {
	if m != nil {
		return m.PaReq
	}
	return ""
}

func (m *ThreeDSResult) GetAcsUrl() string {
	if m != nil {
		return m.AcsUrl
	}
	return ""
}

func (m *ThreeDSResult) GetPaRes() string {
	if m != nil {
		return m.PaRes
	}
	return ""
}

func (m *ThreeDSResult) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ThreeDSResult) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *ThreeDSResult) GetLiability() Liability {
	if m != nil {
		return m.Liability
	}
	return LIABILITY_INVALID
}

func (m *ThreeDSResult) GetSdkResponse() string {
	if m != nil {
		return m.SdkResponse
	}
	return ""
}

type VerificationResult struct {
	AddressVerificationResult string         `protobuf:"bytes,1,opt,name=address_verification_result,json=addressVerificationResult,proto3" json:"address_verification_result,omitempty"`
	CvvVerificationResult     string         `protobuf:"bytes,2,opt,name=cvv_verification_result,json=cvvVerificationResult,proto3" json:"cvv_verification_result,omitempty"`
	FraudResult               string         `protobuf:"bytes,3,opt,name=fraud_result,json=fraudResult,proto3" json:"fraud_result,omitempty"`
	ThreedsResult             *ThreeDSResult `protobuf:"bytes,5,opt,name=threeds_result,json=threedsResult,proto3" json:"threeds_result,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}       `json:"-"`
	XXX_unrecognized          []byte         `json:"-"`
	XXX_sizecache             int32          `json:"-"`
}

func (m *VerificationResult) Reset()         { *m = VerificationResult{} }
func (m *VerificationResult) String() string { return proto.CompactTextString(m) }
func (*VerificationResult) ProtoMessage()    {}
func (*VerificationResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{4}
}
func (m *VerificationResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerificationResult.Unmarshal(m, b)
}
func (m *VerificationResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerificationResult.Marshal(b, m, deterministic)
}
func (m *VerificationResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerificationResult.Merge(m, src)
}
func (m *VerificationResult) XXX_Size() int {
	return xxx_messageInfo_VerificationResult.Size(m)
}
func (m *VerificationResult) XXX_DiscardUnknown() {
	xxx_messageInfo_VerificationResult.DiscardUnknown(m)
}

var xxx_messageInfo_VerificationResult proto.InternalMessageInfo

func (m *VerificationResult) GetAddressVerificationResult() string {
	if m != nil {
		return m.AddressVerificationResult
	}
	return ""
}

func (m *VerificationResult) GetCvvVerificationResult() string {
	if m != nil {
		return m.CvvVerificationResult
	}
	return ""
}

func (m *VerificationResult) GetFraudResult() string {
	if m != nil {
		return m.FraudResult
	}
	return ""
}

func (m *VerificationResult) GetThreedsResult() *ThreeDSResult {
	if m != nil {
		return m.ThreedsResult
	}
	return nil
}

type AttemptDetail struct {
	ChargeTransactionNumber  int64    `protobuf:"varint,1,opt,name=ChargeTransactionNumber,proto3" json:"ChargeTransactionNumber,omitempty"`
	ChargeAttemptNumber      int64    `protobuf:"varint,2,opt,name=ChargeAttemptNumber,proto3" json:"ChargeAttemptNumber,omitempty"`
	AttemptTransactionNumber int64    `protobuf:"varint,3,opt,name=AttemptTransactionNumber,proto3" json:"AttemptTransactionNumber,omitempty"`
	AttemptMethodCascade     int64    `protobuf:"varint,4,opt,name=AttemptMethodCascade,proto3" json:"AttemptMethodCascade,omitempty"`
	AttemptConnectorCascade  int64    `protobuf:"varint,5,opt,name=AttemptConnectorCascade,proto3" json:"AttemptConnectorCascade,omitempty"`
	IsPrimaryMethod          bool     `protobuf:"varint,6,opt,name=IsPrimaryMethod,proto3" json:"IsPrimaryMethod,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *AttemptDetail) Reset()         { *m = AttemptDetail{} }
func (m *AttemptDetail) String() string { return proto.CompactTextString(m) }
func (*AttemptDetail) ProtoMessage()    {}
func (*AttemptDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{5}
}
func (m *AttemptDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttemptDetail.Unmarshal(m, b)
}
func (m *AttemptDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttemptDetail.Marshal(b, m, deterministic)
}
func (m *AttemptDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttemptDetail.Merge(m, src)
}
func (m *AttemptDetail) XXX_Size() int {
	return xxx_messageInfo_AttemptDetail.Size(m)
}
func (m *AttemptDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_AttemptDetail.DiscardUnknown(m)
}

var xxx_messageInfo_AttemptDetail proto.InternalMessageInfo

func (m *AttemptDetail) GetChargeTransactionNumber() int64 {
	if m != nil {
		return m.ChargeTransactionNumber
	}
	return 0
}

func (m *AttemptDetail) GetChargeAttemptNumber() int64 {
	if m != nil {
		return m.ChargeAttemptNumber
	}
	return 0
}

func (m *AttemptDetail) GetAttemptTransactionNumber() int64 {
	if m != nil {
		return m.AttemptTransactionNumber
	}
	return 0
}

func (m *AttemptDetail) GetAttemptMethodCascade() int64 {
	if m != nil {
		return m.AttemptMethodCascade
	}
	return 0
}

func (m *AttemptDetail) GetAttemptConnectorCascade() int64 {
	if m != nil {
		return m.AttemptConnectorCascade
	}
	return 0
}

func (m *AttemptDetail) GetIsPrimaryMethod() bool {
	if m != nil {
		return m.IsPrimaryMethod
	}
	return false
}

func init() {
	proto.RegisterType((*Transaction)(nil), "chtype.Transaction")
	proto.RegisterType((*TransactionDetail)(nil), "chtype.TransactionDetail")
	proto.RegisterMapType((map[string]string)(nil), "chtype.TransactionDetail.AdditionalDataEntry")
	proto.RegisterType((*VerifyRequestData)(nil), "chtype.VerifyRequestData")
	proto.RegisterMapType((map[string]string)(nil), "chtype.VerifyRequestData.DataEntry")
	proto.RegisterType((*ThreeDSResult)(nil), "chtype.ThreeDSResult")
	proto.RegisterType((*VerificationResult)(nil), "chtype.VerificationResult")
	proto.RegisterType((*AttemptDetail)(nil), "chtype.AttemptDetail")
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_2cc4e03d2c28c490) }

var fileDescriptor_2cc4e03d2c28c490 = []byte{
	// 1490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xdb, 0x6e, 0xdb, 0x46,
	0x13, 0xfe, 0x25, 0xd9, 0xb2, 0x34, 0x3a, 0x58, 0x5a, 0x9f, 0x18, 0xff, 0x40, 0xea, 0x38, 0x08,
	0xe0, 0xb4, 0xb0, 0x9c, 0x38, 0xc8, 0xb1, 0x41, 0x51, 0xc7, 0x4e, 0x01, 0xa3, 0x69, 0x61, 0xd0,
	0x6e, 0x2e, 0x7a, 0x23, 0xac, 0xc9, 0x95, 0xb4, 0x35, 0x45, 0x2a, 0xbb, 0x4b, 0xa6, 0xea, 0xa3,
	0xf4, 0x39, 0xda, 0x9b, 0xbe, 0x44, 0xfb, 0x0a, 0x7d, 0x80, 0xbe, 0x43, 0xb1, 0xb3, 0x4b, 0x8a,
	0xb2, 0x29, 0xc4, 0xe8, 0x1d, 0x67, 0xe6, 0xfb, 0xb8, 0x3b, 0xcb, 0x99, 0x6f, 0x96, 0xd0, 0x55,
	0x82, 0x86, 0x92, 0x7a, 0x8a, 0x47, 0x61, 0x6f, 0x22, 0x22, 0x15, 0x91, 0xaa, 0x37, 0x52, 0xd3,
	0x09, 0xdb, 0x6e, 0x0d, 0x59, 0xc8, 0x04, 0xf7, 0x8c, 0x7b, 0x1b, 0x58, 0x18, 0x8f, 0xed, 0x73,
	0x63, 0x20, 0x68, 0xec, 0x5b, 0x63, 0x5d, 0x30, 0x39, 0x89, 0x42, 0xc9, 0xfa, 0x5e, 0xe4, 0x33,
	0x69, 0xbd, 0xfb, 0x43, 0xae, 0x46, 0xf1, 0x65, 0xcf, 0x8b, 0xc6, 0x07, 0xc3, 0x68, 0x18, 0x1d,
	0xa0, 0xfb, 0x32, 0x1e, 0xa0, 0x85, 0x06, 0x3e, 0x59, 0xf8, 0x67, 0xc3, 0x28, 0x1a, 0x06, 0x6c,
	0x86, 0x52, 0x7c, 0xcc, 0xa4, 0xa2, 0xe3, 0x89, 0x01, 0xec, 0xfe, 0x51, 0x83, 0xc6, 0xc5, 0x6c,
	0xaf, 0xe4, 0x0e, 0xd4, 0x54, 0x74, 0xc5, 0xc2, 0x3e, 0xf7, 0x9d, 0xd2, 0x4e, 0x69, 0xaf, 0xee,
	0xae, 0xa0, 0x7d, 0xea, 0x93, 0x07, 0xd0, 0xce, 0x65, 0xa5, 0x01, 0x65, 0x04, 0xb4, 0x72, 0xde,
	0x53, 0x9f, 0x3c, 0x81, 0x15, 0x9f, 0x29, 0xca, 0x03, 0xe9, 0x54, 0x76, 0x2a, 0x7b, 0x8d, 0xc3,
	0x3b, 0x3d, 0x93, 0x79, 0x2f, 0xb7, 0xce, 0x09, 0x22, 0xdc, 0x14, 0x49, 0x5e, 0x43, 0x73, 0x42,
	0xa7, 0x63, 0x16, 0xaa, 0xbe, 0x86, 0x3a, 0x4b, 0x3b, 0xa5, 0xbd, 0xf6, 0x8c, 0x79, 0x66, 0x62,
	0xdf, 0x31, 0x35, 0x8a, 0xfc, 0x8b, 0xe9, 0x84, 0xb9, 0x0d, 0x0b, 0xd7, 0x86, 0xde, 0x59, 0xca,
	0x96, 0xde, 0x88, 0x8d, 0x99, 0xb3, 0x6c, 0x76, 0x66, 0xbd, 0xe7, 0xe8, 0x24, 0x6f, 0xa0, 0x93,
	0x4f, 0x00, 0x17, 0xaa, 0xe2, 0x42, 0x5b, 0x05, 0x5b, 0xc4, 0x65, 0x56, 0xd5, 0xbc, 0x83, 0x3c,
	0x85, 0xb6, 0x60, 0x1f, 0x62, 0x26, 0x55, 0x9f, 0x8e, 0xa3, 0x38, 0x54, 0xce, 0xca, 0x4e, 0x69,
	0xaf, 0x71, 0xd8, 0x4e, 0xdf, 0x70, 0x84, 0x5e, 0xb7, 0x65, 0x51, 0xc6, 0x24, 0x5f, 0xce, 0x2a,
	0x82, 0xf9, 0x29, 0xb3, 0x56, 0xc8, 0xec, 0xcc, 0x80, 0x96, 0xfc, 0x08, 0x6a, 0x5e, 0x14, 0x2a,
	0x41, 0x3d, 0xe5, 0xd4, 0x71, 0xbf, 0xeb, 0x29, 0xe7, 0xd8, 0xfa, 0x71, 0xb3, 0x19, 0x8a, 0x3c,
	0x86, 0x75, 0xa9, 0xa8, 0x62, 0x78, 0x24, 0x3e, 0x93, 0x9e, 0xe0, 0x13, 0x15, 0x09, 0x07, 0xf0,
	0x58, 0xd6, 0xb2, 0xd8, 0x49, 0x16, 0x22, 0x8f, 0xa1, 0x2a, 0x98, 0x8c, 0x03, 0xe5, 0x34, 0xe6,
	0xcf, 0x3e, 0x77, 0x24, 0x2e, 0x02, 0x5c, 0x0b, 0x24, 0x5f, 0x43, 0x3b, 0x61, 0x82, 0x0f, 0xa6,
	0x7d, 0x9b, 0xac, 0xd3, 0xc4, 0x8c, 0x32, 0xea, 0x7b, 0x8c, 0xba, 0x26, 0x78, 0x42, 0x15, 0x75,
	0x5b, 0x49, 0xde, 0x45, 0x9e, 0x41, 0x73, 0x40, 0x79, 0x10, 0x0b, 0x66, 0xbe, 0x46, 0x0b, 0x97,
	0x5e, 0x4b, 0xf9, 0xdf, 0x98, 0x98, 0xf9, 0xe0, 0x83, 0x99, 0x41, 0x3a, 0x50, 0xa1, 0x22, 0x74,
	0x56, 0x31, 0x1d, 0xfd, 0x48, 0x9e, 0x41, 0x0d, 0x5f, 0xcd, 0x99, 0xef, 0x74, 0xf0, 0x2d, 0xdb,
	0x73, 0xbb, 0xe0, 0x1e, 0xd5, 0x19, 0x9c, 0x2b, 0xaa, 0x62, 0xe9, 0x66, 0x58, 0x72, 0x00, 0xf5,
	0x80, 0xd3, 0x4b, 0x1e, 0x70, 0x35, 0x75, 0xba, 0x48, 0xec, 0xa6, 0xc4, 0x77, 0x69, 0xc0, 0x9d,
	0x61, 0xc8, 0x6b, 0x68, 0x53, 0xa5, 0xd8, 0x78, 0xa2, 0x0f, 0x56, 0x17, 0xaf, 0xb3, 0x86, 0x49,
	0x6f, 0x64, 0x9f, 0xd1, 0x44, 0x6d, 0x85, 0xb7, 0x68, 0xde, 0x24, 0x2f, 0xa0, 0x85, 0x3d, 0xde,
	0x37, 0x47, 0x28, 0x9d, 0x75, 0x6c, 0x91, 0x59, 0xc6, 0x3a, 0x68, 0x8f, 0xb9, 0x39, 0x98, 0x19,
	0x92, 0x1c, 0x42, 0x2d, 0x15, 0x04, 0x67, 0x03, 0x57, 0xdc, 0x4c, 0x49, 0xae, 0xf5, 0xdb, 0x25,
	0x33, 0x1c, 0x39, 0x84, 0x0d, 0x19, 0xc5, 0xc2, 0x63, 0xfd, 0x6b, 0x8d, 0xbb, 0x69, 0xeb, 0x00,
	0x83, 0x17, 0x73, 0xed, 0xfb, 0x39, 0x74, 0xd3, 0x5e, 0x1a, 0x63, 0xbb, 0x69, 0xfc, 0x16, 0xe2,
	0x57, 0x27, 0xf9, 0x36, 0x3c, 0xf5, 0x77, 0x7f, 0xaf, 0x41, 0xf7, 0x46, 0x53, 0x6b, 0x09, 0xa1,
	0x9e, 0x8a, 0x44, 0x4e, 0x42, 0xd0, 0x3e, 0xf5, 0xc9, 0x7d, 0x68, 0x99, 0x50, 0xc2, 0x84, 0xe4,
	0x51, 0x68, 0x15, 0xa4, 0x89, 0xce, 0xf7, 0xc6, 0x47, 0x1e, 0x01, 0x18, 0x10, 0x96, 0x44, 0x65,
	0xfe, 0x9b, 0x1c, 0xe9, 0x08, 0x16, 0x44, 0x9d, 0xa6, 0x8f, 0x05, 0xca, 0xb4, 0x54, 0xa4, 0x4c,
	0x2f, 0xa1, 0x63, 0x0b, 0x75, 0xd6, 0x83, 0xcb, 0x85, 0x3d, 0xb8, 0x9a, 0xe1, 0x6c, 0x0b, 0xbe,
	0x84, 0xce, 0x44, 0x44, 0x1e, 0x93, 0x72, 0x46, 0xad, 0x16, 0x53, 0x33, 0x9c, 0xa5, 0x3e, 0x86,
	0xe6, 0x80, 0xb1, 0x3e, 0x93, 0x8a, 0x8f, 0xa9, 0x62, 0x0b, 0xf4, 0xa2, 0x31, 0x60, 0xec, 0xad,
	0x85, 0x90, 0x7d, 0x00, 0x4d, 0xa1, 0x9e, 0x8a, 0x69, 0xb0, 0x40, 0x26, 0xea, 0x03, 0xc6, 0x8e,
	0x10, 0x40, 0x5e, 0x02, 0x48, 0x45, 0x85, 0xea, 0x6b, 0x71, 0x47, 0x85, 0x68, 0x1c, 0x6e, 0xf7,
	0x8c, 0xf2, 0xf7, 0x52, 0xe5, 0xef, 0x5d, 0xa4, 0xca, 0xef, 0xd6, 0x11, 0xad, 0x6d, 0xf2, 0x14,
	0x6a, 0x2c, 0xf4, 0x0d, 0x11, 0x3e, 0x49, 0x5c, 0x61, 0xa1, 0x8f, 0xb4, 0x07, 0xd0, 0xfe, 0x48,
	0x65, 0x5f, 0xc6, 0x9e, 0x4e, 0x75, 0x10, 0x07, 0x28, 0x1a, 0x35, 0xb7, 0xf5, 0x91, 0xca, 0xf3,
	0xcc, 0x79, 0xa3, 0xbd, 0x9b, 0xb7, 0x6c, 0xef, 0xa7, 0xd0, 0x60, 0x61, 0xc2, 0x45, 0x14, 0xea,
	0x72, 0xc3, 0x36, 0xcf, 0xd1, 0xde, 0xce, 0x42, 0x6e, 0x1e, 0x47, 0xbe, 0x85, 0xb5, 0x24, 0xd7,
	0xeb, 0xb6, 0xc7, 0x50, 0x0e, 0x1a, 0xc5, 0x72, 0x60, 0x3b, 0x8d, 0x24, 0x37, 0x7c, 0xe4, 0x3d,
	0xac, 0x52, 0xdf, 0xe7, 0xda, 0x43, 0x83, 0xbe, 0x4f, 0x15, 0x75, 0xba, 0xd8, 0xab, 0xfb, 0x0b,
	0xc7, 0x59, 0xef, 0x28, 0x23, 0x68, 0xb1, 0x7b, 0x1b, 0x2a, 0x31, 0x75, 0xdb, 0x74, 0xce, 0x49,
	0xf6, 0x81, 0xd0, 0x58, 0x8d, 0x22, 0xc1, 0x7f, 0x31, 0xbb, 0xd4, 0xd3, 0xdd, 0x21, 0x58, 0xaf,
	0xdd, 0xb9, 0xc8, 0x71, 0xe4, 0xb3, 0x79, 0x7d, 0x5a, 0xbb, 0x85, 0x3e, 0x7d, 0x01, 0x5d, 0x2f,
	0x0a, 0x43, 0x86, 0x1d, 0x14, 0xf0, 0x4b, 0x41, 0xc5, 0xd4, 0x59, 0xc7, 0xd7, 0x77, 0xb2, 0xc0,
	0x3b, 0xe3, 0xbf, 0x26, 0x2a, 0x95, 0xdb, 0x88, 0xca, 0xf6, 0x11, 0xac, 0x15, 0xe4, 0xa9, 0x25,
	0xf9, 0x8a, 0x4d, 0x6d, 0xc3, 0xeb, 0x47, 0xb2, 0x0e, 0xcb, 0x09, 0x0d, 0x62, 0x66, 0x9b, 0xdc,
	0x18, 0xaf, 0xca, 0x2f, 0x4a, 0xbb, 0xbf, 0x95, 0xa1, 0x7b, 0x63, 0x36, 0x90, 0x7d, 0x58, 0xc2,
	0x2a, 0x29, 0xcd, 0xcf, 0x9f, 0x39, 0x20, 0xd6, 0x0a, 0xc2, 0xc8, 0x73, 0x58, 0xc2, 0xaf, 0x52,
	0xc6, 0x7d, 0xdf, 0x5f, 0x38, 0x73, 0x7a, 0xb3, 0x6f, 0x81, 0x84, 0xe2, 0x13, 0xaa, 0x2c, 0x38,
	0xa1, 0x6b, 0xa5, 0xb8, 0x74, 0xcb, 0x52, 0xdc, 0xd6, 0x07, 0xfb, 0x21, 0xe6, 0x82, 0xf9, 0x28,
	0x31, 0x35, 0x37, 0xb3, 0xb7, 0x9f, 0x43, 0xfd, 0xbf, 0x1d, 0xdb, 0xaf, 0x4b, 0xd0, 0xba, 0x18,
	0x09, 0xc6, 0x4e, 0xce, 0x6d, 0x91, 0x76, 0xa0, 0xc2, 0x3c, 0x9e, 0xb2, 0x99, 0xc7, 0x09, 0x81,
	0x25, 0x8f, 0x26, 0x89, 0x25, 0xe3, 0xb3, 0x46, 0xfd, 0xcc, 0x7d, 0x9b, 0xa2, 0x7e, 0x24, 0x77,
	0x01, 0x58, 0x28, 0xa2, 0x20, 0xc8, 0x92, 0xaa, 0xbb, 0x39, 0x0f, 0xd9, 0xcc, 0x2e, 0x03, 0xe6,
	0x22, 0x95, 0x4e, 0xfc, 0x87, 0xd0, 0x91, 0x7c, 0x18, 0x52, 0xa5, 0x5b, 0x5a, 0xe2, 0x2c, 0x45,
	0x19, 0xac, 0xbb, 0xab, 0x99, 0xdf, 0x8c, 0x58, 0x9c, 0x3d, 0x4c, 0x24, 0x4c, 0x5c, 0x9f, 0x3d,
	0x2b, 0x76, 0xf6, 0x60, 0x70, 0x7e, 0xf6, 0x6c, 0x42, 0xd5, 0xbe, 0xb4, 0x66, 0x96, 0x35, 0x96,
	0x1e, 0x1b, 0x63, 0xfa, 0x53, 0x6e, 0x6c, 0x68, 0x8d, 0x5b, 0x76, 0x9b, 0xe8, 0x4c, 0xc7, 0x86,
	0x03, 0x2b, 0x69, 0xd8, 0x5c, 0x73, 0x52, 0x93, 0x6c, 0x40, 0x75, 0x42, 0xf5, 0x1d, 0x05, 0x55,
	0xaa, 0xee, 0x2e, 0x4f, 0xa8, 0xcb, 0x3e, 0x90, 0x2d, 0x58, 0xa1, 0x9e, 0xec, 0xc7, 0x22, 0x40,
	0x61, 0xaa, 0xbb, 0x55, 0xea, 0xc9, 0x1f, 0x44, 0x90, 0xe1, 0x25, 0xde, 0x47, 0x2c, 0x5e, 0x92,
	0x36, 0x94, 0xb9, 0xef, 0xb4, 0xd1, 0x55, 0xe6, 0x3e, 0x79, 0x01, 0xf5, 0xec, 0x36, 0x8d, 0x1a,
	0xf5, 0x09, 0xd5, 0xcd, 0xc0, 0xf3, 0x4d, 0xdd, 0xb9, 0x45, 0x53, 0xdf, 0x83, 0xa6, 0xf4, 0xaf,
	0xfa, 0x59, 0xaf, 0x76, 0x71, 0x13, 0x0d, 0xe9, 0x5f, 0xa5, 0x6d, 0xba, 0xfb, 0x4f, 0x09, 0xc8,
	0x4d, 0x69, 0x23, 0x5f, 0xc1, 0xff, 0xa9, 0xef, 0x0b, 0x26, 0x65, 0xbf, 0x48, 0x1b, 0x4d, 0xe5,
	0xdc, 0xb1, 0x90, 0x02, 0xfe, 0x33, 0xd8, 0xf2, 0x92, 0xa4, 0x90, 0x6b, 0x4a, 0x6c, 0xc3, 0x4b,
	0x92, 0x02, 0xde, 0x3d, 0x68, 0xe6, 0x2f, 0x3a, 0xb6, 0xf8, 0x1a, 0xb9, 0x2b, 0x8d, 0xbe, 0x49,
	0x29, 0x5d, 0xcd, 0xbe, 0xec, 0xe7, 0x8a, 0x2d, 0x77, 0x93, 0x9a, 0xab, 0x75, 0xb7, 0x65, 0xc1,
	0xc6, 0xdc, 0xfd, 0xb3, 0x0c, 0xad, 0xa3, 0x6b, 0x77, 0xab, 0xad, 0xe3, 0x11, 0x15, 0xc3, 0xfc,
	0x85, 0xe6, 0xfb, 0x78, 0x7c, 0xc9, 0x04, 0xa6, 0x59, 0x71, 0x17, 0x85, 0xc9, 0x23, 0x58, 0x33,
	0x21, 0xfb, 0x42, 0xcb, 0x2a, 0x23, 0xab, 0x28, 0x44, 0x5e, 0x81, 0x63, 0x1d, 0x37, 0x17, 0xab,
	0x20, 0x6d, 0x61, 0x9c, 0x1c, 0xc2, 0xba, 0x8d, 0x99, 0x8b, 0xd4, 0x31, 0x95, 0x1e, 0xf5, 0xcd,
	0x3f, 0x4f, 0xc5, 0x2d, 0x8c, 0xe9, 0xdc, 0xac, 0xff, 0x38, 0x55, 0xa8, 0x94, 0xb6, 0x6c, 0x72,
	0x5b, 0x10, 0x26, 0x7b, 0xb0, 0x7a, 0x2a, 0xcf, 0x04, 0x1f, 0x53, 0x31, 0x35, 0xef, 0xc4, 0x8e,
	0xad, 0xb9, 0xd7, 0xdd, 0x6f, 0xce, 0xff, 0xfa, 0xfb, 0xee, 0xff, 0xa0, 0xed, 0x45, 0xe3, 0x9e,
	0x87, 0x29, 0x8f, 0x78, 0xc2, 0xde, 0x74, 0x72, 0x09, 0x9c, 0xe9, 0xaa, 0x3e, 0x2b, 0xfd, 0xf8,
	0x30, 0xf7, 0x13, 0x3a, 0x83, 0x1e, 0xa4, 0x7f, 0x9f, 0x01, 0x0d, 0x87, 0x07, 0xe6, 0x1b, 0x5e,
	0x56, 0xd1, 0xf9, 0xe4, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x03, 0x9a, 0x82, 0x11, 0x0f,
	0x00, 0x00,
}
